### PR TITLE
block 100 scams

### PR DESCRIPTION
**Pull request by dubstard**
add 
```
    "airdrop-crypto.app",
    "awesome-apes.com",
    "bittrex-official-walet.com",
    "bittrex-official-wallet.com",
    "bittrex-official-wallett.com",
    "blueskyswap.finance",
    "coinbase-requestss.servehalflife.com",
    "coinbase.auth-recovery.com",
    "coinbase.com-verifyaccountverify.signkdfndsfgsdregdfgh.com",
    "coinbase.verifyccmio150cstomer.com",
    "connectedwallets.xyz",
    "connectwalletinnftcloudshop.cf,
    "connectwalletinnftcloudshop.ga",
    "connectwalletinnftcloudshop.gq",
    "connectwalletinnftcloudshop.ml",
    "connectwalletinnftcloudshop.tk",
    "cornpoumd.finance",
    "crypto-exchange.pro",
    "cryptowallet.ge",
    "cryptowallet.top",
    "dappsecurebrowser.net",
    "dappsmintsyncreveal.com",
    "free-ethereum.net",
    "freeethereum.biz",
    "freeethereumcoins.com",
    "freeethereumcoins.hes.nqd.mybluehost.me",
    "hotcakeswap.finance",
    "kraken-invest.de",
    "kraken-kr.com",
    "krakenpro.ru",
    "metamask-cx6.pages.dev",
    "metamask-for-chrome.com",
    "metamask-us.com",
    "metamask.fit",
    "metamask.haoma.one",
    "metamask.io.merge.dailykashtkar.com",
    "metamask.me",
    "metamask.phpmax.ru",
    "metamask.productions",
    "metamaskc-app.com",
    "metamaskcares.run.place",
    "metamaskk-app.com",
    "metamaskwebswallet.com",
    "metmask.lo.wallet-identlficaton.epapar.gob.ec",
    "pahcakeswap.pw",
    "pahcakeswap.com",
    "pahcakeswap.group",
    "pahcakeswap.host",
    "pahcakeswap.org",
    "pahcakeswap.pro",
    "pahcakeswap.site",
    "pahcakeswap.space",
    "pahcakeswap.tech",
    "polyusd.tech",
    "star-link.app",
    "sushiswapdrop.com",
    "sushiswapies.com",
    "talentblockchain.com",
    "uniswap-info-experimental.now.sh",
    "uniswap.mom",
    "uniswapdiamond.com",
    "uniswapgret.com",
    "uniswapinu-erc.com",
    "uniswapper.com",
    "verify-coinbase.co",
    "wallet-coinbase.platfromdashboardoneelectro.com",
    "wallet.flf.xyz",
    "wallet.fpy.xyz",
    "wallet.jgk.xyz",
    "wallet.jgq.xyz",
    "wallet.jhl.xyz",
    "wallet.jmb.tech",
    "wallet.jmy.xyz",
    "wallet.jpz.xyz",
    "wallet.jwj.xyz",
    "wallet.kbx.xyz",
    "wallet.kgn.xyz",
    "wallet.khd.xyz",
    "wallet.ktd.xyz",
    "wallet.kzd.xyz",
    "wallet.ncx.xyz",
    "wallet.rjx.xyz",
    "wallet.rnc.xyz",
    "wallet.rpj.xyz",
    "wallet.rqs.xyz",
    "wallet.rxb.xyz",
    "wallet.tgf.xyz",
    "wallet.tpz.xyz",
    "wallet.twk.xyz",
    "wallet.uy691.com",
    "wallet.wcl.se",
    "wallet.wgr.xyz",
    "wallet.wrl.xyz",
    "wallet.ygz.xyz",
    "wallet.yikj.work",
    "wallet.ytq.xyz",
    "wallet.zgs.xyz",
    "wallet.zmg.xyz",
    "wallet.zpq.xyz",
    "walletsrectification.network",
    "web3metaverse.network",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add 
```
    "hotcakeswap.finance",
    "pahcakeswap.pw",
    "web3metaverse.network",
    "blueskyswap.finance",
    "dappsmintsyncreveal.com",
    "polyusd.tech",
    "awesome-apes.com",
```

**Review by dubstard — COMMENTED** [review]
fix json fat finger

`"connectwalletinnftcloudshop.cf,` -> `"connectwalletinnftcloudshop.cf",`

**Review by dubstard — COMMENTED** [review]
remove one duplicate `"metamask-cx6.pages.dev"`

**Review by dubstard — COMMENTED** [review]
add
```
    "pahcakeswap.com",
    "pahcakeswap.group",
    "pahcakeswap.host",
    "pahcakeswap.org",
    "pahcakeswap.pro",
    "pahcakeswap.site",
    "pahcakeswap.space",
    "pahcakeswap.tech",
```

PaHcake instead of PaNcake

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
