### PR TITLE
Block 68 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "airdrop-8pay.com",
    "airdrops-ethers.org",
    "airdropsblur.com",
    "alsanati.com",
    "appe-slingshot.finance",
    "authc-metamask-demo.pages.dev",
    "biur-drop.com",
    "blurtokens.io",
    "bllur.xyz",
    "bloekchain.com",
    "blur-drop.link",
    "blurclaim.app",
    "blurclaim.click",
    "bluri.us",
    "chainlist.global",
    "chajnljst-app.christianlanguagesolutions.com",
    "de-bank.co",
    "de-bank.io",
    "e-pancakeswap.com",
    "ethereum.alfaindexer.lol",
    "ethereum.anisimok.dev",
    "ethereum.ingainer.art",
    "ethereum.s3de4fd.xyz",
    "ethereum.verbalabs.xyz",
    "https-www-anyswap.exchange",
    "id-1us-c0inbase.xyz",
    "id-2us-c0inbase.xyz",
    "immutable-x.com",
    "immutable.cab",
    "immutable.com.co",
    "immutadle.com",
    "immutalblex.com",
    "imputable.com",
    "lifeishort.work.gd",
    "lmmutabie.com",
    "luna20airdropcrypto.com",
    "metamask--por4folio-dapp.xyz",
    "metamask--portfoliio-dapp.xyz",
    "metamask-por4folio-dapp.xyz",
    "metamask.io.shop-online.site",
    "metamask.io.support.shop-online.site",
    "metamask.seedphrase-update.com",
    "my-pool.vip",
    "myetherwalet.com.cardano.space",
    "opensea-batch.oss.standardcryptovc.com",
    "opensea.io.offer.brainsonit.co.za",
    "opensea.io.offer.mimshack.co.za",
    "pancakeswapfinance.myftp.org",
    "pancakeswapmoxe.com",
    "pancakeswapresolve.sbs",
    "petticoatrow.com",
    "portalblockchain.com",
    "portfolio-met1mask-io.xyz",
    "reset-support-coinbase.com",
    "seedphrase-update.com",
    "susiswap.top",
    "technologycoin.ink",
    "tecno4me.net",
    "trustpad-airdrops.org",
    "uniswap-support.com",
    "uniswap.gold",
    "update-blockchain.com",
    "updatesc-coinbase.x24hr.com",
    "usdter.nl",
    "walletbinance-infomailer.com",
    "wwf-nfa.org",
    "wwfnfa.com",
    "www-portfolio-met4amaskk.xyz",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block `opensea.io.offer.brainsonit.co.za`

**Review by dubstard — COMMENTED** [review]
block `opensea.io.offer.mimshack.co.za`

**Review by dubstard — COMMENTED** [review]
block `technologycoin.ink`
1DA1CECD-47B7-4F9F-B1C6-66F0E0E88708

**Review by dubstard — COMMENTED** [review]
```
    "alsanati.com",
    "susiswap.top",
    "appe-slingshot.finance",
    "chainlist.global",
    "de-bank.co",
    "de-bank.io",
    "immutable-x.com",
    "immutable.cab",
    "immutadle.com",
    "immutalblex.com",
    "imputable.com",
    "lmmutabie.com",
    "immutable.com.co",
    "petticoatrow.com",
    "tecno4me.net",
```

✅ Real:`immutable.com`

❌ Fake:
```
immutable.com.co
immutable.com.co
immutable-x.com
immutable-x.com
immutable.cab
immutadle.com
immutalblex.com
imputable.com
lmmutabie.com
```

🔎UrlScans
https://urlscan.io/result/23ec3a3d-fa1d-4c72-96ea-837110eb2204/
https://urlscan.io/search/#page.domain%3A(immutable.com~%20AND%20NOT%20immutable.com)
https://urlscan.io/search/#hash%3Ab855851451c3eb7220bc7331d6cf7f19dad4580ebc35610211f028848ba7fc34%20AND%20page.domain%3A(NOT%20arbitrum.io%20NOT%20metamask.io%20NOT%20opensea.io)
https://urlscan.io/search/#hash%3Afac68846ad8761c613a26e93a137244de31a27e34eefc6760b7123faaf04d634%20AND%20page.domain%3A(NOT%20arbitrum.io%20NOT%20metamask.io%20NOT%20opensea.io)

**Review by dubstard — COMMENTED** [review]
block `usdter.nl`
shares same host as `technologycoin.ink`

**Review by dubstard — COMMENTED** [review]
```
    "blurtokens.io",
    "airdropsblur.com",
    "biur-drop.com",
    "bllur.xyz",
    "blur-drop.link",
    "blurclaim.app",
    "blurclaim.click",
    "bluri.us",
```
`hash:212e893baa7e1de78fa2603928b2b33ae8d5378cb4fc2881797423e80c36ad7e AND page.domain:(NOT blur.io)`
https://urlscan.io/search/#hash%3A212e893baa7e1de78fa2603928b2b33ae8d5378cb4fc2881797423e80c36ad7e%20AND%20page.domain%3A(NOT%20blur.io)

h/t @tayvano for the lead
(SMS Spam)

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
