### PR TITLE
Fix arctis.tech 

### PR DESCRIPTION
**Pull request by weisser-dev**

### CODE REVIEW

**Comment by weisser-dev** [comment]
@AlexHerman1 and @409H could you pls merge it these time... i create so much pull requests for that and everytime out of date and so on because nobody take a look at it.

**Comment by weisser-dev** [comment]
> @weisser-dev can you update branch

Done pls merge it

**Comment by weisser-dev** [comment]
@AlexHerman1 you guys still reply after more then 10 hours and then its again outdated... how should i already be up to date?

**Comment by weisser-dev** [comment]
@AlexHerman1 pls merge it now, and take a look at it... tomorrow it is again no longer up-to-date... and then we have discussion again and again... it is already the second pull request.. and i wait now for very long time that our domain is whitelisted...

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
