### PR TITLE
Block Balancer.FI imitators - balencer.fi and baiancer.fi

### PR DESCRIPTION
**Pull request by dubstard**
Phishing alert stealing seed phrase.
image

Already has victims burned :/

FAKE `balEncer[.]fi` (`E` instead of `A`)
FAKE `baIancer[.]fi` (`I` instead of `L`)

image
image
image

[Scam spread via twitter](https://twitter.com/BaIencer)

h/t Cosme for the heads up

### CODE REVIEW

**Comment by dubstard** [comment]
0xd13b093EAfA3878De27183388Fea7D0D2B0AbF9E scammers wallet

**Review by dubstard — COMMENTED** [review]
Remove duplicate (PR was raised with no duplicates.)
Another PR -  #9676  got merged and caused the current PR #9674 to have one duplicate.
This edit fixes that.

**Comment by dubstard** [comment]
the same scammers also have `curve-reward.fi`, how confenient.

**Review by AlexHerman1 — APPROVED** [review]
lgtm.

**Comment by dubstard** [comment]
Thanks

**Pull request merged**
