### PR TITLE
Block 75 scams

### PR DESCRIPTION
**Pull request by dubstard**
```
    "10xprotrade.com",
    "1954financecorp.com",
    "216liveoption.com",
    "24financeoption.com",
    "360liveoption.com",
    "362financeoption.com",
    "365coinoptions.com",
    "3vvwvroninwallet.top",
    "aaveairdrop.com",
    "airdrop-crypto.us",
    "airdroppay.com",
    "airdropwallet.net",
    "alphawallet.online",
    "balancer-dev35-ru.8adm.com",
    "bit-primer.ltd",
    "bitcoinhedgeinvestment.ltd",
    "bitcointradex.com",
    "blockschainsupport.info",
    "blockschian.com",
    "coinbasereset-auth.com",
    "coindividend-holdings.com",
    "coinexmarkets.com",
    "coinfxcash.com",
    "coinfxtrade.com",
    "coinmegatrade.com",
    "cointrex.ltd",
    "connectcoinswallet.com",
    "cryptoforextradeoption.com",
    "cryptoprofitmaking.com",
    "cryptostocksfx.com",
    "cryptoziod.com",
    "cryptschain.live",
    "dashboard-rectify.duckdns.org",
    "ethereum-kar.com",
    "ethereum-pocket.de",
    "ethereum-pocket.eu",
    "ethereum-serve.com",
    "ethereum-space.com",
    "ethereumcode-system-gb.com",
    "ethereumkar.com",
    "ethereumscan.org",
    "exchange.apesvvvap.finance",
    "metamask-1.vip",
    "metamask-claim.com",
    "quickswap.nz",
    "exodus.org.nz",
    "exoduswallet.us",
    "metamask-claim.kpr-mint.com",
    "metamask-kyc.info",
    "metamask.cz.rfn.cz",
    "metamask.earn-io.com",
    "metamask.tech",
    "metamaskcoin.com",
    "pancakeswapus.us",
    "paraswap.cn",
    "paraswap.cn.com",
    "paraswap.ltd",
    "paraswaps.cn.com",
    "paraswaps.space",
    "paraswaps.xyz",
    "serve-ethereum.com",
    "ssl-metamask.io",
    "sumcoin.support",
    "sumscoins.com",
    "sushiswapca.com",
    "uniswap.acbcba.com.bo",
    "uniswap.matrixcreativesolutions.com",
    "uniswap.network.supplies",
    "uniswapp.acbcba.com.bo",
    "uniswapp.myisaproducts.com",
    "vww-1inch.top",
    "e-walletconnectpro.com",
    "wallet.fqm.xyz",
    "wallets-syncing.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupe `metamask.cz`

**Review by dubstard — COMMENTED** [review]
add `xn–mtamask-rya.com` aka `mëtamask.com`

IDN | Punycode
-- | --
mëtamask.com|xn–mtamask-rya.com

</body>
</html>

**Review by dubstard — COMMENTED** [review]
Parser is not happy with the punycode entry

**Comment by dubstard** [comment]
Parser is now happy.

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks

**Pull request merged**
