### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by kellyfends**

### CODE REVIEW

**Comment by kellyfends** [comment]
And add basechaineth.com

**Comment by kellyfends** [comment]
https://claim-tether.net/en/

**Comment by kellyfends** [comment]
https://nft-nakamigos.com/

**Comment by kellyfends** [comment]
https://tether-reward.online/

**Comment by kellyfends** [comment]
https://airlaunchpad.app/

**Comment by kellyfends** [comment]
https://opbnb-bridge.com/

**Comment by kellyfends** [comment]
https://stake-robinhood.com/

**Review by tayvano — APPROVED** [review]

**Pull request merged**
