### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
add
```
    "1inch-v2.com",
    "app.uniswap.org.holder-400uni.site",
    "holder-400uni.site",
    "apple-pancakeswap.finance",
    "claim-airdrop.net",
    "coinbase-verify.servehalflife.com",
    "servehalflife.com",
    "coinbasecoincashminer.finance.blog",
    "coinbasewallet.com.cn",
    "crazydefensehroes.com",
    "ethereum.merge20.repl.co",
    "ethereumv2-pos.com",
    "ethereumv2-pos.net",
    "ethereumv2-pos.org",
    "exoduswallet.app",
    "farmesworld.com",
    "idexns.com",
    "kraken-tradekr.com",
    "kraken.top",
    "krakeninvestmentfund.com",
    "krakenjp.com",
    "lendingofuniswap.top",
    "liquiditycrypto.com",
    "login.coinbase.accounts.e8ja.day",
    "e8ja.day",
    "login.coinbase.verifymypassword.com",
    "verifymypassword.com",
    "martian-wallet.com",
    "martian-wallets.com",
    "metamask-zendesk.rf.gd",
    "metamask.dev",
    "metamask.io.community-scrutiny.in",
    "community-scrutiny.in",
    "metamask.io.community-support.in",
    "community-support.in",
    "metamask.io.merge.allfroofs.com",
    "allfroofs.com",
    "metamask.io.merge.idetgroup.com",
    "idetgroup.com",
    "metamask.ng",
    "metamaskchat.com",
    "metamaske.cc",
    "metamaske.me",
    "metamaskwallet.life",
    "metamaskwallet.site",
    "officialmetamask.help",
    "otcethereum.com",
    "pancakeswap-money.com",
    "pancakeswap.finance.cwap.in",
    "cwap.in",
    "pancakeswap.finance.go-next.in",
    "go-next.in",
    "pancakeswap.finance.start-next.in",
    "start-next.in",
    "pcrivnote.com",
    "premint-xyz.app",
    "radzimierz.com",
    "spookysnwap.com",
    "tcrustwallet.com",
    "tesla-bounty.repl.co",
    "tesla-bountys.repl.co",
    "tesla-crypto.repl.co",
    "tesla-giveaway.repl.co",
    "tesla.coinfund.repl.co",
    "tnrustwallet.com",
    "trnustwallet.com",
    "tronlinckcs-wallet.com",
    "trunstwallet.com",
    "trusctwallet.com",
    "trustcwallet.com",
    "trustwallet.com.security.upgrade-page.cc",
    "upgrade-page.cc",
    "trustwallnet.com",
    "trustwallot.com",
    "trustwcallet.com",
    "trustwnallet.com",
    "vault-bitwarden.com",
    "vault-bitwardenr.com",
    "vault-bitwardens.com",
    "vitalik-ethereum.com",
    "wallet-chainlink.com",
    "wallet-coiinmama.ml",
    "wallet-polkadot.com",
    "yearnwallet.com",
```
➕
```
"annualxrpgiv.com",
    "beargives.eventlive.repl.co",
    "binanceceo.info",
    "bnbdeal.net",
    "bnbdrop.info",
    "bnbgate.net",
    "bnbgive.info",
    "bnbgive.net",
    "bnbgiveme.com",
    "bnbhold.net",
    "bnbsend.net",
    "bnbweek.info",
    "coinbase.giveawayprogram.live",
    "cryptonow.gg",
    "cryptosevent.net",
    "cryptospace.gg",
    "czbnbx10.info",
    "czearn.net",
    "czevent.info",
    "czhold.net",
    "czjoin.com",
    "czstake.com",
    "cztake.info",
    "czwin.info",
    "elon2x-promo.com",
    "elonfinance-promo.com",
    "elonsevent.com",
    "emstake.net",
    "ethmerge2022.com",
    "ethmergegive.info",
    "financialnewstoday.net",
    "giveawayprogram.live",
    "ilangod.com",
    "ilmusk.com",
    "maskiln.com",
    "merge.czbinance.repl.co",
    "muskfinance-event.info",
    "pump-xrp.net",
    "right-xrp.com",
    "stakeevent.com",
    "stakejoin.com",
    "sweekswap.com",
    "tesla-2xprize.com",
    "x1000shibclaim.info",
    "xrp1giv.com",
    "xrpbradgiv.com",
    "xrpevent-finance.org",
    "xrpfirstgiv.com",
    "xrpgivs.com",
    "xrpgivtoday.com",
    "xrplegitgiv.com",
    "xrppost.com",
```

➖(Dupes)
```
metamaskchat.com
coinbasewallet.com.cn
metamask.io.community-support.in
metamask.io.community-scrutiny.in
coinbase.giveawayprogram.live
```

URLScans

```
$ ./BurnTrash.sh | egrep "(result|url)"

  "result"; "https://urlscan.io/result/eefb0f0d-9c11-4e5e-994d-a3096b9e864a/",
  "url": "http://1inch-v2.com",

  "result"; "https://urlscan.io/result/2db0a781-4a9d-4071-9dfa-69195a40fd07/",
  "url": "http://allfroofs.com",

  "result"; "https://urlscan.io/result/b4971154-7858-4ed2-8953-0600791555e9/",
  "url": "http://app.uniswap.org.holder-400uni.site",

  "result"; "https://urlscan.io/result/cbefadd4-6db5-49d6-9056-05c54cb69935/",
  "url": "http://apple-pancakeswap.finance",

  "result"; "https://urlscan.io/result/5e47feac-7286-4100-b73b-d7ff7ff49eb1/",
  "url": "http://beargives.eventlive.repl.co",

  "result"; "https://urlscan.io/result/16c76410-4a0e-4e0d-ba64-9a77b8abcd89/",
  "url": "http://bnbgate.net",

  "result"; "https://urlscan.io/result/9c265928-b5f3-4654-bbc4-bd17ce5e67ef/",
  "url": "http://bnbgiveme.com",

  "result"; "https://urlscan.io/result/18bab12a-3636-47ff-bb43-655456ec8c5a/",
  "url": "http://bnbsend.net",

  "result"; "https://urlscan.io/result/fb3aa49a-6bd4-4e48-86d9-485529705a5b/",
  "url": "http://claim-airdrop.net",

  "result"; "https://urlscan.io/result/5bd6cc0f-b6cd-41a4-a8cb-77e13c674476/",
  "url": "http://coinbase-verify.servehalflife.com",

  "result"; "https://urlscan.io/result/7cbc631b-4f1d-4db0-ad38-6747357b8a44/",
  "url": "http://coinbase.giveawayprogram.live",

  "result"; "https://urlscan.io/result/2ee71cb8-31ff-4860-b2f9-ba8d9e644324/",
  "url": "http://coinbasecoincashminer.finance.blog",

  "result"; "https://urlscan.io/result/908fd074-725f-4275-985c-f32ec4c0f420/",
  "url": "http://coinbasewallet.com.cn",

  "result"; "https://urlscan.io/result/135a0acd-17f4-43b7-9966-6e1ace5f5014/",
  "url": "http://crazydefensehroes.com",

  "result"; "https://urlscan.io/result/5d84e060-cb95-4e11-93e5-e539f3ba4808/",
  "url": "http://cwap.in",

  "result"; "https://urlscan.io/result/f7ffa767-daad-44ed-95e9-632781bc9024/",
  "url": "http://czbnbx10.info",

  "result"; "https://urlscan.io/result/e5149330-3040-49ba-a68f-cb52a046bb1e/",
  "url": "http://cztake.info",

  "result"; "https://urlscan.io/result/16b3fe9e-e05a-468d-941d-10be01ddb701/",
  "url": "http://czwin.info",

  "result"; "https://urlscan.io/result/4a39e8b3-09e9-43da-8b85-dd953ed66e9a/",
  "url": "http://ethereum.merge20.repl.co",

  "result"; "https://urlscan.io/result/e966124d-e7cb-47ea-beea-52e050c5c12e/",
  "url": "http://ethereumv2-pos.com",

  "result"; "https://urlscan.io/result/9b386919-675f-4dca-b851-5a51decc9cdd/",
  "url": "http://ethereumv2-pos.net",

  "result"; "https://urlscan.io/result/e3ec9449-6de2-4f87-997e-903a03c7a6ec/",
  "url": "http://ethereumv2-pos.org",

  "result"; "https://urlscan.io/result/1bbdb8c2-e516-4209-ade3-765e750beb2f/",
  "url": "http://ethmerge2022.com",

  "result"; "https://urlscan.io/result/c40c9778-848d-442d-bfc2-1c6a1b467de7/",
  "url": "http://exoduswallet.app",

  "result"; "https://urlscan.io/result/c6e6b843-188f-412c-a78c-c36deeced9bf/",
  "url": "http://farmesworld.com",

  "result"; "https://urlscan.io/result/9b84876d-bc3e-4d96-b041-c1e7a2312e4b/",
  "url": "http://financialnewstoday.net",

  "result"; "https://urlscan.io/result/b5e790c3-ae12-4133-b4b5-1dd732d671b4/",
  "url": "http://giveawayprogram.live",

  "result"; "https://urlscan.io/result/c18440b5-c23c-4684-bdd0-f8482ef791da/",
  "url": "http://go-next.in",

  "result"; "https://urlscan.io/result/6096d03d-ab1b-4902-ad4d-d12fc826e1b1/",
  "url": "http://holder-400uni.site",

  "result"; "https://urlscan.io/result/b0bbfeca-8d89-497d-8481-cfd284ff9842/",
  "url": "http://idetgroup.com",

  "result"; "https://urlscan.io/result/6f0d1a72-65be-4f20-815d-e04d806be2bd/",
  "url": "http://idexns.com",

  "result"; "https://urlscan.io/result/51e7f5bb-cbb7-4955-8c2b-c68d17052c8f/",
  "url": "http://ilangod.com",

  "result"; "https://urlscan.io/result/ba0a8ae9-a629-4fff-88b6-9b6f2dcf9a08/",
  "url": "http://ilmusk.com",

  "result"; "https://urlscan.io/result/884ac886-de83-42d4-98b1-85fb319916b0/",
  "url": "http://kraken.top",

  "result"; "https://urlscan.io/result/c9865349-e34c-4886-ab75-546add416d8c/",
  "url": "http://krakeninvestmentfund.com",

  "result"; "https://urlscan.io/result/30cb2a40-5eaf-4223-b14c-a186dc539c2f/",
  "url": "http://krakenjp.com",

  "result"; "https://urlscan.io/result/53edebe4-6214-47c5-bb8a-392b3545d11f/",
  "url": "http://liquiditycrypto.com",

  "result"; "https://urlscan.io/result/36a7ee5b-82fc-455b-bafa-0710cd0e4083/",
  "url": "http://login.coinbase.accounts.e8ja.day",

  "result"; "https://urlscan.io/result/a0a0d11c-2348-4f7b-9811-f1fc09a9d3a0/",
  "url": "http://login.coinbase.verifymypassword.com",

  "result"; "https://urlscan.io/result/e432f645-7758-49e5-8ee9-38628e8872d8/",
  "url": "http://martian-wallet.com",

  "result"; "https://urlscan.io/result/45b9a75d-0302-428f-b67b-431907449750/",
  "url": "http://martian-wallets.com",

  "result"; "https://urlscan.io/result/b1c74f02-3df8-4c8d-b71a-5782ff243b1e/",
  "url": "http://maskiln.com",

  "result"; "https://urlscan.io/result/d66371ad-607c-46e5-841b-c633785fbb69/",
  "url": "http://merge.czbinance.repl.co",

  "result"; "https://urlscan.io/result/2fb9fa71-bc3d-48fa-8314-ba5da3aa3233/",
  "url": "http://metamask-zendesk.rf.gd",

  "result"; "https://urlscan.io/result/e1bae170-512d-4610-873a-b89fcac0f598/",
  "url": "http://metamask.dev",

  "result"; "https://urlscan.io/result/dca39f44-ba33-4e61-9eb9-14f0b4399f05/",
  "url": "http://metamask.io.community-scrutiny.in",

  "result"; "https://urlscan.io/result/f32e23ce-908e-4fb4-9b5e-de58efb04db5/",
  "url": "http://metamask.io.community-support.in",

  "result"; "https://urlscan.io/result/440e7e62-cf5e-42f3-a5ab-bb711d90973f/",
  "url": "http://metamask.io.merge.allfroofs.com",

  "result"; "https://urlscan.io/result/084c5602-2341-4ce6-afe6-c0bb6c49e439/",
  "url": "http://metamask.io.merge.idetgroup.com",

  "result"; "https://urlscan.io/result/a51cf68b-c27e-4fab-9cfe-72ec00716e0c/",
  "url": "http://metamask.ng",

  "result"; "https://urlscan.io/result/da6f89da-a697-4c51-a3a8-e89d649cdc19/",
  "url": "http://metamaskchat.com",

  "result"; "https://urlscan.io/result/70426278-b3e8-4a0b-9fc1-69e3165236b5/",
  "url": "http://metamaske.cc",

  "result"; "https://urlscan.io/result/2f216595-3607-43c2-86a5-b77d9e6a5dd4/",
  "url": "http://metamaske.me",

  "result"; "https://urlscan.io/result/103bc3ce-24b1-43db-a264-25b1cbe5c279/",
  "url": "http://metamaskwallet.life",

  "result"; "https://urlscan.io/result/004dc62d-d125-4358-b949-e6229262ac72/",
  "url": "http://officialmetamask.help",

  "result"; "https://urlscan.io/result/6b6b1a70-1bfb-4c38-9c8f-13dcd2412a0e/",
  "url": "http://otcethereum.com",

  "result"; "https://urlscan.io/result/7b2486e5-c436-4cc0-9cbd-72540dc46e62/",
  "url": "http://pancakeswap-money.com",

  "result"; "https://urlscan.io/result/ef1e9276-0c55-4595-8ed7-b36bc6548b3f/",
  "url": "http://pancakeswap.finance.cwap.in",

  "result"; "https://urlscan.io/result/3696e8da-069f-4458-91e0-42581047c95c/",
  "url": "http://pancakeswap.finance.go-next.in",

  "result"; "https://urlscan.io/result/06d3168b-d1ca-42d8-9719-9e40645183b7/",
  "url": "http://pancakeswap.finance.start-next.in",

  "result"; "https://urlscan.io/result/b7ef3b4a-6b50-4ce1-8728-91e21e4b4a6f/",
  "url": "http://pcrivnote.com",

  "result"; "https://urlscan.io/result/19aa9476-a984-46ae-adb7-4360d8bac655/",
  "url": "http://premint-xyz.app",

  "result"; "https://urlscan.io/result/dae201ab-2d1d-4ec6-9f7b-738b6c30720b/",
  "url": "http://radzimierz.com",

  "result"; "https://urlscan.io/result/f5c613a9-a3c1-47cf-9e57-dd88c581b903/",
  "url": "http://servehalflife.com",

  "result"; "https://urlscan.io/result/a14e6514-ea02-4769-8b22-6ae6d3a42c46/",
  "url": "http://spookysnwap.com",

  "result"; "https://urlscan.io/result/1b2738a8-2570-420f-abd4-36d3a48f2900/",
  "url": "http://start-next.in",

  "result"; "https://urlscan.io/result/22344333-8d06-4628-8d70-9878ba0d5063/",
  "url": "http://tcrustwallet.com",

  "result"; "https://urlscan.io/result/90af6876-7832-4cfb-a8ae-dc593d3cdc90/",
  "url": "http://tesla-bounty.repl.co",

  "result"; "https://urlscan.io/result/e3cb88d5-b992-4afe-8f8b-c0cd49939549/",
  "url": "http://tesla-bountys.repl.co",

  "result"; "https://urlscan.io/result/f4b16172-07c4-44fb-a88a-2a7793e08a65/",
  "url": "http://tesla-crypto.repl.co",

  "result"; "https://urlscan.io/result/2295d728-7125-449e-97ae-a4fa7548d045/",
  "url": "http://tesla-giveaway.repl.co",

  "result"; "https://urlscan.io/result/74b09db3-daa7-4306-9936-61ef16a55d88/",
  "url": "http://tesla.coinfund.repl.co",

  "result"; "https://urlscan.io/result/e73ed1bd-20af-4d80-a860-e93ef13b8cb2/",
  "url": "http://tnrustwallet.com",

  "result"; "https://urlscan.io/result/e826648d-9e50-4231-ab9a-6b06f974bf82/",
  "url": "http://trnustwallet.com",

  "result"; "https://urlscan.io/result/35a5f920-29f9-4054-9e40-f9f2bb7ba77f/",
  "url": "http://tronlinckcs-wallet.com",

  "result"; "https://urlscan.io/result/ac25517f-a4db-4472-ac34-1ca6ef14e161/",
  "url": "http://trusctwallet.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
```
metamaskchat.com
coinbasewallet.com.cn
metamask.io.community-support.in
metamask.io.community-scrutiny.in
```

**Review by dubstard — COMMENTED** [review]
add fake giveaways and "Ethereum doublers"
image

IoC
image

image

https://urlscan.io/search/#hash%3Ad1de21730854ea4db035a81914cb0bd57aa74d715af6f89b46a2d002917ca1ed

```
    "annualxrpgiv.com",
    "beargives.eventlive.repl.co",
    "binanceceo.info",
    "bnbdeal.net",
    "bnbdrop.info",
    "bnbgate.net",
    "bnbgive.info",
    "bnbgive.net",
    "bnbgiveme.com",
    "bnbhold.net",
    "bnbsend.net",
    "bnbweek.info",
    "coinbase.giveawayprogram.live",
    "cryptonow.gg",
    "cryptosevent.net",
    "cryptospace.gg",
    "czbnbx10.info",
    "czearn.net",
    "czevent.info",
    "czhold.net",
    "czjoin.com",
    "czstake.com",
    "cztake.info",
    "czwin.info",
    "elon2x-promo.com",
    "elonfinance-promo.com",
    "elonsevent.com",
    "emstake.net",
    "ethmerge2022.com",
    "ethmergegive.info",
    "financialnewstoday.net",
    "giveawayprogram.live",
    "ilangod.com",
    "ilmusk.com",
    "maskiln.com",
    "merge.czbinance.repl.co",
    "muskfinance-event.info",
    "pump-xrp.net",
    "right-xrp.com",
    "stakeevent.com",
    "stakejoin.com",
    "sweekswap.com",
    "tesla-2xprize.com",
    "x1000shibclaim.info",
    "xrp1giv.com",
    "xrpbradgiv.com",
    "xrpevent-finance.org",
    "xrpfirstgiv.com",
    "xrpgivs.com",
    "xrpgivtoday.com",
    "xrplegitgiv.com",
    "xrppost.com",
```

**Review by dubstard — COMMENTED** [review]
Remove duplicate
```
coinbase.giveawayprogram.live
```

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
