### PR TITLE
Whitelist metamaze.eu

### PR DESCRIPTION
**Pull request by JosPolfliet**
Hi,

Metamaze is a scale-up from Belgium focused on using Artificial Intelligence for intelligent document processing. Some customers are notifying us that our domain is blocked by the metamask extension due to the resemblance in name.

We are a legit company.

Home: https://metamaze.eu/
LinkedIn https://www.linkedin.com/company/metamaze/
Twitter https://twitter.com/meta_maze
Can you please whitelist us?

Thank you

Metamaze team

### CODE REVIEW

**Comment by Pruxis** [comment]
Related to https://github.com/MetaMask/eth-phishing-detect/issues/4518

**Comment by Pruxis** [comment]
Also related to https://github.com/MetaMask/eth-phishing-detect/issues/4518

**Comment by Pruxis** [comment]
Also related to https://github.com/MetaMask/eth-phishing-detect/issues/4973

**Review by Gudahtt — APPROVED** [review]
Thanks for the report! LGTM

**Pull request merged**
