### PR TITLE
Block 104 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
IDN| Punycode
-- | --
reṿoke.cash|xn--reoke-qv1b.cash
revóke.cash|xn--revke-2ta.cash
revọke.cash|xn--revke-481b.cash
revȯke.cash|xn--revke-8dc.cash
revokė.cash|xn--revok-b0a.cash
revoké.cash|xn--revok-fsa.cash
rèvoke.cash|xn--rvoke-4ra.cash
révoke.cash|xn--rvoke-bsa.cash
rẹvoke.cash|xn--rvoke-n51b.cash

</body>
</html>

```
    "1inch-app.cf",
    "1inch-app.ga",
    "1inch-app.gq",
    "1inch-app.ml",
    "1inch-app.tk",
    "arbium.finance",
    "binancexmetamask.pw",
    "bitaur.com",
    "co-coinbase.com",
    "etherairdrops.org",
    "ethscan.store",
    "fox-inu.tech",
    "giveaway-stepn.com",
    "giveuniswap.com",
    "ii-coinbase.com",
    "iogin.bloickchaln.com",
    "io-coinbase.com",
    "ir-coinbase.com",
    "jp-metamask.org",
    "jp-opensea.network",
    "jp-opensea.ooo",
    "jp-opensea.xyz",
    "kr-metamask.org",
    "logln.blockchalh.secureonllnelogin.com",
    "metamask-jp.org",
    "moonbirds-event.com",
    "moonbirds-event.xyz",
    "moonbirds-project.com",
    "opensea-jp.org",
    "opensea-jp.xyz",
    "opensea-nft.site",
    "opensea-nfts.com",
    "opensea.markets",
    "opensea.vg",
    "openseains.com",
    "pancakeswap-finance-v1.com",
    "pancakeswap-finance-v5.com",
    "pancakeswap-finance-v6.com",
    "pancakeswap-finance-v7.com",
    "pancakeswap-finance-v8.com",
    "pancakeswap-finance-v9.com",
    "pancakeswap.finance.0x0e09.site",
    "phantomm-wallet.us",
    "polygon-stake-app.com",
    "polygon-stake-app.org",
    "quickswap-exchange.online",
    "quickswap-exchange.pro",
    "quickswapexchange.pro",
    "reconfirmaccount-coinbase.com",
    "reovke.cash",
    "rervoke.cash",
    "reverifyaccount-coinbase.com",
    "revoke.cf",
    "revoke.ga",
    "revoke.gq",
    "revoke.ml",
    "revoke.tk",
    "revokedapp.support",
    "revokes.cash",
    "revokex.cash",
    "revokke.cash",
    "rewoke.cash",
    "stake-polygon.info",
    "stake-polygon.top",
    "stake-polygon.xyz",
    "staking-dapp.com",
    "trasts-wallets.store",
    "trrezorr-wallet.com",
    "trustwallet-compliance.com",
    "trustwalletportfolio.com",
    "trustwalletsurvey.com",
    "uniswap-airdrop2023.ddns.net",
    "uniswap1.top",
    "uniswapexchangedefi.com",
    "uniswapp.website",
    "wallet.exodus.com.americanfamilyadvisors.com",
    "wallet.exodus.com.amilbawa.com",
    "wallet.exodus.com.astromrsajid.com",
    "wallet.exodus.com.directsalespro.net",
    "wallet.exodus.com.istikhara.uk",
    "wallet.exodus.com.istikharalive.com",
    "wallet.exodus.com.madnimarkaz.com",
    "wallet.exodus.com.rabiahall.com",
    "wallet.exodus.com.rehmanresidentialapartment.com",
    "wallet.exodus.com.rohaniilajuk.com",
    "wallet.exodus.com.surveyproxies.com",
    "wallet.exodus.com.truckeefinancial.com",
    "wcdapconnect.pages.dev",
    "www-opensea.ink",
    "xn--reoke-qv1b.cash",
    "xn--revke-2ta.cash",
    "xn--revke-481b.cash",
    "xn--revke-8dc.cash",
    "xn--revok-b0a.cash",
    "xn--revok-fsa.cash",
    "xn--rvoke-4ra.cash",
    "xn--rvoke-bsa.cash",
    "xn--rvoke-n51b.cash",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block 
```
    "chainlink-event.xyz",
    "heni-airdrop.art",
    "binance-x-metamask.com",
    "criptogold.online",
```

**Review by dubstard — COMMENTED** [review]
block "event-axieinfinity.xyz",

**Review by dubstard — COMMENTED** [review]
block "planetbridgeswap.website",
image
image

**Review by tayvano — APPROVED** [review]
lgtm

some good lulz too

Screen Shot 2023-01-28 at 12 43 54 AM

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
