### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
ℹ Same scam, different domain.

1. Open random known scam site
2. Inspect IoCs
3. Search for more instances of this hash in other less-than-honest sites

image
image

https://urlscan.io/search/#hash%3AAF847989815CDBB9C1870B7B32A3B2BD92F0235753287C8676868261C98CA99E
image
image

https://urlscan.io/search/#hash%3Aead0e09f6ac19f6cde1eeeabed70b72d1ac34b792927aabb46f8a049f1846292
image
image

https://urlscan.io/search/#hash%3A42D6D510DA85527B104A9893E53F60EB9FF4B25336041532DADF8D5494E32CF9
https://urlscan.io/search/#hash%3A1412D9C2DF9A008EAB99865F6D513D269269C25E6C1E1D87CDD43C5E99FBCA41
https://urlscan.io/search/#hash%3A283a2c89f10d06927c5395e943365a63df8f3029d297b074427b3e7afd6c6dd3
https://urlscan.io/search/#hash%3A99C8AE449D64FCB85C6EF9B7183EB76B7B92F033AECE904C7DC7960FE839C9D3

```
		"0vvwvuniswap.top",
		"0vvwwuniswap.top",
		"0vwwuniswap.top",
		"accessnode.surge.sh",
		"adcon-wall.web.app",
		"airdrop-pancakeswap.pro",
		"airdropdefi.com",
		"algonodvault.online",
		"aligntools.live",
		"allchainsaunthenticator.live",
		"alldaapschain.live",
		"allwalletsvalidator.com",
		"apicollab.online",
		"app.coinodeservice.com",
		"app.mainetonline.org",
		"app.webtornadocash.com",	
		"apytechlink.online",
		"assetgroup.network",
		"assetrectification.io",
		"authenticateaddress.icu",
		"authprotocol.net",
		"autobugcalibrator.com",
		"avalaunchapp.online",
		"avvvvuniswap.top",
		"awuniswap.top",
		"awvwvvuniswap.top",
		"binanmainquest.quest",
		"binanmainrect.quest",
		"binanmainresolver.shop",
		"binanrector.online",
		"binansync.homes",
		"binarectifyresolve.xyz",
		"binaryoption-bachrein.cryptocurrencyexchanges.site",
		"binasolutionconnect.art",
		"binasyncart.online",
		"binasyncart.xyz",
		"binrectifier.site",
		"biswap-org-exchange.approc.com",
		"biswaponlinedapps.com",
		"bitautaffix.com",
		"bitflex.live",
		"bitgert.online",
		"blockchain-phrase.ml",
		"blockchain-recovery.ml",
		"blockchain-recovery.tk",
		"blockchain-wallets.tk",
		"blockchains-recovery.ml",
		"blockchains-recovery.tk",
		"blockchains-wallet.tk",
		"blockchains-wallets.tk",
		"blockscanfix.com",
		"bnarectifierer.quest",
		"bonus-pay.com",
		"bonusservies.com",
		"boredbunnny.com",
		"bridgcrypto.com",
		"bridgdapp.com",
		"bridgdapp.online",
		"bridgdapps.com",
		"bridge-41glvsnd.live",
		"bridge-app.co",
		"bridge-rfagwuc25l.live",
		"bridgedex.online",
		"bridges-link.online",
		"bridges-links.live",
		"cexus-master.com",
		"chainvalidator.tech",
		"click-here.one",
		"clouddigitaltray.com",
		"coinbasewallets.online",
		"coinpasc.com",
		"coinvault.exchange",
		"connectedbridges.live",
		"connectwallet.xslim.org",
		"correctionconnect.com",
		"crosswebfix.live",
		"daorectifier.com",
		"daovalidator.net",
		"daovalidator.xyz",
		"dapp.affixwallet.net",
		"dapprestoraccess.com",
		"datanodeschains.org",
		"decentralizenetworkinterface.com",
		"deficonfigure.com",
		"defimultiexpressfix.com",
		"defsyn.com",
		"defsync.com",
		"defysync.com",
		"defysyncd.com",
		"dexbridgelink.com",
		"dexcloudlink.com",
		"dexsmartrec.com",
		"diagnosticsbots.tech",
		"digitalvaultbridge.tech",
		"drelapp.link",
		"drvapp.link",
		"eblockconnect.live",
		"en.appchainsauth.com",
		"en.livecosystem.com",
		"erroresolver.art",
		"esychaindexxio.com",
		"ethereum-mainnet.xyz",
		"ethereum-merger.com",
		"unipool.online",
		"ethereum-usdt-jfdisil.com",
		"ethereum-validator.info",
		"ethermine-airdrop.com",
		"ethpow.ink",
		"exchangeconnect.art",
		"expressnetinterface.com",
		"exxplorerprotocol.online",
		"fastrectifier.com",
		"fixernet.live",
		"fixerspotweb.live",
		"fixsolutionwallet.000webhostapp.com",
		"frafchaincoldstorage.com",
		"gaterateway.art",
		"getcoins.eu",
		"holdervalidator.icu",
		"hsbcabsb.ycab.org",
		"https-metamask.ddns.net",
		"https-walletconnect.com",
		"hubconnect.me",
		"hubsystem-syncnetwork.net",
		"hubvalidator.net",
		"interline-asia.com",
		"irs.us.irssm.co",
		"itvission.com",
		"iwallet.live",
		"krowfund.network",
		"launch-dapp.herokuapp.com",
		"launch-my-wallet.netlify.app",
		"launchpads.herokuapp.com",
		"launnchh.netlify.app",
		"lcfy.org",
		"login.coinbase.com.appcoinbaseauth.com",
		"mainbibanres.store",
		"maindappsweb.com",
		"mainnetsyncer.live",
		"mainodes.com",
		"mainrectifier.live",
		"mainsyncenet.com",
		"mainttdapp.com",
		"merge-ethereum.com",
		"metakongzclaim.one",
		"metamask.i0.id74853758.in",
		"metamask.io.id343556788987655.in",
		"moduleprotocol.com",
		"modulesct.com",
		"moduleweb3.com",
		"multialignfix.site",
		"multifix-links.com",
		"multinetworkinterface.com",
		"multiuse-chainserver.net",
		"mydaolink.tech",
		"mynodesprotocol.com",
		"mysmartswing.com",
		"netlifyasset.com",
		"nft-and-gift-baa257.ingress-comporellon.ew",
		"nft.niron-capital.com",
		"nk-authcoinbase.com",
		"nodaffix.com",
		"nodesauths.com",
		"nodestringtool.live",
		"openprotocol.xyz",
		"osynclive-nds.info",
		"p-stkconn.online",
		"pancakecwap.exchange",
		"pancakeswaap.pw",
		"pancaketransfer.com",
		"pancakeswap-finance.top",
		"pancakeswap.finance.dackrengas.top",
		"pancakeswap.fs.video",
		"pancakeswap.pro",
		"porkexverse.com",
		"projectsinterface.fr-par.site",
		"rawefdsr.sbs",
		"recognitionaward.link",
		"rectifybinan.quest",
		"rectifyconn.site",
		"rectifyconns.site",
		"resetcnt.com",
		"resolvemaster.live",
		"resolveprocess.com",
		"royalbitcoinexchange.org",
		"royalexchangecrypto.com",
		"safeblocknetwork.live",
		"safetyconnectcenter.com",
		"sale-metagear.online",
		"selftool.online",
		"slotmetamaskshop.com",
		"smartautsolution.com",
		"smartechapps.com",
		"stackchainledger.com",
		"stakedapps.online",
		"stakingdex.online",
		"subulussalamkota.desa.id",
		"swiftappsfixed.com",
		"syn-validationchain.com",
		"sync.universalresolve.net",
		"syncdatanodes.org",
		"synchdatachain.org",
		"syncl.000webhostapp.com",
		"synconnect.link",
		"syncresolved.online",
		"syncresolved.xyz",
		"syndefn.com",
		"syndefs.com",
		"techappaccess.com",
		"thewallet-sync.com",
		"trustcoinbasewallet.com",
		"trustwallet-updates.estacionamientoaeropuertosantiago.cl",
		"uniquecryptonftpunk.io",
		"uniswap-app.org",
		"uniswap-login.pw",
		"uniswap-ui-fork-eez.pages.dev",
		"uniswap-verif.com",
		"uniswap-zeit.now.sh",
		"uniswapchads.com",
		"uniswapexchangefinance.com",
		"uniswappil.com",
		"unixgren.com",
		"useraddressinfo.icu",
		"validatemywalletservice.com",
		"validateverify.shop",
		"validatordapps.com",
		"vaultseedify.online",
		"verifydot-websynyc.org",
		"verifyresolve.shop",
		"wal-connects.live",
		"waletbridge.com",
		"wallet-brigdes.live",
		"wallet-connects.herokuapp.com",
		"wallet-dapp.net",
		"walletcoinbases.com",
		"walletconnect-protect.org",
		"walletconnect-secured.crypto247network.com",
		"walletdappsprotocol.cf",
		"wallets.scourcloud.com",
		"walletscoinbase.com",
		"walletvalidationportal.netlify.app",
		"walsyncvalidation.com",
		"wc.entronbit.xyz",
		"web-dpps.netliweb.live",
		"web.flowlinksapp.com",
		"web3-syntaxx.com",
		"web3dappsconnect.com",
		"webauttaffix.com",
		"webresolver.live",
		"webresolvernode.net",
		"webservernode.net",
		"websmartauths.com",
		"webwalletconnect.com",
		"westsideblock.center",
		"wonderlandmoneey.online",
		"wonderlandmoneyy.online",
```

```
$ ./BurnTrash.sh | egrep '(result|url)'

  "result": "https://urlscan.io/result/c74e57ab-8786-4adc-be90-4ee9ea0f98f5/",
  "url": "http://0vvwvuniswap.top",

  "result": "https://urlscan.io/result/a5214b2c-3fb7-4dbe-b3a2-7d69ef216e04/",
  "url": "http://0vvwwuniswap.top",

  "result": "https://urlscan.io/result/95b2cc50-858b-4d8e-a74b-8269f6b10c03/",
  "url": "http://0vwwuniswap.top",

  "result": "https://urlscan.io/result/aa7375c3-19bc-494d-8335-5f477e5fb6c8/",
  "url": "http://accessnode.surge.sh",

  "result": "https://urlscan.io/result/464aba12-2a41-45fb-9830-ada9385f743a/",
  "url": "http://adcon-wall.web.app",

  "result": "https://urlscan.io/result/5a0b9161-8373-4ceb-9de5-f90c6c4d15dc/",
  "url": "http://airdrop-pancakeswap.pro",

  "result": "https://urlscan.io/result/6e0ef0ef-d626-494f-a20f-ebba9301a9a3/",
  "url": "http://airdropdefi.com",

  "result": "https://urlscan.io/result/489343d5-6b96-4353-8d94-62eb4ff7a40d/",
  "url": "http://autobugcalibrator.com",

  "result": "https://urlscan.io/result/19377968-8ee0-4ed5-8ad8-d4dbed1c3def/",
  "url": "http://avvvvuniswap.top",

  "result": "https://urlscan.io/result/7d84a878-3cf2-4145-b1f6-7eee0db3d506/",
  "url": "http://awuniswap.top",

  "result": "https://urlscan.io/result/7b88a70e-2e1c-403c-b33b-e8384e775bcc/",
  "url": "http://awvwvvuniswap.top",

  "result": "https://urlscan.io/result/903ed54c-c988-43e3-92eb-d54f667dd751/",
  "url": "http://binaryoption-bachrein.cryptocurrencyexchanges.site",

  "result": "https://urlscan.io/result/3cb4436b-7e1c-451f-9b48-183f790277df/",
  "url": "http://biswap-org-exchange.approc.com",

  "result": "https://urlscan.io/result/eccc60e7-c277-404b-a9f0-d981a5ad6689/",
  "url": "http://bnarectifierer.quest",

  "result": "https://urlscan.io/result/568ace2e-a298-4abd-86f3-3765778d0e72/",
  "url": "http://boredbunnny.com",

  "result": "https://urlscan.io/result/c8196cbe-59ea-46e7-8a03-e354c67ffc24/",
  "url": "http://bridgcrypto.com",

  "result": "https://urlscan.io/result/9711e1f6-2800-40f4-86c8-9dda08b07323/",
  "url": "http://coinbasewallets.online",

  "result": "https://urlscan.io/result/0cfeedde-9c80-4a41-8307-12280c3a1532/",
  "url": "http://coinvault.exchange",

  "result": "https://urlscan.io/result/16bc76cc-b50f-4a81-ac74-b227248b975f/",
  "url": "http://correctionconnect.com",

  "result": "https://urlscan.io/result/1c3e470e-1c80-4800-961a-b32e172a684d/",
  "url": "http://dapp.affixwallet.net",

  "result": "https://urlscan.io/result/20c71c24-dc57-40a7-9f8f-bde4631f0377/",
  "url": "http://dapprestoraccess.com",

  "result": "https://urlscan.io/result/419364d6-9aea-4f1c-94ca-59f5447316f2/",
  "url": "http://diagnosticsbots.tech",

  "result": "https://urlscan.io/result/3ee69b88-befd-41fe-842b-74734d603353/",
  "url": "http://drvapp.link",

  "result": "https://urlscan.io/result/e2b67b23-eadc-4e44-b18b-f4ef2a5bf105/",
  "url": "http://esychaindexxio.com",

  "result": "https://urlscan.io/result/a163426d-5286-4b79-afb2-719f9c7a1bbc/",
  "url": "http://ethereum-mainnet.xyz",

  "result": "https://urlscan.io/result/e62fc512-ea40-4dae-9b28-2c86934e2f47/",
  "url": "http://ethereum-merger.com",

  "result": "https://urlscan.io/result/ed7c692c-1f97-4cc8-96d2-0498cf8a3e61/",
  "url": "http://ethereum-validator.info",

  "result": "https://urlscan.io/result/f9790f22-b412-4e48-aee0-e0f241d7e76b/",
  "url": "http://fixsolutionwallet.000webhostapp.com",

  "result": "https://urlscan.io/result/d9d5741d-f117-429f-aa24-66daadbef37a/",
  "url": "http://getcoins.eu",

  "result": "https://urlscan.io/result/a159b0f1-86ea-4856-b77f-204aed0f0afa/",
  "url": "http://hsbcabsb.ycab.org",

  "result": "https://urlscan.io/result/cd412210-ed17-4503-942b-7f22d5cb803e/",
  "url": "http://https-metamask.ddns.net",

  "result": "https://urlscan.io/result/fc5dc825-d62e-46b7-af1e-493a634e92e7/",
  "url": "http://interline-asia.com",

  "result": "https://urlscan.io/result/540da515-bc83-47c1-a122-464f4a6e8e69/",
  "url": "http://launch-dapp.herokuapp.com",

  "result": "https://urlscan.io/result/ae01f409-a4ee-43d2-9117-3edd99aefcf0/",
  "url": "http://launch-my-wallet.netlify.app",

  "result": "https://urlscan.io/result/2ed50212-97ff-4bb9-a50c-d42de03b0cf2/",
  "url": "http://launchpads.herokuapp.com",

  "result": "https://urlscan.io/result/7658688e-50da-4678-8578-8d516b0f1869/",
  "url": "http://launnchh.netlify.app",

  "result": "https://urlscan.io/result/e499e6ac-1959-4a2d-9e4c-e7b9d542f87b/",
  "url": "http://maindappsweb.com",

  "result": "https://urlscan.io/result/52946b99-bd5b-4af6-b936-fd98da8aa960/",
  "url": "http://merge-ethereum.com",

  "result": "https://urlscan.io/result/21111b7f-71ed-4c17-83c3-00b05e8b2668/",
  "url": "http://metamask.io.id343556788987655.in",

  "result": "https://urlscan.io/result/feae37d1-f5ac-4194-baf0-4662f1044c75/",
  "url": "http://moduleprotocol.com",

  "result": "https://urlscan.io/result/820df65b-0e13-4d8b-8f98-f481c960df07/",
  "url": "http://mynodesprotocol.com",

  "result": "https://urlscan.io/result/3b6fabad-0cdf-467c-a1db-c056af110cb9/",
  "url": "http://netlifyasset.com",

  "result": "https://urlscan.io/result/917a3a8e-dbc2-4744-82ca-1a355a7e9281/",
  "url": "http://osynclive-nds.info",

  "result": "https://urlscan.io/result/aa43c9a8-5b38-4729-a36a-fa9a3c717bfc/",
  "url": "http://pancakeswaap.pw",

  "result": "https://urlscan.io/result/7cb420b6-bbd9-422b-b591-0aff9d5c1153/",
  "url": "http://pancaketransfer.com",

  "result": "https://urlscan.io/result/15b01996-4544-4c9e-906a-f6e563f5ce68/",
  "url": "http://pancakeswap-finance.top",

  "result": "https://urlscan.io/result/3f66c56b-2fff-4138-a20f-c9e65c880cdd/",
  "url": "http://pancakeswap.finance.dackrengas.top",

  "result": "https://urlscan.io/result/52e1c340-ac2d-406b-95f4-fd126792d62a/",
  "url": "http://pancakeswap.fs.video",

  "result": "https://urlscan.io/result/a4895074-c091-4807-958f-8ff8d9898999/",
  "url": "http://pancakeswap.pro",

  "result": "https://urlscan.io/result/aac9da53-f35a-4e92-a86d-f4552e2b88fc/",
  "url": "http://resolveprocess.com",

  "result": "https://urlscan.io/result/03d8d280-8362-42c5-b72f-24ca73ca1186/",
  "url": "http://royalbitcoinexchange.org",

  "result": "https://urlscan.io/result/063cb31c-200e-447c-b3af-2bb4788ceed5/",
  "url": "http://royalexchangecrypto.com",
```

IoCs
```
https://urlscan.io/search/#hash%3AAF847989815CDBB9C1870B7B32A3B2BD92F0235753287C8676868261C98CA99E
https://urlscan.io/search/#hash%3Aead0e09f6ac19f6cde1eeeabed70b72d1ac34b792927aabb46f8a049f1846292
https://urlscan.io/search/#hash%3A42D6D510DA85527B104A9893E53F60EB9FF4B25336041532DADF8D5494E32CF9
https://urlscan.io/search/#hash%3A1412D9C2DF9A008EAB99865F6D513D269269C25E6C1E1D87CDD43C5E99FBCA41
https://urlscan.io/search/#hash%3A283a2c89f10d06927c5395e943365a63df8f3029d297b074427b3e7afd6c6dd3
https://urlscan.io/search/#hash%3A99C8AE449D64FCB85C6EF9B7183EB76B7B92F033AECE904C7DC7960FE839C9D3
```

### CODE REVIEW

**Comment by dubstard** [comment]
Removing duplicates:
```
biswaponlinedapps.com
blockchain-wallets.tk
blockchains-wallet.tk
blockchains-wallets.tk
ethereum-validator.info
https-metamask.ddns.net
https-walletconnect.com
launchpads.herokuapp.com
mainttdapp.com
merge-ethereum.com
nk-authcoinbase.com
nodesauths.com
openprotocol.xyz
rectifybinan.quest
swiftappsfixed.com
walletconnect-secured.crypto247network.com
```

And one FP that almost slipped in
```
uniswap-graph.0xplutus.com
```

**Review by dubstard — COMMENTED** [review]
Removing duplicates:
```
biswaponlinedapps.com
blockchain-wallets.tk
blockchains-wallet.tk
blockchains-wallets.tk
ethereum-validator.info
https-metamask.ddns.net
https-walletconnect.com
launchpads.herokuapp.com
mainttdapp.com
merge-ethereum.com
nk-authcoinbase.com
nodesauths.com
openprotocol.xyz
rectifybinan.quest
swiftappsfixed.com
walletconnect-secured.crypto247network.com
```

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks

**Pull request merged**
