### PR TITLE
Add sites to blocklist [ 14 ]

### PR DESCRIPTION
**Pull request by ShenWe0x**
Add sites to blocklist

Phishing Airdrop Claim website

https://twitter.com/syncswop/status/1748777734359429154
https://twitter.com/SinceIbrahim/status/1749411137337110688
https://twitter.com/LancedBeltran/status/1749418531794334151
https://twitter.com/darkvampy1994/status/1749384156893589968
https://twitter.com/darkvampy1994/status/1749389380207222791
https://twitter.com/KidrauhlzArmy/status/1748999110483472635
https://twitter.com/alysha_d/status/1749088002712936829
https://twitter.com/DcAmineMesky/status/1749396472653631675

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@ShenWe0x  i am removing the tornado.ws domain because it is listed as the website for a token on CMC.

**Comment by ShenWe0x** [comment]
> @ShenWe0x i am removing the tornado.ws domain because it is listed as the website for a token on CMC.

You're correct that it has been added to CMC and Coingecko, but the original domain is tornado.cash, and this website was likely created during the hack, possibly added to CMC and Coingecko at that time. They updated the domain by providing proof from the contract. However, there are hidden codes in the JS files on the mentioned website that shouldn't be there.

**Comment by ShenWe0x** [comment]
The hacker who seized control can maintain control because I don't believe anyone else can update the domain without proof. CMC doesn't update the domain without evidence. If this is the proof, it is highly likely that the hacker who hacked the DAO did this. This is because there are multiple hidden codes in the JavaScript files of the website that looks original, and I am certain that the Eset team labeling the site indicates the presence of unwanted types of code in the files. Moreover, almost the entire structure is different from the original GitHub repository codes; everything seems to have been completely re-coded, from the JavaScript files running in the background to the gzip files.

Nevertheless, the decision is, of course, yours. I reviewed it because someone requested it through another PR. Whether to remove the domain from the list is entirely up to you.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by ShenWe0x** [comment]
My concern is that I am aware of a loss of around $10 million during the Dao hack. The person behind this must be a high-level hacker because the Dao has not been hacked before. I believe that for someone so professional, updating on CMC should not be difficult.

**Comment by aredkina205** [comment]
> Add sites to blocklist
> 
> Phishing Airdrop Claim website
> 
> https://twitter.com/syncswop/status/1748777734359429154 https://twitter.com/SinceIbrahim/status/1749411137337110688 https://twitter.com/LancedBeltran/status/1749418531794334151 https://twitter.com/darkvampy1994/status/1749384156893589968 https://twitter.com/darkvampy1994/status/1749389380207222791 https://twitter.com/KidrauhlzArmy/status/1748999110483472635 https://twitter.com/alysha_d/status/1749088002712936829 https://twitter.com/DcAmineMesky/status/1749396472653631675
> 
> Tornado.ws - SCAM***
> 
> https://tornado.ws/cdn-cgi/challenge-platform/scripts/jsd/main.js https://tornado.ws/cdn-cgi/challenge-platform/h/b/scripts/jsd/c8377512/main.js https://tornado.ws/cdn-cgi/challenge-platform/h/b/jsd/r/845f93698f93c268
> 
> The relevant JavaScript files were examined and dangerous code was detected. This was also confirmed by the Eset team. I requested the existing JavaScript files to be examined and as a result of the review, the site was marked as '**Potentially unwanted content**'.
> 
> I suspect that the official-looking website is actually under the control of a hacker who gained access via DAO hacking.
> 
> 

Hello, /cdn-cgi/challenge-platform may be using a javascript-detections service enabled by cloudflare by default. This is the introduction information https://developers.cloudflare.com/bots/reference/javascript-detections/

**Comment by aredkina205** [comment]
> > @ShenWe0x i am removing the tornado.ws domain because it is listed as the website for a token on CMC.
> 
> You're correct that it has been added to CMC and Coingecko, but the original domain is tornado.cash, and this website was likely created during the hack, possibly added to CMC and Coingecko at that time. They updated the domain by providing proof from the contract. However, there are hidden codes in the JS files on the mentioned website that shouldn't be there.

tornado.cash is the earliest official community website. Later, tornado.cash was sanctioned. Now multiple teams have forked and continued to develop and launched different versions.

**Pull request merged**
