### PR TITLE
Erroneous phishing site deletion

### PR DESCRIPTION
**Pull request by dongri**
tofunft.com is not a phishing site

### CODE REVIEW

**Comment by dongri** [comment]
@409H @devenblake @AlexHerman1 @ethphishingmaintainer1000 This is urgent. Please review

**Review by ukishima — APPROVED** [review]

**Review by FrederikBolding — APPROVED** [review]

**Comment by FrederikBolding** [comment]
Thanks for opening a PR to correct this issue! The change should be reflected in MetaMask within a few hours max.

**Comment by dongri** [comment]
@FrederikBolding Thanks!

**Comment by 409H** [comment]
@dongri I'll also follow up internally to add these domains to our CI test (https://github.com/MetaMask/eth-phishing-detect/blob/main/test/dapps.json) to make sure CI fails if added again

**Pull request merged**
