### PR TITLE
Remove FP balancer-marketing.pages.dev

### PR DESCRIPTION
**Pull request by dubstard**
Remove FP balancer-marketing.pages.dev from blocked sites.
it was blocked in https://github.com/MetaMask/eth-phishing-detect/pull/9927

```
Here's a msg coming from our marketing team. Can you give this a look? 
Hi, you recently linked to a dubstard report. Some of our preview URLs for our marketing site currently get the Metamask phishing warnings. thinks it's because dubstard has potentially flagged them.
Can you check with him, if these sites are flagged? If so, can you get him to remove them from the list:
https://7726377f.balancer-marketing.pages.dev/
https://nuxt3.balancer-marketing.pages.dev/
You can see that they are automatically generated via our Github: https://github.com/balancer-labs/marketing-site/pull/31
```
image

### CODE REVIEW

**Comment by dubstard** [comment]
Hm great catch! Let me check with the Balancer team. Looks like they use the pages.dev quite a lot.

**Comment by dubstard** [comment]
The team responded
`Yeah, please remove it.`

**Review by dubstard — COMMENTED** [review]
remove balancer-tests.pages.dev

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
