### PR TITLE
Adding phishing sites to blocklist [5]

### PR DESCRIPTION
**Pull request by AlexHerman1**
addresses #13714
addresses #13716
addresses #13719
addresses #13720 
ZD 1085684

    "ecoinchanger.com",
    "instantexchange.net",
    "boomchange.com",
    "binacy.com",
    "ai-moveworks.info",

### CODE REVIEW

**Review by deshvin — APPROVED** [review]

**Comment by User-Jack22** [comment]
Please remove Boomchange.com from blocklist . Just because someone wanted to do something bad for Boomchange.com
(Maybe competitors) . The site is over 1.5 years old

**Comment by User-Jack22** [comment]
Need your help , 1 or 2 complaints cannot judge a site that has over 5,000 customers.

**Comment by Uscompanylaw** [comment]
Please remove Boomchange.com from blacklist , its 100% legit website .

**Comment by Rodriguez3234** [comment]
Please add boomchange.com into whitelist because its safe and normal working website.

**Comment by Uscompanylaw** [comment]
> addresses #13714 addresses #13716 addresses #13719 addresses #13720 ZD 1085684
> 
> ```

> "boomchange.com",

> ```

The account that opened the fake Issues about us has been deleted by Github Please add our domains to the whitelist (Boomchange.com and Boomchange.io)

**Pull request merged**
