### PR TITLE
Block 107 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "1inch-coin.com",
    "1inch.exchanges.help",
    "aaveprotocol.us",
    "anuyswap.com",
    "balancer-app.top",
    "balancer-app.xyz",
    "balancer-fi.live",
    "balancer.com.cn",
    "balancer.us.com",
    "balancerfii.com",
    "binancepay.info",
    "bitcoingenics.com",
    "bolancerfi.com",
    "cardanofoundation-1.org",
    "cardanofoundation-2.org",
    "cardanofoundation-3.org",
    "claim-porsche.com",
    "coinbase-securee.myddns.me",
    "coinbiss.com",
    "coingateescrow.com",
    "contactmetamask.org",
    "cryptohasbuiianft.com",
    "cryptotop.cyou",
    "cryptotop.icu",
    "dai-events.com",
    "debankconnect.com",
    "defillama.foundation",
    "defiprotocol-live.online",
    "dexcointrade.com",
    "ehtminne.com",
    "eth-arbitrum.com",
    "ethereum-porsche.com",
    "ethmergex.net",
    "ex-wallets.net",
    "foundation-tezos.net",
    "foundationtezos.com",
    "foundationtezos.net",
    "foundationtezos.org",
    "funtesttutoring.com",
    "gitcoin.fund",
    "helenaclaim.com",
    "in-stellar.org",
    "lidofinance.pro",
    "looks-rares.com",
    "luncairdropppl.duckdns.org",
    "mdex-home.link",
    "metaltrader.comon.wallet-near.xyz",
    "metamask.io-4r3s.16-74.site",
    "metamask.nordgroup.io",
    "metamask.uk.to",
    "metamaskio8.com",
    "metamaskmtalearning.com",
    "mirror-web3.site",
    "mutantdao.art",
    "mutantdao.club",
    "niftygetaway.pro",
    "nixtradingltd.com",
    "official-aave.com",
    "officially-porsche.com",
    "optlmism.io-serviceflow.com",
    "pancakeswap.biociencias.com",
    "pancakeswap.us.org",
    "penguins-pudgy.com",
    "pudgy-penguins.store",
    "reward-arbitrum.com",
    "ripple.org.im",
    "ripple.org.ve",
    "rocketnexo.com",
    "safecaptal.com",
    "seeclify.pro",
    "shibatoken.space",
    "stellar.org.ge",
    "stellar.org.hn",
    "stellar.org.pe",
    "stellar.org.ph",
    "sushiswap-airdrop.xyz",
    "telebotpilot.com",
    "tenset.pro",
    "tenset.top",
    "tez-foundation.com",
    "tez-foundation.net",
    "tez-foundation.org",
    "tezfoundation.com",
    "tezfoundation.net",
    "tezfoundation.org",
    "thetamadoge.com",
    "trust-wallet-earning.cf",
    "trust-wallet-earning.ga",
    "trust-wallet-earning.gq",
    "trust-wallet-earning.ml",
    "trust-wallet-earning.tk",
    "u-opensea.com",
    "uniswap-help.com",
    "uniswap-lp.net",
    "uniswap-lp.org",
    "uniswap-promo.com",
    "uuniswap.myisaproducts.com",
    "us-porsche.com",
    "web3apigm.tk",
    "web3bcta.com",
    "webapppt.tk",
    "xtzfoundation.net",
    "zapper.web3bcta.com",
    "zkmoney.mirror-web3.site",
    "zksync.team",
    "zksyncwallet.airdrops.shop",
```

Fresh spam from today (discord):
image

Fresh spam from today (twitter):
image

Fake Porsche
image
image
image

Fake Balancer
image

Fake Uniswap "2fa"
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate "app.airdroplert.com",
already exists line 1169

**Review by dubstard — COMMENTED** [review]
All conveniently hosted on the same IP https://www.virustotal.com/gui/ip-address/93.189.42.5/community

```
    "cardanofoundation-1.org",
    "cardanofoundation-2.org",
    "cardanofoundation-3.org",
    "foundation-tezos.net",
    "foundationtezos.com",
    "foundationtezos.net",
    "foundationtezos.org",
    "in-stellar.org",
    "optlmism.io-serviceflow.com",
    "ripple.org.im",
    "ripple.org.ve",
    "stellar.org.ge",
    "stellar.org.hn",
    "stellar.org.pe",
    "stellar.org.ph",
    "tez-foundation.com",
    "tez-foundation.net",
    "tez-foundation.org",
    "tezfoundation.com",
    "tezfoundation.net",
    "tezfoundation.org",
    "xtzfoundation.net",
```

**Review by dubstard — COMMENTED** [review]
block "dexcointrade.com", discord spam 419 scam
Unsolicited DMs about advance fee scam (you won fake money, but need to deposit real money as “verification”.)

Anything sent is lost.

Advance fee scam or 419 scam.
image

**Review by dubstard — COMMENTED** [review]
Block 10 scams, [all hosted on the same IP](https://www.virustotal.com/gui/ip-address/194.36.191.196/relations)


```
    "bitcoingenics.com",
    "coinbiss.com",
    "coingateescrow.com",
    "cryptotop.cyou",
    "cryptotop.icu",
    "ehtminne.com",
    "ex-wallets.net",
    "nixtradingltd.com",
    "rocketnexo.com",
    "safecaptal.com",
```

**Review by dubstard — COMMENTED** [review]
trim empty lines

**Review by dubstard — COMMENTED** [review]
block "us-porsche.com",
https://urlscan.io/result/790f1e53-251e-4c70-9e19-e240bebe8ee5/

**Review by dubstard — COMMENTED** [review]
remove duplicate "officially-porsche.com",
keep only "us-porsche.com", (registered today)

**Review by dubstard — COMMENTED** [review]
block `"web-porsche.com",`

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
Yes.
Thanks!

**Pull request merged**
