### PR TITLE
unblock legit website

### PR DESCRIPTION
**Pull request by Gamingbro123**
@legobeat please help us remove this site from blocklist

### CODE REVIEW

**Comment by Gamingbro123** [comment]
@409H please help

**Comment by Gamingbro123** [comment]
@alexherman1
help

**Comment by Gamingbro123** [comment]
@alexherman1 please don't reject my request kindly accept my request

**Comment by Gamingbro123** [comment]
@alexherman1 Please I beg to you for this

**Comment by Gamingbro123** [comment]
@Alexherman1 you are my last hope

**Comment by Sufi333** [comment]
Please unblock this site as soon as BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!

I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.

**Comment by bin786** [comment]
BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!

I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.

**Comment by Demolator1987** [comment]
BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!

I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.

**Comment by Sufi333** [comment]
Please unblock this site'fep faucet

**Comment by JimmiAugust** [comment]
https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509
You guys can check all transactions by this Faucet ☺️ i hope you guys will know this is not scam.

**Comment by vanhuyit89** [comment]
MetaMask/devs: please remove block, this is trush site.

**Comment by csr5lainez** [comment]
BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!

I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.

**Comment by Demolator1987** [comment]
I will say this: each of the Fautec participants made a standard fee for a smart cotract of $0.06 For every field from which he wanted to extract tokens. The maximum day of profit from the tap for the most patient is $ 0.5, it was enough to collect their tokens from a given field every 15 minutes to continue collecting. And so for 24 hours. So the real profit for each of us who used the tap was $ 0.25 on the field he chose. In addition, prizes were paid regularly until there was a group of people who wanted to easily earn a lot without putting anything into the project, for which they got a ban.On the same principle, after all, many dapps work, except that to earn you have to put a lot of tokens and I'm talking about projects such as spacemining or smartmining, except that it is best to put 0.5BNB there and reinvest every day additionally paying gas for a smart contract. Now let the metamask team analyze what could be a bigger scam. Because the maximum on Bep-Faucet our fee was $ 0.36 with a real profit of $ 3 per day and regular payments of min $ 6 every 48 hours or sites that offer to earn a profit of 250k$ in 3 months with a deposit of 300$ and somehow so far have not been blocked, and there is the same amount of time as Bep-faucet

**Comment by csr5lainez** [comment]
BEP Faucet is a legitimate site that pays out rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge!

I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config.json
I kindly request that GitHub admins remove this domain from the phishing list.

**Pull request closed without merging**
