### PR TITLE
Add "victus.finance" to the whitelist.

### PR DESCRIPTION
**Pull request by daedboi**
Issue was raised earlier but I read that PRs are reviewed quicker, my website has been blacklisted due to similarity to "auctus.org". I don't bear any connection with them, this is my own site and isn't fraudulent.

Thanks for reviewing!

#5364

### CODE REVIEW

**Comment by daedboi** [comment]
@409H Hello, would it be possible to resolve this quickly, as my project is time-sensitive, and I would be very grateful for your understanding. Thanks!

**Comment by davidwgrossman** [comment]
@daedboi I'm a bit confused...the Twitter link on their site points to [@PlatinumPolygon](https://twitter.com/PlatinumPolygon) which has no reference to Victus Finance on their site. Is there any way I can verify that this site is legit?

However, I would note that it is clearly not impersonating actus.org, so we may be able to give the site the benefit of the doubt

**Comment by daedboi** [comment]
@davidwgrossman Hello, PlatinumPolygon is my previous project comprising of 2 yield farms on the Polygon network, and Victus is my new one on the Avalanche network. I haven't created the Twitter for it yet, hence the timeline shows my old project's Twitter. My other github which has the code for those sites is @polydaedalus. You can also see that the first commit for the front-end on this Github account is from that account.

**Comment by daedboi** [comment]
If there is anything else that you may require please let me know, I would be extremely grateful if this can be resolved within the next 24 hours, thanks!

**Review by gravelcycles — APPROVED** [review]

**Comment by daedboi** [comment]
@davidwgrossman Hello, thanks for approving this! How long should the changes take to propagate, as I still receive the MetaMask phishing page when trying to view my site.

**Comment by davidwgrossman** [comment]
The cache should update within 24-48 hours however it may take longer.

**Pull request merged**
