### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by kellyfends**

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@kellyfends  can you pls dedupe this pr?

**Comment by kellyfends** [comment]
[18afe0d] dont have dupe

**Comment by kellyfends** [comment]
> @kellyfends can you pls dedupe this pr?

no dupl list here:

 "3000usdt.com",
    "stethlido.com",
    "apyeth.io",
    "zxpool.net",
    "etoroclaim.com",
    "claim.opensea-drop.com",
    "bids-opensea.web.app",
    "update-opensea.web.app",
    "pepe-distribution.com",
    "pancake-distribute.com",
    "claimpepe20.vip",
    "debank-x.com",
    "blurregister.com",
    "migration-lightningbot.xyz",
    "decryptco.com",
    "dash2trade.us.com",
    "op-reward.net",
    "pay.pancakesfiance.com",
    "syncwasp.xyz",
    "stakingpaalai.xyz",
    "polyguard.one",
    "aitrader.site",
    "1ex.info",
    "connects-bankless.org",
    "review-wallet-activity.com",
    "retsync.pages.dev",
    "op-claims.net",
    "nakamigos-drops.com",
    "maskclaim.top",
    "poly-guards.web.app",
    "criptopulse.xyz",
    "memeswallstreet.com",
    "chimpers.space",
    "coinsraise.com",
    "mail-ftx.com",
    "claimoptimism.org",
    "h2finance.io",
    "entanmo.io",
    "nnetamask.io",
    "lidoairdrop.io",
    "argent.claims",
    "apy-eth.com",
    "earn-eth.net",
    "aeth.trade",
    "aeth.network",
    "airdrop.zknsyc.com",
    "liveboxnft.com",
    "layerzero.networkx.dev",
    "mevstrategy.info",
    "ethstrategy.info",
    "arbstrategy.info",
    "ethereum.org-nft.com",

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
