### PR TITLE
src/fuzzylist.md; alphabetize fuzzylist in src/config.json

### PR DESCRIPTION
**Pull request by trn1ty**
Apologies for #6084, my finger slipped and hit the Enter key and GitHub helpfully submitted the request. This is a continuation of #5750.

This commit alphabetizes the fuzzylist in src/config.json and creates src/fuzzylist.md, which documents the introduction (and sometimes the removal) of fuzzylist entries.

### CODE REVIEW

**Comment by devenblake** [comment]
Requesting comment and suggestions for changing the fuzzylist description in src/fuzzylist.md.

**Comment by devenblake** [comment]
There were some temporary removals/readditions to the fuzzylist that I didn't document because it didn't seem to be particularly useful to do so, and I might have missed any entries lasting less than a day.

**Review by gravelcycles — APPROVED** [review]

**Comment by davidwgrossman** [comment]
@devenblake one next step we could take: we could write a unit test to make sure that the list is always sorted.

**Comment by devenblake** [comment]
For future reference, one of the perks of this change was because `git blame` output was already misleading (this does not appear in the prior discussion because I hadn't yet compiled the documentation and realized this).

Commits at the end of the fuzzylist will have to add or remove a semicolon from the preceding line for JSON syntax, so they'll show up as the blame for the last line whether or not that commit actually added/removed that item. For example see this `mkr.tools` removal which was the blame of `oasis.app` for a while: [5c03787](https://github.com/MetaMask/eth-phishing-detect/commit/5c03787). Entries also have been temporarily removed and re-added to test things, I can't remember an example of this off the top of my head but I can find one if anybody's interested.

**Pull request merged**
