### PR TITLE
add 34 scam urls

### PR DESCRIPTION
**Pull request by blocksecscamreport**
Hello, we are from blocksec(https://blocksec.com/), yesterday our system detects many phishing domains and extracts 34 scam urls. These domains need to be blocked, details here:

| reported url | phishing domain | phishing_behavior |
| :----: | :----: | :----: |
| dna.nft.bang-olfusen.com | dna.nft.bang-olfusen.com | Transfer To address 0x2007F9d0ee39F342eE0e6153B36FAA0d824371BC |
| premints-live.xyz | premints-live.xyz | Transfer To address 0x5A3EA59cea41E9C3975FE408e6EEaF1B3C2271a1 |
| puripetmint.com | puripetmint.com | Transfer To address 0xfd2692d0e6c30a2b3a921d9d9ca2c6b960b52444 |
| damienhirstnft.org | damienhirstnft.org | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| procrastination-world-nft.com | procrastination-world-nft.com | Transfer To address 0x4d6a07ad7e7870e5d0fe4bb3d0a6a4c7d5e15f56 |
| castawaysnfts.com | castawaysnfts.com | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| dmitriychernyaknfts.com | dmitriychernyaknfts.com | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| remember-meta.com | remember-meta.com | Transfer To address 0x3782630c0db047ff6470a13b4554a3a9268a8022 |
| ancientcatsclub.io | ancientcatsclub.io | Transfer To address 0xdbdd8d8340f59e30e05b3cb3fb96a0b79f4a597c |
| shibasocialclub.tv | shibasocialclub.tv | Transfer To address 0xc46fb8728EB5441E5C9ba1c5f23514A63d74c937 |
| sale.alphakongclub.co | sale.alphakongclub.co | Transfer To address 0xaB17b79E847A08Ce51D06794b1C17e26F0D14eB2 |
| drawxapelab.com | drawxapelab.com | Mint Valueless Token, mint price is 0.4 ETH, but floor price is 0 ETH |
| birdersanonymous.com | birdersanonymous.com | Mint Valueless Token, mint price is 0.05 ETH, but floor price is 0 ETH |
| letswalk.mintsystems.io | letswalk.mintsystems.io | Transfer To address 0x3262A2c9472466bD3e8a9a78f76f4cc433fF754C |
| dreamy-nft.com | dreamy-nft.com | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| sonart.tools | mint.sonart.tools<br>mint2.sonart.tools | Mint Valueless Token, mint price is 0.15 ETH, but floor price is 0.085 ETH |
| shibasocailclub.com | shibasocailclub.com | Transfer To address 0xdbdd8d8340f59e30e05b3cb3fb96a0b79f4a597c |
| mint.metaboards.mintfoundry.tech | mint.metaboards.mintfoundry.tech | Mint Valueless Token, mint price is 0.1 ETH, but floor price is 0 ETH |
| mintrealapesclub.com | mintrealapesclub.com | Transfer To address 0xE26a73b33bFeCE6061b36571F910D667E1B698b2 |
| dreamy-nft.com.whitelist-spots.com | dreamy-nft.com.whitelist-spots.com | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| metaskulls.net | metaskulls.net | Transfer To address 0x202535a4d4f225093b84f0854466e9Ee4E21Df5d |
| mint.spacebeanscoffee.io | mint.spacebeanscoffee.io | Mint Valueless Token, mint price is 0.17 ETH, but floor price is 0 ETH |
| mint.metaboards.space | mint.metaboards.space | Mint Valueless Token, mint price is 0.1 ETH, but floor price is 0 ETH |
| castaways-nft.com | castaways-nft.com | Approve Token To address 0xdac17f958d2ee523a2206206994597c13d831ec7 |
| mint.mvrstoken.space | mint.mvrstoken.space | Mint Valueless Token, mint price is 10 ETH, but floor price is 0 ETH |
| modernpokersclub.worldcuriositie.com | modernpokersclub.worldcuriositie.com | Transfer To address 0x708ea8cd8d4e9f487d7f05e33a3d4ea844c8db80 |
| shlnzonft.xyz | shlnzonft.xyz | Transfer To address 0xB085aB6893791d5782DAA269477cE347E0c0244c |
| invisiblefriend.co | invisiblefriend.co | Transfer To address 0x087f87aC0A05CFC380be099EA3e721d40226Eb2E |
| boredbunny.me | boredbunny.me | Transfer To address 0x01e13C3E0366e95C9965e00eB75D2b799703E307 |
| mentionnfts.xyz | birdezgang.mentionnfts.xyz<br>mypethooligan.mentionnfts.xyz<br>bywassies.mentionnfts.xyz | Transfer To address 0x0D524a5B52737C0a02880d5E84F7D20b8d66bfba |
| cyborg86nft.io | cyborg86nft.io | Transfer To address 0xdBDD8D8340f59E30e05b3cb3fB96a0B79f4A597C |
| giveaway-nfts.xyz | blockchainminersclub.giveaway-nfts.xyz<br>dresempire.giveaway-nfts.xyz<br>degenpass.giveaway-nfts.xyz | Transfer To address 0x0D524a5B52737C0a02880d5E84F7D20b8d66bfba |
| public.ttraderjoe.xyz | public.ttraderjoe.xyz | Premint Phishing |
| public.traderjjoe.xyz | public.traderjjoe.xyz | Premint Phishing |

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by diklou** [comment]
I don't understand why sonart.tools was flagged here. Just because floor price is below public mint price ? 
We also have our main site sonart.tools and our subdomains app.sonart.tools that are being flagged because of this. You are hurting our holders that need access to app.sonart.tools. Please do something

**Comment by blocksecscamreport** [comment]
We apologize to any inconvenience brought for you, we have removed all minting-related phishing records since 2022-12-02, but we forgot to remove them on 2022-12-01. We have removed related minting urls and pulled new requests.

**Comment by diklou** [comment]
Your mistake caused a lot of trouble and made us lose a lot of money

**Pull request merged**
