### PR TITLE
Block 156 scam URLs 🎄

### PR DESCRIPTION
**Pull request by dubstard**
```
    "1inch.appv8.com",
    "airdrops-trustpad.online",
    "balancer-invest.com",
    "balancerr.shop",
    "balancerv2.icu",
    "balancerv2.top",
    "balancerv2.monster",
    "balancerv2.buzz",
    "balancerv2.finance",
    "best-crypto-wallet.yivesites.com",
    "binance-exchange.yivesites.com",
    "cloud-metamask.com",
    "coinbase-defimining.com",
    "connect-metamasks.com",
    "cryptoswap-wallet.com",
    "ethereum-dopp.uk",
    "ethereum-eth.top",
    "ethereum-validator.org",
    "ethereumfastcloudminer.com",
    "exodus-wallet.yivesites.com",
    "metamaskewallet.com",
    "mywallet-blqckchain.host",
    "official-myetherwallet.ga",
    "official-myetherwallet.gq",
    "official-myetherwallet.cf",
    "official-myetherwallet.tk",
    "pancakesvvap.cf",
    "pancakesvvap.ga",
    "pancakesvvap.gq",
    "pancakesvvap.ml",
    "pancakesvvap.tk",
    "polygonbridgeofficial.com",
    "reconfirmsaccountcoinbase.com",
    "secure-coinbasereverify.com",
    "recover-coinbaseaccount.com",
    "secureaccountverifycoinbase.com",
    "signin-coinbasereverify.com",
    "the-bit-balancer.newfinancialmarketworld.com",
    "uniswap-flnance.org",
    "uniswap.app4j.org",
    "web-metamasks.com",
    "www-debank.exchange",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
image
IoC: https://urlscan.io/search/#hash%3A3814e2aae394a05ef5f9b877c26d41a341fb2a36138e26d79270f393e34205e8
 
```
    "aefx.info",
    "arkr.me",
    "artq.me",
    "dex88.net",
    "ff18.org",
    "flowdao.me",
    "gaxy.xyz",
    "kccmemepad.com",
    "pownft.me",
    "swap8.co",
    "zers.me",
```

**Review by dubstard — COMMENTED** [review]
```
    "ixexchangi.com",
```
h/t ecarlesi

**Review by dubstard — COMMENTED** [review]
https://urlscan.io/result/aa88034e-dcf9-47aa-a088-facbffc27b08/

```
ca-wallet.com
```

**Review by dubstard — COMMENTED** [review]
```
    "24trustfxtrade.online",
    "accountcoinbaserecomfirm.com",
    "airdropclaims.com",
    "airdrops-trustpad.app",
    "alpharendition.top",
    "app-unlswap.org",
    "armstrongsavings.finance",
    "assetmarketincome.live",
    "assetstocktrade.com",
    "atestowanycapital.com",
    "betaprofx.live",
    "bridgestandtrust.com",
    "bristolenergy.ltd",
    "capacityproviders.com",
    "chatcash.com.ng",
    "coinbasesecureupdate.com",
    "coinscash.com.ng",
    "connect4dapps.com",
    "d-imeratebank.com",
    "dapp-validators.com",
    "dapp-validators.solflarewebwallet.com",
    "easycashd.com",
    "easyfxtradeplatforms.live",
    "elevationmoneyfx.com",
    "elitestockminer.com",
    "fxbinaryoptions.24trustfxtrade.online",
    "fxbinaryoptions.live",
    "fxgoldenmarket.live",
    "getfxfunding.com",
    "globalsyncwallet.top",
    "goldcreditbnk.net",
    "goldenfxopt.online",
    "gzcoinbase23652356.com",
    "htpps-wallet-1inch.com",
    "leadsmetamask.line.pm",
    "leadsnmetamask.line.pm",
    "legacymineltd.com",
    "legacymineltd.com.atestowanycapital.com",
    "lifegateministriesworldwide.com",
    "metamask-security.cyou",
    "metamaskextension.one",
    "metamasks-ext.com",
    "metamasks-ext.com.phantoms-ext.com",
    "metamasks.website",
    "pancakeswap.gives",
    "phantom-dex.com",
    "phantoms-ext.com",
    "phantoms-extension.com",
    "phantoms-extension.com.maiarwallets.com",
    "recoverycoinbaseupdate.com",
    "signinaccountscoinbase.com",
    "smartclickyhub.site",
    "smartcointradefx.com",
    "smsgate.online",
    "solflare-wallet.com",
    "solflarewallets.com",
    "solflarewallets.defitvalidator.com",
    "solflarewebwallet.com",
    "toptraders-fx.com",
    "toptraders-fx.xipcapitalgroups.com",
    "tr-emp.com",
    "trustfund-finance.com",
    "uniswap.fund",
    "uniswap.sh",
    "uniswaplpart.com",
    "unitedcoinsprofits.com",
    "unniverso-wallet.cf",
    "unniverso-wallet.ga",
    "unniverso-wallet.gq",
    "unniverso-wallet.ml",
    "unniverso-wallet.tk",
    "updateaccountcoinbase.com",
    "uss00zs-h3lpsecuree-coinbase-ver1fyy.com",
    "v1-uniswap.org",
    "verifyrecheckcoinbase.com",
    "walletdapp-validators.com",
    "walletdapp-validators.solflarewebwallet.com",
    "worldtrustbanking.com",
    "www-quickswap-exchange.cf",
    "www-quickswap-exchange.ga",
    "www-quickswap-exchange.gq",
    "www-quickswap-exchange.ml",
    "www-quickswap-exchange.tk",
    "xipcapitalgroups.com",
    "xipcapitalsgroup.com",
    "xipcapitalsgroup.com.atestowanycapital.com",
    ```

**Review by dubstard — COMMENTED** [review]
Block one more scam URL

**Review by dubstard — COMMENTED** [review]
block one more scam
```
"premium-poe.com",
```
image

**Review by dubstard — COMMENTED** [review]
block 

block six "twins" of `premium-poe.com`
```
    "dentraders.com",
    "ecotradingmining.live",
    "exchange-poe.com",
    "perfectminingoption.com",
    "poe-exchange.com",
    "poe-trader.com",
```

**Review by dubstard — COMMENTED** [review]
block
```
"fifa-adidas.xyz",
 "vipeth7.com",
"ethereumchristmas.org",
```
image
image
image

**Review by dubstard — COMMENTED** [review]
block balancer fake giveaway
```
bit.ly/3YPCCrK
⬇️⬇⬇⬇
host1853091.hostland.pro
⬇⬇⬇⬇
multi-trustpade.io/balancer/
```
image

**Review by dubstard — COMMENTED** [review]
block `xn--curvefnance-hcb.com` (`curvefìnance.com`)
image
h/t Flavio

**Review by dubstard — COMMENTED** [review]
block `huyxbit.com`
image

Imagine believing some random "exchange", registered 3 days ago would gift you 11K via an unsolicited twitter spam DM.

**Review by AlexHerman1 — APPROVED** [review]
lgtm.

**Pull request merged**
