### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
add
```
		"lpv3uniswap.com",
		"uniswap.run",
		"uniswap.team",
		"metamask-institutional.io",
		"metamask-mintnft.biz",
		"metamask-nft.io",
		"metamask.bar",
		"metamask.io-defi-web3-dapps-and-nfts.welcome-bore.site",
		"metamask.io-defi-web3-dapps-and-nfts47876.demi-expensilon.site",
		"metamask.io-defi-web3-dapps-and-nfts9856.welcome-bore.site",
		"metamask.io-waiiet-ycloipd-544rty36f.welcome-bore.site",
		"metamask.sb",
		"metamask88.com",
		"metamaskes.com",
		"metamaskpay.org",
		"metamaskwallet.servebeer.com",
```
All those were registered last night.
Not sure should I block the domain as well
i.e. `welcome-bore.site` as well as `metamask.io-waiiet-ycloipd-544rty36f.welcome-bore.site`

It could be an ATO or a bogus domain.

For example `servebeer.com` is a free service and the blocking the main domain would be a FP (false positive), but the full FQDN is definitely bad 
`metamaskwallet.servebeer.com`

`lpv3uniswap.com` belongs to the same criminal syndicate that had those registered. They are very well funded.

```
lpuniswap.com
v3lpuniswap.com
uniswaplp.org
lpuniswap.org
uniaward.org
unilp.org
univ3lp.org
```

### CODE REVIEW

**Comment by dubstard** [comment]
edit: [took care of welcome bore](https://twitter.com/dubstard/status/1548211611407568898) either way

**Review by dubstard — COMMENTED** [review]
add Balancer labs scams

Those are old, already revoked, still worth blocking in case the domains get ressurected.
```
"balancerr.finance",
"balancer-flnance.com",
"balancer-exchange.com",
"balancer-pro.com",
"balancer.live",
```
This one is new live and dangerous.
Same as the Uniswap LP scam.
```"balancerlp.com",```

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
thank you

**Pull request merged**
