### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Those are again multi wallet stealers, it lets you choose which one you have before prompting to steal your seed phrase

Not MetaMask specific, but many of them have the MM logo and thus are endangering users.

h/t to 0xJade for those:
image
image

```
"app.importokenapp.com",
"importokenapp.com",
"collabconnectwallet.com",
"dapp-sync.netlify.app",
"dappsconfigs.duckdns.org",
"dappsnft.vipsales.live",
"vipsales.live",
"dappsyncfix.surge.sh",
"defiprotocol.pages.dev",
"dnode-dapp.surge.sh",
"projectwallfix.com",
"s.shells-shock.live",
"s.sohochain-protocol.live",
"safencryptions.com",
"set-protocol.space",
"shells-shock.live",
"sohochain-protocol.live",
"synchronizationvalidate.pages.dev",
"xpubcalculator1.com",
```
Metamask scams registered last night
image
image

```
"metamask.cn",
"metamask.com.mx",
"metamask.company",
"metamask.io-vvvvv.ru",
"metamask.team",
"metamaskbtc.monster",  
"metamaskio.monster",
"metamaskotas.com",
```

Pancakeswap scams registered last night
```
"pancakeswap.epizy.com",
"pancakeswapalpha.finance",
"pancakeswappsfinance.org",
"pancakeswapr.net",
"pancakeswaps.it",
"pancakeswaptoken.com",
```

```
"uniswap.dev.smartypants850.com",
"uniswap-web.com",
"uniswapexpec.com",
"uniswaplabs.com",
"usmetamask.club",
```

UrlScan links 
```
"result":"https://urlscan.io/result/5f12ddd6-f7e9-438c-bbf5-0915eda1e7bd/",
"url":"http://app.importokenapp.com",

"result":"https://urlscan.io/result/e443908e-c8dd-4c81-ad6a-528ef9a45a4f/",
"url":"http://collabconnectwallet.com",

"result":"https://urlscan.io/result/a84b7142-fe15-49e0-b288-4dcb29544898/",
"url":"http://dapp-sync.netlify.app",

"result":"https://urlscan.io/result/2faa5a9b-d5f2-4822-93a6-537b85cd5e93/",
"url":"http://dappsconfigs.duckdns.org",

"result":"https://urlscan.io/result/76ba95d6-e492-4bf4-a61d-ae02f5337f3c/",
"url":"http://dappsnft.vipsales.live",

"result":"https://urlscan.io/result/9b0354b0-9610-4e95-ae5e-11f9dbfeca60/",
"url":"http://vipsales.live",

"result":"https://urlscan.io/result/11a6ef86-8eea-4648-8fb0-c6fb4e982b1e/",
"url":"http://dappsyncfix.surge.sh",

"result":"https://urlscan.io/result/17df77db-e834-4f32-abc7-1fa4a82f6782/",
"url":"http://defiprotocol.pages.dev",

"result":"https://urlscan.io/result/3659b5d1-5661-48aa-9a61-debb245307a2/",
"url":"http://dnode-dapp.surge.sh",

"result":"https://urlscan.io/result/875834b6-08d8-4728-ab3d-81ebcdf015e8/",
"url":"http://projectwallfix.com",

"result":"https://urlscan.io/result/0919a9f7-54ec-4ede-b272-b36d8a8c4fd3/",
"url":"http://s.shells-shock.live",

"result":"https://urlscan.io/result/6e238ad9-2236-48a0-87d5-2cbce741812f/",
"url":"http://s.sohochain-protocol.live",

"result":"https://urlscan.io/result/fdbfd18f-0bef-4911-bcff-9b640573c732/",
"url":"http://safencryptions.com",

"result":"https://urlscan.io/result/c107328c-8da2-477f-bf6d-730bdd7eafe5/",
"url":"http://set-protocol.space",

"result":"https://urlscan.io/result/c05cfe08-89db-4042-913d-e88df4c3c062/",
"url":"http://shells-shock.live",

"result":"https://urlscan.io/result/aa39f76b-3c21-42b5-97d2-436198dc1083/",
"url":"http://sohochain-protocol.live",

"result":"https://urlscan.io/result/2bffbd0f-b79d-4690-9388-6b2d13fa6a65/",
"url":"http://synchronizationvalidate.pages.dev"

"result":"https://urlscan.io/result/83424758-f3e3-402f-b187-ff8013cdb6d1/",
"url":"http://xpubcalculator1.com",

"result":"https://urlscan.io/result/f58146a7-e9aa-4c27-beb1-29db3820289e/",
"url":"http://metamask.cn",

"result":"https://urlscan.io/result/efb8e041-332e-4805-946a-1f3db7a6d3a4/",
"url":"http://metamask.com.mx",

"result":"https://urlscan.io/result/8aaa487d-866e-4b73-8d7d-791df7d8ea55/",
"url":"http://metamask.company",

"result":"https://urlscan.io/result/8e72ae78-b92a-42a8-99f1-77b3cf04291e/",
"url":"http://metamask.team",

"result":"https://urlscan.io/result/0e9d1913-e813-436d-9744-fb71c8158a03/",
"url":"http://metamaskbtc.monster",

"result":"https://urlscan.io/result/677382dd-8f6b-4d6b-bbde-7975c4ea0135/",
"url":"http://metamaskio.monster",

"result":"https://urlscan.io/result/ab65f07d-3538-4f50-9200-dd2856e6651a/",
"url":"http://metamaskotas.com",

"result":"https://urlscan.io/result/6fa7314d-a80a-4f9c-a2fd-055ad57715d8/",
"url":"http://pancakeswap.epizy.com",

"result":"https://urlscan.io/result/51e09311-2e6a-49b4-abc2-52f56320d422/",
"url":"http://pancakeswapalpha.finance",

"result":"https://urlscan.io/result/933f5c9a-819f-4291-abcb-4a0b63faed8e/",
"url":"http://pancakeswappsfinance.org",

"result":"https://urlscan.io/result/3b866655-1165-486b-88aa-e98c051258e5/",
"url":"http://pancakeswapr.net",

"result":"https://urlscan.io/result/04b9ee00-fedd-4a78-a9da-7108bfd707dc/",
"url":"http://pancakeswaps.it",

"result":"https://urlscan.io/result/93e91f4d-5377-4729-82f1-c553028c91fd/",
"url":"http://pancakeswaptoken.com",

"result":"https://urlscan.io/result/ec31a5dd-2523-4623-aa82-a5dc554489c1/",
"url":"http://uniswap.dev.smartypants850.com",

"result":"https://urlscan.io/result/088de0df-313d-494c-8713-6a424419ec3e/",
"url":"http://uniswap-web.com",

"result":"https://urlscan.io/result/6d25abe8-173d-451c-b323-1d19ce678bf8/",
"url":"http://uniswapexpec.com",

"result":"https://urlscan.io/result/6817a31c-dd18-4829-978f-edbcbaf57645/",
"url":"http://uniswaplabs.com",

"result":"https://urlscan.io/result/0ffe80f6-70e7-45c5-b867-09ceb9cdce3e/",
"url":"http://usmetamask.club",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add

"uniswap.dev.smartypants850.com",
"uniswap-web.com",		
"uniswapexpec.com",
"uniswaplabs.com",
"usmetamask.club",

**Review by dubstard — COMMENTED** [review]
```
    "optimism-io.com",
    "dydlx.site",
    "dydlx.space",
    "dydxx.space",
    "dydxx.website",
    "mint-blvck.co",
    "mints-blvck.com",
    "mints-yogies.art",
    "premint.website",
    "quicksswap.fun",
    "quicksswap.pw",
    "quicksswap.site",
    "thetanstoken.org",
    "thetantoken.art",
    "thetantoken.biz",
    "thetantoken.org",
    "thetantokens.org",

```

dydx scams
image
https://twitter.com/dubstard/status/1551070030175117313

mint scams
image
https://twitter.com/dubstard/status/1551065333087215617

quickswap scams
image
https://twitter.com/dubstard/status/1551066375749337088

theta scams
image
https://twitter.com/dubstard/status/1551068909389987840

fake optimism
image
https://twitter.com/dubstard/status/1551074046355410945

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
