### PR TITLE
block 77 fraudulent URLs

### PR DESCRIPTION
**Pull request by dubstard**
📅 22 September

D: [Would it be possible to monitor for this known abuse pattern internally - Yes or No?](https://twitter.com/dubstard/status/1572840542823911427)

NC: [Yes, there's an option to monitor subdomains. We'll keep an eye on suspicious activity with this subdomain and take action where needed, thanks for alerting.](https://twitter.com/Namecheap/status/1572923851113373696)

----------

📅29 November

NC: [Please be informed that this type of abuse is proactively monitored on our side and we do our best to block it asap. 
](https://twitter.com/Namecheap/status/1597516188350910465)

----------------------
image

Pattern 
https://urlscan.io/search/#metamask.io.*%20AND%20page.asn%3AAS22612%20OR%20page.ASN%3Anamecheap

"proactively monitoring"
image

```

    "accountrecoverycoinbase.com",
    "adidasoriginals.whitelist-mints.xyz",
    "airdrop-cryptoswaptokens.quest",
    "alert-account-coinbasecs.com",
    "alienfrens.whitelist-mints.xyz",
    "app-metamask.live",
    "app-uniswap.info",
    "appuniswapp.com",
    "bitslogin.com",
    "cionbaselogin.com",
    "coinabasa.net",
    "coinbasalog.com",
    "coinloginn.com",
    "dappfactoryvalidationconnect.online",
    "doc-uniswap.org",
    "dogeclub.whitelist-mints.xyz",
    "ethereum-2022.org",
    "ethereum-france.com",
    "found-eth.org",
    "free-ethereum.biz",
    "integrationnodechain.netlify.app",
    "metamask-helpcenter.com",
    "metamask-ru.app",
    "metamask-walletsecurity.com",
    "metamask.co.nz",
    "metamask.io.merge.bluebrox.co.uk",
    "metamask.io.merge.busela.or.tz",
    "metamask.io.merge.cbrandheli.info",
    "metamask.io.merge.cbrmovies.info",
    "metamask.io.merge.disutech.com",
    "metamask.io.merge.foras-tech.com",
    "metamask.io.merge.gamersranks.com",
    "metamask.io.merge.hpmsolutions.ca",
    "metamask.io.merge.instapple.com",
    "metamask.io.merge.instapple.us",
    "metamask.io.merge.muginiandsons.com",
    "metamask.io.merge.newlifestylebd.com",
    "metamask.io.merge.payasyougowebs.co.uk",
    "metamask.io.merge.pivoine.com.qa",
    "metamask.io.merge.problogcontentwriting.com",
    "metamask.io.merge.reef.co.ke",
    "metamask.io.merge.rojgarbikash.com",
    "metamask.io.merge.shopattala.com",
    "metamask.io.merge.sohicohe.org",
    "metamask.io.merge.starhost.cloud",
    "metamask.io.merge.thakurgaoerkhabor.com",
    "metamask.io.merge.theonionnewspapercom.com",
    "metamask.io.merge.toosdei.space",
    "metamask.io.merge.transportesglobaltur.com",
    "metamask.io.merge.yiteism.org",
    "metamask.security-radar.xyz",
    "metamask.walletreauth.net",
    "metamask2.online",
    "metamask2.site",
    "metamask2022care1129.run.place",
    "metamaskeu.com",
    "metamaskk.datasupermarket.cn",
    "mycryptocoinwallet.com",
    "practical-shockley.161-35-131-47.plesk.page",
    "stake-sso.com",
    "unicrypto.exchange",
    "uniswap.buildoor.xyz",
    "uniswap.trungtinpham.com",
    "uniswap.wshift.trade",
    "uniswapmax.com",
    "uniswaps.org.factupos.co",
    "update.coinbase.com.bakulrujak.me",
    "v3-rify.com",
    "walleterrorconnect.ga",
    "walleterrorconnect.gq",
    "walleterrorconnect.ml",
    "walleterrorconnect.cf",
    "walleterrorconnect.tk",
    "wallextconnectdapps.online",
    "wciclaim.com",
    "whitelist-mints.xyz",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
duplicate `metamask.exchange` removed

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Comment by jdetychey** [comment]
Folks, @dubstard @409H , seems like you added     "ethereum-france.com" with this PR...
For the record https://ethereum-france.com is a registred non-profit organisation that has been live since ~ genesis block, providing technical ressources in French for years, organising EthCC and helping the French community grow. Can you reverse those changes shortly please ?

**Comment by dubstard** [comment]
Sorry for the trouble, appears it has been taken care of already.

**Comment by dubstard** [comment]
Remember the registrar claims that they are "PROACTIVELY MONITORING" for this type of abuse.

Meanwhile:
image

**Pull request merged**
