### PR TITLE
Add phishing scam websites

### PR DESCRIPTION
**Pull request by web3validator**
"tuvturkistasyonlari.com",
    "masocialbooster.store"

### CODE REVIEW

**Comment by AndrewMohawk** [comment]
`masocialbooster.store` doesnt resolve:
```
» host masocialbooster.store
Host masocialbooster.store not found: 3(NXDOMAIN)
```

And I dont see a scam on `tuvturkistasyonlari.com`, can you provide some screenshots etc for this please? Thanks :)

**Comment by web3validator** [comment]
I receive it in spam folder and it definatly looks like scam 
Знімок екрана 2023-11-26 о 09 39 43

**Comment by web3validator** [comment]
Yes, correct. It is visible in the bottom right corner.

**Comment by AlexHerman1** [comment]
i dont think this URL is a phishing page, and doesn't appear to be attempting to phish metamask users.

**Pull request closed without merging**
