### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
🧪Probe 136 scams (pre dupe check)
🤞 Spray and pray there will be little to no duplicates
🛑 Add 118 scams (post dupe check)

```
		"1inch-pay.cf",
		"1inch-pay.ga",
		"1inch-pay.gq",
		"1inch-pay.tk",
		"allnodeauthenticator.com",
		"app-ethermiinewallet.xyz",
		"app-uniswap.pro",
		"assets.coinbase.secureauthlogin.com",
		"auth-idverification-coinbase.com",
		"bittrrex-conect-wallet.cf",
		"bittrrex-conect-wallet.ga",
		"bittrrex-conect-wallet.gq",
		"bittrrex-conect-wallet.ml",
		"bittrrex-conect-wallet.tk",
		"blockchaindapp.xyz",
		"cardona-ecosys.com",
		"coinbase-reset.duckdns.org",
		"coinbase-trade.cloud",
		"coinbase.com-authyf-fd.com",
		"coinbase.com-wallet-login.com",
		"coinbase.com.secure-auth.sessionid092163.app",
		"coinbase.comsignin.autos",
		"coinbaseuslogin.com.metamasklogins.com",
		"coinbasewallet.workers.dev",
		"coinbasewalletbtc.com",
		"consensus-poschain.live",
		"cwnodeconnecting.online",
		"dappsannex.live",
		"dappsmanual.work",
		"digital-smarthub.live",
		"digital-synchub.live",
		"digitalhubsyncs.live",
		"dynamic.coinbase.secureauthlogin.com",
		"etf-uniswap.pages.dev",
		"ethereum-give.net",
		"ethereum-live.com",
		"ethereumpowgiveaway-drops.com",
		"ethereumpowgiveaway-drops.ultimatefxtrading.us",
		"ethereumprofit.net",
		"ethereumprofit.org",
		"exchange.pancakeswap-finance-pools.site",
		"exodus.com.merge.androponsel.com",
		"exodus.com.merge.puskesmastabaatas.com",
		"exodus.com.merge.wisatabengkulu.com",
		"fixchainode.com",
		"glveaways-ethereums-metamasks-io.is-best.net",
		"glveaways-ethereums-trustswallet-com.html-5.me",
		"google.coinbase.secureauthlogin.com",
		"googletag.coinbase.secureauthlogin.com",
		"heliumwallet-minersyncfix-247.square.site",
		"images.coinbase.secureauthlogin.com",
		"indexval.online",
		"mainnethub.pages.dev",
		"mainsbscrectify.live",
		"metamask.io.breachprevention.in",
		"metamask.io.log29865.com",
		"metamask.io.log73821.org",
		"metamask.io.merge.blocprest.ro",
		"metamask.io.merge.blocservice.ro",
		"metamask.io.merge.callhometutor.com",
		"metamask.io.merge.cimce.org",
		"metamask.io.merge.pvchomeinteriors.in",
		"metamask.io.zaa-tech.com",
		"metamaskexts.com",
		"metamasklogins.com",
		"metamcryptowallets.wonstasite.com",
		"metanftcryptoexchange.com",
		"migrate-safemoon.com",
		"migrates-smartfixs.live",
		"mintchainauth.netlify.app",
		"musk3dapp.com",
		"mybitcoinexchange.xyz",
		"new.pancokeswap.com",
		"nxconnector.tk",
		"pancakesvvap-fiinance.com",
		"pancakeswaps.top",
		"pancakeswop.com",
		"pancakewallet.com",
		"panel.pancokeswap.com",
		"paraswap-io.com",
		"poolofnodes.com",
		"procoinbase.comsignin.autos",
		"projectmainn.com",
		"projectmainnet.netlify.app",
		"rectifyprotocol.site",
		"routerprotocolfixing.com",
		"s.consensus-poschain.live",
		"s.dappsannex.live",
		"s.digital-smarthub.live",
		"s.digital-synchub.live",
		"s.digitalhubsyncs.live",
		"s.migrates-smartfixs.live",
		"s.smart-shellshocks.live",
		"s.smartprotocol-solution.live",
		"s.stepn-fixs.live",
		"secure-walletmask.pointdns.click",
		"sessions.coinbase.secureauthlogin.com",
		"site.darpicsols.com",
		"smart-indexprotocol.com",
		"smart-shellshocks.live",
		"smartnoderestore.live",
		"smartnodes.one",
		"smartprotocol-solution.live",
		"stepn-fixs.live",
		"support.pancakeswaps.it",
		"svice-online-marketingupport.pancakeswaps.it",
		"switchrectifier.live",
		"tokensyncer.xyz",
		"uniswap-tech.com",
		"uniswap.pink",
		"uniswaps.in",
		"unverifyedslogin-coinbase.com",
		"vechainunlockauth.org",
		"walletconnect-user.info",
		"walletsolveteam.com",
		"walletssycnauthentications.online",
		"yearn-finance.exchange",
		"ylpydg3ryks5p8v.wallet.sergiy.top",
```

```
$ ./BurnTrash.sh | egrep "(result|url)"

  "api": "https://urlscan.io/api/v1/result/5d93d320-97de-41c4-86a4-fa226bdee192/",
  "url": "http://allnodeauthenticator.com",

  "api": "https://urlscan.io/api/v1/result/f1b84709-5c1d-43d5-ab03-3bc25a17aa75/",
  "url": "http://app-ethermiinewallet.xyz",

  "api": "https://urlscan.io/api/v1/result/d1af3c02-c3f1-4a03-a4bc-d8cb146dafcd/",
  "url": "http://app-uniswap.pro",

  "api": "https://urlscan.io/api/v1/result/cf30a04f-c94d-4e44-a31e-2fdcbf38e24e/",
  "url": "http://auth-idverification-coinbase.com",

  "api": "https://urlscan.io/api/v1/result/2ea25cbc-66af-4e88-bb68-baf31148cfa2/",
  "url": "http://bittrrex-conect-wallet.cf",

  "api": "https://urlscan.io/api/v1/result/10b5802b-c12f-40c1-858b-03b1724c0e85/",
  "url": "http://bittrrex-conect-wallet.ga",

  "api": "https://urlscan.io/api/v1/result/1fa33667-9218-45cd-a373-8210955e5ed2/",
  "url": "http://bittrrex-conect-wallet.gq",

  "api": "https://urlscan.io/api/v1/result/091f0a54-0c69-4bd3-913f-d9cecc73683e/",
  "url": "http://bittrrex-conect-wallet.ml",

  "api": "https://urlscan.io/api/v1/result/a07994bf-2f7c-47ad-91ac-96cc600ed1c7/",
  "url": "http://bittrrex-conect-wallet.tk",

  "api": "https://urlscan.io/api/v1/result/6ab6cbb5-6cce-4ac9-ba89-9201d27b61d1/",
  "url": "http://blockchaindapp.xyz",

  "api": "https://urlscan.io/api/v1/result/8bd7889d-d3aa-4995-a522-22cdc371c1c0/",
  "url": "http://cardona-ecosys.com",

  "api": "https://urlscan.io/api/v1/result/80694bba-7695-4589-a85d-37ec4fa821b7/",
  "url": "http://coinbase-reset.duckdns.org",

  "api": "https://urlscan.io/api/v1/result/ee5895c9-ba77-4b0c-a9b3-12b39bc9e0d2/",
  "url": "http://coinbase-trade.cloud",

  "api": "https://urlscan.io/api/v1/result/68f4b46f-2e3f-460b-951e-9f28b9817679/",
  "url": "http://coinbase.com-authyf-fd.com",

  "api": "https://urlscan.io/api/v1/result/92753058-582d-4277-a491-a134315c1b4c/",
  "url": "http://coinbase.com-wallet-login.com",

  "api": "https://urlscan.io/api/v1/result/f7e8f607-d38f-4499-a88e-c9890fc73527/",
  "url": "http://coinbase.com.secure-auth.sessionid092163.app",

  "api": "https://urlscan.io/api/v1/result/8cf78d32-59b0-4e58-beb9-236817fc5e36/",
  "url": "http://coinbase.comsignin.autos",

  "api": "https://urlscan.io/api/v1/result/4008e9da-21e6-4a7d-ae38-10c9a5946122/",
  "url": "http://coinbaseuslogin.com.metamasklogins.com",

  "api": "https://urlscan.io/api/v1/result/8bed90c7-1152-444f-b4ec-0abd5058bfc5/",
  "url": "http://coinbasewalletbtc.com",

  "api": "https://urlscan.io/api/v1/result/74f439f9-bb00-4cf8-850c-97271678ffc7/",
  "url": "http://consensus-poschain.live",

  "api": "https://urlscan.io/api/v1/result/612374bd-70b9-4f3c-8246-2202353df8f6/",
  "url": "http://cwnodeconnecting.online",

  "api": "https://urlscan.io/api/v1/result/387d4f92-ac84-48f1-a1fd-cf6d19fe012b/",
  "url": "http://dappsannex.live",

  "api": "https://urlscan.io/api/v1/result/9941e9ee-7856-47e7-8460-5f901159a51b/",
  "url": "http://dappsmanual.work",

  "api": "https://urlscan.io/api/v1/result/c364af4d-2f59-4cc4-9777-42b25c43f8dd/",
  "url": "http://digital-smarthub.live",

  "api": "https://urlscan.io/api/v1/result/9d2ac6e1-9017-4991-abec-a8f5f0cb708e/",
  "url": "http://digital-synchub.live",

  "api": "https://urlscan.io/api/v1/result/1bdc8eeb-ee1b-409e-a866-9353b3154a03/",
  "url": "http://digitalhubsyncs.live",

  "api": "https://urlscan.io/api/v1/result/99aa552e-e00a-43be-9842-d95e30a5e945/",
  "url": "http://etf-uniswap.pages.dev",

  "api": "https://urlscan.io/api/v1/result/7348af0b-ea8e-4e20-bee1-c40513d0b5a2/",
  "url": "http://ethereum-give.net",

  "api": "https://urlscan.io/api/v1/result/8d7bbff4-8c36-4b20-b793-b1e8372ee505/",
  "url": "http://ethereum-live.com",

  "api": "https://urlscan.io/api/v1/result/5b6d2e1d-fb9d-4fa6-b84c-d497aa7bcf36/",
  "url": "http://ethereumpowgiveaway-drops.com",

  "api": "https://urlscan.io/api/v1/result/5271285e-05ee-4130-868d-0c884e74e2c5/",
  "url": "http://ethereumpowgiveaway-drops.ultimatefxtrading.us",

  "api": "https://urlscan.io/api/v1/result/bbe5fdb7-c100-4a67-a3f6-1bc2f3f4f13a/",
  "url": "http://ethereumprofit.net",

  "api": "https://urlscan.io/api/v1/result/bffbc0a5-7ffd-4eb5-bbb2-7ad430456efa/",
  "url": "http://ethereumprofit.org",

  "api": "https://urlscan.io/api/v1/result/34d4b896-acbf-4716-9ddf-552edeeec3d2/",
  "url": "http://exchange.pancakeswap-finance-pools.site",

  "api": "https://urlscan.io/api/v1/result/d778046c-fae8-46b1-87d2-11644499c251/",
  "url": "http://exodus.com.merge.androponsel.com",

  "api": "https://urlscan.io/api/v1/result/0820cb04-d60c-493f-a1ab-1af66d919d3c/",
  "url": "http://exodus.com.merge.puskesmastabaatas.com",

  "api": "https://urlscan.io/api/v1/result/e79a65ea-d852-4d71-b7ae-e3d994da7519/",
  "url": "http://exodus.com.merge.wisatabengkulu.com",

  "api": "https://urlscan.io/api/v1/result/a851c880-c6d0-473c-9951-f3efd874f10c/",
  "url": "http://fixchainode.com",

  "api": "https://urlscan.io/api/v1/result/90826c87-7e14-46e5-96d1-b6c636315286/",
  "url": "http://glveaways-ethereums-metamasks-io.is-best.net",

  "api": "https://urlscan.io/api/v1/result/2c94b062-d1a5-429f-8f8a-6d5d20c181d4/",
  "url": "http://glveaways-ethereums-trustswallet-com.html-5.me",

  "api": "https://urlscan.io/api/v1/result/6ba2836d-a3de-459d-8ba4-e159c96ea0fa/",
  "url": "http://heliumwallet-minersyncfix-247.square.site",

  "api": "https://urlscan.io/api/v1/result/59ccaa2a-94af-4c9a-b70d-4ccccfb8deae/",
  "url": "http://indexval.online",

  "api": "https://urlscan.io/api/v1/result/707b8d29-8b66-45eb-95b5-a5d96213c723/",
  "url": "http://mainnethub.pages.dev",

  "api": "https://urlscan.io/api/v1/result/40ee9f31-5d23-491e-a48d-979f6fdefcc1/",
  "url": "http://mainsbscrectify.live",

  "api": "https://urlscan.io/api/v1/result/4dc108b8-9f15-4ae8-98b9-413646da8e3f/",
  "url": "http://metamask.io.breachprevention.in",

  "api": "https://urlscan.io/api/v1/result/0a0e364b-c6c7-4a10-8773-a932d24c2b60/",
  "url": "http://metamask.io.log29865.com",

  "api": "https://urlscan.io/api/v1/result/ba73e841-ac7c-46a2-8bc7-5d018ad93a83/",
  "url": "http://metamask.io.merge.blocprest.ro",

  "api": "https://urlscan.io/api/v1/result/bd9ddfa6-2316-4ec9-9386-59835b0a2ff2/",
  "url": "http://metamask.io.merge.blocservice.ro",

  "api": "https://urlscan.io/api/v1/result/46a292c4-e2ee-4225-b472-4b8ec0474b2a/",
  "url": "http://metamask.io.merge.callhometutor.com",

  "api": "https://urlscan.io/api/v1/result/539d6249-9a67-423a-8fa5-ff79e7ce11ea/",
  "url": "http://metamask.io.merge.cimce.org",

  "api": "https://urlscan.io/api/v1/result/d9c2270a-b9af-4b94-b86f-b2bf4b9e47c7/",
  "url": "http://metamask.io.merge.pvchomeinteriors.in",

  "api": "https://urlscan.io/api/v1/result/f32c7963-af66-49b2-877a-28eeca714cc7/",
  "url": "http://metamask.io.zaa-tech.com",

  "api": "https://urlscan.io/api/v1/result/f856ddb4-dde8-4ae1-87f6-9d8a86f22727/",
  "url": "http://metamaskexts.com",

  "api": "https://urlscan.io/api/v1/result/01c685e0-18ba-49f3-82fa-3f2ef7e13a10/",
  "url": "http://metamasklogins.com",

  "api": "https://urlscan.io/api/v1/result/40f80393-b10b-41b9-b621-452b4ee1d701/",
  "url": "http://metamcryptowallets.wonstasite.com",

  "api": "https://urlscan.io/api/v1/result/736f15ba-2515-4ce8-a3d3-1c1ad28b525d/",
  "url": "http://metanftcryptoexchange.com",

  "api": "https://urlscan.io/api/v1/result/ded3e938-645d-4c57-b539-3bd9980fe013/",
  "url": "http://migrate-safemoon.com",

  "api": "https://urlscan.io/api/v1/result/3b007ee0-016c-4cf1-ab36-09f28609423a/",
  "url": "http://migrates-smartfixs.live",

  "api": "https://urlscan.io/api/v1/result/4012b033-77d7-4b4d-85f1-4d3dcab5049a/",
  "url": "http://mintchainauth.netlify.app",

  "api": "https://urlscan.io/api/v1/result/8277e3a7-d175-40fd-8ae9-b76c8e8f3553/",
  "url": "http://musk3dapp.com",

  "api": "https://urlscan.io/api/v1/result/a2fc8223-8688-4ec4-83ee-ecea57bcef41/",
  "url": "http://mybitcoinexchange.xyz",

  "api": "https://urlscan.io/api/v1/result/24a418ab-5990-41d2-abe3-9263bc92f443/",
  "url": "http://new.pancokeswap.com",

  "api": "https://urlscan.io/api/v1/result/577d77cb-9dae-46a7-a576-0f5f968be509/",
  "url": "http://nxconnector.tk",

  "api": "https://urlscan.io/api/v1/result/badb7fbf-a86e-4e76-9115-7ac1faec067a/",
  "url": "http://pancakesvvap-fiinance.com",

  "api": "https://urlscan.io/api/v1/result/b2cc0445-7fe8-4db6-a6de-d3242817af46/",
  "url": "http://pancakeswaps.top",

  "api": "https://urlscan.io/api/v1/result/09946a42-6546-46e9-92d1-dfdba2d7a9cd/",
  "url": "http://pancakeswop.com",

  "api": "https://urlscan.io/api/v1/result/dd85cecf-6f4f-4b66-badc-e27346dc77a0/",
  "url": "http://pancakewallet.com",

  "api": "https://urlscan.io/api/v1/result/8874a60a-06e5-4e72-84b1-82b824548aea/",
  "url": "http://panel.pancokeswap.com",

  "api": "https://urlscan.io/api/v1/result/49996069-524a-4dac-9196-884e6e8e7818/",
  "url": "http://paraswap-io.com",

  "api": "https://urlscan.io/api/v1/result/16823347-16c0-4d22-8d0d-beaa113eb2fb/",
  "url": "http://poolofnodes.com",

  "api": "https://urlscan.io/api/v1/result/6d14c55a-df35-444b-adc7-59873f1eb73b/",
  "url": "http://procoinbase.comsignin.autos",

  "api": "https://urlscan.io/api/v1/result/c24335fa-9720-482c-ab03-612a04a1b804/",
  "url": "http://projectmainn.com",

  "api": "https://urlscan.io/api/v1/result/e0b6dfee-0a51-411e-b02a-94052d455588/",
  "url": "http://projectmainnet.netlify.app",

  "api": "https://urlscan.io/api/v1/result/23886e68-404e-4b7c-a9cc-69f38c3109a1/",
  "url": "http://rectifyprotocol.site",

  "api": "https://urlscan.io/api/v1/result/9f788518-36c3-4d45-9e3c-b029e16e939a/",
  "url": "http://routerprotocolfixing.com",

  "api": "https://urlscan.io/api/v1/result/ca3e1701-c9e3-470b-a51f-9f97194864dd/",
  "url": "http://s.consensus-poschain.live",

  "api": "https://urlscan.io/api/v1/result/b4357abe-3e21-4c2a-bca1-ffe073a8d645/",
  "url": "http://s.dappsannex.live",

  "api": "https://urlscan.io/api/v1/result/1a9a2aa0-cddd-422a-b4ed-22e24c71801f/",
  "url": "http://s.digital-smarthub.live",

  "api": "https://urlscan.io/api/v1/result/12475e7b-99ef-43e0-979b-461ef2fcd641/",
  "url": "http://s.digital-synchub.live",

  "api": "https://urlscan.io/api/v1/result/24a9d72a-96d2-48f7-93b1-09c5d53368b3/",
  "url": "http://s.digitalhubsyncs.live",

  "api": "https://urlscan.io/api/v1/result/65326694-6d57-4884-b5fb-cc18b288e58b/",
  "url": "http://s.migrates-smartfixs.live",

  "api": "https://urlscan.io/api/v1/result/78b1b3c2-7ef0-4ebd-9b9f-a5af2382dbdb/",
  "url": "http://s.smart-shellshocks.live",

  "api": "https://urlscan.io/api/v1/result/3804f0b1-35f0-4771-9adf-a42980ec1692/",
  "url": "http://s.smartprotocol-solution.live",

  "api": "https://urlscan.io/api/v1/result/befdbf00-6712-49f5-b1bf-f3413b941b7c/",
  "url": "http://s.stepn-fixs.live",

  "api": "https://urlscan.io/api/v1/result/0d92bcf9-4515-42f4-84f8-87c9fe5c7131/",
  "url": "http://secure-walletmask.pointdns.click",

  "api": "https://urlscan.io/api/v1/result/18e4067f-9f54-4c79-8963-14045f3fc7d4/",
  "url": "http://site.darpicsols.com",

  "api": "https://urlscan.io/api/v1/result/b421db0d-17f2-4367-aac7-3ffd6b05019e/",
  "url": "http://smart-indexprotocol.com",

  "api": "https://urlscan.io/api/v1/result/d3fe26b0-7a8c-4caa-8a0c-8a5e82f39df0/",
  "url": "http://smart-shellshocks.live",

  "api": "https://urlscan.io/api/v1/result/0887bd91-6c27-452d-8a87-5f564af0b921/",
  "url": "http://smartnoderestore.live",

  "api": "https://urlscan.io/api/v1/result/75c2295f-930b-460d-bcd0-8994e0ecfa79/",
  "url": "http://smartnodes.one",

  "api": "https://urlscan.io/api/v1/result/0595b6c1-0b78-42b1-8154-93ec0fdebc10/",
  "url": "http://smartprotocol-solution.live",

  "api": "https://urlscan.io/api/v1/result/7f81ac45-4433-493f-b2d8-b80aacc89dff/",
  "url": "http://stepn-fixs.live",

  "api": "https://urlscan.io/api/v1/result/51e5fe75-0f4a-4cf2-8fbb-9f5ad3a2c2e2/",
  "url": "http://support.pancakeswaps.it",

  "api": "https://urlscan.io/api/v1/result/665ce99e-dea3-4273-a333-de5bb1dfd16e/",
  "url": "http://svice-online-marketingupport.pancakeswaps.it",

  "api": "https://urlscan.io/api/v1/result/7b86ccc4-11aa-467a-8e38-fc61d265ec43/",
  "url": "http://switchrectifier.live",

  "api": "https://urlscan.io/api/v1/result/bdb06123-a015-4dfe-b0f7-2ef1ae2d309c/",
  "url": "http://tokensyncer.xyz",

  "api": "https://urlscan.io/api/v1/result/b7b9916f-0d21-4e42-b0f5-86095ac05723/",
  "url": "http://uniswap-tech.com",

  "api": "https://urlscan.io/api/v1/result/a2b3e238-bc4b-4576-a82c-adcefd50da72/",
  "url": "http://uniswap.pink",

  "api": "https://urlscan.io/api/v1/result/51e447f4-2cde-409b-951f-2b31cb728659/",
  "url": "http://unverifyedslogin-coinbase.com",

  "api": "https://urlscan.io/api/v1/result/c9e208cf-8373-4258-9010-246c9dcc32ab/",
  "url": "http://vechainunlockauth.org",

  "api": "https://urlscan.io/api/v1/result/f94b9c67-dd20-452d-9a0c-2c98e7d42a35/",
  "url": "http://walletconnect-user.info",

  "api": "https://urlscan.io/api/v1/result/1ccd412b-4bd5-467b-95fd-d59e9c55b174/",
  "url": "http://walletsolveteam.com",

  "api": "https://urlscan.io/api/v1/result/a1e06e0c-712e-4bb4-8214-9a5801fcde4d/",
  "url": "http://walletssycnauthentications.online",

  "api": "https://urlscan.io/api/v1/result/9016e83a-e47f-4998-be1b-a545afee65fe/",
  "url": "http://yearn-finance.exchange",

  "api": "https://urlscan.io/api/v1/result/bf5e89ac-6888-450f-88d3-a5ad7c82a0fc/",
  "url": "http://ylpydg3ryks5p8v.wallet.sergiy.top",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove duplicates
```
		"coinbase.secureauthlogin.com",
		"defiprotocolservices.net",
		"metamask.21travel.mindshards.net",
		"metamask.cirii.co",
		"metamask.io.merge.blocexpert.com",
		"metamask.lsnto.me",
		"metamask.oxog.net",
		"metamaskdao.io",
		"myeatherwallet.com",
		"myetherwallet.me",
		"pancakeswaps.it",
		"protocolsyncdapp.live",
		"uniswap-token.org",
		"uniswap.dev.smartypants850.com",
		"uniswaplabs.com",
```

**Comment by dubstard** [comment]
✅Ready for review.

**Review by dubstard — COMMENTED** [review]
Remove FP 
```
uniswap.pink
```
related to https://github.com/metroswap/uniswap-pink

image

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
