### PR TITLE
Polygon related phishing sites

### PR DESCRIPTION
**Pull request by rpolysec**
A list of Polygon related phishing sites from rpolysec.

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@rpolysec  can you remove dupes please

**Comment by AlexHerman1** [comment]
please also note that future new entries should be added to the top of the blacklist

**Comment by rpolysec** [comment]
My mistake, I missed a few duplicates.  Will try again.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
