### PR TITLE
Add Phishing Sites to Blocklist [18]

### PR DESCRIPTION
**Pull request by deshvin**
981004, 983662, 984767, 980098, 982383, 983537, 984178, 984195, 983454, 982539, 983321, 983826, 984017, 983190

fc69dd5a-2853-46ec-8a3f-ebcefdaf2f5c, eedb3b93-d07b-4efc-a5c0-712fd744e765, bbefc7d5-237f-4506-9133-7da409827b16, 22a97a59-c574-4702-b81e-8d4c4abcffb6

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by gleuch** [comment]
@deshvin @AlexHerman1 herokuapp.com is the top level domain for Heroku (hosting provider) in which many smaller apps running under subdomains. This could impact many apps and APIs using the default hosting subdomain URL.

**Comment by jmgraf** [comment]
@deshvin What was the reason for adding the top level domain for herokuapp.com, but not for the other hosting provider in the same commit (netlify.app)? 

@AlexHerman1 I think different branch protections need to be added to prevent merges of large lists of domains like this. Perhaps multiple required approvals before merging.

**Comment by AlexHerman1** [comment]
@jmgraf @gleuch  my apologies will address this

**Comment by 409H** [comment]
> What was the reason for adding the top level domain for herokuapp.com

Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/10241

**Pull request merged**
