### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Add 1̴2̴3̴  scams (sans duplicates). (updated to 187).

Add 187 scams (sans duplicates and with new baddies added 25-SEP-22)
```
		"abso.site",
		"0xethereumtoken.com",
		"37protocolwallet.com",
		"7023167.com",
		"accessmagiceden.io",
		"airdropallerts.com",
		"airdropcrypto.net",
		"airdrops.gifts",
		"amto.site",
		"apod.site",
		"apop.site",
		"app-etherminwallet.xyz",
		"app-kyberswap-exchanger.ga",
		"app-kyberswap-exchanger.gq",
		"app-kyberswap-exchanger.ml",
		"app-kyberswap-exchanger.tk",
		"app.sushi.com.farms-are-incentivized-pools.site",
		"app.xn--uniswp-tta.org",
		"arbitrum.top",
		"ardai.xyz",
		"as-uni.org",
		"as-uni.xyz",
		"asdai.xyz",
		"asol.site",
		"assets.login.coinbase.com.signin.sreman.site",
		"balancer.finance.royalfarmscatering.com",
		"balancerpro.com",
		"binance-airdrop.com",
		"bitcoinerwallet.net",
		"bitcoinerwallet.xyz",
		"bitcoinexchanges.space",
		"bitcoins-wallets.xyz",
		"bppo.site",
		"cdn.login.coinbase.com.signin.sreman.site",
		"claim.for-3.5-eth.holders.powering-web3-communities.site",
		"coinbase-authomatic.myddns.me",
		"coinbase.com.secure-auth.sessionid092322.app",
		"coinbase.thecryptoknights.io",
		"coinbasepay.org.uk",
		"connectmagiceden.net",
		"crypto-investing-bitcoin-bnb-ethereum-filcoin-cardano-chiliz.com",
		"deal-hk.info",
		"debugdappnode.com",
		"diviproject.net",
		"drop-claimairdrop.com",
		"eos-uniswap.com",
		"ethereum-pow.claims",
		"ethereum2.pl",
		"ethereum2.tokyo",
		"ethereum3.org",
		"ethereum4.org",
		"ethereumbuterin.com",
		"ethereummonthlyreturns-net.pureix.com",
		"ethereummonthlyreturns.net",
		"ethermine.biz",
		"ethermine.tires",
		"events.login.coinbase.com.signin.sreman.site",
		"exceptions.login.coinbase.com.signin.sreman.site",
		"exchange-y5crypto.com",
		"exchange.pancakeswap.finances.diwanvoyage.com",
		"exchange.spookyswaq.finance",
		"exchange.suslhlswap.com",
		"exchange.techcombank.com.vn",
		"exchange.topcryptofunds.com",
		"exchange1.blockchainhat.com",
		"exodos-wallet.com",
		"farms-are-incentivized-pools.site",
		"fart-app.com",
		"ferozo.com",
		"freeads-pay.com",
		"goblinstown.fun",
		"google.login.coinbase.com.signin.sreman.site",
		"googletag.login.coinbase.com.signin.sreman.site",
		"harmony-one.ltd",
		"hash.uniswap.team",
		"home-ethermine.com",
		"homeethermine.org",
		"horizen.plus",
		"housebank.online",
		"iexchangecrypto.com",
		"images.login.coinbase.com.signin.sreman.site",
		"imtoken-wallet-news.xyz",
		"imtokenmetamask.com",
		"imtokenmetamask.top",
		"keeper-wallet.app",
		"kyc-metamask-consensys.c1911585.ferozo.com",
		"ledgerlive.finance",
		"ledgerrlive.com",
		"ledgerwallet.finance",
		"legderlev.com",
		"live.ledgerlive.finance",
		"lives.ledgerwallet.finance",
		"login-zed.run",
		"login.coinbase.com.signin.sreman.site",
		"lotteryapi.uniswap.team",
		"magic-eden-collections-nft.co",
		"magic-eden-nft.net",
		"magic-eden.run",
		"magiceden-nft-marketplace.com",
		"magicedennft.co",
		"magicedennft.io",
		"magicedennft.tech",
		"magicedennfts.net",
		"mdai.io",
		"mergemetamask.com",
		"metamask-extension.com.yayasantqh.com",
		"metamask-flask.zendesk.com",
		"metamask.jajawprinters.com",
		"metamask.monster",
		"metamask.space",
		"metamask3.repl.co",
		"metamaskim.com",
		"metamaskio.repl.co",
		"metamaskloginn.com",
		"metamaskonline.email",
		"metamasks.fit",
		"metamasks.ink",
		"metamasks.win",
		"metamasks.world",
		"metamasksafe.com",
		"metamaskwallet.top",
		"money-payments.com",
		"multisignaturewallet.xyz",
		"multisignaturewallets.xyz",
		"muskwallet.com",
		"mvethereum.com",
		"myetherwallet.com.ng",
		"nft-wallet.finance",
		"olyimpusdao.finance",
		"online.uniswap.team",
		"opensa.nft-wallet.finance",
		"opensea.nft-wallet.finance",
		"pancakesvolendam.nl",
		"pancakeswap.finance.tokenswap.in",
		"pancakeswapair.finance",
		"pancakeswapandroidapp.com",
		"pancakeswapassetc.com",
		"pancakeswapbill.com",
		"pancakeswapfinance.design",
		"pancakeswaps.digitalkm.com.br",
		"pancakeswapsniperbot.thesniperbot.io",
		"pancakeswaptew.com",
		"paribu.swa-p.finance",
		"pivx.plus",
		"platform.uniswap-trade.com",
		"powering-web3-communities.site",
		"prohoster.biz",
		"racing-zed-run.com",
		"racing-zed-run.net",
		"racing-zed.run",
		"reclaim-coinbase.com",
		"royalfarmscatering.com",
		"saqy.games",
		"secure-hk.website",
		"shapeshift.finance",
		"sreman.site",
		"sushiswapx.com",
		"sushiv2.live",
		"swa-p.finance",
		"synapseprotocol.ltd",
		"syscoin.ltd",
		"the-flow.net",
		"unisvvap.claims",
		"uniswap-trade.com",
		"uniswap.cx",
		"uniswap.moe",
		"uniswap.now.sh",
		"uniswap.top",
		"uniswapp.me",
		"uniswaps.org.ams.rw",
		"usb-ledger.com",
		"usb.ledgerlive.finance",
		"v-wallet-graph.cf",
		"v3-uniswap.com",
		"visa-payments.site",
		"vvs-finance-exchange.com",
		"wallet-to-zed.run",
		"wallet.myycoinbase.com",
		"walletfrens.xyz",
		"webmetamask.net",
		"www-pancakeswap.ru",
		"www-trustwallet-safetycode.91-218-65-223.plesk.page",
		"xn--c1ajahiit.com",
		"xn--uniswp-tta.org",
		"xuniswap.com",
		"zedrun.biz",
		"app-kyberswap-exchanger.cf",
```

h/t 0xjade

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
get rid of redundant duplicates
```
access-spooky-swap.net
access-to-wallet-balancer-exchange.info
connectspookyswap.com
login-spooky.com.mx
metamask-web.co
metamask-web.ru
metamask.oxog.net
myetherwallet.me
pancakeswap-page.com
pancakeswap.co.com
spookyswapapp.com
uniswap.airdrops.gifts
vintage-myetherwallet.com
vintagemyetherwallet.com
wwwmyetherwallet.com
yearn-finance.exchange
```

**Review by dubstard — COMMENTED** [review]
add fake airdrops
```
		"abso.site",
		"amto.site",
		"apod.site",
		"apop.site",
		"ardai.xyz",
		"as-uni.org",
		"as-uni.xyz",
		"asdai.xyz",
		"asol.site",
		"bppo.site",
		"mdai.io",
```

**Review by dubstard — COMMENTED** [review]
add 
```
		"app-kyberswap-exchanger.cf",
		"app-kyberswap-exchanger.ga",
		"app-kyberswap-exchanger.gq",
		"app-kyberswap-exchanger.ml",
		"app-kyberswap-exchanger.tk",
		"coinbase.thecryptoknights.io",
		"coinbasepay.org.uk",
		"ethereum2.pl",
		"ethereum2.tokyo",
		"ethereum3.org",
		"ethereum4.org",
		"exodos-wallet.com",
		"goblinstown.fun",
		"iexchangecrypto.com",
		"imtoken-wallet-news.xyz",
		"imtokenmetamask.com",
		"imtokenmetamask.top",
		"ledgerrlive.com",
		"legderlev.com",
		"ledgerlive.finance",
		"live.ledgerlive.finance",
		"ledgerwallet.finance",
		"lives.ledgerwallet.finance",
		"metamask.monster",
		"metamask.space",
		"metamaskim.com",
		"metamaskloginn.com",
		"metamaskonline.email",
		"metamasks.win",
		"metamasks.world",
		"metamasksafe.com",
		"metamaskwallet.top",
		"muskwallet.com",
		"mvethereum.com",
		"nft-wallet.finance",
		"opensa.nft-wallet.finance",
		"opensea.nft-wallet.finance",
		"olyimpusdao.finance",
		"pancakeswap.finance.tokenswap.in",
		"pancakeswapandroidapp.com",
		"paribu.swa-p.finance",
		"swa-p.finance",
		"reclaim-coinbase.com",
		"shapeshift.finance",
		"sushiswapx.com",
		"sushiv2.live",
		"uniswap.now.sh",
		"uniswap.top",
		"uniswapp.me",
		"usb-ledger.com",
		"usb.ledgerlive.finance",
		"vvs-finance-exchange.com",
		"webmetamask.net",
		"www-trustwallet-safetycode.91-218-65-223.plesk.page",
		"xuniswap.com",
```

**Review by AlexHerman1 — APPROVED** [review]
ty!

**Comment by dubstard** [comment]
Thanks for the fast merge.
There are a couple of fake airdrop circulating right now so this speed really helps:
image

image

**Pull request merged**
