### PR TITLE
Block 65 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "1ww-uniswap.com",
    "airdrops-ethers.io",
    "appsecureauthsecure-coinbase.institutogomedicina.com.br",
    "appssecure-coinbaseaapps.injetaveisnapratica.com.br",
    "arbitrum.wlairdrop.xyz",
    "arbitrums.web3-frmint.com",
    "assetprotection-coinbase.com",
    "assets-coinbase.com",
    "babydoge.claim-web3.xyz",
    "care-coinbase.com",
    "claim.arbitrum.is",
    "arbitrum.is",
    "coinbase-pump22.org",
    "coinbase-service.top",
    "coinbasebank.top",
    "coinsmetamask.com",
    "connecting-wallet.xyz",
    "defi-binances.com",
    "defi-binances.net",
    "defi-binances.org",
    "ethereum-airdrops.org",
    "ethereums-airdrop.org",
    "ethereums-airdrops.io",
    "ethers-airdrope.org",
    "ethers-airdrops.org",
    "etherse-airdrop.org",
    "ethpow-coinbase.xyz",
    "graphpro.site",
    "ice-metemask.com",
    "login.coinbase.customerpage7272664.com",
    "login.coinbase.stillalive.website",
    "login.coinbase.unit21.com",
    "logincoinbase.efec3df3.tech",
    "logincoinbase.f3d3aa.systems",
    "maticwallet-technology.cf",
    "maticwallet-technology.ga",
    "maticwallet-technology.gq",
    "maticwallet-technology.ml",
    "maticwallet-technology.tk",
    "metamask-por4folio-dap.xyz",
    "metamaskio.net",
    "metapad.top",
    "mobile-coinbase.com",
    "ok-metamask.com",
    "openseaswap.com",
    "pancakeswap.finance.promodinamic.com",
    "pancakeswapp.net",
    "pancakeswaprest.com",
    "pushpro.space",
    "reconfirm-financialcoinbase.com",
    "recovery-metamask.com",
    "syncportals.com",
    "system-coinbase.com",
    "unisvvap-trading.org",
    "uniswap-official.monster",
    "uniswap-official.buzz",
    "uniswap-official.top",
    "uniswap-official.icu",
    "user63552-metamask.ddns.net",
    "vulcanbots.net",
    "wadzpay-airdrop.com",
    "woecoin.org",
    "xrpevent-x2.com",
    "xrpevent-x2.net",
```

```
  "description": "The domain 1ww-uniswap.com could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "result": "https://urlscan.io/result/4a20d4ac-a398-4f89-8130-772aaaaa44c3/",
  "url": "http://airdrops-ethers.io/",
}
  "result": "https://urlscan.io/result/748f199d-994b-4e96-bebd-6c7a89780eb3/",
  "url": "http://appsecureauthsecure-coinbase.institutogomedicina.com.br/",
}
  "result": "https://urlscan.io/result/425fb482-3d3b-4d53-aec0-1026b2899ae7/",
  "url": "http://appssecure-coinbaseaapps.injetaveisnapratica.com.br/",
}
  "result": "https://urlscan.io/result/26e21c40-65f9-4b4e-9bf0-95da66da2137/",
  "url": "http://arbitrum.wlairdrop.xyz/",
}
  "result": "https://urlscan.io/result/f4ca08fc-8142-44b9-ae8f-80cd9ccc5098/",
  "url": "http://arbitrums.web3-frmint.com/",
}
  "result": "https://urlscan.io/result/65aef6f7-3088-4632-8dfb-f103077507a5/",
  "url": "http://assetprotection-coinbase.com/",
}
  "description": "The domain assets-coinbase.com could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "result": "https://urlscan.io/result/b9eb8c77-42a5-4cc9-a74b-52ded2a0aee0/",
  "url": "http://babydoge.claim-web3.xyz/",
}
  "result": "https://urlscan.io/result/3761edb1-5ba5-4945-9a0f-f0d038d48420/",
  "url": "http://care-coinbase.com/",
}
  "result": "https://urlscan.io/result/94088a1c-2fd1-4f2d-bdca-14c72d0843d3/",
  "url": "http://claim.arbitrum.is/",
}
  "result": "https://urlscan.io/result/cbfab207-1014-4d30-a251-42ab4fd3d936/",
  "url": "http://arbitrum.is/",
}
  "result": "https://urlscan.io/result/7a7af93c-b88e-47b1-8b3b-9b5ad2a57eca/",
  "url": "http://coinbase-pump22.org/",
}
  "result": "https://urlscan.io/result/c2e49632-a748-4ad5-a46f-d91bb1df9e70/",
  "url": "http://coinbase-service.top/",
}
  "result": "https://urlscan.io/result/f28b6c21-cc37-4ecf-b722-a25a43ee6ba5/",
  "url": "http://coinbasebank.top/",
}
  "result": "https://urlscan.io/result/1ce6f4c8-609c-4d4c-8645-81c5e5157d19/",
  "url": "http://coinsmetamask.com/",
}
  "result": "https://urlscan.io/result/de6f11a6-bf33-49ce-bfd8-6a6b661fb740/",
  "url": "http://connecting-wallet.xyz/",
}
  "result": "https://urlscan.io/result/05495981-8ed6-46ca-8632-1e6d737367ad/",
  "url": "http://defi-binances.com/",
}
  "result": "https://urlscan.io/result/d82e6dd8-495c-40e9-999c-bb351f8b0738/",
  "url": "http://defi-binances.net/",
}
  "result": "https://urlscan.io/result/6a551d2c-927f-4b24-bc77-208cbf90ecb4/",
  "url": "http://defi-binances.org/",
}
  "result": "https://urlscan.io/result/05ace5f8-071d-46b9-9bf7-9ee95beb46bc/",
  "url": "http://ethereum-airdrops.org/",
}
  "result": "https://urlscan.io/result/7d84e2a4-f07d-4ea0-b86e-1055ade5f089/",
  "url": "http://ethereums-airdrop.org/",
}
  "result": "https://urlscan.io/result/66661333-3248-417d-8cc0-d7d3088b5538/",
  "url": "http://ethereums-airdrops.io/",
}
  "result": "https://urlscan.io/result/93df532f-bf51-4be6-b2ba-e3a3dc94f932/",
  "url": "http://ethers-airdrope.org/",
}
  "result": "https://urlscan.io/result/603dd51f-630b-45c0-94ac-346d271dbdc2/",
  "url": "http://ethers-airdrops.org/",
}
  "result": "https://urlscan.io/result/c21081f7-6758-484a-9440-4a7c4a5221c2/",
  "url": "http://etherse-airdrop.org/",
}
  "result": "https://urlscan.io/result/68590173-6789-43f8-8c15-758a6ab2a1ef/",
  "url": "http://ethpow-coinbase.xyz/",
}
  "result": "https://urlscan.io/result/8728c3a6-6902-4d44-9a37-291b482afd8c/",
  "url": "http://graphpro.site/",
}
  "result": "https://urlscan.io/result/fdd89db7-9ffe-4cb0-af81-2b93020171a6/",
  "url": "http://ice-metemask.com/",
}
  "result": "https://urlscan.io/result/9b6c1766-32c5-4110-93b8-0f124ab0b020/",
  "url": "http://login.coinbase.customerpage7272664.com/",
}
  "result": "https://urlscan.io/result/a73b2da8-3db7-4bbe-b535-1095d02e7f2f/",
  "url": "http://login.coinbase.stillalive.website/",
}
  "result": "https://urlscan.io/result/4e287872-34de-4406-8ae7-4b06ddb41086/",
  "url": "http://login.coinbase.unit21.com/",
}
  "result": "https://urlscan.io/result/ddfa31cb-3977-4b29-b6ac-6ce7465d3117/",
  "url": "http://logincoinbase.efec3df3.tech/",
}
  "result": "https://urlscan.io/result/2c564037-c6d6-46f9-ad21-2f0af5da580e/",
  "url": "http://logincoinbase.f3d3aa.systems/",
}
  "result": "https://urlscan.io/result/8675117d-8e35-48ed-bec4-24231aa621fe/",
  "url": "http://maticwallet-technology.cf/",
}
  "description": "The domain maticwallet-technology.ga could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain maticwallet-technology.gq could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain maticwallet-technology.ml could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain maticwallet-technology.tk could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "result": "https://urlscan.io/result/00948670-b4aa-4635-a921-23fdb5c8fb61/",
  "url": "http://metamask-por4folio-dap.xyz/",
}
  "result": "https://urlscan.io/result/82aa6404-20ea-4156-b936-66f18c4cbfb4/",
  "url": "http://metamaskio.net/",
}
  "result": "https://urlscan.io/result/2f1e2542-9340-4101-ac6f-f0aa72624a9b/",
  "url": "http://metapad.top/",
}
  "result": "https://urlscan.io/result/6652ffa0-4ab8-4a94-a6bc-4a0de03d15cc/",
  "url": "http://mobile-coinbase.com/",
}
  "result": "https://urlscan.io/result/43b43308-7530-4806-8b81-9ea89bbec42e/",
  "url": "http://ok-metamask.com/",
}
  "result": "https://urlscan.io/result/6dd3adcd-eb75-45ed-8a8c-70476278bdfb/",
  "url": "http://openseaswap.com/",
}
  "result": "https://urlscan.io/result/25616d3f-3a9f-4add-b73d-0ff6d1c128c4/",
  "url": "http://pancakeswap.finance.promodinamic.com/",
}
  "result": "https://urlscan.io/result/9c966210-eab3-417b-a333-f58827136e89/",
  "url": "http://pancakeswapp.net/",
}
  "result": "https://urlscan.io/result/aa37abdb-0a54-4251-b7b8-a392d74e374b/",
  "url": "http://pancakeswaprest.com/",
}
  "result": "https://urlscan.io/result/140e62c2-37c0-42b2-9ba0-d38b448a0a3c/",
  "url": "http://pushpro.space/",
}
  "result": "https://urlscan.io/result/025285ab-32e8-405d-81a2-9ea01849e3f8/",
  "url": "http://reconfirm-financialcoinbase.com/",
}
  "result": "https://urlscan.io/result/6f33d247-5d69-4147-bcf2-233977601e98/",
  "url": "http://recovery-metamask.com/",
}
  "result": "https://urlscan.io/result/66313c26-fee0-4c32-b73c-64a43ce36e0a/",
  "url": "http://syncportals.com/",
}
  "result": "https://urlscan.io/result/e44fef19-be3d-4cba-93d7-17197402dc7b/",
  "url": "http://system-coinbase.com/",
}
  "result": "https://urlscan.io/result/0250e022-0a11-466d-99c8-c5c3fa2ea770/",
  "url": "http://unisvvap-trading.org/",
}
  "description": "The domain uniswap-official.monster could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain uniswap-official.buzz could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain uniswap-official.top could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain uniswap-official.icu could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "result": "https://urlscan.io/result/9c72cddf-2aee-4143-815f-fde625ec6af8/",
  "url": "http://user63552-metamask.ddns.net/",
}
  "description": "The domain vulcanbots.net could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "result": "https://urlscan.io/result/8ac53f5b-cffb-4874-bd49-6155ca9ba1f7/",
  "url": "http://wadzpay-airdrop.com/",
}
  "result": "https://urlscan.io/result/e7470bbc-6f74-43e7-a8a8-a732dbd71eca/",
  "url": "http://woecoin.org/",
}
  "description": "The domain xrpevent-x2.com could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  "description": "The domain xrpevent-x2.net could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block `krypt-crest.surge.sh`
image

image

scammer fail
MF bolted a word to the URL, rendering it nonworking 🤡

**Review by dubstard — COMMENTED** [review]
block 
```
    "defipad.top",
    "metaspot.top",
    "boxweb3.top",
```

**Review by dubstard — COMMENTED** [review]
block
```
    "porsche-911-web3.netlify.app",
    "sappy-seals-web3.netlify.app",
```
image
image
image

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
