### PR TITLE
Block 53 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
image

```
    "airdrop-1inch.com",
    "airdrop.optimism-labs.org",
    "app.uniswapv3lp.org",
    "arbitrum-live.com",
    "arbitrum-monday.com",
    "arbitrum-reward.com",
    "arbitrum-store.com",
    "arbitrum-tokens.com",
    "blrdrop.site",
    "bridge.arbitrum-tokens.com",
    "claimoptimism.xyz",
    "coinbase-authvcsae.condition-ogc.com",
    "coinbase-authvcsae.dsmtp.com",
    "coinbase-authvcsae.dsmtp.com.condition-ogc.com",
    "litterabbitproject.com",
    "metamask0.com",
    "metamask0.org",
    "metamask1.com",
    "metamask2.org",
    "metamask3.org",
    "metamask4.org",
    "metamask5.com",
    "metamask5.org",
    "metamask6.com",
    "metamask6.org",
    "metamask7.com",
    "metamask7.org",
    "metamask8.com",
    "metamask9.com",
    "metamask9.org",
    "metamass.xyz",
    "mglandnft.com",
    "musk-promotion.org",
    "optimism-labs.org",
    "pancake-airdrops.com",
    "pancakeswap-token.com",
    "reset-security-coinbase.com",
    "resets-coinbase.com",
    "svc-security-coinbase.com",
    "teslapresale.finance",
    "the-ethereumcode-pro.com",
    "tokens-arbitrum.com",
    "trustwallet.com.secure.login.lansmanmedia.com",
    "uniswap.v2-protocol.org",
    "uniswapv3lp.io,
    "updates-metamask.co",
    "wax-wallet-login.icu",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block teslapresale.finance

whoops, someone left their kit in the open, haha
image

**Review by dubstard — COMMENTED** [review]
remove wax-wallet-login.icu (not sure what is it, does not appear harmful (yet)

**Review by dubstard — COMMENTED** [review]
block fake OpenSea chompersanctuary.com

**Review by dubstard — COMMENTED** [review]
fix json fat finger
add punycode scams h/t @tayvano

**Review by dubstard — COMMENTED** [review]
block `dappwalletnode.web.app`
h/t MalwareHunterTeam
image

**Review by dubstard — COMMENTED** [review]
block walletconnecty.netlify.app
h/t [MalwareHunterTeam](https://twitter.com/malwrhunterteam)

**Review by deshvin — APPROVED** [review]

**Pull request merged**
