### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Spray and pray (PRE duplicate check)

image

https://user-images.githubusercontent.com/49607867/195275345-86441ce6-00c1-413a-b118-067a2eafe83f.mov

```
    "1inch-in.com",
    "1inch.money",
    "2factor-metamask.io",
    "access-account-sushiswap.ga",
    "accesssrewards.web.app",
    "accountmetamask.online",
    "accounts.coinbase-eth.net",
    "airdrop-coins-givecap.fun",
    "airdrop-coins-givecap.pw",
    "airdrop-coins-givecap.space",
    "airdrop-coins-givecap.top",
    "airdrop-coins-givecap.xyz",
    "airdrop-coinsgivecap.fun",
    "airdrop-coinsgivecap.pw",
    "airdrop-coinsgivecap.space",
    "airdrop-coinsgivecap.top",
    "airdrop-coinsgivecap.xyz",
    "app-uniswap.finance",
    "bii-swap.com",
    "binance-nfts.web.app",
    "bonus-pancakeswap.com",
    "ccl-pancakeswop.com",
    "ccp-pancakeswop.com",
    "centralizedapp-crypto.my.id",
    "chaintradecopy.com",
    "ethereumerge.info",
    "coinbase-eth.net",
    "coinbase-market.com",
    "coinbase-signinaccount.infomy-media.com",
    "coinbase-support-password-reseting826272666.top",
    "coinbase-taxsupportcenter.com",
    "coinbase-updated.servehalflife.com",
    "coinbase.wallet-commerce.com",
    "coinbasecloud.cn",
    "coinbasecwap.com",
    "coinbaseverify.com",
    "coinbasewalletnft.com",
    "coinbasewalletpro.co",
    "coinelitepro.com",
    "com.merge.corpbancafinance.com",
    "connect-dappsconnectf5a.10cek.ru",
    "corpbancafinance.com",
    "cosmos-wallets.com",
    "crypto-mainfunds.com",
    "crypto-virtues.com",
    "crypto3base.cf",
    "crypto3base.ga",
    "crypto3base.gq",
    "crypto3base.ml",
    "crypto3base.tk",
    "crypto4base.cf",
    "crypto4base.gq",
    "crypto4base.tk",
    "curva-finance.com",
    "deficonnector.netlify.app",
    "earn-pancakeswap.com",
    "ethereum-privatekey.com",
    "ethereumv2-pos.org",
    "exodus.com.merge.corpbancafinance.com",
    "exodus.com.merge.creativeartistinternational.com",
    "exodus.com.merge.gtaaccounting.us",
    "exodus.com.merge.ibrandcart.com",
    "exodus.com.merge.ifeoluwaajetomobi.xyz",
    "exodus.com.merge.msecorp9.com",
    "exodus.com.merge.msvcorporation.com",
    "exodus.com.merge.multikme.info",
    "exodus.com.merge.platwise.com",
    "exodus.com.merge.waamcomputersllc.com",
    "exoduswallet.app",
    "extension-metamask-io.c2091686.ferozo.com",
    "extension-metamask-io.hnalkhedmad.com",
    "extension-metamask-nkbihfbeogaeaoehlefn.c1541460.ferozo.com",
    "extension-metamask-nkbihfbeogaeaoehlefn.hnalkhedmad.com",
    "extensions.hnalkhedmad.com",
    "ftxwallets.net",
    "help-metamask-io.c1931535.ferozo.com",
    "help-metamask-ioasasaaq.hnalkhedmad.com",
    "help-opensea-io.c2501312.ferozo.com",
    "help-opensea-io.hnalkhedmad.com",
    "ht.uniswapv4.com",
    "imetamask.live",
    "imtokern.info",
    "io.merge.corpbancafinance.com",
    "kraken-mining.com",
    "kraken-mining.primecapitalltd.com",
    "ledger-fix.solutions",
    "ledger-live.nyc",
    "ledger-phraselive.org",
    "ledgerrlive.org",
    "ledgers-live.org",
    "link-secure-online-identity-verification-coinbase.com",
    "ll-poocoiin-appswap.cf",
    "ll-poocoiin-appswap.ga",
    "ll-poocoiin-appswap.gq",
    "ll-poocoiin-appswap.ml",
    "ll-poocoiin-appswap.tk",
    "login.coinbase.accounts.e1th.homes",
    "login.coinbase.com.signin.inf-eh.com",
    "login.metamask.io.vigoroustechnologies.org",
    "login.opensea.2fasset.c2511312.ferozo.com",
    "loginopensea.hnalkhedmad.com",
    "mainnet-uniswap.org",
    "merge.corpbancafinance.com",
    "metamask-accouht.com",
    "metamask-exchange.com",
    "metamask-flask1665412637.zendesk.com",
    "metamask-giveaway.com",
    "metamask-iowallet.rhymetimedaycare.com",
    "metamask-live.com",
    "metamask-migrate.com",
    "metamask-portfolio1665412638.zendesk.com",
    "metamask-recover.myvnc.com",
    "metamask-verify.meta-tag.org",
    "metamask.404exist.com",
    "metamask.ac",
    "metamask.army",
    "metamask.co.uk",
    "metamask.io.merge.aava.com.bd",
    "metamask.io.merge.amdaplanejados.com.br",
    "metamask.io.merge.anishpahi.com.np",
    "metamask.io.merge.boipondit.com",
    "metamask.io.merge.buyhosting2022.xyz",
    "metamask.io.merge.constructiontimelapsesaskatchewan.com",
    "metamask.io.merge.corpbancafinance.com",
    "metamask.io.merge.creativeartistinternational.com",
    "metamask.io.merge.deltaproductcorporation.com",
    "metamask.io.merge.enduck.com",
    "metamask.io.merge.getshrooms.org",
    "metamask.io.merge.ifeoluwaajetomobi.xyz",
    "metamask.io.merge.jfinvest-group.com",
    "metamask.io.merge.livestreamsaskatchewan.com",
    "metamask.io.merge.osbprinting.com",
    "metamask.io.merge.platwise.com",
    "metamask.io.merge.premiumnow.xyz",
    "metamask.io.merge.primeplex.xyz",
    "metamask.io.merge.timelapsesaskatchewan.com",
    "metamask.io.merge.tonyquinones.me",
    "metamask.io.merge.unitedcables.pk",
    "metamask.io.merge.universalfreightmovers.com",
    "metamask.io.merge.xpertfuneralhome.com",
    "metamask.io.merge.xpertwheel.com",
    "metamask.io.merge.ynotmedia.ca",
    "metamask.merge-approval.info",
    "metamask.project.socjsc.com",
    "metamask.promo",
    "metamask.sgcrypto.info",
    "metamask1665412636.zendesk.com",
    "metamaskaccouht.com",
    "metamaskaccount.online",
    "metamaskawallet.online",
    "metamaskdownload.com",
    "metamaskinfo.com",
    "metamaskio.livrariapressao.com",
    "metamasklagin.com",
    "metamasklogih.com",
    "metamaskloqih.com",
    "metamaskmint.com",
    "metamaskswaps1665412639.zendesk.com",
    "metamaskvallet.online",
    "metamaskwalledown.azurewebsites.net",
    "metamaskwallet.life",
    "metamaskwallet.site",
    "metamaskwhois.com",
    "metamaskworld.azurewebsites.net",
    "muskdapp.org",
    "my-metamask.com",
    "myetherwallet.com.co",
    "nft-charity.net",
    "nominexauth.web.app",
    "official-bittrex.exchange",
    "opensea-2faccount.duia.eu",
    "opensea-2faccount.hnalkhedmad.com",
    "opensea-io-assets-ethereum.com",
    "opensea-login.hnalkhedmad.com",
    "opensea-nftometamask-tools.azurewebsites.net",
    "opensea-wallet.duia.us",
    "opensea-wallet.hnalkhedmad.com",
    "opensea.hnalkhedmad.com",
    "opensea.loginextensions.c1971529.ferozo.com",
    "openseaasasawwa.hnalkhedmad.com",
    "opensealogin.dynv6.net",
    "opensealogin.hnalkhedmad.com",
    "othersïde.xyz",
    "pacificethereum.com",
    "pancakeswajp.com",
    "pancakeswap-airdrop.pro",
    "pancakeswap-connectwallet.granticket.com",
    "pancakeswap-informat.com",
    "pancakeswap-supp.com",
    "pancakeswap-wael.com",
    "pancakeswap.com.kz",
    "pancakeswap.duckdns.org",
    "pancakeswap.finance.cwap.in",
    "pancakeswap.finance.trade-change.in",
    "pancakeswap.gq",
    "pancakeswap.jp",
    "pancakeswapairdrop.info",
    "pancakeswapescrow.com",
    "pancakeswapps.com",
    "pancakeswapreward.tk",
    "pancakeswapwallets.granticket.com",
    "pancakkeswap.org",
    "polygn-wallet.online",
    "polygon-finance.ru",
    "polygon.tamadogegiveaway.online",
    "pool-pancakeswap.com",
    "portfolio-metamask.com",
    "premiumwealthltd.net",
    "pro-minter.com",
    "protocol-uniswap.org",
    "protocolmetamask.org",
    "qfsledger-security.com",
    "recover-wallet-dat.tech",
    "safe-hedge-io.safe-swap.exchange",
    "safe-nfts-io.safe-swap.exchange",
    "safe-swap.exchange",
    "safe-wallet-io.safe-swap.exchange",
    "secure012-v3riff-coinbases.com",
    "server-7-collab.land",
    "stablecoin-fx.co",
    "stakes-pancakeswap.com",
    "suhslswap.wvw-suwaps.xyz",
    "support-coinbase.workers.dev",
    "supportpro-coinbase.com",
    "sushiswap-login.cf",
    "sushiswap-login.ga",
    "sushiswap-login.gq",
    "sushiswap-login.ml",
    "sushiswap-login.tk",
    "sushiswap-manage.tech",
    "sushiswap.org",
    "sushiswapfor.com",
    "sushiswapgeet.tech",
    "sushiswapp-app-login.cf",
    "sushiswaptrendin.com",
    "sushiswaptrust.tech",
    "swap-exchange.com",
    "themetamask.xyz",
    "tpwalletpro.info",
    "tronwallet.online",
    "trustwallethud.xyz",
    "trustwalletlogin.ml",
    "uniswap-app.com",
    "uniswap-defi-vip.co",
    "uniswap-defi-vip.com",
    "uniswap.cn.com",
    "uniswap.co.cm",
    "uniswap.direct",
    "uniswap.eu",
    "uniswap.global",
    "uniswap.la",
    "uniswap.morpheuscommunity.net",
    "uniswap.nuanchansoft.llc",
    "uniswap.org.accept-now.site",
    "uniswap.org.in",
    "uniswap.se",
    "uniswap.team",
    "uniswap.wap-v3.org",
    "uniswap.zapto.org",
    "uniswap2dex.com",
    "uniswapassets.tech",
    "uniswapbuybot.com",
    "uniswapc.net",
    "uniswaper.me",
    "uniswapfoundation.org",
    "uniswapi.cloud",
    "uniswapj.com",
    "uniswapk.com",
    "uniswapl.net",
    "uniswaplending.net",
    "uniswaply.com",
    "uniswapm.net",
    "uniswapmobile.com",
    "uniswapn.net",
    "uniswappe.com",
    "uniswapps.org",
    "uniswapr.net",
    "uniswapr.org",
    "uniswapu.net",
    "uniswapu.org",
    "uniswapv3.art",
    "uniswapv4.com",
    "uniswapventures.com",
    "uniswapw.info",
    "update-authentication-coinbase.com",
    "update-metamask.myddns.me",
    "update.decentralizedapps.top",
    "verifyaccess3d-coinbase.com",
    "vvwwpancakeswap.top",
    "wallet-connect.solutions",
    "wallet-near-account.ga",
    "wallet-near-account.ml",
    "wallet-near-account.tk",
    "wallet-persistence-one.cf",
    "wallet-persistence-one.ga",
    "wallet-persistence-one.gq",
    "wallet-persistence-one.tk",
    "wallet.coinbase-eth.net",
    "wallet.discord-acc.ru",
    "walletmetamask.online",
    "wallets-crypto.xyz ",
    "walletsconnetmulticoin.online",
    "walletsupport-coinbase.com",
    "web3-uniswap.org",
    "wvvvv-kraken.website",
    "wvw-pancakesvvap.vip",
    "wwioth.com",
    "wwvvuniswap.top",
    "www-account-bitvavo.cf",
    "www-account-bitvavo.ga",
    "www-account-bitvavo.gq",
    "www-account-bitvavo.ml",
    "www-account-bitvavo.tk",
    "wwwethereum.xyz",
    "wwwkraken.com",
    "xn--othersde-z2a.xyz",
```

### CODE REVIEW

**Comment by dubstard** [comment]
Some duplicates and one punycode entry need removing
IDN Punycode
```
othersïde.xyz
```

Dupes
```
1inch-in.com
ethereumerge.info
coinbase.wallet-commerce.com
coinbasewalletnft.com
ethereumv2-pos.org
exoduswallet.app
extension-metamask-nkbihfbeogaeaoehlefn.c1541460.ferozo.com
extension-metamask-nkbihfbeogaeaoehlefn.hnalkhedmad.com
metamask-iowallet.rhymetimedaycare.com
metamask-live.com
metamask-verify.meta-tag.org
metamask.project.socjsc.com
metamask.sgcrypto.info
metamaskdownload.com
metamaskinfo.com
metamaskwallet.life
metamaskwallet.site
myetherwallet.com.co
pancakeswap.finance.cwap.in
pancakeswap.gq
pancakeswapreward.tk
uniswap-defi-vip.co
uniswap-defi-vip.com
uniswap.eu
uniswap.global
uniswap.org.in
uniswap.se
uniswap.team
uniswaper.me
uniswaply.com
uniswapmobile.com
uniswapv4.com
uniswapventures.com
walletsupport-coinbase.com
web3-uniswap.org
xn--othersde-z2a.xyz
```

**Review by dubstard — COMMENTED** [review]
Remove punycode
```
othersïde.xyz
```

Remove duplicates
```
1inch-in.com
ethereumerge.info
coinbase.wallet-commerce.com
coinbasewalletnft.com
ethereumv2-pos.org
exoduswallet.app
extension-metamask-nkbihfbeogaeaoehlefn.c1541460.ferozo.com
extension-metamask-nkbihfbeogaeaoehlefn.hnalkhedmad.com
metamask-iowallet.rhymetimedaycare.com
metamask-live.com
metamask-verify.meta-tag.org
metamask.project.socjsc.com
metamask.sgcrypto.info
metamaskdownload.com
metamaskinfo.com
metamaskwallet.life
metamaskwallet.site
myetherwallet.com.co
pancakeswap.finance.cwap.in
pancakeswap.gq
pancakeswapreward.tk
uniswap-defi-vip.co
uniswap-defi-vip.com
uniswap.eu
uniswap.global
uniswap.org.in
uniswap.se
uniswap.team
uniswaper.me
uniswaply.com
uniswapmobile.com
uniswapv4.com
uniswapventures.com
walletsupport-coinbase.com
web3-uniswap.org
```

**Review by dubstard — COMMENTED** [review]
fix json (remove extra space)

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
Thank you, Preparing another one now.

**Pull request merged**
