### PR TITLE
Block 73 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
Block 73 scam URLs
```
    "1inch-airdrop.io",
    "about-dafiprotocol.com",
    "activation-metamask.ddns.net",
    "airdrop-alert-me.com",
    "airdrop-dogecoin.com",
    "airdrop-metamask.lol",
    "airdrop-zone.com",
    "allocation-zksync.com",
    "apeswap-fi.com",
    "appbungee-exchange.com",
    "arbitrumprotocols.netlify.app",
    "asternetwork-portal.com",
    "blockchain-technode.com",
    "changenet.work",
    "claim-premint.xyz",
    "claim-starkware.com",
    "claim-your-prize.xyz",
    "claimusdc.online",
    "collablands.co",
    "cryptocueupdate.info",
    "dapps-seedify.org",
    "event-1inch.site",
    "foundaiton-check-your-eligibility-to-claims.pw",
    "gloryfinance.info",
    "home-souffl3.com",
    "kodapendant-otherside.xyz",
    "kyc-metamask.servehttp.com",
    "lidorating.com",
    "looks-distributions.org",
    "metamask-kyc.serveftp.com",
    "metamask-refer.com",
    "metamask.review",
    "metamask.tel",
    "metamask.vn",
    "metamaskt.com",
    "my-metamask.co",
    "network-portalastar.com",
    "nftplacelist.com",
    "nova-dogecoin.com",
    "opensea-pro.com",
    "pancake.financeswap.click",
    "pancakeswep.site",
    "portal-networkastar.com",
    "portfolio-metamaskio.com",
    "portfollo-meltamask.com",
    "pullhilep.com",
    "redlido.com",
    "register-aave.com",
    "register-dogecoin.com",
    "register-zeta.com",
    "seedify-dapps.com",
    "seedjfy-fund.com",
    "signin-layerzero.com",
    "spaceidprotocol.org",
    "suite-maticbridge.com",
    "tatecobra.net",
    "tesladouble-event.com",
    "tokenclaim.win",
    "tpad-airdrop.top",
    "trustpad-500.top",
    "trustpads-500.top",
    "trustpads500.top",
    "uniswap-community.com",
    "uniswap.launch-v2.org",
    "uniswapcoin.net",
    "uniswaps.net",
    "unlock-protocol.com",
    "vulcan.to",
    "whitelist-dogecoin.com",
    "www-1nch.com.trustpadx.org",
    "zapper.cx",
    "zk-sync.sk",
    "zk-synks.space"
```

Not the 1inch you need
```
    "1inch-airdrop.io",
    "event-1inch.site",
    "www-1nch.com.trustpadx.org",
```

Not the Airdrop you need
image
I wonder how Andrew Tate would do a giveaway from jail, but whatever
```
    "airdrop-alert-me.com",
    "airdrop-dogecoin.com",
    "airdrop-zone.com",
    "claim-premint.xyz",
    "claim-starkware.com",
    "claim-your-prize.xyz",
    "claimusdc.online",
    "tatecobra.net", 
    "tesladouble-event.com",
    "tokenclaim.win",
    "foundaiton-check-your-eligibility-to-claims.pw",
```

Not the Apeswap you need
```
    "apeswap-fi.com",
```

Not the Opensea you need
```
    "opensea-pro.com",
```
   
Not the Bungee you need
```
    "appbungee-exchange.com",
```

Not the Collabland you need
```
    "collablands.co",
```

Not the Uniswap you need
```
    "uniswap-community.com",
    "uniswap.launch-v2.org",
    "uniswapcoin.net",
    "uniswaps.net",
    "pullhilep.com",
```

Not the Looksrare you need
```
    "looks-distributions.org",
```

Not the Lido you need
```
    "lidorating.com",
    "redlido.com",
```

Not the Metamask you need
```
    "activation-metamask.ddns.net",
    "airdrop-metamask.lol",
    "metamask-kyc.serveftp.com",
    "metamask-refer.com",
    "metamask.review",
    "metamask.tel",
    "metamask.vn",
    "metamaskt.com",
    "my-metamask.co",
    "portfolio-metamaskio.com",
    "portfollo-meltamask.com",
    "kyc-metamask.servehttp.com",
```

Not the Pancakeswap you need
```
    "pancake.financeswap.click",
    "pancakeswep.site",
```

Not the Deedify you need
```
    "seedify-dapps.com",
    "seedjfy-fund.com",
    "dapps-seedify.org",
```

Not the Arbitrum you need
```
    "arbitrumprotocols.netlify.app",
```

Not the Doge you need
```
    "register-dogecoin.com",
    "whitelist-dogecoin.com",
    "nova-dogecoin.com",
```	

Not the Astar you need
```
    "asternetwork-portal.com",
    "portal-networkastar.com",
```	

Not the ZkSync you need
```    
    "allocation-zksync.com",
    "zk-sync.sk",
    "zk-synks.space",
```
	

Not the AAVE you need
```    
    "register-aave.com",
```

Not the Trustpad you need
```    
    "tpad-airdrop.top",
    "trustpad-500.top",
    "trustpads-500.top",
    "trustpads500.top",
    "unlock-protocol.com",
```

Not the Discord vulcan bot you need
```    
    "vulcan.to",
```    

Not the Zapper.fi you need
```    
    "zapper.cx",
```    	

Not the Polygon Matic you need
``` 
    "suite-maticbridge.com",
``` 	

Not the Otherside you need
``` 
    "kodapendant-otherside.xyz",
```

Not the WalletConnect you need
``` 
    "about-dafiprotocol.com",    
    "blockchain-technode.com",
    "changenet.work",
    "coiresolveapps.live",
    "cryptocueupdate.info",
    "gloryfinance.info",
    "home-souffl3.com",
    "network-portalastar.com",
    "nftplacelist.com",
    "register-zeta.com",
    "signin-layerzero.com",
    "spaceidprotocol.org",
```

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
thanks!

**Comment by julien51** [comment]
Hey, any reason why `unlock-protocol.com` is in there? https://unlock-protocol.com/

**Comment by julien51** [comment]
@AlexHerman1 @dubstard I am not sure how to get this changed... but I dont think that's correct.

**Pull request merged**
