### PR TITLE
remove Ethereum Classic domains from blocklist

### LINKED ISSUE #10124: [Legitimate Site Blocked] ethereumclassic.com
https://ethereumclassic.com/

This is a legitimate website.

### PR DESCRIPTION
**Pull request by gitr0n1n**
<ethereumclassic.com>, and the other domains I've included in this PR are legitimate domains owned by myself or [Ethereum Classic DAO](https://github.com/EthereumClassicDAO). I'm the leading dev of the organization and a long-term contributor to the [Ethereum Classic repo](https://github.com/orgs/ethereumclassic/people). Thanks!

Close https://github.com/MetaMask/eth-phishing-detect/issues/10124.

Add Legitimate Ethereum Classic Sites to Whitelist:
+ ethclassic domains
+ ethereumclassic domains
+ etc grants dao domain
+ ethereum classic dao domain
+ etcswap domain
+ wrapped ether (WETC) domain

Remove Legitimate Sites from Blacklist:
+ ethereumclassic.com
+ ethereumclassicdao.org
+ ethereumclassic.kve.mcr.mybluehost.me

Follow Up after Deeper Review into how our sites got on this blacklist: 👀 

@dubstard @AlexHerman1 It looks like our websites were accidentally blacklisted in this bulk PR collection. Please be more cautious when submitting/reviewing these bulk PRs. 🙏
https://github.com/MetaMask/eth-phishing-detect/pull/10034

Proactively, we will add our websites to this whitelist repo in the future in our product launch checklist to prevent this error as well. 👍  Thanks in advance for correcting! ~ r0n1n

### CODE REVIEW

**Comment by gitr0n1n** [comment]
@dubstard @AlexHerman1 It looks like our websites were accidentally blacklisted in this bulk PR collection. Please be more cautious when submitting/reviewing these bulk PRs. Proactively, we will add our websites to this whitelist repo in the future in our product launch checklist to prevent this error. Thanks for correcting! ~ r0n1n

https://github.com/MetaMask/eth-phishing-detect/pull/10034

**Comment by dubstard** [comment]
thanks for the heads up and apologies for the nuisance!
cc @409H

**Comment by legobeat** [comment]
Thank you for the report. "Proactive" allowlist entries should not be part of the list so I am reducing this to the blocklist removals as none of the other hostnames are blocked with that. Apologies for the false flags and again, thanks for preparing a fix.

**Review by legobeat — APPROVED** [review]

**Comment by dubstard** [comment]
Thank you sincerely for the fast reaction and apologies for the FP.

**Pull request merged**
