### PR TITLE
Block 62 scams

### PR DESCRIPTION
**Pull request by dubstard**
---------------

`usacryptowallet.com`
❌remove nested subdomains    "shibuswap.net.usacryptowallet.com",
✅keep only main apexdomain    "usacryptowallet.com",

same domain has countless trash subdomains
image

------------------------

image

``````````````


```
    "1inch-exchange.globalcryptopress.com",
    "1inch-network.app-mdex.com",
    "apecoindao.vip",
    "arbdoges.gift",
    "avalaunchs.app",
    "avaslaunch.co",
    "banterbubbles.com",
    "bradevent.net",
    "bradgive.com",
    "chainlayerzero.com",
    "chainresolve.io",
    "claim-airdrop-355.pages.dev",
    "claim-mask.org",
    "claims-ripple.app",
    "coinchange.world",
    "connect-claim.network",
    "crypto.claims",
    "cymfw.com",
    "defi-lido.fi",
    "defi-ripple.com",
    "degods-claim.xyz",
    "earnripple.live",
    "earnripple.xyz",
    "elon-claim.com",
    "enter-thorchain.net",
    "just-pads.top",
    "kaspa.gifts",
    "lidoevent.com",
    "meta-claim.online",
    "metamask-extension-io.online",
    "metamask-extension-io.site",
    "metamask-recovery.ddns.net",
    "metamask.com-receive-token.site",
    "metamask.mobi",
    "metamask.nitriumsg.com",
    "metamask6.shop",
    "metamaskairdrop.online",
    "metamaskclaim.com",
    "metamaskextension.online",
    "metamaskextension.site",
    "metis-claims.org",
    "mrbeastgiftclaim.com",
    "optimism-bridge.io",
    "ripple-web3.net",
    "ripple.gives",
    "ripple.lc",
    "ripples.claims",
    "rippleweb3.me",
    "scroll.gift",
    "starbucks-nft.marketing",
    "web3-arbitrum.com",
    "xblur-io.cloud",
    "xrpledger.top",
    "xrps-claim.org",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
image

**Review by dubstard — COMMENTED** [review]
image

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by CryptoBanterSchool** [comment]
> `usacryptowallet.com` ❌remove nested subdomains "shibuswap.net.usacryptowallet.com", ✅keep only main apexdomain "usacryptowallet.com",
> 
> same domain has countless trash subdomains image
> 
> image
> 
> ```
> 
> 
> ```
>     "1inch-exchange.globalcryptopress.com",
>     "1inch-network.app-mdex.com",
>     "apecoindao.vip",
>     "arbdoges.gift",
>     "avalaunchs.app",
>     "avaslaunch.co",
>     "banterbubbles.com",
>     "bradevent.net",
>     "bradgive.com",
>     "chainlayerzero.com",
>     "chainresolve.io",
>     "claim-airdrop-355.pages.dev",
>     "claim-mask.org",
>     "claims-ripple.app",
>     "coinchange.world",
>     "connect-claim.network",
>     "crypto.claims",
>     "cymfw.com",
>     "defi-lido.fi",
>     "defi-ripple.com",
>     "degods-claim.xyz",
>     "earnripple.live",
>     "earnripple.xyz",
>     "elon-claim.com",
>     "enter-thorchain.net",
>     "just-pads.top",
>     "kaspa.gifts",
>     "lidoevent.com",
>     "meta-claim.online",
>     "metamask-extension-io.online",
>     "metamask-extension-io.site",
>     "metamask-recovery.ddns.net",
>     "metamask.com-receive-token.site",
>     "metamask.mobi",
>     "metamask.nitriumsg.com",
>     "metamask6.shop",
>     "metamaskairdrop.online",
>     "metamaskclaim.com",
>     "metamaskextension.online",
>     "metamaskextension.site",
>     "metis-claims.org",
>     "mrbeastgiftclaim.com",
>     "optimism-bridge.io",
>     "ripple-web3.net",
>     "ripple.gives",
>     "ripple.lc",
>     "ripples.claims",
>     "rippleweb3.me",
>     "scroll.gift",
>     "starbucks-nft.marketing",
>     "web3-arbitrum.com",
>     "xblur-io.cloud",
>     "xrpledger.top",
>     "xrps-claim.org",
> ```
> ```

Why was banterbubbles added to this list @AlexHerman1? It's not a scam / phishing site?

**Pull request merged**
