### PR TITLE
Block fake Vulcans (discord social engineering attack)

### PR DESCRIPTION
**Pull request by dubstard**
image
image
image
image
image
image
image
image
image
image
image
image

```
    "1inch.web3-dexapp.online",
    "arb-drop.com",
    "aragon.cab",
    "arbitrumbrldge.com",
    "arbitrumlink.com",
    "arbitrurn-labs.com",
    "authvulcan.xyz",
    "azuki-bean.com",
    "balancerfi.workers.dev",
    "balancerprice.com",
    "balancerprice.org",
    "blockchainbets-airdrops.org",
    "bluri.co",
    "bridge-erbltrom.com",
    "bridgo-erbltram.com",
    "c0lnbasesupportupdate.imnubgkepi.buzz",
    "decentralnodemultichaindapp.online",
    "gigaswap-airdrope.org",
    "hhuuop.com",
    "kyc-walletcoinbase.serveirc.com",
    "lido.onl",
    "mellonfeased.000webhostapp.com",
    "metamask-verification-process.com",
    "metamask.appocean.mobi",
    "metamask.learnblockchain.today",
    "metamask4.repl.co",
    "metamaskapp.link",
    "metamasks.net",
    "metamasksupporttask.com",
    "officialtrustwallet.com",
    "pancakeswop.space",
    "pancakewalet.com",
    "pensive-meitner-298020.netlify.app",
    "rubic.claims",
    "sudoswapairdrops.org",
    "support-metamask-connect.com",
    "trustpadairdrop.net",
    "uniswaption.com",
    "vulcan-xyz-verify-a98db973kwl8xp1lz94.netlify.app",
    "vulcanauth.eu",
    "vulcanauth.net",
    "vulcanauthy.com",
    "vulcancaptcha.xyz",
    "vulcansauths.xyz",
    "vulcansbot.com",
    "vulcansupport.xyz",
    "vulcanverify.com",
    "web3-dexapp.online",
    "xn--rbitrum-owa.com",
    "xrpupdate.org",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupe, add fake ledger
remove duplicate `arbitrurn.io`
add `hhuuop.com`

**Review by dubstard — COMMENTED** [review]
block `aragon.cab`
fake scam
image

**Review by dubstard — COMMENTED** [review]
block live-metemask.com
h/t Milan

**Review by dubstard — COMMENTED** [review]
Remove FP  `uniswaption.com` https://twitter.com/ChanceofXYZ/status/1457814825619243009
add `defisyncprotocols.com`
image

**Review by dubstard — COMMENTED** [review]
block `captchaverification.live`
image

**Review by dubstard — COMMENTED** [review]
remove weird sites
```
balancerprice.org
balancerprice.com
```
image
no idea what are those
don't like them one bit
```
0xprice.org
acalaprice.com
alchemixusdprice.com
alchemixusdprice.org
alusdprice.org
ampprice.org
ankrprice.org
apenftprice.org
apeprice.org
arrrprice.com
arweaveprice.org
astarprice.org
astrprice.com
astrprice.org
atomprice.org
audioprice.org
audiusprice.com
audiusprice.org
balancerprice.org
balprice.com
balprice.org
basicattentionprice.org
batprice.com
batprice.org
bchprice.org
bitkubcoinprice.com
bitkubcoinprice.org
bittorrentprice.com
bittorrentprice.org
bsvprice.com
bsvprice.org
bttprice.org
cakeprice.org
caspernetworkprice.org
cdaiprice.com
ceekprice.org
ceeksmartvrprice.org
celoprice.org
cethprice.com
cetprice.org
chainprice.org
chromiaprice.com
chromiaprice.org
chrprice.org
chzprice.org
civicprice.org
ckbprice.com
ckbprice.org
coinexprice.org
```
I don't have proof right now so will leave them alone and block via another PR.
image
image


add
```
    "chattheres234.com",
    "cjmigcoisolutionmigratee.xyz",
```
h/t ecarlesi
https://twitter.com/ecarlesi/status/1628634037303537664
https://twitter.com/ecarlesi/status/1628679598979383298

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
