### PR TITLE
[Scam Sniffer] add  goblinwilldoit.wtf,   goblintown.world,  boki-nft.live

### PR DESCRIPTION
**Pull request by lljxx1**
## Phishing Report

```json
[
  "goblinwilldoit.wtf",
  "goblintown.world",
  "boki-nft.live"
]
```

### Boki
- phishing link: [https://boki-nft.live](https://boki-nft.live)
- phishing domain: `boki-nft.live`
- official site: [http://boki.art](http://boki.art)

### goblintown.wtf
- phishing link: [https://goblintown.world](https://goblintown.world), [https://goblinwilldoit.wtf](https://goblinwilldoit.wtf)
- phishing domain: `goblintown.world`, `goblinwilldoit.wtf`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)

*****
> 
> image
> 
> 
> Report from the [Scam Sniffer](https://scamsniffer.io/?utm_source=pr-footer). 
> 
> Scam sniffer is a plugin build upon Mask Network which can help people against with the crypto scammers
> Let's fight against evil !
> 
> [Twitter](https://twitter.com/scamsniffer_), [Discord](https://discord.com/invite/q6pJMAbeH7), [GitHub](https://github.com/scamsniffer), [GitCoin](https://gitcoin.co/grants/6049/scam-sniffer), [WebSite](https://scamsniffer.io/?utm_source=pr-footer)

### CODE REVIEW

**Review by 409H — DISMISSED** [review]

**Comment by AlexHerman1** [comment]
@lljxx1  can you resolve the conflicts

**Comment by lljxx1** [comment]
@AlexHerman1 done

**Comment by lljxx1** [comment]
@AlexHerman1 updated

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
