### PR TITLE
Update hosts.txt

### PR DESCRIPTION
**Pull request by andriytyurnikov**
Scams from #1590, #1592

### CODE REVIEW

**Comment by rstormsf** [comment]
poa network is not a scam. 
please elaborate

**Comment by andriytyurnikov** [comment]
@rstormsf , what is tokensale contract address?

**Comment by rstormsf** [comment]
Presale was closed on November 17, 2017
https://etherscan.io/address/0xc8fe4a2d14cb9027ef955d15e8bf811a6db0bf74#readContract
there is no any other presale
It was finished in 56 seconds

**Comment by andriytyurnikov** [comment]
@rstormsf , seriously, you've collected 15 ETH, and want to sell $100 000 000 USD of tokens?

**Comment by rstormsf** [comment]
where do read that information from? 
@andriytyurnikov

**Comment by andriytyurnikov** [comment]
@rstormsf from blockchain, Solidity Guru like you should know such things

**Comment by rstormsf** [comment]
@andriytyurnikov I understand  POA network pretty well, yes and what you are doing is misinforming people just by looking at POA20 bridge contract without understand what the  bridge is and what POA is and that it's completely separate chain that created interoperability protocol.

**Comment by andriytyurnikov** [comment]
@rstormsf so how you explain 15 ETH tokensale, which mooned to 100 MUSD?

**Comment by rstormsf** [comment]
@andriytyurnikov where do u see 15 eth tokensale?

**Comment by andriytyurnikov** [comment]
@rstormsf , tokensale transaction history, you genius, this is a blockchain, you know

**Comment by rstormsf** [comment]
@andriytyurnikov yeah show us, genius.
You can't prove anything

**Comment by andriytyurnikov** [comment]
ERC-20 is created ... 6 months after ICO?

**Comment by rstormsf** [comment]
POA.network is sidechain started without ERC-20.
Learn what POA.network is

**Pull request closed without merging**
