### PR TITLE
Add WalletConnect to the MetaMask fuzzylist.

### PR DESCRIPTION
**Pull request by jacobc-eth**
Fake WalletConnect sites have become the dominant phishing vector. This PR blocks thousands of phishing scams by adding WalletConnect to the MetaMask fuzzy list.

### CODE REVIEW

**Comment by ethphishingmaintainer1000** [comment]
@danfinlay I'm thinking it could be best if all additions to the `fuzzylist` go through you. Could you approve and merge this PR if you are on board? 🙏

**Comment by devenblake** [comment]
I'm not a big fan of adding anything to the fuzzylist - from my perspective, it'll just add to the amount of issues that stream into here. However I do see a lot of sites in the denylist that are phishing for `walletconnect.com` users that fuzzylisting would have automatically blocked.

**Comment by vaska2727** [comment]
თუ შეგიძლით მიტხარით ისეთი რეალური საიტი სადაც კრიპტოს გამომუშავებას შევძლებ უსასყიდლოდ?

**Comment by AlexHerman1** [comment]
i think well close this for now, the future of the fuzzylist is a question mark and we can always revisit this at a later date.

**Pull request closed without merging**
