### PR TITLE
Block 77 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
🛑Not the MetaMask you need
```
    "metamask.verifytoken.in",
    "extension-metamask.com",
    "extension-metamask.com.budget.co.tz",
    "extension-metamask.com.ozti.co.tz",
    "fixmetamask.org",
    "kmetamaskverification.duckdns.org",
    "metamask-7cas.onrender.com",
    "metamask-airdrop.fun",
    "metamask-airdrop.pw",
    "metamask-airdrop.xyz",
    "metamask-securityupdate.com",
    "metamask.filmshd.top",
    "metamask.grandinvest.top",
    "metamask.io.22782-5069.s1.webspace.re",
    "metamask.kz",
    "metamask.oxuin.us",
    "metamask78.com",
    "metamaskauthentication.in",
    "metamaskkverify.duckdns.org",
    "metamasklogin.oxuin.us",
    "metamaskwallet.duckdns.org",
    "nmetamaskverification.duckdns.org",
    "nnewmetamaskverify.duckdns.org",
    "portfolio-metamask-service.com",
    "setup-metamask.net",
    "setup-metamask.org",
    "verificationformetamask.duckdns.org",
    "verificationformetamaskkk.duckdns.org",
    "vmetamaskverification.duckdns.org",
    "walletverifymetamask.duckdns.org",
    "wmetamaskverification.duckdns.org",
    "mmlucky.site",
    "wgdspfkse.one",
    "clnrone-extension-fdgfkebogiimcoedliclksmjklklkaju.cfd",
    "metamsak.net",
    "xiaohuli2016.top",
```

🛑Not the 1inch you need
```
    "ad-1inch.io",
```

🛑Not the Adidas you need
```
    "just-adidas.com",
```

🛑Not the Arbitrum you need
```
    "monday-arbitrum.com"
```

🛑Not the Tesla you need
```
    "teslapromo-2023.com",`
```

🛑Not the Beethoven-X you need (☣scam spread via Google Ads)
```
    "beethovenx-fi.net",
```
image

🛑Not the Uniswap you need
```
    "app-uniswap-connect.com",
    "casinouniswap.com",
    "uniswap-v3-positions.metabench.io",
    "uniswap-v3-positions.mintingsmart.io",
    "uniswap.ae.org",
    "uniswap.boston",
    "uniswap.care",
    "uniswap.geek.nz",
    "uniswap.gen.nz",
    "uniswap.irish",
    "uniswap.mex.com",
    "uniswap.net.nz",
    "uniswap.ryukyu",
    "uniswap.vg",
    "uniswapcut.com",
    "uniswapinf.com",
    "uniswapinterface.net",
    "uniswaplending.xyz",
    "unlswaps.online",

```

🛑Not the PancakeSwap you need
```
    "pancakeswaip.com",
    "pancakeswap.finance.bridge.atlasgis.rs",
    "pancakeswap.finance.swap.oni0.sbs",
    "pancakeswap.io-walletopti.com",
    "pancakeswapfinance.website",
    "pancakeswaup.com",
```

🛑Not the Balancer Finance you need
```
    "balancerfi.store",
```

🛑Not the Exodus Wallet you need
```
    "wallet.exodus.com.wheelbalancer.shop",
```

🛑Not the Trust Wallet you need
```
    "marketingsgerichtheidscontrole.com",
```

🛑Not the XRP you need
```
"xrpwonthelawsuit.com",
```
---------------------------------------------

🛑All
```
    "app-uniswap-connect.com",
    "ad-1inch.io",
    "balancerfi.store",
    "beethovenx-fi.net",
    "casinouniswap.com",
    "clnrone-extension-fdgfkebogiimcoedliclksmjklklkaju.cfd",
    "extension-metamask.com",
    "extension-metamask.com.budget.co.tz",
    "extension-metamask.com.ozti.co.tz",
    "fixmetamask.org",
    "grandinvest.top",
    "io-walletopti.com",
    "just-adidas.com",
    "kmetamaskverification.duckdns.org",
    "marketingsgerichtheidscontrole.com",
    "metamask-7cas.onrender.com",
    "metamask-airdrop.fun",
    "metamask-airdrop.pw",
    "metamask-airdrop.xyz",
    "metamask-securityupdate.com",
    "metamask.filmshd.top",
    "metamask.grandinvest.top",
    "metamask.io.22782-5069.s1.webspace.re",
    "metamask.kz",
    "metamask.oxuin.us",
    "metamask.verifytoken.in",
    "metamask78.com",
    "metamaskauthentication.in",
    "metamaskkverify.duckdns.org",
    "metamasklogin.oxuin.us",
    "metamaskwallet.duckdns.org",
    "metamsak.net",
    "mmlucky.site",
    "nmetamaskverification.duckdns.org",
    "nnewmetamaskverify.duckdns.org",
    "monday-arbitrum.com",
    "pancakeswaip.com",
    "pancakeswap.finance.bridge.atlasgis.rs",
    "pancakeswap.finance.swap.oni0.sbs",
    "pancakeswap.io-walletopti.com",
    "pancakeswapfinance.website",
    "pancakeswaup.com",
    "portfolio-metamask-service.com",
    "setup-metamask.net",
    "setup-metamask.org",
    "teslapromo-2023.com",
    "uniswap-v3-positions.metabench.io",
    "uniswap-v3-positions.mintingsmart.io",
    "uniswap.ae.org",
    "uniswap.boston",
    "uniswap.care",
    "uniswap.geek.nz",
    "uniswap.gen.nz",
    "uniswap.irish",
    "uniswap.mex.com",
    "uniswap.net.nz",
    "uniswap.ryukyu",
    "uniswap.vg",
    "uniswapcut.com",
    "uniswapinf.com",
    "uniswapinterface.net",
    "uniswaplending.xyz",
    "unlswaps.online",
    "verificationformetamask.duckdns.org",
    "verificationformetamaskkk.duckdns.org",
    "vmetamaskverification.duckdns.org",
    "wallet.exodus.com.wheelbalancer.shop",
    "walletverifymetamask.duckdns.org",
    "wgdspfkse.one",
    "withdrawal.confirminfo-coinbase.com",
    "withdrawal.reconfirminfo-coinbase.com",
    "wmetamaskverification.duckdns.org",
    "xiaohuli2016.top",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
-`uniswap123.com` FP (just a statistics site, not phishing)
+`sync-protocol.net`

**Review by dubstard — COMMENTED** [review]
block
```
    "mmlucky.site",
    "wgdspfkse.one",
    "clnrone-extension-fdgfkebogiimcoedliclksmjklklkaju.cfd",
    "metamsak.net",
    "xiaohuli2016.top",
```

**Review by dubstard — COMMENTED** [review]
Block 
```
    "mmlucky.site",
    "wgdspfkse.one",
    "clnrone-extension-fdgfkebogiimcoedliclksmjklklkaju.cfd",
    "metamsak.net",
    "xiaohuli2016.top",
```

**Review by dubstard — COMMENTED** [review]
block "marketingsgerichtheidscontrole.com",

**Review by dubstard — COMMENTED** [review]
block `"teslapromo-2023.com",`

**Review by dubstard — COMMENTED** [review]
block ```"xrpwonthelawsuit.com",```

**Review by dubstard — COMMENTED** [review]
block
```
    "just-adidas.com",
    "monday-arbitrum.com",
    "beethovenx-fi.net",
```

**Review by dubstard — COMMENTED** [review]
block `"cooienswappv2.art"` and force CI recheck

**Comment by dubstard** [comment]
roll eyes.gif
image

**Review by dubstard — COMMENTED** [review]
block `"metamask77.com",`

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
