### PR TITLE
Add 215 Domains to blocklist (fixed)

### PR DESCRIPTION
**Pull request by BlockMageSec**
This should DEFINITELY work lol. Sorry for the mess before.

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by CoinHunter314159** [comment]
Hello, I saw you added our domain into this PR, may I know what is the reason about it? Our domain is garbi.io. It is running well and no issues, all sources are verified and open on the Github.

Thank you so much.

**Comment by BlockMageSec** [comment]
> Hello, I saw you added our domain into this PR, may I know what is the reason about it? Our domain is garbi.io. It is running well and no issues, all sources are verified and open on the Github.
> 
> Thank you so much.

Hi, I apologize - this was erroneous on our behalf. I am working to resolve the issue now.

**Comment by CoinHunter314159** [comment]
> > Hello, I saw you added our domain into this PR, may I know what is the reason about it? Our domain is garbi.io. It is running well and no issues, all sources are verified and open on the Github.
> > Thank you so much.
> 
> Hi, I apologize - this was erroneous on our behalf. I am working to resolve the issue now.

Thank you so much for your helps.

**Pull request merged**
