### PR TITLE
Immediate fix to address erroroneous domains in PR

### PR DESCRIPTION
**Pull request by BlockMageSec**
This pull request undoes our previous changes, but keeps any other modifications made by other contributors. We are investigating which domains were mistakenly flagged and how many were affected. Meanwhile, we are being careful by resubmitting a list only of the domains we have confirmed manually. We will resubmit any others once we establish their validity to avoid conflicts with legitimate sites. We acknowledge that many of the removals here are clearly "suspicious," but this is a temporary measure taken with an excess of caution.

### CODE REVIEW

**Review by samczsun — DISMISSED** [review]

**Comment by CoinHunter314159** [comment]
This PR is linked with my issue: https://github.com/MetaMask/eth-phishing-detect/issues/11780 . Can anyone in the team help merge it.

**Comment by BlockMageSec** [comment]
We've updated this PR after verifying each domain listed did in fact meet our current criteria.

**Review by AlexHerman1 — APPROVED** [review]
ty for updating.

**Comment by CoinHunter314159** [comment]
Thank you all for your helps.

**Pull request merged**
