### PR TITLE
Add sites to blocklist

### PR DESCRIPTION
**Pull request by ShenWe0x**
fake remix ethereum websites

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@ShenWe0x  i need an explanation regarding previous accusations against a site before i can merge this.

**Comment by ShenWe0x** [comment]
@AlexHerman1 smartcontractshacking.com if that's what you're talking about, I've already removed it from the block list.

I thought they had a connection with RealJohnnyTime because they made fake videos on YouTube such as "mevbot", "uniswap earn $1000" and used RealJohnnyTime's face in the videos, but later I realized that they created this by cutting certain parts of their videos.

After reviewing the videos on RealJohnnyTime's official YouTube account, I realized there was an error. There is no existing block on the domain, the problem has been resolved.

**Comment by AlexHerman1** [comment]
@ShenWe0x  thanks for getting back to me. yes I was referring to that incident.

**Comment by AlexHerman1** [comment]
@ShenWe0x  can you please apologize to johnny and the students in the other issue thread?

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
