### PR TITLE
Normalize ipfs gateway links to CIDs

### PR DESCRIPTION
**Pull request by umar-ahmed**
- Update `clean:blocklist` script to normalize and extract CIDs from IPFS subdomain gateway links
- Run script to clean up existing config and remove some duplicates as a result
- Add a test case to cover the IPFS normalization codepath

### CODE REVIEW

**Comment by mindofmar** [comment]
Why do we want to only store the IPFS CIDs instead of the full URL? Will this break existing functionality?

**Comment by mindofmar** [comment]
@umar-ahmed ah I see. So the goal is to be able to block `asdf` as an IPFS CID regardless of whether a user navigates to it from `ipfs.io/ipfs/asdf` or `asdf.ipfs.dweb.link`?

@409H can you confirm that the Phishing Controller now supports just CID as input to block these as intended above?

**Comment by umar-ahmed** [comment]
> @umar-ahmed ah I see. So the goal is to be able to block `asdf` as an IPFS CID regardless of whether a user navigates to it from `ipfs.io/ipfs/asdf` or `asdf.ipfs.dweb.link`?

Yup 👍 

Those should theoretically be the same content, just available at different gateways, so I think it makes most sense that EPD and PhishingController treat them as such for better coverage

**Review by 409H — APPROVED** [review]
lgtm

**Comment by 409H** [comment]
@mindofmar yes looks like it was merged in https://github.com/MetaMask/core/blob/main/packages/phishing-controller/src/PhishingDetector.ts#L119

**Review by 409H — CHANGES_REQUESTED** [review]
**We will wait to merge until rollout complete**

**Comment by umar-ahmed** [comment]
> Hey @umar-ahmed would you mind fixing the merge conflict? We are now ready to deploy this.

Yup, I can fix those up

**Comment by umar-ahmed** [comment]
@mindofmar I've rebased this PR on latest `main` branch. I decided to remove the changes to `config.json` from running `yarn clean:blocklist` to avoid the risk of future conflicts

Once this is merged in, I can create a separate PR to clean up the config.json file

**Review by 409H — APPROVED** [review]

**Review by AugmentedMode — APPROVED** [review]
lgtm

**Pull request merged**
