### PR TITLE
Add sites to blocklist [ 10 ]

### PR DESCRIPTION
**Pull request by ShenWe0x**
https://github.com/MetaMask/eth-phishing-detect/pull/14929

 @AlexHerman1 

I made a mistake while updating and the existing PR was deleted so I had to create a new one.

I wrote in detail the results of the necessary investigations on the subject,  "rewards.toncrypto.net" was removed from the banned sites and replaced with the main domain, "toncrypto.net"

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by PrivateMiner** [comment]
@ShenWe0x 

I hope this message finds you well. I recently came across a site and attempted to share my thoughts about it in the group. However, I got banned without any explanation.

I'm reaching out to kindly request your assistance in reviewing the website. I've taken a look at it myself and would appreciate your insights. If there are any guidelines or specific ways I should approach sharing such information, please let me know.

Looking forward to your guidance, and thank you in advance for your help!

**Comment by PrivateMiner** [comment]
The reason I told you is that I wanted to get help from you because you have reviewed similar sites and are familiar with the subject.

**Comment by ShenWe0x** [comment]
@PrivateMiner Of course, if it's something I can help with, why not. What is the domain address?

Is what you found on the website some kind of phishing method?

**Comment by PrivateMiner** [comment]
@ShenWe0x

Suspicion: TornadoCash Dao was recently hacked and the attacker took control of Dao administration. According to my research, tornado.ws was an active domain name at the time and caused serious concerns. Currently the official domain appears to be under the control of the attacker, as the attacker has all the authority and can manipulate any vote as they wish. Unfortunately nothing was done to prevent this. While continuing my research with these doubts, I came across a file that was not in the original GitHub repository but was examining the code specific to the tornado.ws site.

https://tornado.ws/cdn-cgi/challenge-platform/scripts/jsd/main.js
https://tornado.ws/cdn-cgi/challenge-platform/h/b/scripts/jsd/c8377512/main.js
https://tornado.ws/cdn-cgi/challenge-platform/h/b/jsd/r/845f93698f93c268

Asking ChatGPT about this file and related files further strengthened my suspicions. I would be very happy if you review these.

**Comment by ShenWe0x** [comment]
@PrivateMiner Coinmarketcap and Coingecko are considered legal on these sites; it is nearly impossible to be added without proof. However, as you mentioned, the DAO was hacked a few months ago, and proving ownership might not be difficult to update websites. What caught my attention is the official statement on the Telegram channel, stating, "Telegram control has been transferred from xGozzy, and the website created by him is fake and fraudulent." If xGozzy is a scammer, why would he transfer Telegram control? It could be possible that xGozzy is involved in the management behind the hack, and by transferring control, he is hiding behind the recognition.

In any case, I'm starting to suspect something suspicious. If xGozzy is in control of tornado.ws, it means calling it a scam. If he is not in control, it implies that the hacker who hacked TornadoCash DAO is in control, and both scenarios are problematic.

Has @alexherman1's website been examined? It has been mentioned a few times in pull requests, but I haven't seen any reviews. If you want it to be checked, I can verify it.

**Comment by PrivateMiner** [comment]
Yes, you are right; the situation is very complicated. In the group, they ban you when you ask questions about these topics.

@deshvin I have seen your reviews on tornadocash, and I wanted to add that since you are familiar with the subject. I would like you to get involved in the matter as well; your information is important to me.

**Comment by ShenWe0x** [comment]
I've examined the provided JavaScript file at 
https://tornado.ws/cdn-cgi/challenge-platform/h/b/scripts/jsd/c8377512/main.js
Normally, such scripts are used by Cloudflare for security purposes, but in this case, the code has been customized, and certain sections are encrypted. Codes of this nature are often designed for malicious activities, such as installing malware or stealing user information through the browser. The content of such codes is typically encrypted or obfuscated to prevent clear understanding.

Within the code, there is an operation using XMLHttpRequest to send specific data to the server. However, I cannot see what data is being posted due to the encrypted section. Considering the successful manipulation of Tornadocash Management, I continued my investigation, finding a lot of suspicious data. When compared with the resources in the official Tornadocash GitHub repository, the tornado.ws files have entirely different function names, and the entire code structure is distinct.

To @AlexHerman1 and @deshvin  Given that the hacker who compromised Tornadocash management appears to be highly knowledgeable and professional, and considering the significant differences in code structure and function names compared to the official Tornadocash GitHub resources, what steps should we take regarding the domain?

**Comment by PrivateMiner** [comment]
I appreciate your evaluation, and I knew I was right in my doubts about the website. Thank you for helping me. Now, what do I need to do?

**Comment by PrivateMiner** [comment]
I appreciate your evaluation, and I knew I was right in my doubts about the website. Thank you for helping me. Now, what do I need to do?

**Comment by PrivateMiner** [comment]
@deshvin I'm curious about your comments about the reviews.

**Pull request merged**
