### PR TITLE
[Scam Sniffer] add 'goblin-town.wtf, adidas-metaverse.io, doodlesdooplicate.com, theoddities.xyz, merch-azuki.com, otheraside.com, otherside.ape-coin.cloud, apecoins-airdrop.com, othraside.xyz, metaverse-adidas.io' to black list

### PR DESCRIPTION
**Pull request by lljxx1**
Hi, this is fun from the [scamsniffer](https://scamsniffer.io/),
Recently we have discovered a lot of scam tweets on twitter, these sites need to be block, details here:

### adidas Originals Into the Metaverse
- phishing link: [https://metaverse-adidas.io](https://metaverse-adidas.io)
- phishing domain: `metaverse-adidas.io`
- official site: [https://www.adidas.com/into_the_metaverse](https://www.adidas.com/into_the_metaverse)
- phishing tweet: https://twitter.com/adidasoriginals/status/1528260015185879042

### Otherdeed for Otherside
- phishing link: [http://othraside.xyz/otherdeed](http://othraside.xyz/otherdeed)
- phishing domain: `othraside.xyz`
- official site: [https://otherside.xyz](https://otherside.xyz)
- phishing tweet: https://twitter.com/adidasoriginals/status/:1528347601849880576

### ApeCoin
- phishing link: [http://apecoins-airdrop.com](http://apecoins-airdrop.com)
- phishing domain: `apecoins-airdrop.com`
- official site: [https://apecoin.com/](https://apecoin.com/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1521233566943830016

### Otherdeed for Otherside
- phishing link: [http://otheraside.com/koda](http://otheraside.com/koda)
- phishing domain: `otheraside.com`
- official site: [https://otherside.xyz](https://otherside.xyz)
- phishing tweet: https://twitter.com/adidasoriginals/status/1523559264836792320

### Azuki
- phishing link: [http://merch-azuki.com](http://merch-azuki.com)
- phishing domain: `merch-azuki.com`
- official site: [http://www.azuki.com](http://www.azuki.com)
- phishing tweet: https://twitter.com/adidasoriginals/status/1528479188537294848

### Moonbirds
- phishing link: [http://theoddities.xyz](http://theoddities.xyz)
- phishing domain: `theoddities.xyz`
- official site: [https://moonbirds.xyz](https://moonbirds.xyz)
- phishing tweet: https://twitter.com/adidasoriginals/status/1528571653621284864

### Doodles
- phishing link: [https://doodlesdooplicate.com](https://doodlesdooplicate.com)
- phishing domain: `doodlesdooplicate.com`
- official site: [https://doodles.app](https://doodles.app)
- phishing tweet: https://twitter.com/adidasoriginals/status/1528887437879132161

### adidas Originals Into the Metaverse
- phishing link: [https://adidas-metaverse.io](https://adidas-metaverse.io)
- phishing domain: `adidas-metaverse.io`
- official site: [https://www.adidas.com/into_the_metaverse](https://www.adidas.com/into_the_metaverse)
- phishing tweet: https://twitter.com/adidasoriginals/status/:1528523670762795012

### goblintown.wtf
- phishing link: [https://goblin-town.wtf](https://goblin-town.wtf)
- phishing domain: `goblin-town.wtf`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1530027124647919618

*****
> 
> image
> 
> 
> Report from the [Scam Sniffer](https://scamsniffer.io/?utm_source=pr-footer). 
> 
> Scam sniffer is a plugin build upon Mask Network which can help people against with the crypto scammers
> Let's fight against evil !
> 
> [Twitter](https://twitter.com/scamsniffer_), [Discord](https://discord.com/invite/q6pJMAbeH7), [GitHub](https://github.com/scamsniffer), [GitCoin](https://gitcoin.co/grants/6049/scam-sniffer), [WebSite](https://scamsniffer.io/?utm_source=pr-footer)

### CODE REVIEW

**Comment by lljxx1** [comment]
Also, is there a faster way to report phishing domains to metamask?

**Comment by lljxx1** [comment]
`https://cdn.jsdelivr.net/gh/MetaMask/eth-phishing-detect@master/src/config.json`
`jsdelivr` has a reponse header `cache-control: public, max-age=604800, s-maxage=43200`,
which means this data  will cache on user's browser for 7 days

**Comment by AlexHerman1** [comment]
@lljxx1 can you update branch

**Comment by lljxx1** [comment]
@AlexHerman1 what's branch should I switch?

**Comment by lljxx1** [comment]
> @lljxx1 can you update branch

updated

**Comment by lljxx1** [comment]
## Phishing Report

```json
[
  "gobllintown.wtf",
  "boki.gift",
  "adidas.claims",
  "gobllntown.com",
  "goblimtown.com",
  "goblintown.livemint.live"
]
```

### goblintown.wtf
- phishing link: [https://goblintown.livemint.live](https://goblintown.livemint.live)
- phishing domain: `livemint.live`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1530211068236427265

### goblintown.wtf
- phishing link: [https://goblimtown.com](https://goblimtown.com)
- phishing domain: `goblimtown.com`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1530909475019931651

### goblintown.wtf
- phishing link: [https://gobllntown.com](https://gobllntown.com)
- phishing domain: `gobllntown.com`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1531161142386728960

### adidas Originals Into the Metaverse
- phishing link: [https://adidas.claims](https://adidas.claims)
- phishing domain: `adidas.claims`
- official site: [https://www.adidas.com/into_the_metaverse](https://www.adidas.com/into_the_metaverse)
- phishing tweet: https://twitter.com/adidasoriginals/status/1529587900886695938

### Boki
- phishing link: [https://boki.gift](https://boki.gift)
- phishing domain: `boki.gift`
- official site: [http://boki.art](http://boki.art)
- phishing tweet: https://twitter.com/adidasoriginals/status/1530630284458303489

### goblintown.wtf
- phishing link: [https://gobllintown.wtf](https://gobllintown.wtf)
- phishing domain: `gobllintown.wtf`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1531028594197241856

**Review by AlexHerman1 — APPROVED** [review]
LGTM. please add the new sites to the top of the blacklist next time @lljxx1

**Comment by lljxx1** [comment]
> LGTM. please add the new sites to the top of the blacklist next time @lljxx1
@AlexHerman1 👌

**Comment by lljxx1** [comment]
@AlexHerman1 BTW, I am now trying to automate the collection of attacker addresses from phishing websites. Is there any way to block these addresses?

**Pull request merged**
