### PR TITLE
Block 156 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
image
image
image
image
image
image

```
    "1inch.press",
    "2fametamask.ddns.net",
    "airdrop-arbitrum.info",
    "americankryptosbank.com",
    "coindigital-mainnet.com",
    "coinport-limited.com",
    "dappsmobilesynchro.com",
    "ethereum-eth23.com",
    "ethereum-link.com",
    "ethereum-miners.com",
    "ethereumhub22.me",
    "ethereumhub33.net",
    "metamask-binance.com",
    "metamask.fasilk.com",
    "multiprotrades.com",
    "myetherwallet.tw",
    "nethfx.com",
    "stablemartfix.com",
    "stactraders.com",
    "starknet-token.sale",
    "uniswap-x2.com",
    "uniswaplab.shop",
    "uniswaps.biz",
    "uniswaps.xyz",
    "uniswapse.org",
    "v3-metamask.io",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Block fake "event", "airdrop" and "giveaway" scams
image

Based on IoC `3A06dfbf67dba5fe85c27b20cf7e600e7f15749b2154ad2ca200948ce3f3cd2ee5`

https://urlscan.io/search/#hash%3A06dfbf67dba5fe85c27b20cf7e600e7f15749b2154ad2ca200948ce3f3cd2ee5

```

    "2022xrp.net",
    "21-xrp.net",
    "21xrp.net",
    "22-avax.com",
    "account.coinbase-eth.net",
    "account.coinbase-giveaway.net",
    "accounts.coinbase-eth.net",
    "bch-bonus.com",
    "bch-bonus.org",
    "bch-event.com",
    "bchfound.com",
    "bonusxrp.net",
    "buterin2021.ceo",
    "buterin2021.org",
    "buterin2021.to",
    "cardano-prize.com",
    "ceo-ethereum.org",
    "claimxrp22.com",
    "coin-ether.com",
    "coin-ether.net",
    "coinbase-2x.com",
    "coinbase-bonus.com",
    "coinbase-eth.live",
    "coinbase-eth.us",
    "coinbase-ether.org",
    "coinbase-foundation.com",
    "coinbase-give.cash",
    "coinbase-giveaway.live",
    "coinbase-invest.us",
    "coinbase-twitter.em69420.com",
    "crypto-pump.org",
    "cryptoevents2021.com",
    "cryptorise.cc",
    "currency-event.com",
    "dogecoin-event.pro",
    "dogecoin.reisen",
    "dropether.org",
    "elon44.com",
    "eth-event.org",
    "eth-event.pro",
    "eth-event20.com",
    "eth-events.cc",
    "eth-future.net",
    "eth21.live",
    "eth2x.site",
    "ethdrops.info",
    "ether-coin.org",
    "ether-coins.info",
    "ether-drops.info",
    "ether-event.info",
    "ether-event.pro",
    "ether-funds.info",
    "ether-give.info",
    "ether.tokyo",
    "ether21.info",
    "ethereum2023.us",
    "ethereum2022.us",
    "ethereumevent21.com",
    "etherprize.us",
    "ethevent-22.com",
    "ethevent-23.com",
    "ethevent-21.com",
    "ethevents.info",
    "ethprize.live",
    "ethx2.cash",
    "event-currency.com",
    "events-cardano.org",
    "events-eth.com",
    "exodus-eth.com",
    "get-eth2021.com",
    "get-x2-eth.com",
    "get-x2-eth.net",
    "getsolana21.com",
    "giftxrp.us",
    "give-away-eth.com",
    "gives-ripple.net",
    "japanxrp.net",
    "linuxbonus.org",
    "live-xrp.us",
    "news-xrp.com",
    "ripple-22.net",
    "ripple-21.net",
    "ripple-gives.org",
    "ripple-info.net",
    "ripple-io.org",
    "ripple-promo.live",
    "rippledep.net",
    "ripplejp.net",
    "ripplemore.org",
    "ripplex2.com",
    "ripplex2.org",
    "risexrp.net",
    "secure.buterin2021.org",
    "secure.coinbase-giveaway.net",
    "service.coinbase-eth.net",
    "shib-airdrop.com",
    "shibinu.info",
    "solana2021.live",
    "solana21.org",
    "spacex2023.com",
    "spacex2022.com",
    "spacex2021.com",
    "theta2023.com",
    "theta2022.com",
    "twicexrp.com",
    "uniswap2023.com",
    "uniswap2022.com",
    "uniswap2021.com",
    "winklevoss.events",
    "winklevoss2023.org",
    "winklevoss2022.org",
    "x2-buterin.org",
    "xrp-back.com",
    "xrp-events.com",
    "xrp-new.com",
    "xrp-promo.org",
    "xrp-ripple21.com",
    "xrp-swell.net",
    "xrp-up.net",
    "xrp-x2.info",
    "xrpbonus.us",
    "xrpevent2023.com",
    "xrpevent2022.com",
    "xrpget21.com",
    "xrpmore.org",
    "xrppromo.net",
    "xrprise.org",
    "xrptwitter.com",
    "xrpus.org",
    "xrpx2.pro",
```

**Comment by dubstard** [comment]
When I added the PR there were no duplicates.

Upon merge with master 3 days later a "duplicate" appears, even though i have added it here first 3 days ago.
I have also alerted the affected entity.
image

**Review by dubstard — COMMENTED** [review]
remove obsolete entry
`airdrop-arbitrum.info`

**Comment by dubstard** [comment]
CI is now happy

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
