### PR TITLE
Remove galxe.com from blocklist

### PR DESCRIPTION
**Pull request by deshvin**
Can be merged once the issue has been confirmed resolved. This will undo the temporary block from #13751

### CODE REVIEW

**Comment by deshvin** [comment]
DON'T MERGE THIS YET

**Comment by oyyblin** [comment]
Hi there :)

I'm with the Galxe team. Just wanted to bump this up. Would love to hear if there are any updates on the review process.

Thank you <3

**Comment by Stumble** [comment]
Hey @deshvin , Galxe.com's DNS records are now correctly pointing the records of Galxe's server. Can you merge this PR?
```
galxe.com.		60	IN	A	44.224.111.157
galxe.com.		60	IN	A	35.81.73.130
galxe.com.		60	IN	A	34.213.52.73
galxe.com.		60	IN	A	54.68.28.2
galxe.com.		60	IN	A	44.238.33.110
galxe.com.		60	IN	A	35.162.110.183
galxe.com.		60	IN	A	50.112.193.217
galxe.com.		60	IN	A	52.24.93.231
```

**Comment by deshvin** [comment]
Looking to get this resolved soon. I'm the author of the PR so I can't merge it myself.

**Comment by Stumble** [comment]
I will send out a separated PR and at you there! Thanks

**Comment by deshvin** [comment]
closing this PR, will handle in #13785

**Comment by dubstard** [comment]
@Stumble @oyyblin

You can sign up for a service that will SMS you / email you if DNS were to change.
image
image
There are others as well of cource, and you can also do an inhouse solution with a simple nslooup scripted.

Nice work by all BUT dynadot 🤦‍♂️🤦‍♀️

**Pull request closed without merging**
