### PR TITLE
Added Drivity.org on the whitelist

### LINKED ISSUE #8301: [Legitimate Site Blocked] drivity.org
https://drivity.org/

UNA Blockchain just bought this domain name for a new project on "Digital ID for automotive"

Please see the WHOIS (updated on Aug. 22) : https://who.is/whois/drivity.org

Contact: joseph@bedminster.fr

Best regards,
Joseph Bedminster
Blockchain Developer

### PR DESCRIPTION
**Pull request by josephbedminster**
Add Drivity.org portfolio to the whitelist
Close #8301

### CODE REVIEW

**Comment by vergaraed** [comment]
Hi MetaMask development team.  LGTM please.

**Comment by AlexHerman1** [comment]
@josephbedminster  thanks for the request, can you clarify what drivity.org is and provide more context?

**Comment by josephbedminster** [comment]
> @josephbedminster thanks for the request, can you clarify what drivity.org is and provide more context?

Hey, as described in #8301 : 
```https://drivity.org/

UNA Blockchain just bought this domain name for a new project on "Digital ID for automotive"

Please see the WHOIS (updated on Aug. 22) : https://who.is/whois/drivity.org

Contact: [joseph@bedminster.fr](mailto:joseph@bedminster.fr)

Best regards,
Joseph Bedminster
Blockchain Developer
```

UNA Blockchain is a registered company in the United States of America :

https://www.unablockchain.io/

We are launching a new brand "Drivity", for a Digital Identity project for Driving usage (automotive industry).
This will allow to launch our Proof-of-ownership tokens for our users.

Best regards,
Joseph Bedminster

**Review by AlexHerman1 — APPROVED** [review]
thanks.

**Pull request merged**
