### PR TITLE
Add phishing sites to blocklist

### PR DESCRIPTION
**Pull request by rohitmukerji1**

### CODE REVIEW

**Comment by 409H** [comment]
@rohitmukerji1 can we mark this as a non-draft now and merge?

**Comment by rohitmukerji1** [comment]
@409H yes!

**Comment by ktian94** [comment]
Just rebased it

**Comment by AlexHerman1** [comment]
@ktian94  mind fixing this when you get the chance?

**Comment by ktian94** [comment]
@AlexHerman1 should be fixed now

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
