### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Not the Compound you are looking for 

```
    "claimcompound.com",
```
IoCs:
```
Token Contract: 0x0795619e02716a81ac9ef6e55363d538da104e57
Token Name: $ ClaimCompound.com
Token Symbol: ClaimCompound.com
Token Decimals: 0
```

Not the AMM you are looking for - random webiste requests to interact with metamask, no description, no explanation why = 100% drainer scam.
```
    "ammearn.top",
    "ammearn.biz",
```

Not the MetaMask you are looking for 

```
    "verifymetamask.tk",
    "web-metamask.net",
```

Not the PancakeSwap you are looking for
   ```
 "nft-pancakeswap.finance",
    "pancakeswap-dapps.com",
    "pancakeswap-fre.com",
    "pancakeswap-live.site",
    "pancakeswap.belgianwaffle.site",
    "pancakeswap.sa.com",
    "pancakeswapa.org",
    "pancakeswapes.ltd",
    "pancakeswapfin.app",
    "pancakeswapis.click",
    "pancakeswaptrading.com",
    "pancakeswvaps.com",
    "wvvvvpancakeswap.top",
```

Not the UniSwap you are looking for

```
    "univ2rewards.com",
    "uniswaps.website",
```

Not the goblintown you are looking for
```
"goblins-town.com",
"goblin-town.org",
```

Not the moonbirds you are looking for
```
"moonbirds-nft.net",
```

All submitted in URL Scan with my tag `SpamReports`
```
  "message": "Submission successful",
  "uuid": "a6878d0b-a0dd-418d-bc85-b678d8075bb4",
  "result": "https://urlscan.io/result/a6878d0b-a0dd-418d-bc85-b678d8075bb4/",
  "url": "http://univ2rewards.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469  100   351  100   118   3156   1061 --:--:-- --:--:-- --:--:--  4342{
  "message": "Submission successful",
  "uuid": "fcf6738f-2242-4679-b6a1-b799b52352b3",
  "result": "https://urlscan.io/result/fcf6738f-2242-4679-b6a1-b799b52352b3/",
  "url": "http://claimcompound.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   457  100   345  100   112   1154    374 --:--:-- --:--:-- --:--:--  1543{
  "message": "Submission successful",
  "uuid": "580aca41-4abc-4e35-a13c-424cfce408d7",
  "result": "https://urlscan.io/result/580aca41-4abc-4e35-a13c-424cfce408d7/",
  "url": "http://ammearn.top",
  "country": "nl"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   457  100   345  100   112   1089    353 --:--:-- --:--:-- --:--:--  1469{
  "message": "Submission successful",
  "uuid": "eb5b0e93-601d-4197-86a8-70751523d2d5",
  "result": "https://urlscan.io/result/eb5b0e93-601d-4197-86a8-70751523d2d5/",
  "url": "http://ammearn.biz",
  "country": "nl"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   467  100   350  100   117   1271    425 --:--:-- --:--:-- --:--:--  1716{
  "message": "Submission successful",
  "uuid": "c06e1a40-7db3-4c87-ad08-ed3b37f7bf7e",
  "result": "https://urlscan.io/result/c06e1a40-7db3-4c87-ad08-ed3b37f7bf7e/",
  "url": "http://uniswaps.website",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469  100   351  100   118   1180    396 --:--:-- --:--:-- --:--:--  1622{
  "message": "Submission successful",
  "uuid": "53fcb98b-5e63-4396-abbf-5597dee0d3c4",
  "result": "https://urlscan.io/result/53fcb98b-5e63-4396-abbf-5597dee0d3c4/",
  "url": "http://verifymetamask.tk",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   467  100   350  100   117   1814    606 --:--:-- --:--:-- --:--:--  2457{
  "message": "Submission successful",
  "uuid": "397fc6bd-e8fc-4c76-a96a-c5ab53f34566",
  "result": "https://urlscan.io/result/397fc6bd-e8fc-4c76-a96a-c5ab53f34566/",
  "url": "http://web-metamask.net",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   481  100   357  100   124   1221    424 --:--:-- --:--:-- --:--:--  1652{
  "message": "Submission successful",
  "uuid": "4d46bf47-db06-40f3-a5fd-b522f4b1c4d5",
  "result": "https://urlscan.io/result/4d46bf47-db06-40f3-a5fd-b522f4b1c4d5/",
  "url": "http://nft-pancakeswap.finance",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   477  100   355  100   122    735    252 --:--:-- --:--:-- --:--:--   993{
  "message": "Submission successful",
  "uuid": "c948b50b-d472-4bd4-8278-a74e931918ac",
  "result": "https://urlscan.io/result/c948b50b-d472-4bd4-8278-a74e931918ac/",
  "url": "http://pancakeswap-dapps.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   473  100   353  100   120    562    191 --:--:-- --:--:-- --:--:--   756{
  "message": "Submission successful",
  "uuid": "c99918dd-28f9-459f-8a3e-830508ce60d3",
  "result": "https://urlscan.io/result/c99918dd-28f9-459f-8a3e-830508ce60d3/",
  "url": "http://pancakeswap-fre.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   339  100   217  100   122   2036   1145 --:--:-- --:--:-- --:--:--  3228{
  "message": "DNS Error - Could not resolve domain",
  "description": "The domain pancakeswap-live.site could not be resolved to a valid IPv4/IPv6 address. We won't try to load it in the browser.",
  "status": 400
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   495  100   364  100   131    391    140 --:--:-- --:--:-- --:--:--   532{
  "message": "Submission successful",
  "uuid": "ba40eff9-f3bb-4a15-901d-d7f6ea45d039",
  "result": "https://urlscan.io/result/ba40eff9-f3bb-4a15-901d-d7f6ea45d039/",
  "url": "http://pancakeswap.belgianwaffle.site",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   471  100   352  100   119    589    199 --:--:-- --:--:-- --:--:--   794{
  "message": "Submission successful",
  "uuid": "0f88f2ea-c025-450d-951f-09c8e0e270f1",
  "result": "https://urlscan.io/result/0f88f2ea-c025-450d-951f-09c8e0e270f1/",
  "url": "http://pancakeswap.sa.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   467  100   350  100   117   1896    633 --:--:-- --:--:-- --:--:--  2565{
  "message": "Submission successful",
  "uuid": "c136a019-95da-4990-977c-ec8722a8998f",
  "result": "https://urlscan.io/result/c136a019-95da-4990-977c-ec8722a8998f/",
  "url": "http://pancakeswapa.org",
  "country": "nl"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469  100   351  100   118    779    262 --:--:-- --:--:-- --:--:--  1049{
  "message": "Submission successful",
  "uuid": "d6f4a3af-9cfa-4872-b0ae-688d73378d57",
  "result": "https://urlscan.io/result/d6f4a3af-9cfa-4872-b0ae-688d73378d57/",
  "url": "http://pancakeswapes.ltd",
  "country": "nl"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   471  100   352  100   119    390    131 --:--:-- --:--:-- --:--:--   522{
  "message": "Submission successful",
  "uuid": "55cee5ec-0d30-4f63-89a9-93b71598880d",
  "result": "https://urlscan.io/result/55cee5ec-0d30-4f63-89a9-93b71598880d/",
  "url": "http://pancakeswapfin.app",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   473  100   353  100   120    798    271 --:--:-- --:--:-- --:--:--  1079{
  "message": "Submission successful",
  "uuid": "1668674c-b660-4966-9375-dffa3c0a39dc",
  "result": "https://urlscan.io/result/1668674c-b660-4966-9375-dffa3c0a39dc/",
  "url": "http://pancakeswapis.click",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   479  100   356  100   123   1427    493 --:--:-- --:--:-- --:--:--  1931{
  "message": "Submission successful",
  "uuid": "6f598bf2-818a-4137-b896-165a3447b00c",
  "result": "https://urlscan.io/result/6f598bf2-818a-4137-b896-165a3447b00c/",
  "url": "http://pancakeswaptrading.com",
  "country": "no"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469  100   351  100   118   2863    962 --:--:-- --:--:-- --:--:--  3908{
  "message": "Submission successful",
  "uuid": "a3f1f223-907b-4f53-9f3d-8ca0608e4782",
  "result": "https://urlscan.io/result/a3f1f223-907b-4f53-9f3d-8ca0608e4782/",
  "url": "http://pancakeswvaps.com",

}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   475  100   354  100   121   1226    419 --:--:-- --:--:-- --:--:--  1666{
  "message": "Submission successful",
  "uuid": "c14d783f-7aa3-40a0-8a0e-453b7265b12d",
  "result": "https://urlscan.io/result/c14d783f-7aa3-40a0-8a0e-453b7265b12d/",
  "url": "http://wvvvvpancakeswap.top",

```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate 🤦‍♂️
"web-metamask.net",

**Review by dubstard — COMMENTED** [review]
remove one more missed duplicate

**Review by dubstard — COMMENTED** [review]
Not the goblintown you are looking for
"goblins-town.com",
"goblin-town.org",

Not the moonbirds you are looking for
"moonbirds-nft.net",

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
