### PR TITLE
Block 125 scams (many used in the KYC email spam❗)

### PR DESCRIPTION
**Pull request by dubstard**
block em
no mercy
Block 123 scams (many used in the KYC email spam❗)

image

```
"1inch-in.com",    
    "1inch.media",
    "airdrop-elon.com",
    "airdrop-swap.com",
    "airdropclaim.xyz",
    "apps-metamask.up-nextt.com",
    "appuniswaps.com",
    "appuniswaps.icu",
    "appuniswaps.top",
    "associatemetamaskiosma.ddnss.eu",
    "authenticationmetamask.com",
    "authorization-coinbase.com",
    "balancer-fl.online",
    "balancer-shop.com",
    "balancer-singin.com",
    "balancerrfi.xyz",
    "becusecuredservice.duia.us",
    "binance-cryptocurrency-exchanges.forex-trader.site",
    "bulletimetamaskiotimes.ddnss.eu",
    "chrome-extension.duia.us",
    "chrome-extention.duia.us",
    "claim-uniswap.app",
    "claim-uniswap.buzz",
    "claim-uniswap.icu",
    "claim-uniswap.monster",
    "claim-uniswap.cf",
    "claim-uniswap.ga",
    "claim-uniswap.gq",
    "claim-uniswap.ml",
    "claim-uniswap.tk",
    "claimairdropscrypto.com",
    "coinbase-enverify.com",
    "deficlaimingairdropandrewards.online",
    "ethereum10000x.repl.co",
    "ethereum17.ru",
    "ethereumfund.io",
    "ethereumhub.live",
    "ethereumhub.top",
    "ethereumhub0.me",
    "ethereumhub1.me",
    "ethereumhub2.me",
    "ethereumhub3.me",
    "ethereumhub4.me",
    "ethereumhub5.me",
    "ethereumhub6.me",
    "ethereumhub7.me",
    "ethereumhub8.me",
    "ethereumhub9.me",
    "evalidate-login-info02.srvsecure.duia.us",
    "extension-metamask.duia.us",
    "kyc-metamask.duia.us",
    "kyc.auth-host.info",
    "kyc.bip-portal.info",
    "kyc.connection-auth-server.info",
    "connection-auth-server.info",
    "kyc.portal-auth.xyz",
    "portal-auth.xyz",
    "limitedaccount-secureapp.duia.us",
    "meta-extension-wallet.duia.us",
    "meta-extension.duia.us",
    "meta-help-extension.duia.us",
    "metamask-io.duia.us",
    "metamask-test.discoverfeed.info",
    "metamask.be1os.com",
    "metamask.linkpc.net",
    "metamask.romwe.in",
    "metamask.verifymeta.net",
    "metamask198.myds.me",
    "metamask2.io",
    "metamask3.io",
    "metamaskiosioassociate.ddnss.eu",
    "metamaskiotimesbulleti.ddnss.eu",
    "metamasknetwork.bip.sh",
    "metamasksoft.top",
    "metamaskverify.info",
    "my-ethereum-code.com",
    "myetherwallet-logi.com",
    "mysafebridge.info",
    "pancake-finance.exchange",
    "pancakeswap-cripto.com",
    "pancakeswap.finance.0x8aa.live",
    "pancakeswap.finance.changecake.in",
    "pancakeswap.fnanse.pw",
    "pancakeswapfinance.pancakeswape.com",
    "pancakeswapget.com",
    "pancakeswaps.xyz",
    "pancakeswopp.com",
    "portfolio-metamask-buy.com",
    "portfolio-metamask-service.org",
    "ru-metamask.site",
    "secret-metamask-demo.pages.dev",
    "secure02.duia.us",
    "secure04b-verify.duia.us",
    "secure07b-verify.duia.us",
    "secure09update.duia.us",
    "secure5-user3.duia.us",
    "secure68-admn2.duia.us",
    "secureclaims-ui-cdle.duia.us",
    "securedacrestore03.duia.us",
    "secureof25884136chase2.duia.us",
    "securepayment.duia.us",
    "servsecure5-user3.duia.us",
    "signincoinbase.com",
    "srvsecure.duia.us",
    "swap-connect-1inch.io",
    "uniswap-amm.org",
    "uniswap-goerli.vmeta3.com",
    "uniswap-pools.pages.dev",
    "uniswap.co.bz",
    "uniswap.gen.in",
    "uniswap.ind.in",
    "uniswap.koeln",
    "uniswap.nagoya",
    "uniswap.net.in",
    "uniswaper-axieinfinitystake.com",
    "uniswapstop.com",
    "us-access-mobile-secure.duia.us",
    "us-secure-access.duia.us",
    "us-secure-zone.duia.us",
    "user36632-metamask.servebeer.com",
    "user584633-metamask.ddns.net",
    "user9664-metamask.ddns.net",
    "user99656-metamask.ddns.net",
    "walletcoinbase.trade",
    "wallets-info-blockchaln.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupe and add `"cqnaecsf.clickfunnels.com",` on its place
image

**Review by dubstard — COMMENTED** [review]
remove dupes

**Review by dubstard — COMMENTED** [review]
block "defi-solutions.netlify.app",

**Review by dubstard — COMMENTED** [review]
block "bakeryswap-org-token-staking-g.web.app",

**Review by dubstard — COMMENTED** [review]
block 
```
www-openzea-app.xyz
```

**Comment by dubstard** [comment]
h/t malwrhunterteam for the netlify and web app
h/t ecarlesi for the fake opensea

**Review by dubstard — COMMENTED** [review]
remove FP `uniswap-pools.pages.dev`
some sort of pool data aggregation statistics site, does not ask to connect to wallet/ not phish or harmful

h/t dk

**Review by tayvano — APPROVED** [review]

**Review by tayvano — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
