### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
image

More of that fake MetaMask ETH merge campaign
https://twitter.com/dubstard/status/1572834975233220609
https://twitter.com/dubstard/status/1572839856623210496

image
image

add
```
"balancer-fi.org",
"coinbase.com-signauth.com",
"coinbase.com-wallet-sign-in.com",
"com-wallet-sign-in.com",
"coinbasepay.com",
"ethereum-official.net",
"krakenacessexchange.com",
"metamask-update-v2.com",
"metamask.exchange",
"metamask.io-defi-web5-dapps-and-nft.jajawprinters.com",
"metamask.io.merge.adyencapital.ltd",
"metamask.io.merge.aplanet.in",
"metamask.io.merge.arpixcertificado.com.br",
"metamask.io.merge.bcbhausa.com",
"metamask.io.merge.blocexpert.com",
"metamask.io.merge.blocmanager.com",
"metamask.io.merge.cifaglobal.com",
"metamask.io.merge.curatenie-bloc.ro",
"metamask.io.merge.dbs.web.id",
"metamask.io.merge.easportsgames.com.co",
"metamask.io.merge.gestational-age-calculator.site",
"metamask.io.merge.grupoidet.com",
"metamask.io.merge.iluminarenergia.com",
"metamask.io.merge.itsapp.cloud",
"metamask.io.merge.joyauxdumaroc.shop",
"metamask.io.merge.marabuspa.com",
"metamask.io.merge.microdam.co.ke",
"metamask.io.merge.outme.cc",
"metamask.io.merge.portalpnkendal.com",
"metamask.io.merge.portalpnkendal.gelisgede.com",
"metamask.io.merge.qantikaint.com",
"metamask.io.merge.qantikaint.site",
"metamask.io.merge.senglobalmarket.com",
"metamask.io.merge.tanger-spot.com",
"metamask.io.merge.websitedemo.website",
"metamask.io.merge.wrench.ae",
"metamask.live",
"metamask.lsnto.me",
"metamask.win",
"metamaskdao.io",
"metamaskioextension.com",
"metamaskl.com",
"metamasky.top",
"pancakeswap.mx",
"pancakeswapdapp.com",
"signinwithethereum.org",
"trustwallet-newupdate.estacionamientoaeropuertosantiago.cl",
"trustwallet-securitybreach.estacionamientoaeropuertosantiago.cl",
"uniswap-eth.com",
"uniswap.cf",
"uniswap.tk",
"uniswap.gq",
"uniswap.ml",
"uniswap.airdrops.gifts",
"uniswap.is",
"uniswapfukii.selfip.com",
"uniswaplog.org",
"uphold-wallett.ml",
"uphold-wallett.gq",
"uphold-wallett.ga",
"uphold-wallett.cf",
"uphold-wallett.tk",
"wallet-polygon-finances.info",
"wallet-uphold-oc.ml",
"wallet-uphold-oc.gq",
"wallet-uphold-oc.ga",
"wallet-uphold-oc.tk",
"web3ethereum.xyz",
"wowswap-exchange.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove dupe
```
		"metamask.io.merge.senglobalmarket.com",
```

Add back 🤦‍♂️
```
		"liveconnect.plugh.tech",
		"merge-meta.com",
```

**Review by dubstard — COMMENTED** [review]
Add 2 more scams
```
"dapp-solution.firebaseapp.com",
"dapp-solution.web.app",
```
h/t thwjanssen89

screenshots

https://user-images.githubusercontent.com/97024090/191683949-62457871-9bf9-41de-920b-0b1f9096bc2a.png
https://user-images.githubusercontent.com/97024090/191684874-4bef83c5-a474-4a85-a3cf-9d7bc3679cd9.png

**Review by dubstard — COMMENTED** [review]
add OpenSea scam
image

promoted via youtube
image

```
"cryptojoin.pro",
```

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks

**Pull request merged**
