### PR TITLE
ADDED - consensys-nft --> phosphor.xyz

### PR DESCRIPTION
**Pull request by waskow-consensys**
Hi Team,

Consensys has rebranded Consensys-nft to Phosphor! 

We are actively moving to our new domains!

Thanks!

### CODE REVIEW

**Comment by 409H** [comment]
Waiting on domain ownership confirmation before fixing

**Comment by waskow-consensys** [comment]
> Waiting on domain ownership confirmation before fixing

https://twitter.com/tryphosphor

**Comment by 409H** [comment]
> > Waiting on domain ownership confirmation before fixing
> 
> https://twitter.com/tryphosphor

That is not confirmation I am looking for.

**Comment by waskow-consensys** [comment]
> > > Waiting on domain ownership confirmation before fixing
> > 
> > 
> > https://twitter.com/tryphosphor
> 
> That is not confirmation I am looking for.

What do you need?

**Comment by 409H** [comment]
> > > > Waiting on domain ownership confirmation before fixing
> > > 
> > > 
> > > https://twitter.com/tryphosphor
> > 
> > 
> > That is not confirmation I am looking for.
> 
> What do you need?

Messaging you internally

**Comment by AlexHerman1** [comment]
creating a new PR for this

**Pull request closed without merging**
