### PR TITLE
Remove bnbminer.finance from blacklist

### PR DESCRIPTION
**Pull request by TheRealDeveloper-BNBMiner**
Successfully operating for nearly 3 years, bnbminer.finance is a legitimate site that has been erroneously blocked.

As the developer and maintainer of the official bnbminer.finance website, I can confirm that bnbminer.finance has never engaged, and will never engage, in harmful activities such as creating fake versions of MetaMask, stealing Secret Recovery Phrases or passwords, initiating malicious transactions resulting in asset theft, phishing, or any other form of malicious activity. As we explained when our website was flagged nearly two years ago, we also do not claim to actually mine BNB; our name is merely a concept, and our contract is fully explained on our website, in our litepaper, and other documents.

Like MetaMask and many other successful projects, we are consistent victims of impersonators and scammers targeting both us and our users. We continuously do everything within our power to warn and protect our current and potential users to the fullest. Our website and documents are filled with tips and warnings.

The warning message from MetaMask that is currently being displayed to our users is erroneous and unfairly damaging to our community. I have removed bnbminer.finance from the blacklist in this branch and hope you will strongly consider accepting its removal. Thank you!

### CODE REVIEW

**Comment by BNBminerFan** [comment]
100% here are the "Scam-Clones" that are causing the ACTUAL ISSUES not BNBminer.finance itself.
another fake
github

**Comment by Esoxo** [comment]
This is really a confusing situation. I feel like our community is doing all it can to handle this the right way. If notifying that the flag on our site is false is not the correct way to handle our current situation, then please notify us to the correct way to rectify the current problem. Appreciate

**Comment by deshvin** [comment]
blocked in #14111 

This domain has historically been blocked/unblocked several times. We will discuss a plan to prevent this from happening.

Screenshot 2023-11-10 at 14 18 07

Thank you for the PR.

**Review by deshvin — APPROVED** [review]

**Comment by Esoxo** [comment]
This is great news. I hope this get sorted sooner than later but really appreciate you taking time to review our project.

**Pull request merged**
