### PR TITLE
Add phishing sites to blocklist

### PR DESCRIPTION
**Pull request by vincianechen**
"org-community-referral.tech",
    "154374-coinbase.com",
    "layerzerorewardfundr.net",
    "celestialzcommunity.xyz",
    "uni.live",
    "tdameritrading516.online",
    "coinbaseai-dex.com",
    "early-blur.io",
    "zro-sale.site",
    "alrdrop-blur.com",
    "pepe-degods.xyz",
    "layerzrofoundation.network",
    "winter-boredapeyachtclub.com",
    "winter-yuga.com",
    "register-layerzero-events.com",
    "app-layerzero.space",
    "layerzeronetworkweb.space",
    "layerzero-networks.xyz",
    "blurnftt.online",
    "taxes-colnbase.com",
    "degods-com.events",
    "arfblocks.in",
    "incentives.site",
    "layerzero-airdrop.top",
    "crptopunks.app",
    "swap.org.in",
    "blurree.pages.dev",
    "banklesslaw.com",
    "worlddrop.win",
    "layerzero-network.claims",
    "signup-layerzro.events",
    "distribution-layerzero.xyz",
    "bankless-governance.com",
    "celestialzgroup.xyz",
    "celestiatoken.com",
    "celestial-refresh.pages.dev",
    "layerzero-networks.net",
    "layerzero.fyi",
    "register-a16z.com",
    "celestgroup.tech",
    "glaze-glimmer-empress.glitch.me",
    "celestia.cool",
    "layerzero-airdroop.online",
    "boredapayachtclub.com",
    "ordinalsy00ts.com",
    "tia-celestiacommunity.quest",
    "blast-blur.io",
    "layerzerofndrewarsd.net",

### CODE REVIEW

**Review by deshvin — APPROVED** [review]

**Comment by jcstein** [comment]
hi, I am the maintainer and owner of [celestia.cool](https://celestia.cool), which is [an open source site](https://github.com/jcstein/celestia-cool) that displays statistics from the Celestia blockchain. there is no wallet connection on this site at all. can you please help me understand how it was added to this list @deshvin @vincianechen? thank you.

**Comment by uri-bloXroute** [comment]
hey @deshvin @vincianechen 
can you explain why you added uni.live was added to this list?

we (bloXroute) built an alternative Uniswap front-end (Uniswap are aware, feel free to ping Austin), and the warning really scared all the users from trying it.

MOST IMPORTANTLY - we're going to relaunch using swap.live , and I want to make absolutely sure it isn't added to the list by accident.

If you need to confirm this is legit from bloXroute, @samczsun has my TG handle and can DM me.

Thanks a lot,
Uri

**Comment by jcstein** [comment]
it's also not possible to tell why something was added to the blocklist, because the tool is outdated.
screenshot 2024-01-10 at 12 11 18
screenshot 2024-01-10 at 12 11 24

**Comment by ktian94** [comment]
> hey @deshvin @vincianechen can you explain why you added uni.live was added to this list?
> 
> we (bloXroute) built an alternative Uniswap front-end (Uniswap are aware, feel free to ping Austin), and the warning really scared all the users from trying it.
> 
> MOST IMPORTANTLY - we're going to relaunch using swap.live , and I want to make absolutely sure it isn't added to the list by accident.
> 
> If you need to confirm this is legit from bloXroute, @samczsun has my TG handle and can DM me.
> 
> Thanks a lot, Uri

@uri-bloXroute , good to re-connect. This was an intentional push -- will work to get all parties aligned on this so there's no friction going forward.

**Pull request merged**
