### PR TITLE
Denylist goblintown-drop.art, b0ki.live, goblintownwtf.net, claims-chimpers.xyz, goblin-town.net

### PR DESCRIPTION
**Pull request by lljxx1**
## Phishing Report

```json
[
  "goblintown-drop.art",
  "b0ki.live",
  "goblintownwtf.net",
  "claims-chimpers.xyz",
  "goblin-town.net"
]
```

### report_button
- phishing link: [http://goblintown-drop.art](http://goblintown-drop.art)
- phishing domain: `goblintown-drop.art`
- phishing tweet: https://twitter.com/adidasoriginals/status/1534440074661830657

### Boki
- phishing link: [http://B0ki.live](http://B0ki.live)
- phishing domain: `b0ki.live`
- official site: [http://boki.art](http://boki.art)
- phishing tweet: https://twitter.com/adidasoriginals/status/1534931009610952704

### goblintown.wtf
- phishing link: [https://goblintownwtf.net/?mint](https://goblintownwtf.net/?mint)
- phishing domain: `goblintownwtf.net`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1535032267587846144

### Chimpers
- phishing link: [http://claims-chimpers.xyz](http://claims-chimpers.xyz)
- phishing domain: `claims-chimpers.xyz`
- official site: [https://www.chimpers.xyz/](https://www.chimpers.xyz/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1535019028770705412

### goblintown.wtf
- phishing link: [http://goblin-town.net](http://goblin-town.net)
- phishing domain: `goblin-town.net`
- official site: [https://goblintown.wtf/](https://goblintown.wtf/)
- phishing tweet: https://twitter.com/adidasoriginals/status/1534291325088153602

> 

*****
> 
> image
> 
> Let's fight against evil !
> Report from the [Scam Sniffer](https://scamsniffer.io/?utm_source=pr-footer). 
> [Twitter](https://twitter.com/scamsniffer_), [Discord](https://discord.com/invite/q6pJMAbeH7), [GitHub](https://github.com/scamsniffer), [GitCoin](https://gitcoin.co/grants/6049/scam-sniffer), [WebSite](https://scamsniffer.io/?utm_source=pr-footer)

### CODE REVIEW

**Review by 409H — DISMISSED** [review]

**Comment by 409H** [comment]
Please can you update your branch to be inline with the base branch

**Comment by lljxx1** [comment]
done

**Comment by AlexHerman1** [comment]
@lljxx1  can you resolve conflicts

**Comment by lljxx1** [comment]
@AlexHerman1 done

**Comment by lljxx1** [comment]
Also can metamask block the address? We recently tried to do automated collection of attacker addresses from phishing sites, and these addresses can be blocked in time to reduce user losses.

**Comment by lljxx1** [comment]
@AlexHerman1 @409H plz take look again

**Comment by devenblake** [comment]
I edited the title to be a little more accurate to the content (`discord.gg` isn't a part of this and is a well-known reputable domain so it was odd to see it in the title here).

**Comment by lljxx1** [comment]
> I edited the title to be a little more accurate to the content (`discord.gg` isn't a part of this and is a well-known reputable domain so it was odd to see it in the title here).

yeah, I forgot to remove it from the title

**Comment by lljxx1** [comment]
@AlexHerman1 @409H plz take look again

**Comment by lljxx1** [comment]
@409H @AlexHerman1 hi?

**Comment by AlexHerman1** [comment]
Hi sorry @lljxx1 , needs conflicts resolved.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
