### PR TITLE
Add Openswap.one to the allowlist

### PR DESCRIPTION
**Pull request by lalFF80**
Related to issue #5480   . Add https://openswap.one to allowlist .

Alex, dev for OpenSwap, opened 5480 and included additional information there.

### CODE REVIEW

**Comment by TheOpenFinanceProject** [comment]
Alex here, i second this PR.

**Comment by davidwgrossman** [comment]
@lalFF80 @TheOpenFinanceProject is `openswap.one` getting blocked? It doesn't look like it is blocked to me

**Comment by lalFF80** [comment]
It is receiving a erroneous phishing message.  We temporarily redirected the url (openswap.one) to app.openswap.one to keep operation up and going but the underlining phishing error was present on openswap.one.

**Comment by davidwgrossman** [comment]
Got it. I'll approve and move forward now with the PR

**Review by gravelcycles — APPROVED** [review]

**Pull request merged**
