### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Add various scams
---

Some are ETH merge themed, some are approval scams seeking users to interact with them to drain their assets, and some are plain old seed stealers.

Also some of the good old "we decided to double your crypto, just send here and get 2X bla bla"

Oh and last but not least BABADEDA and REDLINE STEALER trojans that will pwn all your keys immediately if you were naive enough to run them on the same machine you deal with crypto.

---
Exhibit A - This is not the `Optimism-dApp-v2.1.2.exe` file you are looking for. Actually as Web3 apps run in the browser and there is rarely any `.exe` to download. Fake update, trojan.
image
(note some projects do have legit executables, like Axie Infinity)

---
Exhibit B - ETH fake giveaway
image

---
Exhibit C - ETH fake giveaways
image
image

---
Exhibit D - Fake Near wallet
image

---
Exhibit E - Fake Uniswap
image

---
Exhibit D - Fake ETH Merge (connect your wallet, sure...)
image

```
1inch.financial
1inch.international
1lnch.launchapp.finance
1vvv-roninwallet.top
1vvwvroninwallet.top
1wvvroninwallet.top
app-oppensea.com
app-pancakeswap.exchange
app-tomb.com
app-uniswap-org.ml
app.1inch.financial
app.opptimism.com
app.optimism.run
app.x2y2.financial
app.yetifinance.top
arcticasfalt.com
axelar.space
bestinvestcloud-usdt.ml
binance-exchange.net
burgerswap.net
burgerswap.tech
cilpper.exchange
cipper.exchange
clapper.exchange
clepper.exchange
clilpper.exchange
coinbasecashgiveaway.finance.blog
confirms-coinbase.myddns.me
connect-hotbit-exchange.cf
connect-hotbit-exchange.ga
connect-hotbit-exchange.gq
connect-hotbit-exchange.ml
connect-hotbit-exchange.tk
cryptowallet-trust.com
ether-coinbase.com
ethereum-2-0-giveaway.com
ethereum-announcement.org
ethereum-buterin.live
ethereum-celebration.info
ethereum-merge-2-0.com
ethereum-merge-event.online
ethereum-merge.cloud
ethereum-merge2.com
ethereum-merge2x.com
ethereum-merge2x.org
ethereum-merge2xx.com
ethereum-mergex2.com
ethereum-panel.homes
ethereum-v2.live
ethereumakex2.com
ethereumdouble.net
ethereumerge.info
ethereumerge.org
ethereumerges-blogspot.com
ethereumget2x.com
ethereumgivesback.co
ethereumholdings.xyz
ethereummerge.link
ethereummerge.net
ethereummerge.xyz
ethereummergehub.com
ethereumswap.xyz
event-ethereum.tech
exchange-v2.finance
exodus.com.download-wallet.arcticasfalt.com
grapefinance.net
launchapp.finance
launchpad.app-tomb.com
lido-finance.biz
lido-finance.cloud
lido-finance.ink
lido-finance.io
login-hotbitwallet.ga
login.coinbase.com.authidsession992004882.com
login.trushwallet.xyz
logo-edge.app-tomb.com
magic-edun.cryptouswallets.com
mcryptowallets.com
menschen-immcloudapp.uksivt.ru
merge-ethereum-giveaway.com
mergethereum.online
metamask-ad.infinityfreeapp.com
metamask.gifts
metamask.io-defi-web3-dapps-and-nfts.jajawprinters.com
metamask.io.web8548.web07.bero-webspace.de
metamask.io.web8604.web07.bero-webspace.de
metamask.web8565.web07.bero-webspace.de
metamask.web8606.web07.bero-webspace.de
metamaskapp.info
metamasksupport.io
mlppkokicmxzjwd.demo.pancakeswaps.it
nft-uniswap.life
nft-uniswap.online
okexcryptoexchange.com
opptimism.com
pancakesvvap.exchange-v2.finance
pancakeswap-verificationvhost207777.lowhost.ru
pancakeswap.claims
pancakeswap.skuld.deepskeye.hu
pancakeswapfiancen.app
rariblle-whitelist.com
red-edge.pool-1inch.finance
sce-coinbase.com
serverstorage-downl2.com
tradecapitol-wallet.cc
trustpool.info
trxusdt.uniswap.team
uniswap-exchange.co
uniswap-exchange.info
uniswap-syst.com
uniswap-uniswap.com
uniswap.apackard.com
uniswap.homey.center
uniswapav.net
uniswaper.me
uniswapiinterface.com
usdt-crypto.vip
usdtapi.uniswap.team
usdtcryptomine.com
v2exchange-pancakeswap.financial
v3-aave.com
wallet.near-ex.com
web3wallet.ink
wwwuniswap.com
x2y2.financial
yfdai.financial
```

```
$ ./submit.sh | egrep "(result|url)"

  "api": "https://urlscan.io/api/v1/result/d76871d6-4e04-4c73-b1bc-66f6f4b7272c/",
  "url": "http://1inch.financial",

  "api": "https://urlscan.io/api/v1/result/f708ffba-b688-43ab-b1a7-1e6f397bc2ca/",
  "url": "http://1inch.international",

  "api": "https://urlscan.io/api/v1/result/aea05224-8d9d-4aca-b356-84941f34cef9/",
  "url": "http://1vvv-roninwallet.top",

  "api": "https://urlscan.io/api/v1/result/6905f634-3b8b-4154-8de8-46419e7e4295/",
  "url": "http://1vvwvroninwallet.top",

  "api": "https://urlscan.io/api/v1/result/a098e29f-8470-46e5-ac16-f6e485dbfb66/",
  "url": "http://1wvvroninwallet.top",

  "api": "https://urlscan.io/api/v1/result/ee4fdb2a-cca7-47a6-b0d5-d82806b78a31/",
  "url": "http://app-pancakeswap.exchange",

  "api": "https://urlscan.io/api/v1/result/80bfeca9-f1f2-4acb-9810-76b606f41038/",
  "url": "http://app-uniswap-org.ml",

  "api": "https://urlscan.io/api/v1/result/cb3e00ea-e82a-42d4-96c5-7e4b1a03b8c8/",
  "url": "http://app.opptimism.com",

  "api": "https://urlscan.io/api/v1/result/9bbf4aa2-c09f-47be-ab82-92e45ed8a077/",
  "url": "http://app.optimism.run",

  "api": "https://urlscan.io/api/v1/result/6b73bf6f-a4bf-42b1-85f9-df26af0474b9/",
  "url": "http://app.yetifinance.top",

  "api": "https://urlscan.io/api/v1/result/0ca5b28e-96d3-4b13-9bdf-589daf727f09/",
  "url": "http://arcticasfalt.com",

  "api": "https://urlscan.io/api/v1/result/a6d7eb1a-5d6b-4f9c-9bb7-8aeea16cb112/",
  "url": "http://axelar.space",

  "api": "https://urlscan.io/api/v1/result/0c27cdfd-ea0b-44e5-8308-80232c7054b4/",
  "url": "http://bestinvestcloud-usdt.ml",

  "api": "https://urlscan.io/api/v1/result/0b522c33-131f-498f-b5e2-2661af790da2/",
  "url": "http://binance-exchange.net",

  "api": "https://urlscan.io/api/v1/result/0e6a2c96-1a87-47ec-9523-d4e33326b2a1/",
  "url": "http://burgerswap.net",

  "api": "https://urlscan.io/api/v1/result/05c4bf7b-66cc-47ee-9203-060204af9b4d/",
  "url": "http://burgerswap.tech",

  "api": "https://urlscan.io/api/v1/result/682e37a7-958e-45cb-a76d-b144559a560a/",
  "url": "http://cilpper.exchange",

  "api": "https://urlscan.io/api/v1/result/c55dbdf6-90ba-497b-9c5a-1f7ef8627611/",
  "url": "http://cipper.exchange",

  "api": "https://urlscan.io/api/v1/result/e0ed85d3-b4a1-4657-b9b3-daaa2f181b77/",
  "url": "http://clapper.exchange",

  "api": "https://urlscan.io/api/v1/result/3a7482b3-5538-40f2-8ddd-23e8e516ad71/",
  "url": "http://clepper.exchange",

  "api": "https://urlscan.io/api/v1/result/4d9f3820-a842-4774-aedf-4881a4d02869/",
  "url": "http://clilpper.exchange",

  "api": "https://urlscan.io/api/v1/result/6bc85334-2d58-403f-a668-ea4c5a5609fb/",
  "url": "http://coinbasecashgiveaway.finance.blog",

  "api": "https://urlscan.io/api/v1/result/a3a13a38-f8a8-412a-8b9f-cd7868152d68/",
  "url": "http://confirms-coinbase.myddns.me",

  "api": "https://urlscan.io/api/v1/result/3110c62d-a5bd-4945-8d96-4968df897a6e/",
  "url": "http://connect-hotbit-exchange.ga",

  "api": "https://urlscan.io/api/v1/result/e8d9e6a1-686a-472e-91ec-4a3b73b74083/",
  "url": "http://cryptowallet-trust.com",

  "api": "https://urlscan.io/api/v1/result/5231b66a-fad5-4f9e-927e-4c278e9b03b9/",
  "url": "http://ether-coinbase.com",

  "api": "https://urlscan.io/api/v1/result/f656f50a-8574-4c32-907c-8515dd2a727c/",
  "url": "http://ethereum-2-0-giveaway.com",

  "api": "https://urlscan.io/api/v1/result/a91d1d66-3ce2-4de0-a1fa-e28eee96ba01/",
  "url": "http://ethereum-announcement.org",

  "api": "https://urlscan.io/api/v1/result/ca6d8c80-4063-4b64-b711-4cffb9eb6175/",
  "url": "http://ethereum-buterin.live",

  "api": "https://urlscan.io/api/v1/result/2b2dab9c-8d16-4226-8e34-22d17549f616/",
  "url": "http://ethereum-celebration.info",

  "api": "https://urlscan.io/api/v1/result/3062630e-0d11-44bc-91e5-0f3da8367af4/",
  "url": "http://ethereum-merge-2-0.com",

  "api": "https://urlscan.io/api/v1/result/af6ce79c-0797-40f2-8434-7daac65ce7f6/",
  "url": "http://ethereum-merge-event.online",

  "api": "https://urlscan.io/api/v1/result/07b45be6-4438-43cb-a44f-0d9fb8438bb2/",
  "url": "http://ethereum-merge.cloud",

  "api": "https://urlscan.io/api/v1/result/8454c814-aef8-416b-97fb-2ddcf2b827aa/",
  "url": "http://ethereum-merge2.com",

  "api": "https://urlscan.io/api/v1/result/7a89fe56-72b6-4e64-8a48-790fa36dd7be/",
  "url": "http://ethereum-merge2x.com",

  "api": "https://urlscan.io/api/v1/result/022a6bb5-2289-43f5-8170-f43214712380/",
  "url": "http://ethereum-merge2xx.com",

  "api": "https://urlscan.io/api/v1/result/6cbde750-2b89-4216-9ffb-69627f399c4e/",
  "url": "http://ethereum-mergex2.com",

  "api": "https://urlscan.io/api/v1/result/2c0e0801-f067-492c-89f0-1049229e98c3/",
  "url": "http://ethereum-panel.homes",

  "api": "https://urlscan.io/api/v1/result/7b1f7278-4bf0-4934-bf0d-44d17b61b3ba/",
  "url": "http://ethereum-v2.live",

  "api": "https://urlscan.io/api/v1/result/496cea9a-28af-47ce-814f-0700a86764eb/",
  "url": "http://ethereumakex2.com",

  "api": "https://urlscan.io/api/v1/result/613a95c2-2602-493b-ad2c-3af2bf0f56cb/",
  "url": "http://ethereumdouble.net",

  "api": "https://urlscan.io/api/v1/result/0a6a62a1-4b5c-4e71-8c83-b391032c8caf/",
  "url": "http://ethereumerge.info",

  "api": "https://urlscan.io/api/v1/result/93d423a3-bdaf-45db-bf54-d4bfc8c0458b/",
  "url": "http://ethereumerge.org",

  "api": "https://urlscan.io/api/v1/result/e53f704e-2283-4d7b-8fd3-7445884d8394/",
  "url": "http://ethereumerges-blogspot.com",

  "api": "https://urlscan.io/api/v1/result/1d5b256a-2cb0-43f1-b2dd-c99e2e9077d8/",
  "url": "http://ethereumget2x.com",

  "api": "https://urlscan.io/api/v1/result/59193fa2-9fe3-4337-be97-69b81fcf4a6d/",
  "url": "http://ethereumholdings.xyz",

  "api": "https://urlscan.io/api/v1/result/7606e011-9eba-45fc-8037-ed940e5c4c70/",
  "url": "http://ethereummerge.link",

  "api": "https://urlscan.io/api/v1/result/ec458f2b-bab3-43d5-95df-acc3e2e6d664/",
  "url": "http://ethereummerge.net",

  "api": "https://urlscan.io/api/v1/result/21dac821-7716-4b0c-ad9d-bd8175a95430/",
  "url": "http://ethereummerge.xyz",

  "api": "https://urlscan.io/api/v1/result/f46bc21d-2e95-492f-b829-e9a0fc4ccefc/",
  "url": "http://ethereummergehub.com",

  "api": "https://urlscan.io/api/v1/result/af337e72-8b89-4582-8474-a089a0e1039f/",
  "url": "http://ethereumswap.xyz",

  "api": "https://urlscan.io/api/v1/result/d79b94ad-1e49-4883-97c9-56fc1dd33a4e/",
  "url": "http://event-ethereum.tech",

  "api": "https://urlscan.io/api/v1/result/1997e8ff-19f3-49df-bb4c-2c815e7d58e2/",
  "url": "http://exodus.com.download-wallet.arcticasfalt.com",

  "api": "https://urlscan.io/api/v1/result/3c199e94-481c-4b4f-8ae2-a1f4253196b1/",
  "url": "http://grapefinance.net",

  "api": "https://urlscan.io/api/v1/result/d6a05aa8-abc5-4cc8-a2bd-ff753c50ebf4/",
  "url": "http://lido-finance.biz",

  "api": "https://urlscan.io/api/v1/result/a4b73155-1b68-4e57-b765-9c6147804527/",
  "url": "http://lido-finance.cloud",

  "api": "https://urlscan.io/api/v1/result/78e23968-8f36-4694-b56b-fa528d797fbb/",
  "url": "http://lido-finance.ink",

  "api": "https://urlscan.io/api/v1/result/9f348f1d-c222-4152-8d87-c6217d43b89b/",
  "url": "http://lido-finance.io",

  "api": "https://urlscan.io/api/v1/result/2c4eee0f-8d04-4357-a3e6-2e8df8280bfe/",
  "url": "http://login-hotbitwallet.ga",

  "api": "https://urlscan.io/api/v1/result/dd7bd944-e44c-4edf-b0e2-23528f81a1c1/",
  "url": "http://login.coinbase.com.authidsession992004882.com",

  "api": "https://urlscan.io/api/v1/result/64759f96-17f4-4458-a0d2-9b9238c3df03/",
  "url": "http://login.trushwallet.xyz",

  "api": "https://urlscan.io/api/v1/result/cbd6952c-fe9c-44ee-92bd-c87dfe4ee850/",
  "url": "http://magic-edun.cryptouswallets.com",

  "api": "https://urlscan.io/api/v1/result/59e46907-f67a-48cd-8760-7f7d3d6f6bf1/",
  "url": "http://mcryptowallets.com",

  "api": "https://urlscan.io/api/v1/result/27fa9a73-d47c-42cc-8015-2e53eb0764b1/",
  "url": "http://menschen-immcloudapp.uksivt.ru",

  "api": "https://urlscan.io/api/v1/result/3d1e5cbe-e817-4aa5-bcba-210c5532a02d/",
  "url": "http://merge-ethereum-giveaway.com",

  "api": "https://urlscan.io/api/v1/result/0103f663-0b41-4bb3-b1f5-c616af559105/",
  "url": "http://mergethereum.online",

  "api": "https://urlscan.io/api/v1/result/2b40ad2c-5d2e-4d0c-bc8f-7bdc798c84ef/",
  "url": "http://metamask-ad.infinityfreeapp.com",

  "api": "https://urlscan.io/api/v1/result/39b48f6d-3aff-46b0-8ea4-6bacd1e0ca94/",
  "url": "http://metamask.gifts",

  "api": "https://urlscan.io/api/v1/result/249bea60-39a3-478b-860e-b8ff4bf79039/",
  "url": "http://metamask.io-defi-web3-dapps-and-nfts.jajawprinters.com",

  "api": "https://urlscan.io/api/v1/result/3112f086-f652-4abc-b321-e55176fc096f/",
  "url": "http://metamask.io.web8548.web07.bero-webspace.de",

  "api": "https://urlscan.io/api/v1/result/4aad98ec-2f56-4f9f-881a-2cc3208c8ad3/",
  "url": "http://metamask.io.web8604.web07.bero-webspace.de",

  "api": "https://urlscan.io/api/v1/result/fa65c8df-d2d9-453a-be49-e9f374500612/",
  "url": "http://metamask.web8565.web07.bero-webspace.de",

  "api": "https://urlscan.io/api/v1/result/a891f37c-fd93-4024-bc13-3b26701a7ddb/",
  "url": "http://metamask.web8606.web07.bero-webspace.de",

  "api": "https://urlscan.io/api/v1/result/47d6db54-17a2-47a7-bb7b-825915925b84/",
  "url": "http://metamaskapp.info",

  "api": "https://urlscan.io/api/v1/result/4767a0f5-bb46-4f34-b442-561ef11ad9c1/",
  "url": "http://metamasksupport.io",

  "api": "https://urlscan.io/api/v1/result/d11a2a4a-7f1c-4387-a87b-e3f551ddf7a8/",
  "url": "http://mlppkokicmxzjwd.demo.pancakeswaps.it",

  "api": "https://urlscan.io/api/v1/result/39ec279a-0898-48d9-9301-d7d9a24cf4ca/",
  "url": "http://nft-uniswap.life",

  "api": "https://urlscan.io/api/v1/result/e4cf1082-5cca-45a5-aeb2-a232baf889ed/",
  "url": "http://nft-uniswap.online",

  "api": "https://urlscan.io/api/v1/result/fe7070ca-11f5-4159-80ee-5468f5dc46ba/",
  "url": "http://okexcryptoexchange.com",

  "api": "https://urlscan.io/api/v1/result/6fd694fb-7243-4931-af05-ae4265e245d9/",
  "url": "http://opptimism.com",

  "api": "https://urlscan.io/api/v1/result/75a7a965-2c42-4c25-a5f1-57b3b512ccb3/",
  "url": "http://pancakeswap-verificationvhost207777.lowhost.ru",

  "api": "https://urlscan.io/api/v1/result/623f0c44-a623-487a-89e2-ab9f0df8ef13/",
  "url": "http://pancakeswap.claims",

  "api": "https://urlscan.io/api/v1/result/9d7ac86c-45ec-4e06-9aec-9d00877b1e52/",
  "url": "http://pancakeswap.skuld.deepskeye.hu",

  "api": "https://urlscan.io/api/v1/result/7a49b77c-f5d4-41da-a494-23de4ed7aeae/",
  "url": "http://pancakeswapfiancen.app",

  "api": "https://urlscan.io/api/v1/result/46e7c3c2-9d9a-4e84-8596-8cb9b92fecce/",
  "url": "http://serverstorage-downl2.com",

  "api": "https://urlscan.io/api/v1/result/6753a240-9fb2-4de8-a6f1-51e224947ada/",
  "url": "http://trxusdt.uniswap.team",

  "api": "https://urlscan.io/api/v1/result/ae15b48a-5b12-40c5-89bc-409e0b52a70f/",
  "url": "http://uniswap-exchange.co",

  "api": "https://urlscan.io/api/v1/result/2feb5bad-0afd-4510-ad1a-9c74cc1746fa/",
  "url": "http://uniswap-exchange.info",

  "api": "https://urlscan.io/api/v1/result/04cea808-56cd-441f-88fe-69013f483c24/",
  "url": "http://uniswap-syst.com",

  "api": "https://urlscan.io/api/v1/result/6264e092-1c7a-4981-bf70-7f23a374b75e/",
  "url": "http://uniswap-uniswap.com",

  "api": "https://urlscan.io/api/v1/result/bddd6283-8404-48e6-8ece-01242ad615ca/",
  "url": "http://uniswap.apackard.com",

  "api": "https://urlscan.io/api/v1/result/eafd6d23-320a-405b-b0d6-7d39dac160f7/",
  "url": "http://uniswap.homey.center",

  "api": "https://urlscan.io/api/v1/result/0ee30674-1b49-4277-8c2f-d2aa47e716a1/",
  "url": "http://uniswapav.net",

  "api": "https://urlscan.io/api/v1/result/0df5a57e-2923-4dfe-9506-12c8056cdb98/",
  "url": "http://uniswaper.me",

  "api": "https://urlscan.io/api/v1/result/9bd1995b-3db7-4b31-b8e7-03f50bbaf3f8/",
  "url": "http://uniswapiinterface.com",

  "api": "https://urlscan.io/api/v1/result/66b5f6b7-640f-4da1-a159-d93eb54a99fb/",
  "url": "http://usdt-crypto.vip",

  "api": "https://urlscan.io/api/v1/result/27847ae3-a9ff-486d-81b1-eb7f7b8e76ca/",
  "url": "http://usdtapi.uniswap.team",

  "api": "https://urlscan.io/api/v1/result/4f232217-994a-4b67-8dd7-2c148294298c/",
  "url": "http://usdtcryptomine.com",

  "api": "https://urlscan.io/api/v1/result/5bc09f56-8ea5-4245-ba6f-598490d7e22c/",
  "url": "http://wallet.near-ex.com",

  "api": "https://urlscan.io/api/v1/result/4d07bcaa-8661-4bb7-ad36-315717fb9569/",
  "url": "http://wwwuniswap.com",

  "api": "https://urlscan.io/api/v1/result/18557242-13c2-4ca8-b25f-6c6db6e1d12e/",
  "url": "http://1inch.financial",

  "api": "https://urlscan.io/api/v1/result/970bcc1e-e74a-4261-8cde-2c40c85fb067/",
  "url": "http://app-oppensea.com",

  "api": "https://urlscan.io/api/v1/result/77503b6e-a3ed-4cef-a199-ac1e9a5dcae6/",
  "url": "http://app-tomb.com",

  "api": "https://urlscan.io/api/v1/result/15b331f3-0e5b-40d7-8add-eb1d5e50efb2/",
  "url": "http://app.1inch.financial",

  "api": "https://urlscan.io/api/v1/result/c8e146a4-036c-4c8a-a3c9-da4bcfd0f921/",
  "url": "http://app.x2y2.financial",

  "api": "https://urlscan.io/api/v1/result/e8e14e9c-3d3f-4a33-b096-a28e7a1616f6/",
  "url": "http://exchange-v2.finance",

  "api": "https://urlscan.io/api/v1/result/01a889ca-cecc-4bfd-a397-ef1015c06550/",
  "url": "http://launchapp.finance",

  "api": "https://urlscan.io/api/v1/result/e092c4fe-3eee-4853-b37f-d89613445771/",
  "url": "http://launchpad.app-tomb.com",

  "api": "https://urlscan.io/api/v1/result/0121f61b-69a8-480e-976c-737f4f6e566c/",
  "url": "http://logo-edge.app-tomb.com",

  "api": "https://urlscan.io/api/v1/result/425bec17-44cc-43bb-834d-d8687b7757ad/",
  "url": "http://rariblle-whitelist.com",

  "api": "https://urlscan.io/api/v1/result/0af2dad1-ebce-4324-bb98-1065d090782b/",
  "url": "http://red-edge.pool-1inch.finance",

  "api": "https://urlscan.io/api/v1/result/73a94c74-4ea9-4f14-a392-6e03e195b1fa/",
  "url": "http://trustpool.info",

  "api": "https://urlscan.io/api/v1/result/149a061c-bf13-48f6-a011-a671b5c56d5d/",
  "url": "http://v2exchange-pancakeswap.financial",

  "api": "https://urlscan.io/api/v1/result/dd9a7f50-a954-49d9-953a-c806e2a05332/",
  "url": "http://v3-aave.com",

  "api": "https://urlscan.io/api/v1/result/61817e90-2809-4085-9468-4ae00f19094a/",
  "url": "http://web3wallet.ink",

  "api": "https://urlscan.io/api/v1/result/d226daec-8e87-45ae-85a1-008ea0abbec4/",
  "url": "http://x2y2.financial",

  "api": "https://urlscan.io/api/v1/result/dea65b2f-56af-41d0-a422-2f6428e61783/",
  "url": "http://yfdai.financial",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicate 
`burgerswap.net`

**Review by dubstard — COMMENTED** [review]
add
```
1inch.financial
1lnch.launchapp.finance
app-oppensea.com
app-tomb.com
app.1inch.financial
app.x2y2.financial
exchange-v2.finance
launchapp.finance
launchpad.app-tomb.com
logo-edge.app-tomb.com
pancakesvvap.exchange-v2.finance
rariblle-whitelist.com
red-edge.pool-1inch.finance
trustpool.info
v2exchange-pancakeswap.financial
v3-aave.com
web3wallet.ink
x2y2.financial
yfdai.financial
```

**Review by dubstard — COMMENTED** [review]
add
```
		"login-spooky.com.mx",
		"spooky-swap.info",
		"spookyswapapp.com",
		"connect-to-wallet-raydium.net",
		"sushiusd.org",
		"connect-wallet-balancer.com",
		"access-to-wallet-balancer-exchange.info",
		"balancerdefiprotocol.com",
		"balancerprotocol.info",
		"raydiumdex.io",
		"sushiusd.info",
		"sushi.salon",
		"raydiumswap.co",
		"connect-raydium.com",
		"balancer.fyi",
```

**Comment by dubstard** [comment]
Nothing to see here, move along.

Just harmless Microsoft IPs.
image
image
image

[roasted](https://twitter.com/dubstard/status/1315139636730245120)
[roasted](https://twitter.com/dubstard/status/1469029210018693124)

**Review by dubstard — COMMENTED** [review]
remove 1inch.zone (false positive)

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Comment by dubstard** [comment]
@AlexHerman1 sorry for the trouble
Slight correction here
https://github.com/MetaMask/eth-phishing-detect/pull/8476

**Comment by dubstard** [comment]
FML I accidentally white listed bad sites and meant to whitelist only
`balancer.fyi`



those are bad and must be moved from whitelist to blacklist
```
		"login-spooky.com.mx",
		"spooky-swap.info",
		"spookyswapapp.com",
		"connect-to-wallet-raydium.net",
		"sushiusd.org",
		"connect-wallet-balancer.com",
		"access-to-wallet-balancer-exchange.info",
		"balancerdefiprotocol.com",
		"balancerprotocol.info",
		"raydiumdex.io",
		"sushiusd.info",
		"sushi.salon",
		"raydiumswap.co",
		"connect-raydium.com",
```

**Pull request merged**
