### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Not the 1inch you need

```
		"1inch-vv.com",
		"1in-vvv.com",
		"1inch-in.com",
		"1in-bf.com",
		"1inch-777.com",
```
Not the Wallet you need
```
		"acess-walletcoinsbit.ga",
		"acess-walletcoinsbit.ml",
		"acess-walletcoinsbit.gq",
		"acess-walletcoinsbit.cf",
    		"acess-walletcoinsbit.tk",
		"coinsbitwallet-com.tk",
		"crypto.airdroplerts.com",
		"dev-wcadmin.pantheonsite.io",
		"quantumsafe.center",
```

Not the NFT you need (wallet drainers upon attempt to "mint")
image
image
fake hardcoded list of wallets supposedly to instill trust - see "transaction success." 🤡
```
		"billionairespre.xyz",
		"bossbeaautiesnft.xyz",
		"gangsteerallstar.xyz",
		"jrnyyclub.xyz",
		"sabbet.xyz",
		"thesnooopavatars.xyz",
```
Not the Coinbase you need
```
		"coinbase-secured.com",
		"coinbase.signinlogon.com",
		"signinlogon.com",
		"coinbasewallet-farmworld.org",
		"coinbasewallets.xyz",
		"help.coinbase-authsession133745019.com",
		"coinbase-authsession133745019.com",
		"help.coinbase-authsession133758920.com",
		"coinbase-authsession133758920.com",
		"login.coinbase-authsession133745019.com",
		"login.coinbase-authsession133758920.com",
```

Not the Discord you need
```
		"discordbots.top",
```

Not the Ethereum you need
image

```
		"ethereum-merge.io",
		"ethereumname.exchange",
		"ethereumupgrade.org",
		"ethereumwrap.ga",
		"ethereumwrap.gq",
		"ethereumwrap.ml",
		"ethereumwrap.tk",
		"ethereumwrap.cf",
```
Not the Uniswap you need
```
		"uniswap-kit.com",
		"uniswap-mine.com",
		"uniswapy.net",
		"yuniswap.org",
		"exchanger-uniswap.com",
```	

Not the Ledger you need
```
		"ledger-liveapp.org",
		"ledgerlives.org",
		"ledgerlivess.com",
		"legderslive.com",
		"complaints-ledger.com",
```

Not the Pancakeswap you need
```
		"lms.pancakesvqp.com",
		"manage.pancakesvqp.com",
		"market.pancakesvqp.com",
		"pancakeswap.pub",
		"pancakeswap.sc163.shop",
		"pancakeswaps-finance.com",
		"xn--pancakeswp-c5a.com",
		"cs.pancakesvqp.com",
```

Not the MetaMask you need
```
		"metamask.fartit.com",
		"metamask.fernando-olmos.com",
		"metamask.io.signature5.in",
		"metamask.io.wallet-sign.in",
		"metamasking.xyz",
		"music.pancakesvqp.com",
		"notify-metamasks.zyns.com",
		"service-metamask.io",
```
Not the MyEtherWallet you need
```
		"metherwallet.com.acluvamerica.org",
		"myetiherwallet.app",
```

Not the AMM / DEX you need
image

```
		"smartuplan.com",
		"uplanamm.com",
```

```
./BurnTrash.sh | egrep '(result|url)'

  "result": "https://urlscan.io/result/5f90cdbe-2681-44a5-8546-f3aea865ef9e/",
  "url": "http://1in-bf.com",

  "result": "https://urlscan.io/result/8e4dbda8-fe74-472d-a7bb-626f1239a73d/",
  "url": "http://1in-vvv.com",

  "result": "https://urlscan.io/result/2ae5370c-f971-4285-9011-cf7bb1ea89cf/",
  "url": "http://1inch-777.com",

  "result": "https://urlscan.io/result/57808a3f-5208-4ecf-857d-a48f932ede03/",
  "url": "http://1inch-in.com",

  "result": "https://urlscan.io/result/2837d45e-55d6-4d10-9ef4-9b1d6ac11b31/",
  "url": "http://1inch-vv.com",

  "result": "https://urlscan.io/result/63a9df13-31ec-4688-9b51-e8cac4bd6e50/",
  "url": "http://acess-walletcoinsbit.ga",

  "result": "https://urlscan.io/result/ffcfe48b-7f2f-450d-8b8b-864a713b2ba7/",
  "url": "http://airdropgiveaway.com",

  "result": "https://urlscan.io/result/4df51693-271f-4065-9e27-3f0382bacd34/",
  "url": "http://billionairespre.xyz",

  "result": "https://urlscan.io/result/1b40acf2-51ad-43ee-bab8-b5c444756202/",
  "url": "http://bossbeaautiesnft.xyz",

  "result": "https://urlscan.io/result/854a34e6-e9d0-4b0d-a8fd-e54073de48be/",
  "url": "http://cake.pancakeswap.cn.com",

  "result": "https://urlscan.io/result/ffc66502-2215-4300-8f88-02a53ba910fa/",
  "url": "http://coinbase-authsession133745019.com",

  "result": "https://urlscan.io/result/d1dd7e16-fb86-408d-b3ff-c5a651069f1b/",
  "url": "http://coinbase-authsession133758920.com",

  "result": "https://urlscan.io/result/28dfe991-3c9f-40f5-a447-df3cabfba647/",
  "url": "http://coinbase-secured.com",

  "result": "https://urlscan.io/result/c883d696-efb8-4065-bce7-2ffaf898caf3/",
  "url": "http://coinbasewallets.xyz",

  "result": "https://urlscan.io/result/9feda5a3-a86e-48b4-90a7-3e00f531d22c/",
  "url": "http://coinsbitwallet-com.tk",

  "result": "https://urlscan.io/result/e4b58f83-789b-4148-8026-11c3f85eed0d/",
  "url": "http://complaints-ledger.com",

  "result": "https://urlscan.io/result/a5bed42f-cf94-4f2b-962d-a22d609546f7/",
  "url": "http://crypto.airdroplerts.com",

  "result": "https://urlscan.io/result/f65325df-2db8-4d5b-9048-4f9312670a19/",
  "url": "http://cs.pancakesvqp.com",

  "result": "https://urlscan.io/result/ef17f1e6-3799-4807-a9bb-9c0dc5093eb6/",
  "url": "http://discordbots.top",

  "result": "https://urlscan.io/result/e46432d7-feb5-48fc-b608-9afa2e98d455/",
  "url": "http://ethereum-merge.io",

  "result": "https://urlscan.io/result/68c4b3cd-2b42-4f7a-90d0-fd091750a7c3/",
  "url": "http://ethereumname.exchange",

  "result": "https://urlscan.io/result/b4a8d871-2869-483a-bfb0-d73101f6698a/",
  "url": "http://ethereumupgrade.org",

  "result": "https://urlscan.io/result/0a78b6a9-103c-4633-9035-eb0fa0e88261/",
  "url": "http://ethereumwrap.ga",

  "result": "https://urlscan.io/result/c255ae56-463e-469c-84dc-6059ccb0ee2e/",
  "url": "http://exchanger-uniswap.com",

  "result": "https://urlscan.io/result/7740fc3d-276d-4b32-99d6-4c37bd371e22/",
  "url": "http://gangsteerallstar.xyz",

  "result": "https://urlscan.io/result/6fe86f93-f52c-42fa-a8c9-9814ca6628c4/",
  "url": "http://help.coinbase-authsession133745019.com",

  "result": "https://urlscan.io/result/35415ad2-c942-439e-b746-8c450f92ab6e/",
  "url": "http://help.coinbase-authsession133758920.com",

  "result": "https://urlscan.io/result/dcb6783e-08a5-46e2-aeaf-663e55c7ef0c/",
  "url": "http://jrnyyclub.xyz",

  "result": "https://urlscan.io/result/07d567e7-14b2-4ee1-aff6-0292e0b7a165/",
  "url": "http://ledger-liveapp.org",

  "result": "https://urlscan.io/result/38c678dc-b5a2-40d2-92cd-90bf7649c1fd/",
  "url": "http://ledgerlives.org",

  "result": "https://urlscan.io/result/b89cf37f-f73e-4119-b4f6-69ebb26a33b6/",
  "url": "http://ledgerlivess.com",

  "result": "https://urlscan.io/result/40656512-c4c7-4034-99c6-50aa83c682e4/",
  "url": "http://legderslive.com",

  "result": "https://urlscan.io/result/df3e46a4-c9a3-4b97-a817-95b10aec912e/",
  "url": "http://lms.pancakesvqp.com",

  "result": "https://urlscan.io/result/47ae3299-1c15-4b2f-9c6c-d42a9a3231c8/",
  "url": "http://login.coinbase-authsession133745019.com",

  "result": "https://urlscan.io/result/3285b9d0-47c3-402f-9b2e-2aa7e7f94ae7/",
  "url": "http://login.coinbase-authsession133758920.com",

  "result": "https://urlscan.io/result/06503a1a-7281-4cf0-a60a-7d10a1c2dd68/",
  "url": "http://manage.pancakesvqp.com",

  "result": "https://urlscan.io/result/236b5fd5-afd9-43bd-ae40-942239c3d8aa/",
  "url": "http://market.pancakesvqp.com",

  "result": "https://urlscan.io/result/0d4b26aa-4cfe-4d85-bc0a-3cd17d752114/",
  "url": "http://metamask.fartit.com",

  "result": "https://urlscan.io/result/a1bdaffd-d5a1-49ed-898b-ae46a4061530/",
  "url": "http://metamask.fernando-olmos.com",

  "result": "https://urlscan.io/result/7f4f66d3-8a15-4832-8033-68522ff3567f/",
  "url": "http://metamask.hostinca.com",

  "result": "https://urlscan.io/result/62d592b2-5fba-4622-abd8-88e3212beb17/",
  "url": "http://metamask.io.id74853758.in",

  "result": "https://urlscan.io/result/25b6898f-c338-444c-a174-e1506b9cec27/",
  "url": "http://metamask.io.in",

  "result": "https://urlscan.io/result/fb762b54-9ca1-4848-96a5-238983cd9708/",
  "url": "http://metamask.io.signature5.in",

  "result": "https://urlscan.io/result/f43860e6-b517-44c8-8747-6b1269c71349/",
  "url": "http://metamasking.xyz",

  "result": "https://urlscan.io/result/b93ae8da-6934-4c50-9370-b209fe6dfea1/",
  "url": "http://metherwallet.com.acluvamerica.org",

  "result": "https://urlscan.io/result/e673ffe9-a61c-4605-835f-712855f4ff0e/",
  "url": "http://music.pancakesvqp.com",

  "result": "https://urlscan.io/result/54b533a8-06bc-4fe9-901d-6d9578a994d2/",
  "url": "http://myetherwalet.com",

  "result": "https://urlscan.io/result/ef9b6191-7ccf-46f3-a702-bb27b9e27753/",
  "url": "http://myetiherwallet.app",

  "result": "https://urlscan.io/result/aec0bbb4-173d-4e99-bd38-789757785ab4/",
  "url": "http://myetiherwallet.com",

  "result": "https://urlscan.io/result/0375f6b7-482e-4126-acf0-398bf9be32bf/",
  "url": "http://node-metamask.mobiloitte.org",

  "result": "https://urlscan.io/result/4563c49c-85ad-4ce5-832c-a95c380dedf0/",
  "url": "http://notify-metamasks.zyns.com",

  "result": "https://urlscan.io/result/c613e2b4-50d6-4967-8c1d-496c99195ab2/",
  "url": "http://pancakeswap.fund",

  "result": "https://urlscan.io/result/f51ffbf5-f778-4f21-89e5-4fb215db92f2/",
  "url": "http://pancakeswap.net.cn",

  "result": "https://urlscan.io/result/97feb57d-3218-4ca5-b496-9415a5d52817/",
  "url": "http://pancakeswap.pub",

  "result": "https://urlscan.io/result/b6153cd8-3517-4487-9a32-e775638f5e2c/",
  "url": "http://pancakeswap.sc163.shop",

  "result": "https://urlscan.io/result/ee65da5a-1903-4530-8811-75beb2cd3f07/",
  "url": "http://pancakeswaps-finance.com",

  "result": "https://urlscan.io/result/dac2ccb3-0d15-40de-bcfb-a689a9d23394/",
  "url": "http://sabbet.xyz",

  "result": "https://urlscan.io/result/389585e5-4eed-4a75-bf3e-49cb4778edd1/",
  "url": "http://service-metamask.io",

  "result": "https://urlscan.io/result/41281d83-2d46-4ba2-82b2-64f3db72fb5f/",
  "url": "http://smartuplan.com",

  "result": "https://urlscan.io/result/2b2999ee-bde0-40cd-90c9-9195577bc8d2/",
  "url": "http://support01-coinbase.com",

  "result": "https://urlscan.io/result/14061dec-05ea-4e39-afac-403d5869c215/",
  "url": "http://thesnooopavatars.xyz",

  "result": "https://urlscan.io/result/6a39f718-eaac-46c6-88e3-34c5637713d8/",
  "url": "http://trustwallet-airdrops.nftwealths.com",

  "result": "https://urlscan.io/result/3a38939f-e173-4d36-af31-0c0f1c4f2ca4/",
  "url": "http://uniswap-coins.com",

  "result": "https://urlscan.io/result/435bd9d7-1d26-4b9b-8c1a-ef4a751ea537/",
  "url": "http://uniswap-kit.com",

  "result": "https://urlscan.io/result/bdf4c390-3bd3-493d-af86-e6ac8428c217/",
  "url": "http://dev-wcadmin.pantheonsite.io",
	
  "result": "https://urlscan.io/result/40434184-7ab1-41be-97b9-5c5c3c7ccd4f/",
  "url": "http://quantumsafe.center",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
get rid of dupes
```
"metamask.hostinca.com",
"metamask.io.id74853758.in",
```

**Review by dubstard — COMMENTED** [review]
get rid of duplicate
```
metamask.io.in
```

**Review by dubstard — COMMENTED** [review]
remove `ethereumupgrade.org` from https://github.com/MetaMask/eth-phishing-detect/pull/8405 because the same URL got merged via https://github.com/MetaMask/eth-phishing-detect/pull/8406

This created a retrospective duplicate in https://github.com/MetaMask/eth-phishing-detect/pull/8405

This edit fixes that.

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks!

**Pull request merged**
