### PR TITLE
src/config.json: Alphabetize fuzzylist

### PR DESCRIPTION
**Pull request by trn1ty**
This would alphabetize the fuzzylist in config.json.

Potential issue: `git blame` would stop working for these entries. However, the respective reasons for the entries in the fuzzylist should be noted somewhere that's easy to find, as side effects from fuzzy detection make up the overwhelming majority of the filed bugs in this project; we should be able to point particularly angry people to a `faq.md` that explains why a site being fuzzylisted is inadvertently causing MetaMask or whatever else they're using to block their own legitimate site, and why despite the side effect it's still a good idea to do so.

This commit could potentially introduce vulnerabilities in the form of zero-width characters, make sure to `hexdump -C` this to ensure I did indeed alphabetize the fuzzylist and didn't engage in any funny business.

fuzzylist is alphabetized by second level domain, hence `launchpad.ethereum.org` is alphabetized the same way as if it was `ethereum.org`.

### CODE REVIEW

**Comment by 409H** [comment]
Keeping this list alphabetical seems like a negative and time-cruncher (usually added to without tools/manually), also `git blame` (for these entries) not giving desired output is a negative (although no real issue here as they are all domains that have been on the list for a while)

I'm not sure I am in favour of having this list forced alphabetical but i am in favour of the `faq.md` file. Happy to concede on the alphabetical part if other reviewers vote in favour.

**Comment by devenblake** [comment]
If you look at the blame output they already aren't really ordered in any way. My thinking is that it'd be nice to make it a little neater for referencing - I've been going back and forth between the configuration and various issues a lot as I've been trying to make allowlist PRs. Ideally IMO it would be from first to most recent addition. 

A `fuzzylist.md` with hyperlinks to commits and stuff is doable as part of this (or probably as a separate, related PR to be merged before this one). I'll see if I can get to that later today.

**Comment by 409H** [comment]
>  Ideally IMO it would be from first to most recent addition.

I vote the reverse of this. Having the most recent addition at the top of each array. It means people editing the files with the GitHub UI won't have to scroll far (ie: can do CTRL+F "blacklist" and edit the next line to add to this list. It is also the way it is organised (for the most part) now, with the most recent additions at the top

**Comment by devenblake** [comment]
> > Ideally IMO it would be from first to most recent addition.
> 
> I vote the reverse of this. Having the most recent addition at the top of each array. It means people editing the files with the GitHub UI won't have to scroll far (ie: can do CTRL+F "blacklist" and edit the next line to add to this list.

I would be okay with this too.

> It is also the way it is organised (for the most part) now, with the most recent additions at the top (I may be misinterpreting the "from first to most recent", so ignore me if we are on the same page)

You didn't misinterpret me but I like your idea too. Not picky so long as there *is* organization. Currently there is no organization at all, here's the (abridged and trimmed) `git blame` output right now:
```
2017-08-03 15:46:51 -0700     5)     "metamask.io",
2021-09-22 22:05:09 -0400     6)     "opensea.io",
2021-01-07 12:44:28 -0800     7)     "maskmeta.org",
2017-12-11 17:27:50 -0800     8)     "myetherwallet.com",
2018-02-09 16:25:24 +0000     9)     "cryptokitties.co",
2018-03-01 22:08:47 +0000    10)     "localethereum.com",
2019-12-21 15:48:37 +1100    11)     "localcryptos.com",
2020-09-15 12:10:05 -0700    12)     "auctus.org",
2018-03-23 01:16:30 +0000    13)     "dfinity.org",
2018-03-27 18:26:16 +0100    14)     "hederahashgraph.com",
2018-04-21 10:13:06 -0600    15)     "etherscan.io",
2020-01-21 15:17:09 +0000    16)     "originprotocol.com",
2020-11-06 23:06:23 +0530    17)     "makerfoundation.com",
2020-08-04 18:48:16 -0500    18)     "fulcrum.trade",
2020-11-04 16:32:16 +0000    19)     "launchpad.ethereum.org"
```
This sucks to look at. I have a `fuzzy.txt` in my home directory with this so I can organize it easier for myself. Not a great solution.

I'm working on a Markdown doc listing the fuzzylisted domains, at what commit they were added, and for some at what commit they were removed, and some more info when I see it. Don't expect it soon because it's a lot through which to trudge (some of these timestamps are just when a file went from `"thing"` to `"thing",` or vice versa). But ultimately it could be better than the git blame output. I'm thinking we can let this PR hang until I finish that.

**Pull request closed without merging**
