### PR TITLE
Removing FP's from blocklist [4]

### LINKED ISSUE #12670: [Legitimate Site Blocked] gpt-ai.io
https://gpt-ai.io/
The website will not initiate the user's wallet, only when the user actively clicks the purchase button will it trigger the MetaMask wallet to pay USDT. Please confirm again. This is the way the website sells products.

The GPT project will use three types of contracts:
1. Incubator contract, this is a regular NFT contract that is only used for users to import incubators and has no other functions;
2. The user purchase contract is available on four different chains, and the basic function is to use it when the user purchases goods. The user transfers funds through the contract method;
3. Withdrawal contract, which is used by users for self withdrawal, is available on Polygon and Arbitrum;

### LINKED ISSUE #12683: [Legitimate Site Blocked] floorchecker.com
https://floorchecker.com/

### LINKED ISSUE #12684: [Legitimate Site Blocked] analytics-zksync.vercel.app
https://analytics-zksync.vercel.app/

This is just a zksync analytics page. Users get spezialized data back, on the wallet address they input.

### PR DESCRIPTION
**Pull request by AlexHerman1**
fixes #12670 
fixes #12683
fixes #12684

### CODE REVIEW

**Comment by AlexHerman1** [comment]
fixes #12685

**Review by legobeat — APPROVED** [review]

**Comment by boanbb** [comment]
fixes https://github.com/MetaMask/eth-phishing-detect/issues/12670
Still not work, still be blocked
https://gpt-ai.io/

**Comment by boanbb** [comment]
Still not work
https://gpt-ai.io/

**Comment by boanbb** [comment]
The iOS system has recovered to normal, but the Android system and PC browser still do not work.

**Pull request merged**
