### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
Add scams - Pre dupe check
```
    "1inch.exchange.lineikata.eu",
    "anonymouscryptoexchange.com",
    "anonymouscryptoexchange.io",
    "app-uniswap.finance",
    "app-uniswap.money",
    "appuniswap.money",
    "coinbase-support-password-reseting826272666.top",
    "coinbase.earnfreecrypto.deals",
    "coinbase.reverify.id",
    "coinbase.yuyuhopamazon.com",
    "coinbaseserviceaccount.com",
    "dapps.roziermerge.site",
    "dpp-brdge.web.app",
    "ethereum-mixer.top",
    "exchange-biswap.com",
    "login.coinbase.idsverifys.com",
    "login.coinbase.verifyspassword.com",
    "meta-desk-4111msas.live",
    "meta-moretrades.com",
    "metamask.247ces.com",
    "metamask.io.merge.ifeoluwaajetomobi.xyz",
    "metamask.io.merge.platwise.com",
    "metamask.monster",
    "metamasks.biz",
    "officialtrustwallet.support",
    "offshorecryptowallets.com",
    "pancakedappswap.pankrestore.com",
    "pankrestore.com",
    "pancakeswao.finance",
    "pancakeswap-claims.com.do",
    "pancakeswap.finance.gochange-swap.in",
    "pancakeswap.finance.proceed-change.in",
    "pancakeswap.v3-finance.live",
    "pancakeswop.in",
    "roziermerge.site",
    "sushiswap.vision",
    "thesushiswap.xyz",
    "trustwallet-verify.crypto247mart.com",
    "trustwallet.com-dapp-network.win",
    "trustwallet.crypto247mart.com",
    "uni-swap.exchange",
    "uniswap-cap.com",
    "uniswap-cel.com",
    "uniswap-ecosystem.casa",
    "uniswap.direct",
    "uniswaperrs.com",
    "uniswapj.com",
    "uniswappool.org",
    "uniswaps.exchange",
    "uniswaps.money",
    "walletsconnectsyncs.web.app",
    "win-metamask.com",
    "wuniswap.top",
    "wvw-pancakesvvap.vip",
    "wvwvuniswap.top",
    "wvwvvuniswap.top",
```

```
 ./BurnTrash.sh | egrep "(result|url)"

  "result": "https://urlscan.io/result/105fc426-7f9f-43d2-baf8-9799c8a9ada1/",
  "url": "http://1inch.exchange.lineikata.eu",

  "result": "https://urlscan.io/result/652fff28-eea9-4754-b650-a3aae8f5fd11/",
  "url": "http://anonymouscryptoexchange.com",

  "result": "https://urlscan.io/result/31fd5da3-ef66-40e9-8b56-7ffbe0e5be1d/",
  "url": "http://anonymouscryptoexchange.io",

  "result": "https://urlscan.io/result/9a745f48-0fb4-4ee1-8db9-504ce0e987c9/",
  "url": "http://app-uniswap.finance",

  "result": "https://urlscan.io/result/9f060c9f-ae31-42a2-9b49-b6b035218efa/",
  "url": "http://app-uniswap.money",

  "result": "https://urlscan.io/result/2e453a21-19ed-4577-b718-e3a015100966/",
  "url": "http://appuniswap.money",

  "result": "https://urlscan.io/result/aa136cc7-f8ce-4452-b9aa-70647162f251/",
  "url": "http://coinbase-support-password-reseting826272666.top",

  "result": "https://urlscan.io/result/5df3ab0b-ac22-4d42-9478-3d8b4a624374/",
  "url": "http://coinbase.earnfreecrypto.deals",

  "result": "https://urlscan.io/result/fd4da780-7c55-4dee-870a-a0e7079600ac/",
  "url": "http://coinbase.reverify.id",

  "result": "https://urlscan.io/result/a30a12dd-37e1-4dff-b883-32ff943ff591/",
  "url": "http://coinbase.yuyuhopamazon.com",

  "result": "https://urlscan.io/result/92e47ad1-097a-4e33-9d4b-e9d0269b3100/",
  "url": "http://dapps.roziermerge.site",

  "result": "https://urlscan.io/result/98a4643b-2923-488f-bc4d-85fcced69a24/",
  "url": "http://dpp-brdge.web.app",

  "result": "https://urlscan.io/result/f134da06-8cef-4816-857c-0afeb321d380/",
  "url": "http://ethereum-mixer.top",

  "result": "https://urlscan.io/result/7f9c17d4-8787-4df3-9eab-f56e2fb817cb/",
  "url": "http://exchange-biswap.com",

  "result": "https://urlscan.io/result/4575c2b3-699e-470d-88e5-b9ffc1225f60/",
  "url": "http://login.coinbase.idsverifys.com",

  "result": "https://urlscan.io/result/841811f4-0252-40bd-809e-61e09c869dd2/",
  "url": "http://login.coinbase.verifyspassword.com",

  "result": "https://urlscan.io/result/fa2077f8-3c48-41b1-82bc-bf9a407c1eb6/",
  "url": "http://metamask.247ces.com",

  "result": "https://urlscan.io/result/f2403d0d-cb71-4b32-bf87-404b715284ac/",
  "url": "http://metamask.io.merge.ifeoluwaajetomobi.xyz",

  "result": "https://urlscan.io/result/92d06fea-a4a4-43e5-9921-208385b618d9/",
  "url": "http://metamask.io.merge.platwise.com",

  "result": "https://urlscan.io/result/64b13678-37dd-4f10-9b1c-ae545b4fbf93/",
  "url": "http://metamask.monster",

  "result": "https://urlscan.io/result/c7122029-e199-4d77-a353-3109e7f212ca/",
  "url": "http://metamasks.biz",

  "result": "https://urlscan.io/result/9dd4a62a-0f3b-4f73-8aab-daef9aaa2b2c/",
  "url": "http://officialtrustwallet.support",

  "result": "https://urlscan.io/result/f344ece4-81e4-4759-817a-a28145eaf9c5/",
  "url": "http://offshorecryptowallets.com",

  "result": "https://urlscan.io/result/235d4223-c250-43ce-85f9-537637fa7ea1/",
  "url": "http://pancakedappswap.pankrestore.com",

  "result": "https://urlscan.io/result/453f27a9-d3a3-4177-81b8-777773415781/",
  "url": "http://pankrestore.com",

  "result": "https://urlscan.io/result/e3d54848-bd47-4d1d-bfab-90a870c2c952/",
  "url": "http://pancakeswao.finance",

  "result": "https://urlscan.io/result/ffc7d4b9-4fe8-413f-a9b4-7dc12002377b/",
  "url": "http://pancakeswap-claims.com.do",

  "result": "https://urlscan.io/result/ca7e9672-bdd8-40ca-80c6-f26439b027df/",
  "url": "http://pancakeswap.finance.gochange-swap.in",

  "result": "https://urlscan.io/result/7c70488a-76c0-42f6-99d2-7f68a83e5230/",
  "url": "http://pancakeswap.finance.proceed-change.in",

  "result": "https://urlscan.io/result/37133072-40d3-42ba-91ae-a39895fd75b3/",
  "url": "http://pancakeswap.v3-finance.live",

  "result": "https://urlscan.io/result/79de96d8-f637-4155-bd13-06e2421283f3/",
  "url": "http://pancakeswop.in",

  "result": "https://urlscan.io/result/bbe7fa73-fb89-475e-bd2a-e33021a44650/",
  "url": "http://roziermerge.site",

  "result": "https://urlscan.io/result/a71d8612-a36d-42ac-87b9-f6f8f0d52b45/",
  "url": "http://sushiswap.vision",

  "result": "https://urlscan.io/result/2d25bf18-59e7-457e-820a-9593d2f5b772/",
  "url": "http://thesushiswap.xyz",

  "result": "https://urlscan.io/result/883a2282-0c3d-418d-b5b0-d8964f959480/",
  "url": "http://trustwallet-verify.crypto247mart.com",

  "result": "https://urlscan.io/result/58f63f07-3dd7-4c8b-bc2c-31523102c97f/",
  "url": "http://trustwallet.crypto247mart.com",

  "result": "https://urlscan.io/result/a973de37-d2ab-4e1a-9e04-d342a05759a7/",
  "url": "http://uni-swap.exchange",

  "result": "https://urlscan.io/result/fe1a6e36-7f8e-4455-992b-b8e7ba7b3a17/",
  "url": "http://uniswap-cel.com",

  "result": "https://urlscan.io/result/2a329391-b2cf-4493-9593-736b44d9fa48/",
  "url": "http://uniswap-ecosystem.casa",

  "result": "https://urlscan.io/result/18ee15aa-231d-4a19-9fde-f11c194c45b5/",
  "url": "http://uniswap.direct",

  "result": "https://urlscan.io/result/d908a244-c6da-4822-970d-155aaac0ac05/",
  "url": "http://uniswaperrs.com",

  "result": "https://urlscan.io/result/3175c63b-7347-4580-9b0c-54d2d1d4181c/",
  "url": "http://uniswapj.com",

  "result": "https://urlscan.io/result/95c0e3c8-37ec-4a99-adfb-3c4d410cfbaa/",
  "url": "http://uniswappool.org",

  "result": "https://urlscan.io/result/f0adcd76-afa5-4309-8719-abffdead1577/",
  "url": "http://uniswaps.exchange",

  "result": "https://urlscan.io/result/7402d409-55f1-40a7-bf46-7b3d5769f0de/",
  "url": "http://uniswaps.money",

  "result": "https://urlscan.io/result/ecf244b1-1fd3-4243-919d-7526e6c2fd4d/",
  "url": "http://walletsconnectsyncs.web.app",

  "result": "https://urlscan.io/result/9eb1fa91-a6b2-4310-bba1-4986e0e30939/",
  "url": "http://win-metamask.com",

  "result": "https://urlscan.io/result/8648db28-1816-4b3f-ad12-d6230a269760/",
  "url": "http://wuniswap.top",

  "result": "https://urlscan.io/result/245226f1-071a-47df-b2de-ed00a4842e9d/",
  "url": "http://wvw-pancakesvvap.vip",

  "result": "https://urlscan.io/result/eb29aa34-c77f-494b-aa3f-6488cc2b072b/",
  "url": "http://wvwvuniswap.top",

  "result": "https://urlscan.io/result/4b9108d9-91ea-430c-b124-104f515665c5/",
  "url": "http://wvwvvuniswap.top",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove FP
```
1inch.agency
```

Remove Duplicates

```
app-uniswap.finance
coinbase-support-password-reseting826272666.top
metamask.io.merge.ifeoluwaajetomobi.xyz
metamask.io.merge.platwise.com
metamask.monster
pancakeswap.finance.gochange-swap.in
uniswap.direct
uniswapj.com
uniswappool.org
wvw-pancakesvvap.vip
```

**Review by dubstard — COMMENTED** [review]
fix json

**Review by dubstard — COMMENTED** [review]
remove duplicate 
```
uniswappool.org
```

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks. New one incoming.

**Pull request merged**
