### PR TITLE
Add 224 domains to blocklist

### PR DESCRIPTION
**Pull request by BlockMageSec**
Feel free to inquire on methodology privately. 🧙‍♂️

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@BlockMageSec  thanks for the submission! Can you please fix the dupes?

**Comment by BlockMageSec** [comment]
> @BlockMageSec thanks for the submission! Can you please fix the dupes?

Done, should be all set now! I'll remember this next time - this happened due to my manual intervention after I realized the punycode domains in my prior commit had not been resolved fully.

**Comment by AlexHerman1** [comment]
@BlockMageSec  thanks, can you resolve the conflicts, its not allowing me to access your branch

**Comment by BlockMageSec** [comment]
@AlexHerman1 ok that should be resolved now as well, sorry for the delay.

**Comment by AlexHerman1** [comment]
still dupes :(

**Pull request closed without merging**
