### PR TITLE
Block 75 Scams Circle USDC 1:1 claims - continued

### PR DESCRIPTION
**Pull request by dubstard**
`I hate to brag, but damn I'm good.`
~Shaquille O’Neal

[⚠Scams are mirrored on URLSCAN with my tag](https://urlscan.io/search/#task.tags:%22spamreports%22)
```
    "1inch-app.co",
    "1inchswap.spaceapp-balancer.com",
    "airdrop-circle.com",
    "app-unisvvap.network",
    "approved-networks.live",
    "approved-ntworks.live",
    "arb-chain.com",
    "arbitrum.in",
    "balancer-build.top",
    "balancer-fi.info",
    "bridge.arbitrum.in",
    "case-coinbase.com",
    "chain-protocol.info",
    "circle-bonus.com",
    "circle-gifts.co",
    "circle.web3claim.network",
    "circle.web3claimer.net",
    "circleairdrops.org",
    "clrcleusdcswap.com",
    "coinbase-com.emotesoft.com",
    "coinbase-com.factmeta.com",
    "coinbase-com.fsrocha.com.br",
    "coinbase-com.kentinternationalconsulting.com",
    "coinbase-com.silvestri-international.com",
    "coinbase.top",
    "coinbase.users-verify.com",
    "cryptoai.website",
    "cryptocashdash.site",
    "dedeman.top",
    "daomaker.win",
    "dapp-resolver.netlify.app",
    "en-coinbase.cc",
    "go-coinbase.com",
    "gptcrypto.online",
    "kycprocess-metamask.ddns.net",
    "layers3.com",
    "liquistaking.netlify.app",
    "megametamask.com",
    "metamask.crcoinico.com",
    "metamaskpay.com",
    "metamasktrading.cc",
    "nft-porshe911.site",
    "nftclaim.chain-protocol.info",
    "optismchain.com",    
    "pancakeswap.biz",
    "pancakeswap.la",
    "pancakeswap.trading",
    "pancakeswape.org",
    "pancakeswvap.finance",
    "poll-1inch.io",
    "portfolio-metamask-enter.com",
    "portfolio-metamask-login.com",
    "portfolio-metamask-page.com",
    "portfolio-metamask-signin.com",
    "spaceapp-balancer.com",
    "safedapp.web.app",
    "trustwallet.isairdrop.com",
    "undo-coinbase.com",
    "unisvvap-trading.com",
    "uniswapp.co",
    "uniswapv.com",
    "unlswap.lol",
    "unlswap.online",
    "unlswap.pw",
    "unlswap.site",
    "unlswap.store",
    "usdtkraken.com",
    "walletconnectregistry.online",
    "web3claim.network",
    "web3claimer.net",
    "web3drop.net",
    "xrpevent589.org",
    "xrpstartnow.com",
    "xrpstartnow.org",
    "yourcoinbase.com",
```
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block 
```
    "airdrop-circle.com",
    "circle.web3claimer.net",
    "circle.web3claim.network",
    "web3claimer.net",
    "web3claim.network",
```

**Review by dubstard — COMMENTED** [review]
image

**Review by dubstard — COMMENTED** [review]
block daomaker.win

**Review by dubstard — COMMENTED** [review]
block safedapp.web.app
image
h/t https://twitter.com/malwrhunterteam for the lead

**Review by dubstard — COMMENTED** [review]
remove possible FP     "uniswap-smart-order-router-dev.defihelper.info",

The legitimate domain is defihelper.io
image

[however in the github of the original project i can see references towards this endpoint, so it seems OK](https://github.com/search?q=org%3Adefi-helper+defihelper.info&type=code)

**Review by dubstard — COMMENTED** [review]
block 
```
    "dapp-resolver.netlify.app",
    "liquistaking.netlify.app",
```
image

h/t https://twitter.com/malwrhunterteam for the lead

**Review by 409H — DISMISSED** [review]

**Review by 409H — APPROVED** [review]

**Pull request merged**
