### PR TITLE
Add new blacklist for the following scam website

### PR DESCRIPTION
**Pull request by btcgeo**
unilayerdrop.com

### CODE REVIEW

**Comment by btcgeo** [comment]
I am a core team member for the Unilayer project and this website was setup to scam users "to let them claim the GAIA airdrop" it asks users to connect their MM wallet and provide their seed. Please blacklist this website to prevent people from falling victim to this scam.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Review by ethphishingmaintainer1000 — CHANGES_REQUESTED** [review]
@btcgeo you need to resolve any conflicts and update your branch to merge cleanly with `master`. Once you do so, we can re-review and approve

**Comment by AlexHerman1** [comment]
closing this request. @btcgeo  please open a new PR.

**Pull request closed without merging**
