### PR TITLE
Block 89 scams

### PR DESCRIPTION
**Pull request by dubstard**
image
image
image
image

```
    "accesskyberswap.net",
    "coinbase-recovery.i6ew.services",
    "app-kyberswapusd.com",
    "app-restore-wallets.com",
    "awvwvvuniswap.top",
    "bakeryswap.gold",
    "balancer-dev36.8adm.com",
    "balancer.group",
    "balancer.jp",
    "balancer.ltd",
    "balancercoin.com",
    "bitmartlog.in",
    "coinbase-cold-wallet.com",
    "coinbase-verifications-accounts.i6ew.services",
    "coinbase-verifications-updates.i6ew.services",
    "coinbase-wallet.site",
    "coinbase-walletcoinext.com",
    "coinbase.accounts.y8th.services",
    "coinbasebankyyds.com",
    "coinbasecloud.es",
    "coinbasewallet.us",
    "connectapeswap.com",
    "dappcryptos.com",
    "dappradar.network",
    "expowallet.com",
    "freezywallet.com",
    "gateio-metamask.marketmaking.pro",
    "home-balancer.com",
    "homekyberswap.com",
    "kyberswap.cash",
    "kyberswapapp.tech",
    "kyberswapapp.xyz",
    "kyberswaps.cash",
    "metamask-app.us",
    "metamask-apps.com",
    "metamask-download.net",
    "metamask-extension-cji.pages.dev",
    "metamask-invest.com",
    "metamask-newslettre.com",
    "metamask-web.net",
    "metamask.com.tw",
    "metamask.io.darkside1337.my.id",
    "metamaskblockchain.com",
    "metamasks.eu",
    "metamasks.it",
    "metamasks.xyz",
    "opensea-giveaway.shop",
    "pancakesvvap.tech",
    "pancakeswapevs.finance",
    "pancakeswapsfinances.com",
    "pirate-nation.xyz",
    "review-coinbase.us-account.help",
    "secure-001-link-password-reset-coinbase.com",
    "secure-002-link-password-reset-coinbase.com",
    "smetamask.com",
    "sushiswap.club",
    "sushiswappay.com",
    "sushiswapv3.com",
    "swap-site-polygon.pages.dev",
    "swapdapps.com",
    "tinyman.space",
    "trustdapps-awards.site",
    "uniswap-exchangefinance.com",
    "uniswap-router.net",
    "uniswap-router.org",
    "uniswap-web3.org",
    "uniswap.eth1.one",
    "uniswap.openwallet.dev",
    "uniswap10001.eth1.one",
    "uniswap4.mxi.cloud",
    "uniswapclone.pages.dev",
    "uniswape.com.titans.pk",
    "uniswapechange.com",
    "uniswapfinance.exchange",
    "uniswapsexchange.org",
    "walletsconnected.com",
    "walletsupport.ga",
    "walletsupport.gq",
    "walletsupport.cf",
    "walletsupport.ml",
    "walletsupport.tk",
    "www-sushiswap-com.cf",
    "www-sushiswap-com.ga",
    "www-sushiswap-com.gq",
    "www-sushiswap-com.ml",
    "www-sushiswap-com.tk",
    "xn--ft-q3s.com",
    "xn--fx-rta.com",
    "xn--fx-s0s.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
```
    "awvwvvuniswap.top",
```

**Comment by AlexHerman1** [comment]
@dubstard  can you fix the dupes

**Comment by dubstard** [comment]
Hm. There were no duplicates when i raised it, weird. One moment.

**Comment by dubstard** [comment]
Ah now i understand. Somebody added the FTX Punycode's after my PR, but theirs got merged faster, thus making mine have duplicates, which it previously didn't have.

**Review by dubstard — COMMENTED** [review]
Remove FTX IDN homoglyph duplicates
```
xn--fx-s0s.com
xn--fx-rta.com
xn--ft-q3s.com
```

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks boss, new one incoming

**Pull request merged**
