### PR TITLE
Add DappRadar phishing websites

### PR DESCRIPTION
**Pull request by dragosdydy**
Most of these are phishing links sponsored at the top of Google results

### CODE REVIEW

**Review by 409H — CHANGES_REQUESTED** [review]
please make the edits in `./src/config.json` instead https://github.com/MetaMask/eth-phishing-detect/blob/main/src/config.json

**Comment by dragosdydy** [comment]
Done, thanks. Let me know if this is ok.

**Comment by AlexHerman1** [comment]
@dragosdydy  can you remove the edits to the hosts file please

**Comment by AlexHerman1** [comment]
@dragosdydy  these domains no longer resolve so I'm going to close this for now. thanks for the submission though!

**Pull request closed without merging**
