### PR TITLE
Block 36 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
killed the fake Balancer copycats already, blocking just in case of domain recycle.
image

```	"0-metemask.com",
    "1-metemask.com",
    "2-metemask.com",
    "airdrop-unidex.com",
    "app-1inch.org",
    "balancerl.org",
    "balancerv.org",
    "collab.land-join.com",
    "finspad.top",
    "gigaswap-airdrop.org",
    "gigaswapairdrops.org",
    "import-metemask.com",
    "inc-metemask.com",
    "kyc-954-metamask-logo.verilabs.co",
    "land-join.com",
    "metamask-auth.onrender.com",
    "metamask-eth.com",
    "metamask-verification-processs.com",
    "metamask.argilos.site",
    "metamasksoft.tech",
    "metemask-app.com",
    "metemask-ens.com",
    "metemask-inc.com",
    "now-metemask.com",
    "opensia-nft.com",
    "redirok-two.com",
    "securechainlinkk.com",
    "seedify-pad.online",
    "sudoswap-airdrop.org",
    "sudoswap-airdrops.org",
    "the-metemask.com",
    "uniswape.net",
    "uniswapo.net",
    "up-metemask.com",
    "verif-metemask.com",
    "wl-collabland.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block METE mask scams 🤡
h/t Milan
```
    "0-metemask.com",
    "1-metemask.com",
    "2-metemask.com",
    "import-metemask.com",
    "inc-metemask.com",
    "metemask-app.com",
    "metemask-ens.com",
    "metemask-inc.com",
    "now-metemask.com",
    "redirok-two.com",
    "the-metemask.com",
    "up-metemask.com",
    "verif-metemask.com",
```
image

**Review by dubstard — COMMENTED** [review]
image
image

block
```
    "gtcpro.space",
    "dex-carlivechain.web.app",
```

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
thanks

**Pull request merged**
