### PR TITLE
Block 212 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
Fake 1inch, Arbitrum, Blur, Coinbase, Compound, Gemini, Metamask, Pancakeswap, Uniswap, Ledger wallet (MANY!), YFI, others.

As usual all scams are [mirrored on UrlScan](https://urlscan.io/search/#task.tags:%22spamreports%22) with my tag.

`To be successful in bodybuilding, you have to be a good observer.` 
~Frank Zane
```
    "1inch-crypto.com",
    "1inch-drop.com",
    "1inch.logininister.site",
    "account.metamask.io.produsenkawatbronjong.com",
    "accounthelper-coinbase.com",
    "accountresolvesapp.webflow.io",
    "airdrop.erredj.duckdns.org",
    "airdropsalertdapp.com",
    "airdropsalerts-dapp.com",
    "aplxaz.com",
    "app-txidcontract.com",
    "apskca.com",
    "arbitums-foundation.com",
    "artandcraftz.xyz",
    "artbitrum.com",
    "ascuuhzx.com",
    "asijxal.com",
    "asijxaz.com",
    "asixca.com",
    "asokxa.com",
    "asoxkasl.com",
    "aspxlzasl.com",
    "aszlxspwa.com",
    "ausdux.com",
    "autoswapgallery.tech",
    "avouch-sync.info",
    "axopksaz.com",
    "azpoaz.com",
    "balancers.pro",
    "bbrc.io",
    "bdogedefi.com",
    "beeemmiigrate.xyz",
    "bhbjkkl.com",
    "bjokabc.com",
    "blockbug.live",
    "centrecosistem.store",
    "chatgpt4token.com",
    "chatgpt4token.com.bdogedefi.com",
    "claim.usdc.repl.co",
    "clyptogpt.com",
    "coinbase.com-help.id",
    "coinbase.computersarehard.com",
    "coinbase.sercurecoins.com",
    "coinbase63.com",
    "coinbase649.zendesk.com",
    "coinbase9370.zendesk.com",
    "coinbasecz.com",
    "coinbasetransactions.org",
    "com-0x9.xyz",
    "connectionapprovals.com",
    "connectrectify.site",
    "coompound.org",
    "coumpound.com",
    "cryptokey.site",
    "cryptolink.live",
    "cryptospad.io",
    "cspodfxzkl.com",
    "dallebitbridge.xyz",
    "dapp-to-connect.netlify.app",
    "dapps.manualbridgevalidate.online",
    "dappsfix.pages.dev",
    "dappsfortune.netlify.app",
    "defiapess.xyz",
    "deficonnect.cloud",
    "diofiodp.com",
    "dsodkca.com",
    "duishak.com",
    "eth-app.site",
    "ethereum-launchpad.xyz",
    "exchange.pancakeswap.finances.informecruzonline.com.br",
    "exchange.pancakeswap.finances.snk-iq.com",
    "fgjxkap.com",
    "firstreplycus.online",
    "fixwallet.app",
    "foundation-arbitrum.xyz",
    "freeblur.com",
    "giogoij.com",
    "giveaway-claim-rewards.com",
    "globalapps.site",
    "hasndja.com",
    "incoinbasese.com",
    "infocusdesign.ca",
    "io-srt777.cloud",
    "ixizox.com",
    "jdkop.com",
    "jfjxoal.com",
    "jlkmklhbl.com",
    "kyc.account.metamask.io.produsenkawatbronjong.com",
    "ledger.live-newupdates.com",
    "lido.bio",
    "live-newupdates.com",
    "liveprotocols.net",
    "ljsdklsd.com",
    "logcoinbaseauth.com",
    "login-auth-coinbase.com",
    "login-coinbase.biz",
    "login-coinbase.ltd",
    "login-coinbase.net",
    "login-confirmation-coinbase.com",
    "login-financial-coinbase.com",
    "login-manage-coinbase.com",
    "login-myaccount-coinbase.com",
    "login-withdrawal-coinbase.com",
    "login.coinbase.authsecurefund2579923573.com",
    "maingatesync.co",
    "mainnethubapis.live",
    "mainnetnetworks.org",
    "manualbridgevalidate.online",
    "metamask-protect.com",
    "metamask-protect.net",
    "metamask-uniswap.web.app",
    "metamask-verify.com-0x9.xyz",
    "metamask-verifyprotocol.net",
    "metamask.io-1s2r.io-srt777.cloud",
    "metamask1.buzz",
    "metamask1.icu",
    "metamask1.top",
    "metamaskupgrade.online",
    "metamassk.app",
    "mmetawallet.dynip.online",
    "multichain-app.netlify.app",
    "muskcryptos.net",
    "neutra.netlify.app",
    "nws-hazssfhjwqwz.com",
    "online-verifylogauth.com",
    "ooapsza.com",
    "oweidop.com",
    "pancakeswap.finances.informecruzonline.com.br",
    "pancakeswap.finances.plumbersinpontyclunrhonddacynontaff.com",
    "pancakeswap.finances.snk-iq.com",
    "pancakeswapinc.com",
    "pancakeswapsdefi.com",
    "pancakeswapv3.finance",
    "pay.metamassk.app",
    "pkapksla.com",
    "produsenkawatbronjong.com",
    "profile96.com",
    "projectrxnegade.com",
    "projectsnetfix.com",
    "protocoldapps.firebaseapp.com",
    "rapidrectifier.online",
    "recovery-coinbase.info",
    "redirect.ocoinbase.com",
    "ref-7472829.com",
    "repairvault.onrender.com",
    "salskjkjcaas.com",
    "sc-coinbase.com",
    "secure-coinbase.net",
    "secure-exodus.com",
    "secure-manage-coinbase.com",
    "secure-signin-page-colnbase-01.cleansite.us",
    "secure-signin-page-colnbase-02.cleansite.info",
    "secure2-coinbase.info",
    "secure2-financial-coinbase.com",
    "securecryptodefi.com",
    "shsaza.com",
    "signin-coinbase.biz",
    "signin-coinbase.net",
    "soliditywork.pages.dev",
    "sonar-watch.com",
    "sonarwwatch.com",
    "sterlingcaptcha.tech",
    "swapredirect.online",
    "system.join-guild.info",
    "thecrypto-nftcorpltd.com",
    "theprojectmainnet.live",
    "tokenconnects.network",
    "tradingsignalsdirectlt.com",
    "trustappaidofficials.trustedappaid.store",
    "trustwallet-connect.econtablesegui.online",
    "uniswap-2.org",
    "uniswap-on-ic.icu",
    "uniswap-on-ic.top",
    "uniswap-system.com",
    "uniswap.v2-6.org",
    "uniswapgpt.com",
    "upgrademetamask.tech",
    "usdc.claimz.repl.co",
    "usdc.holdings",
    "vault-metamask.com",
    "verify-coinbase.biz",
    "verify-coinbase.info",
    "verify.trutswallet.com.permnit.xyz",
    "verify.trutswallet.com.yousee-dkis.click",
    "vgvjapx.com",
    "vlaunchconnect.com",
    "vuiciso.com",
    "walletconnecthub.com",
    "wcdapps.pages.dev",
    "web.vaultnet.site",
    "wencoinbase.com",
    "weodpsokql.com",
    "withdrawal2-coinbase.com",
    "withdrawalhistory-coinbase.com",
    "www-exchange-gemini.com",
    "x-coinbase.info",
    "xaozlasa.com",
    "xasoiz.com",
    "xaspoic.com",
    "xaszoxias.com",
    "xdaxdaae.com",
    "xjaoz.com",
    "xjoaksl.com",
    "xn--optmsm-6va.net",
    "xoaplasz.com",
    "xzxzla.com",
    "yearnfi.dapp-web3.com",
    "yearnfi.web3dapp.org",
    "zerobeings.app",
    "zoapoxka.com",
    "zoapska.com",
    "zxsiaskd.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupes
```
"1inch.exchange.blazingblade.pk"
"aipadtech.pages.dev"
"app.blurswaps.com"
"app.blurswaps.uk"
"aribtrum.foundation"
"blur-marketplace.io"
"blurswaps.com"
"blurswaps.uk"
"coinbanko.club"
"coinbase24.com"
"coinbasecashgiveaway.finance.blog"
"ethereum-merge.cloud"
"geminionusdc.com"
"metamask.co.zw"
"metamask.fmg.co.zw"
"metamask.io.merge.artandcraftz.xyz"
"metamask.io.produsenkawatbronjong.com"
"metamask.nordgroup.io"
"metamask.productions"
"metamask1.io"
"newmetamask.io"
"pancakeswapcode.financialmarketsworld.com"
"protocoldapps.web.app"
"service-metamask.io"
"signs-repo.com"
"the-bitcointrendapp.financialmarketsworld.com"
"the-bitcointrendapp.newfinancialmarketworld.com"
"trustwallet.com.verifycation.required.sgldesign.com.au"
"uniswap-on-ic.xyz"
"web3sdk.io"
```

**Review by dubstard — COMMENTED** [review]
block "metamask-uniswap.web.app",

h/t malwrhunterteam (https://twitter.com/malwrhunterteam)

**Review by dubstard — COMMENTED** [review]
scams
```
    "live-newupdates.com",
    "ref-7472829.com",
    "profile96.com",
    "dapps.manualbridgevalidate.online",
    "metamask.io-1s2r.io-srt777.cloud",
    "metamask-verify.com-0x9.xyz",
    "com-0x9.xyz",
    "io-srt777.cloud",
    "manualbridgevalidate.online",
    "online-verifylogauth.com",
    "bdogedefi.com",
    "chatgpt4token.com.bdogedefi.com",
    "chatgpt4token.com",
```

**Review by dubstard — COMMENTED** [review]
block neutra.netlify.app
h/t malwrhunterteam (https://twitter.com/malwrhunterteam)
https://urlscan.io/search/#filename:%22drainer.js%22

**Comment by 409H** [comment]
`git diff --ignore-all-space main patch-188 -- src/config.json`

```
diff --git a/src/config.json b/src/config.json
index d7316348..2f42ceb8 100644
--- a/src/config.json
+++ b/src/config.json
@@ -963,6 +963,218 @@
     "ipfs.io"
   ],
   "blacklist": [
+    "live-newupdates.com",
+    "neutra.netlify.app",
+    "ref-7472829.com",
+    "profile96.com",
+    "dapps.manualbridgevalidate.online",
+    "metamask.io-1s2r.io-srt777.cloud",
+    "metamask-verify.com-0x9.xyz",
+    "com-0x9.xyz",
+    "io-srt777.cloud",
+    "manualbridgevalidate.online",
+    "online-verifylogauth.com",
+    "bdogedefi.com",
+    "chatgpt4token.com.bdogedefi.com",
+    "chatgpt4token.com",
+    "metamask-uniswap.web.app",
+    "1inch-crypto.com",
+    "1inch-drop.com",
+    "1inch.logininister.site",
+    "account.metamask.io.produsenkawatbronjong.com",
+    "accounthelper-coinbase.com",
+    "accountresolvesapp.webflow.io",
+    "airdrop.erredj.duckdns.org",
+    "airdropsalertdapp.com",
+    "airdropsalerts-dapp.com",
+    "aplxaz.com",
+    "app-txidcontract.com",
+    "apskca.com",
+    "arbitums-foundation.com",
+    "artbitrum.com",
+    "ascuuhzx.com",
+    "asijxal.com",
+    "asijxaz.com",
+    "asixca.com",
+    "asokxa.com",
+    "asoxkasl.com",
+    "aspxlzasl.com",
+    "aszlxspwa.com",
+    "ausdux.com",
+    "autoswapgallery.tech",
+    "avouch-sync.info",
+    "axopksaz.com",
+    "azpoaz.com",
+    "balancers.pro",
+    "bbrc.io",
+    "beeemmiigrate.xyz",
+    "bhbjkkl.com",
+    "bjokabc.com",
+    "blockbug.live",
+    "centrecosistem.store",
+    "claim.usdc.repl.co",
+    "clyptogpt.com",
+    "coinbase.com-help.id",
+    "coinbase.computersarehard.com",
+    "coinbase.sercurecoins.com",
+    "coinbase63.com",
+    "coinbase649.zendesk.com",
+    "coinbase9370.zendesk.com",
+    "coinbasecz.com",
+    "coinbasetransactions.org",
+    "connectionapprovals.com",
+    "connectrectify.site",
+    "coompound.org",
+    "coumpound.com",
+    "cryptokey.site",
+    "cryptolink.live",
+    "cryptospad.io",
+    "cspodfxzkl.com",
+    "dallebitbridge.xyz",
+    "dapp-to-connect.netlify.app",
+    "dappsfix.pages.dev",
+    "dappsfortune.netlify.app",
+    "defiapess.xyz",
+    "deficonnect.cloud",
+    "diofiodp.com",
+    "dsodkca.com",
+    "duishak.com",
+    "eth-app.site",
+    "ethereum-launchpad.xyz",
+    "exchange.pancakeswap.finances.informecruzonline.com.br",
+    "exchange.pancakeswap.finances.snk-iq.com",
+    "fgjxkap.com",
+    "firstreplycus.online",
+    "fixwallet.app",
+    "foundation-arbitrum.xyz",
+    "freeblur.com",
+    "giogoij.com",
+    "giveaway-claim-rewards.com",
+    "globalapps.site",
+    "hasndja.com",
+    "incoinbasese.com",
+    "infocusdesign.ca",
+    "ixizox.com",
+    "jdkop.com",
+    "jfjxoal.com",
+    "jlkmklhbl.com",
+    "kyc.account.metamask.io.produsenkawatbronjong.com",
+    "ledger.live-newupdates.com",
+    "lido.bio",
+    "liveprotocols.net",
+    "ljsdklsd.com",
+    "logcoinbaseauth.com",
+    "login-auth-coinbase.com",
+    "login-coinbase.biz",
+    "login-coinbase.ltd",
+    "login-coinbase.net",
+    "login-confirmation-coinbase.com",
+    "login-financial-coinbase.com",
+    "login-manage-coinbase.com",
+    "login-myaccount-coinbase.com",
+    "login-withdrawal-coinbase.com",
+    "login.coinbase.authsecurefund2579923573.com",
+    "maingatesync.co",
+    "mainnethubapis.live",
+    "mainnetnetworks.org",
+    "metamask-protect.com",
+    "metamask-protect.net",
+    "metamask-verifyprotocol.net",
+    "artandcraftz.xyz",
+    "metamask1.buzz",
+    "metamask1.icu",
+    "metamask1.top",
+    "metamaskupgrade.online",
+    "metamassk.app",
+    "mmetawallet.dynip.online",
+    "multichain-app.netlify.app",
+    "muskcryptos.net",
+    "nws-hazssfhjwqwz.com",
+    "ooapsza.com",
+    "oweidop.com",
+    "pancakeswap.finances.informecruzonline.com.br",
+    "pancakeswap.finances.snk-iq.com",
+    "pancakeswap.finances.plumbersinpontyclunrhonddacynontaff.com",
+    "pancakeswapinc.com",
+    "pancakeswapsdefi.com",
+    "pancakeswapv3.finance",
+    "pay.metamassk.app",
+    "pkapksla.com",
+    "produsenkawatbronjong.com",
+    "projectrxnegade.com",
+    "projectsnetfix.com",
+    "protocoldapps.firebaseapp.com",
+    "rapidrectifier.online",
+    "recovery-coinbase.info",
+    "redirect.ocoinbase.com",
+    "repairvault.onrender.com",
+    "salskjkjcaas.com",
+    "sc-coinbase.com",
+    "secure-coinbase.net",
+    "secure-exodus.com",
+    "secure-manage-coinbase.com",
+    "secure-signin-page-colnbase-01.cleansite.us",
+    "secure-signin-page-colnbase-02.cleansite.info",
+    "secure2-coinbase.info",
+    "secure2-financial-coinbase.com",
+    "securecryptodefi.com",
+    "shsaza.com",
+    "signin-coinbase.biz",
+    "signin-coinbase.net",
+    "soliditywork.pages.dev",
+    "sonar-watch.com",
+    "sonarwwatch.com",
+    "sterlingcaptcha.tech",
+    "swapredirect.online",
+    "system.join-guild.info",
+    "thecrypto-nftcorpltd.com",
+    "theprojectmainnet.live",
+    "tokenconnects.network",
+    "tradingsignalsdirectlt.com",
+    "trustappaidofficials.trustedappaid.store",
+    "trustwallet-connect.econtablesegui.online",
+    "uniswap-2.org",
+    "uniswap-on-ic.icu",
+    "uniswap-on-ic.top",
+    "uniswap-system.com",
+    "uniswap.v2-6.org",
+    "uniswapgpt.com",
+    "upgrademetamask.tech",
+    "usdc.claimz.repl.co",
+    "usdc.holdings",
+    "vault-metamask.com",
+    "verify-coinbase.biz",
+    "verify-coinbase.info",
+    "verify.trutswallet.com.permnit.xyz",
+    "verify.trutswallet.com.yousee-dkis.click",
+    "vgvjapx.com",
+    "vlaunchconnect.com",
+    "vuiciso.com",
+    "walletconnecthub.com",
+    "wcdapps.pages.dev",
+    "web.vaultnet.site",
+    "wencoinbase.com",
+    "weodpsokql.com",
+    "withdrawal2-coinbase.com",
+    "withdrawalhistory-coinbase.com",
+    "www-exchange-gemini.com",
+    "x-coinbase.info",
+    "xaozlasa.com",
+    "xasoiz.com",
+    "xaspoic.com",
+    "xaszoxias.com",
+    "xdaxdaae.com",
+    "xjaoz.com",
+    "xjoaksl.com",
+    "xn--optmsm-6va.net",
+    "xoaplasz.com",
+    "xzxzla.com",
+    "yearnfi.dapp-web3.com",
+    "yearnfi.web3dapp.org",
+    "zerobeings.app",
+    "zoapoxka.com",
+    "zoapska.com",
+    "zxsiaskd.com",
     "zyber-swap.com",
     "liquityprotocol.co",
     "pangolinexhange-help.com",
```

**Review by 409H — APPROVED** [review]

**Comment by renshawdev** [comment]
@dubstard Please can you explain the reason and source for `projectrxnegade.com` being added to the blacklist?

**Pull request merged**
