### PR TITLE
Add phishing sites to blocklist [2]

### PR DESCRIPTION
**Pull request by onyourlife**
Hello. Below websites are phishing sites that abuse NFT airdrops. Request to block.
https://www.kbo-kbollect.com/
https://www.kbo-kbollect.online/

scam

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@onyourlife  thanks for the sub! What phishing method do these sites use?

**Comment by onyourlife** [comment]
> @onyourlife thanks for the sub! What phishing method do these sites use?

The attacker send phishing emails to anyone in Korea. The email contents is that KBO(Korea Baseball Organization) give you NFT airdrops. If user clicks a link on email, It moves to the phishing website(https://www.kbo-kbollect.com, https://www.kbo-kbollect.online). Then user connect their blockchain wallet(metamask, kaikas, etc.) to phishing website. The website check balance on user accounts. If user has crypto asset, the attacker asks for transaction approval. The transaction content is as follows:

approve(attacker address, 1,000,000,000,000,000,000)

[ calldata ]
0x095ea7b3000000000000000000000000attacker_address0000000000000000000000000000000000000000000000000de0b6b3a7640000

There are about 1,300 victims who approved this transaction. The attacker continusly make new sites such as Starbuck, KBO, Korean Air, etc. These websites have the same attack method.

Please block the two websites to reduce the phishing victims in Korea.
(https://www.kbo-kbollect.com, https://www.kbo-kbollect.online)

**Comment by AlexHerman1** [comment]
thank you for the explanation!

**Review by onyourlife — COMMENTED** [review]
There are misspelled. So code is updated.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
