### PR TITLE
Adding sublime.finance to the blacklist

### PR DESCRIPTION
**Pull request by Tgemayel**
Updating the blacklist to protect from ongoing prediction market phishing attack

phishing

### CODE REVIEW

**Comment by AlexHerman1** [comment]
hi, can you please clarify what phishing attack is occurring?

**Comment by leapoly** [comment]
@AlexHerman1  Both fake sites are imitating this real site https://polymarket.com/

**Comment by Tgemayel** [comment]
@AlexHerman1 As @leapoly stated, its a fake prediction market that drains a users funds when they connect their wallet

**Comment by AlexHerman1** [comment]
thanks, blocked it in another pull. will close this now.

**Pull request closed without merging**
