### PR TITLE
Remove site from blocklist

### PR DESCRIPTION
**Pull request by legobeat**
Originally added in #10655

@AlexHerman1 @Nick-Son PTAL

Opened issues include #10850 #10851 #10852 #10854 #10855 #10856 #10858 #10860 #10861 #10862 #10863 #10864 #10865 #10866 #10867 #10868 #10869 #10870 #10871 #10872 #10873 #10874 #10875 #10876 #10878 #10879 #10880 #10881 #10882 #10884 #10888 #10896 #10897 #10898 #10899 #10900 #10901 #10902 #10903 #10904 #10905 #10906 #10907 #10908 #10909 #10910 #10911 #10912 #10913 #10914 #10915 #10916 #10917 #10918 #10919 #10920 #10921 #10922 #10923 #10924 #10925 #10926 #10927 #10928 #10929 #10930 #10931 #10932 #10933 #10934 #10935 #10936 #10937 #10938 #10939 #10940 #10941 #10943 #10944 #10945 #10946 #10947 #10948 #10949 #10950 #10951 #10952 #10953 #10954 #10955 #10956 #10957 #10958 #10959 #10960 #10961 #10962 #10963 #10964 #10965 #10966 #10967 #10968 #10969 #10970 #10971 #10972 #10973 #10974 #10975 #10976 #10977 #10978 #10979 #10980 #10981 #10982 #10983 #10984 #10985 #10986 #10987 #10988 #10989 #10990 #10991 #10992 #10993 #10994 #10995 #10996 #10997 #10998 #10999 #11000 #11001 #11003 #11004 #11005 #11006 #11007 #11008 #11009 #11010 #11011 #11012 #11013 #11014 #11015 #11016 #11017 #11018 #11019 #11020 #11021 #11022 #11023 #11024 #11025 #11026 #11027 #11170 #11171 #11172

Submitters: Please stop opening duplicate issues. It's disruptive, against GitHub rules, and does not help prioritization

### CODE REVIEW

**Comment by Paradox008** [comment]
Remove bep faucet from Blocklist it is legit site

**Comment by JimmiAugust** [comment]
😊

**Comment by BKhan213** [comment]
Dear Admin
Keep up the good job, only 'all jobs pass' is required,

**Comment by javedhak** [comment]
please unblock legitsite bepfacout

**Comment by RAFAGARSEG** [comment]
Remove bep faucet from Blocklist it is legit site

**Comment by JimmiAugust** [comment]
Please remove from Blocklist, i can make about 4$/day by this site, from the day you guys block it, i can't make money 😔

**Comment by Mnb34** [comment]
please 🙏🙏🙏🙏

**Comment by Gamingbro123** [comment]
@AlexHerman1 please help us by approving this

**Comment by AlexHerman1** [comment]
We are not removing this site from the blocklist, if you continue to spam our repo action will be taken.

This site is a scam, it calls itself a "faucet", which it is not, and although it mentions nothing about depositing anything it calls for an approval for your tokens. It will not be removed from the list.

**Comment by Gamingbro123** [comment]
@AlexHerman1 please sir!! try to understand 
It is just a gas fee
They don't take our money

**Comment by Gamingbro123** [comment]
@AlexHerman1 I thought you are a good man but you broke my heart

**Comment by Gamingbro123** [comment]
@AlexHerman1 Please it is a legit site!!

**Comment by Gamingbro123** [comment]
@legobeat please help

**Comment by Gamingbro123** [comment]
@AlexHerman1 please man!! it is my only source of income

**Comment by Gamingbro123** [comment]
@AlexHerman1 don't be so rude

**Comment by JimmiAugust** [comment]
See this ?

**Comment by JimmiAugust** [comment]
Shame on you guys.

**Comment by Lukewor** [comment]
Please bro-faucet is not a scam
Please remove it from black list

**Comment by Gamingbro123** [comment]
@legobeat create a new pull request

**Comment by JimmiAugust** [comment]
This is bullshit, created so many accounts then get ban by admin. And now revenge by report Bepfaucet, shame on you guys, fuck all cheating, fuck github.

**Comment by bin786** [comment]
@AlexHerman1 can you give me proof BEP-Faucet scam member tell me i am waiting your reply only give me proof he scam

**Comment by bin786** [comment]
legobeat you give me proof BEP-Faucet scam member

**Comment by bin786** [comment]
@Nick-Son sir BEP-Faucet not scam member he give free withdraw daily i am work 18 days and earn 150$ please sir can you have any proof for scam then send me i check how BEP-Faucet scsm

**Comment by JimmiAugust** [comment]
Unfair for bep-faucet, shame on github by have some people like you guys.

**Comment by JimmiAugust** [comment]
> We are not removing this site from the blocklist, if you continue to spam our repo action will be taken.
> 
> This site is a scam, it calls itself a "faucet", which it is not, and although it mentions nothing about depositing anything it calls for an approval for your tokens. It will not be removed from the list.

**Comment by JimmiAugust** [comment]
> We are not removing this site from the blocklist, if you continue to spam our repo action will be taken.
> 
> This site is a scam, it calls itself a "faucet", which it is not, and although it mentions nothing about depositing anything it calls for an approval for your tokens. It will not be removed from the list.

**Comment by JimmiAugust** [comment]
> We are not removing this site from the blocklist, if you continue to spam our repo action will be taken.
> 
> This site is a scam, it calls itself a "faucet", which it is not, and although it mentions nothing about depositing anything it calls for an approval for your tokens. It will not be removed from the list.

**Comment by joeywhite007** [comment]
This Site is not scam because it pays it's users, the very minute fee being charged for transactions is called a gas fee which is normal in the Crypto Space. Please unblock Bep-Faucet..

**Comment by Demolator1987** [comment]
On the same principle, after all, many dapps work, except that to earn you have to put a lot of tokens and I'm talking about projects such as spacemining or smartmining, except that it is best to put 0.5BNB there and reinvest every day additionally paying gas for a smart contract. Now let the metamask team analyze what could be a bigger scam. Because the maximum on Bep-Faucet our fee was $ 0.36 with a real profit of $ 3 per day and regular payments of min $ 6 every 48 hours

**Comment by JerryMazter** [comment]
BEP faucet is a legitimate site that pays out
rewards without any issues. A few users violated the rules by creating multiple accounts and got blocked. They reported the site as phishing//malicious as revenge.
I double checked and the domain is not listed on cryptoscamdb but it appears to be on the blacklist from the src/config. Json
I kindly request that GitHub admins remove this domain from the from the phishing list.

**Comment by NhanNguyen010899** [comment]
https://bscscan.com/address/0x072069da827fc398f381810150e5a21f01280509

**Comment by NhanNguyen010899** [comment]
I don't know why this site on blacklist, but i really make some cash by this site 😄 Github, you're wrong !

**Pull request closed without merging**
