### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
add scams to blacklist:

Not the 1inch you need
```
		"1inch-bake.org",
		"1inch.exchange.assetsmantra.com",
		"1inch.exchenge.app",
		"eth-v2-1inch.io",
		"eth-v2-1inch.io.eth-1inch.io",
```

Not the Spookyswap you need
```
		"access-spooky-swap.net",
		"connectspookyswap.com",
```

Not the Quickswap you need
```
		"app-quickswap.exchange",
```

Not the Binance you need
```
		"binance-exchange.icu",
		"binance-exchange.org",
		"binance-exchange.site",
		"binance-exchange.vhost140096.cpsite.ru",
```

Not the Coinbase you need
```
		"coinbase-request.com",
		"coinbase-support-update.hillsideinnkuttikkanam.com",
		"coinbase-verifying.serveirc.com",
		"coinbase.com.secure-auth.cb-recover.com",
		"coinbase.com.secure-auth.charter-sso.net",
		"coinbase.com.secure-auth.sessionid091622.app",
		"coinbase.com.secure-auth.sessionid091722.app",
		"coinbasemobile.pages.dev",
		"coinbasepay.co",
		"coinbasesignin.aut-sig.com",
		"coinbasewallet-mining.com",
		"logged-support-coinbase.com",
		"update-coinbase.com",
		"ww17.coinbaseorigin-connect2.kohlz.com",
		"secure-coinbase.io",
		"signin.coinbase-verify-instans.com",
		"signln.coinbase-verify-instans.com",
```

Not the WalletConnect you need
```
		"dappverifymainnet.online",
		"dappverifymainnet.valiblockchains.site",
```
	
Not the Elon Musk Defi (lol) you need
```
		"elondefi.com",
```

Not the ETH Merge "giveaways" you need
```
		"ethereum-drop.net",
		"ethereum-giving.com",
		"ethereum-giving.info",
		"ethereum-post.us",
		"ethereum-x2.info",
		"ethereum2-merge.info",
		"ethereumerges-2x.com",
		"ethereumerges-x2.com",
```

Not the Curve fi you need
```
		"exchange.curve-fi.finance",
		"exchange.curves-fi.finance",
		"exchange.curves-finance.com",
```

Not the MetaMask you need
```
		"metamask-tech.com",
		"metamask.com.in",
		"metamask.community-idd24.bond",
		"metamask.connect-vault-en.site",
		"metamask.ersinkoc.com",
		"metamask.it",
		"metamask.services-money91.com",
		"metamask.timeimprint.com",
		"metamaskinfo.com",
		"metamasknbitmask.com",
		"metamaskonline.net",
		"metamasksvalidator.com",
		"nftmetamask.com",
		"rewardmetamask.com",
		"send.metamask.gifts",
```

Not the Sushiswap you need		
```
		"pancakeswap-apli.com",
		"pancakeswap-ship.com",
		"pancakeswapstake.one",
		"pancakeswip.com",
```

Not the Paraswap you need
```
		"paraswap-capitalo.com",
```

Not the Sushiswap you need
```
		"sushiswap-app.exchange",
```

Not the Trustwallet you need
```
		"trustwallet-verification-protocol.com",
```

Not the Uniswap you need
```
		"admin.uniswapv3-s.com",
		"uniswap.air-drop.org",
		"uniswap.alwayscare.org",
		"uniswap.cafe",
		"uniswap.link",
		"uniswap.neuroguts.com",
		"uniswap.tips",
		"uniswap.trade",
		"uniswap1.workers.dev",
		"uniswapapi.com",
		"uniswapapp.finance",
		"uniswape.org.desmar.cl",
		"uniswapp.alwayscare.org",
		"uniswapp.justtechnologiessl.com",
		"uniswapv3-s.com",
		"kefu.uniswapv3-s.com",
		"usdtv2.uniswap.team",
		"uuniswap.justtechnologiessl.com",
		"peak.uniswap.team",
```

Not the Uphold you need
```
		"wallet-uphold-oc.cf",
		"wallet.worldcryptocarenci.site",

```

Not the Metaverse you need
```
		"nftverse.sbs",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove FP 		"occam-xairdropclaim.fi",

**Review by dubstard — COMMENTED** [review]
add scam google forms
(legitimate service used for illicit purposes)
```
		"https://docs.google.com/forms/d/e/1FAIpQLSfWcSqiPHXb_CD35F4-EG1nSEJeeZKUCK7fhNGnU9b2A1fgug/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSe7fzjbLlqATVQxAw17BqYQKj0atxd_kX1LCpNBvUDK12DIYA/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLScGpLkzi8wKlJjv5v3PhInf_rEhResfPtV07Y1zMjOTTJ68VA/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSd8uOw0729n9uK5cG1qfdfYzbs80qj-jqnW2btTkzM7TRHzXQ/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSdlueDmksi1D05xtKsVPZZg6oT8YoXW0HXW90GYmrLOiWHImQ/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSfY9Ma3YVJE0jjvMEhJSR4hiGERGV7iyC6rL6FHBlfJrEnmMw/viewform",
```
image
image
image
image
image

**Comment by dubstard** [comment]
` ✖ should be valid domain, not path`
image

This is a problem as we can not block the full domain, but path is not accepted.
Thus users are not protected
Removing those, but this shoudl be flagged as a probelmatic vector the protection is not coverint ATM.
cc @409H @AlexHerman1

**Review by dubstard — COMMENTED** [review]
Removing google docs as only domains and not paths are allowed
```
		"https://docs.google.com/forms/d/e/1FAIpQLSfWcSqiPHXb_CD35F4-EG1nSEJeeZKUCK7fhNGnU9b2A1fgug/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSe7fzjbLlqATVQxAw17BqYQKj0atxd_kX1LCpNBvUDK12DIYA/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLScGpLkzi8wKlJjv5v3PhInf_rEhResfPtV07Y1zMjOTTJ68VA/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSd8uOw0729n9uK5cG1qfdfYzbs80qj-jqnW2btTkzM7TRHzXQ/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSdlueDmksi1D05xtKsVPZZg6oT8YoXW0HXW90GYmrLOiWHImQ/viewform",
		"https://docs.google.com/forms/d/e/1FAIpQLSfY9Ma3YVJE0jjvMEhJSR4hiGERGV7iyC6rL6FHBlfJrEnmMw/viewform",
```

**Comment by AlexHerman1** [comment]
@409H  we should figure out a way to block google form specific paths if possible.

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
image

In all fairness the google forms say "do not enter passwords" on the bottom, but the text could be larger.
However currently the warning represents 0.2% of the visual screen space.
I think it could be a tad bigger than that.

**Pull request merged**
