### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by kellyfends**
and add to blacklist dappradaar.net

 "fantomnetwork.com",
    "renderprotocol.com",
    "oceangift.org",
    "fetchnetwork.org",
    "wooprotocol.com",
    "galatoken.org",
    "agixgift.com",
    "earn-link.com",
    "managift.org",
    "makertoken.net",
    "injective.events",
    "quantprotocol.net",
    "enstoken.net",
    "fraxnetwork.com",
    "dydxtoken.net",
    "usdgift.net",
    "beamtoken.org",
    "getSHIBA.org",
    "clink.gift",
    "hexprotocol.org",
    "oceantoken.net",
    "synthetix.events",
    "agix.gift",
    "graphtoken.net",
    "fetchprotocol.com",
    "realio.events",
    "aeth.network",
    "stakeether.net",
    "graphnetwork.org",
    "aaveprotocol.net",
    "hub-fantom.net",
    "app-rendernetwork.com",
    "getocean.net",
    "get-fetchtoken.org",
    "paxos-protocol.com",
    "claim-wootoken.org",
    "gala-hub.com",
    "web3-agix.com",
    "home-chain.link",
    "claim-mana.org",
    "claim-maker.org",
    "injective-claim.com",
    "quantprotocol.net",
    "ens-hub.com",
    "frax-hub.com",
    "claim-dydx.org",
    "usdcoin-hub.net",
    "get-beam.net",
    "get-shibtoken.org",
    "home-chain.link",
    "hexreward.org",
    "getocean.net",
    "synthetixnetwork.org",
    "web3-agix.com",
    "hub-graphtoken.net",
    "get-fetchtoken.org",
    "get-realio.com",
    "apyether-hub.com",
    "liquideth.today",
    "hub-graphtoken.net",
    "hub-aave.net",
    "liquidcompany.net",
    "stakeether.net",
    "liquideth.today",
    "tether-store.online",
    "ethshiba.top",
    "dappradaar.net",
    "bitrock-app.net",
    "elido-earn.site",

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@kellyfends  do you have any interest in being added to a maintainers group for this repo?

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by kellyfends** [comment]
> @kellyfends do you have any interest in being added to a maintainers group for this repo?

Yes, I've been waiting for such an offer for a long time

I agree

**Comment by kellyfends** [comment]
@AlexHerman1 Yes, I've been waiting for such an offer for a long time

I agree

**Comment by AlexHerman1** [comment]
can you set up a slack instance of some kind or provide your email and ill seeif i can add you?

**Comment by kellyfends** [comment]
> can you set up a slack instance of some kind or provide your email and ill seeif i can add you?

@AlexHerman1 thanks

my Email kellyfends@gmail.com

**Comment by kellyfends** [comment]
@AlexHerman1 did you send me an email ?

**Pull request merged**
