### PR TITLE
remove mynearwallet.com from block list

### PR DESCRIPTION
**Pull request by think-in-universe**
Per #14611 and #8206

mynearwallet.com is a legitimate site. It's the official site of one NEAR blockchain wallet called MyNearWallet.  

It's mistakenly included in this PR, when other phishing sites are reported: #14608

Also please notice it's not the first time MyNearWallet is mistakenly reported #8213

### CODE REVIEW

**Comment by ktian94** [comment]
Hmm apologies on this, flagging to reporter

**Comment by nhoxbypass** [comment]
Please review this PR ASAP to avoid confusion 😄

**Comment by SteveKok** [comment]
Hi, I am a developer from My Near Wallet.

Recently our website had been flooded with some Fungible Tokens with weird symbol and name, trying to mislead user to some of the phishing sites, which looks like My Near Wallet...

We have solve the issue in this commit:
https://github.com/mynearwallet/my-near-wallet/commit/8243f8c3284ea1edee9e4ca3fa3e20f51fba95c8

And the commit is currently already active on our website.

We hope that mynearwallet can be removed from the blacklist soon.

**Comment by AlexHerman1** [comment]
getting this merged now

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
