### PR TITLE
Block 65 Scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "accounts-coinbase.net",
    "coinbasemkt.com",
    "coinbasemkt.top",
    "coinbasemkt.xyz",
    "cunestiniversityhome.dedyn.io",
    "en-metemask.com",
    "ethereumporsche.com",
    "i-wallet.space",
    "ledbgerwallet.com",
    "ledgerwalletng.com",
    "ledgyerwallet.com",
    "meetherwallet.com",
    "meta-opensea.com",
    "metamask-login-ens.top",
    "metamask-login-ens.icu",
    "metamask_loogii.godaddysites.com",
    "metamastake.com",
    "ninexo.netlify.app",
    "porshe-x.art",
    "porshe.live",
    "imonline.club",
    "tokenpocket11.com",
    "secure-my-wallet.net",
    "solanaairdrop.fun",
    "stakemetamask.com",
    "staklng-polygon.online",
    "staklng-polygon.store",
    "support-coinbase.live",
    "toshles.com",
    "track-opensea.com",
    "trackeropensea.com",
    "trast-airdrops.site",
    "trezor-walletlogin.com",
    "trustwalletlend.com",
    "unisawp.exchange",
    "uniswap.website",
    "us09-colnbase.com",
    "us69-colnbase.com",
    "wallet-tronlink.online",
    "wallet-tronlink.org",
    "wallet-tronlink.pro",
    "wallet-tronlink.site",
    "walletconn.com",
    "walletconnect-support.pro",
    "walletrust.net",
    "walletvalidators.com",
    "www-metemask.com",
    "xn--trustwalet-xxb.site",
    "xrpwallet.info",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
```
    "ioratoken.com",
    "winselfhelplinejgjkjk-hfjh9878009.online",
    "lab-arbitrum.com",
    "lab-adidas.com",
```

**Review by dubstard — COMMENTED** [review]
```
    "ads-openseas.com",
    "biswops-trade.com",
    "cs-mloncey.com",
    "karemask.co.uk",
    "polkastarterdasboert.com",
    "uniswaape-app.com",
    "ussf-67.com",
    "www-polkastarler.com",
```

**Review by dubstard — COMMENTED** [review]
```

    "coinsbit-trade-login.ga",
    "coinsbit-trade-login.gq",
    "coinsbit-trade-login.ml",
    "coinsbit-trade-login.tk",
```

**Review by dubstard — COMMENTED** [review]
remove dupe ethereumporsche.com

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
yes yes yes dob dob shtibidi dib (dont ask)

**Pull request merged**
