### PR TITLE
Block 53 Scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "coinbasewallet.trade",
    "dappbay-official.com",
    "decentralizedapplications.site",
    "dappbay-official.org",
    "eosuniswap.io",
    "ethereum166.com",
    "ethereumfive.com",
    "ethereumnine.com",
    "ethereumpool.vip",
    "ethereumseven.com",
    "expert20xcapitals.com",
    "honeyswap-liquidity.com",
    "honeyswap-liquidity.org",
    "http-opensea.exchange",
    "https-opensea.exchange",
    "metabench.io",
    "metamask-official.com",
    "metamask.download",
    "metamask.metamskverify.net",
    "metamskverify.net",
    "opensea-finance.com",
    "pancakeswapbad.com",
    "pancakeswopp.xyz",
    "securecoinbase.net",
    "telsync.netlify.app",
    "trustcores.site",
    "unsiwap.org.kz",
    "unstopalledomain.us",
    "wallet.crypto.expert20xcapitals.com",
    "web3-uniswap.top",
    "www-1inch.com",
    "xi2y2.io",
    "xn--zkync-kdb.com",
```
[Took out the unstoppable one.](https://twitter.com/Namecheap/status/1623938821472518144)
How very sad.
image

Added to previous PR #11444 
```
just-adidas.com 
monday-arbitrum.com
```

Added to my current PR
```
xn--zkync-kdb.com 
https-opensea.exchange
unsiwap.org.kz
```

This leaves only those un added (yet) from the _eth_sign_ Barbara sent.
```
tsuwamono.club
www.gem.xyz
mekaapesooga.com
fluffs.wtf
mint.somethingfishy.app
sadbunnies.com
akidcalledbests.com
test.match.bitpencil.xyz
```

### CODE REVIEW

**Comment by dubstard** [comment]
Roll eyes. gif 
image

**Review by dubstard — COMMENTED** [review]
block 
```
    "collabland-holder.xyz",
    "collabland-holder.top",
    "collabland-holder.icu",
    "collabland-holder.buzz",
    "collabland-holder.monster",
```
Adding more, just to force a CI / CD re check.... 🤦‍♂️

**Comment by dubstard** [comment]
Ugh...
image

**Review by dubstard — COMMENTED** [review]
block 
```
"imtokens.social",
```

**Review by dubstard — COMMENTED** [review]
block 
```
    "imkey.pro",
    "polygonscans.com",
    "aircashs.finance",
    "tronscan2.org",
```

**Comment by dubstard** [comment]
Ok CI is happy now.

**Comment by dubstard** [comment]
Oh no, I found more
Gonna add them finger crossed CI does not cry again

**Review by dubstard — COMMENTED** [review]
block 62.204.41.30 🚽
```
    "aavetrack.com",
    "app-anywap.exchange",
    "app-convexfinance.com",
    "gotrack1inch.com",
    "track1inch.com",
    "trackcompound.com",
    "treckopenseefast.com",
    "www-app-anyswap.exchange",
    "www-app-compound.finance",
```

**Comment by dubstard** [comment]
ah, ofcource...
image

**Review by dubstard — COMMENTED** [review]
block
"metamaverify.com",
h/t @ecarlesi 
https://twitter.com/ecarlesi/status/1623954623345090560
literally 5 minutes ago

**Comment by dubstard** [comment]
✅Ready to merge
🎭All are scams
🔎All were individually checked

**Comment by dubstard** [comment]
After merging [11523](https://github.com/MetaMask/eth-phishing-detect/pull/11523)

My two other pending PRs somehow got conflicts that need to be resolved.
[11521](https://github.com/MetaMask/eth-phishing-detect/pull/11521)
[11513](https://github.com/MetaMask/eth-phishing-detect/pull/11513)

I think it has to do with the order of the URLs, there shouldn't be duplicates, but I can not fix it on my own.
Thanks and cheers

**Review by 409H — DISMISSED** [review]

**Review by 409H — APPROVED** [review]

**Pull request merged**
