### PR TITLE
Fake sites used on Facebook and Google ads

### PR DESCRIPTION
**Pull request by randymetamask**

### CODE REVIEW

**Comment by Gudahtt** [comment]
None of these sites are up anymore :thinking: I also can't find any record of these being used in google ads (e.g. they weren't reported to PhishFort, no scans on urlscan.io, etc.). I'll close this for now.

**Comment by randymetamask** [comment]
IMG_4369

IMG_4370

**Comment by Gudahtt** [comment]
I've just checked the whois entry for `meta-token.site` and it's identical to `metatoken.site`, so I'm going to assume that it's the same scammer. See #5195 for a url scan of that site.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
