### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
add
```
		"1inch.caixadirecta.su",
		"1inch.exchange.blazingblade.pk",
		"bankwallet.xyz",
		"bestcryptoexchange24.xyz",
		"bestcryptoexchange365.xyz",
		"bitcoin-exchange.xyz",
		"cardano-airdrop-binance.com",
		"coinbase-alertinformation.duckdns.org",
		"coinbase-alertnotice.duckdns.org",
		"coinbase-alertverify.duckdns.org",
		"coinbase-alertwithdrawl.duckdns.org",
		"coinbase-confirm-identity.com",
		"coinbase-verify-instan.com",
		"coinbase-webhook-updates.silverback.ventures",
		"coinbase-withdrall.duckdns.org",
		"cronosclassic.com.eth-1inch.io",
		"exodus.com.download-best-secure-wallet-online.maskinogasfalt.net",
		"exodus.com.download-secure-wallet-online.maskinogasfalt.net",
		"forexcryptosexchanges.xyz",
		"kefu.uniswap9.org",
		"lotteryethereum.com",
		"lottoethereum.com",
		"metamask-casino.com",
		"metamask-cx6.pages.dev",
		"metamask.authrize.mercamoron.com",
		"metamask.by.lt",
		"metamask.io-services.org",
		"metamask.io.merge.2fast2serious.com",
		"metamask.io.merge.aceros-monterrey.com",
		"metamask.io.merge.adeniyicreations.com",
		"metamask.io.merge.akbara.ac.id",
		"metamask.io.merge.albio.tech",
		"metamask.io.merge.aldhiyaltd.com",
		"metamask.io.merge.btcscloudmining.com",
		"metamask.io.merge.checkmyscoresnow.com",
		"metamask.io.merge.deeventures.net",
		"metamask.io.merge.demmecare.xyz",
		"metamask.io.merge.dgcrecharge.com",
		"metamask.io.merge.dimensionaproyectistas.com",
		"metamask.io.merge.educationalwriters.com",
		"metamask.io.merge.eiarash.ir",
		"metamask.io.merge.emplojo.com",
		"metamask.io.merge.evoitservices.com",
		"metamask.io.merge.grandstyleent.com",
		"metamask.io.merge.groupegerminal.com",
		"metamask.io.merge.i-securepro.com",
		"metamask.io.merge.jantosamstore.xyz",
		"metamask.io.merge.laboratorium.bnn.go.id",
		"metamask.io.merge.nandawahyubi.my.id",
		"metamask.io.merge.okwcq.org",
		"metamask.io.merge.regexbyte.com",
		"metamask.io.merge.ruachclass.com",
		"metamask.io.merge.sevensinnovations.com",
		"metamask.io.merge.simplyamazingidea.com",
		"metamask.io.merge.thelifepeople.com",
		"metamask.io.merge.tigertiao.com",
		"metamask.io.merge.universalshop.pro",
		"metamask.xn--polatelektrikliit-osb.com",
		"metamaskdid.com",
		"metamaskframes.com",
		"metamaskhub.me",
		"metamaskofficial.ru",
		"metamaskslogin.com",
		"metamasksupport.pages.dev",
		"muskswap.exchange",
		"myetherwallet.com.allstarbuildinginc.com",
		"nft-uniswap.org",
		"otponline-account-verification-coinbase.com",
		"pancakeswithfriends.com",
		"secureweb-coinbase.com-2fa-verifyotp.com",
		"support-ethereum.com",
		"thecrypto-coinbase.com",
		"truswallet-connect.cf",
		"uniswap.am",
		"uniswap.credit",
		"uniswap.cryptolisting.com",
		"uniswap.imbc.app",
		"uniswap.zeon.network",
		"uniswapex.xyz",
		"uniswapme.org",
		"uniswap9.org",
		"upgrade-ethereum.com",
		"usaethereum.com",
		"usdethereum.com",
		"v2ethereum.com",
		"www-coinbase-signin.com",
		"yandex-metamask.ru",
		"zethereum.com",
```

```
$ ./BurnTrash.sh | egrep "(result|url)"

  "result": "https://urlscan.io/result/dc8c73fa-7cf0-4668-915e-9ef3d1e337da/",
  "url": "http://1inch.caixadirecta.su",

  "result": "https://urlscan.io/result/3dc4a796-9b78-41d2-852e-86f527f34eb9/",
  "url": "http://1inch.exchange.blazingblade.pk",

  "result": "https://urlscan.io/result/a52de492-f2a7-4318-ad2a-004798ba0ef5/",
  "url": "http://1inch.io.sci-hub.st",

  "result": "https://urlscan.io/result/2505497f-24a8-437c-9596-62b3324d8110/",
  "url": "http://account-recovery-coinbase.com",

  "result": "https://urlscan.io/result/3edc4cc2-62d0-46e8-9634-128247c6dd76/",
  "url": "http://bankwallet.xyz",

  "result": "https://urlscan.io/result/dd393e0e-c437-4e65-b855-4eb306e6322c/",
  "url": "http://bestcryptoexchange24.xyz",

  "result": "https://urlscan.io/result/1b069761-afe7-4274-83ae-20342b150557/",
  "url": "http://bestcryptoexchange365.xyz",

  "result": "https://urlscan.io/result/3684674a-2b5f-46fc-aaa4-7d4a7b86a439/",
  "url": "http://bitcoin-exchange.xyz",

  "result": "https://urlscan.io/result/217df006-211e-429a-beed-37d74bb881b8/",
  "url": "http://cardano-airdrop-binance.com",

  "result": "https://urlscan.io/result/66ca02c5-a606-408a-9633-87e27d176221/",
  "url": "http://coinbase-alertinformation.duckdns.org",

  "result": "https://urlscan.io/result/fff08fc3-3bff-4802-8581-4c83715bcce8/",
  "url": "http://coinbase-alertnotice.duckdns.org",

  "result": "https://urlscan.io/result/dee6ab22-8233-4ce7-9278-35513f23dd71/",
  "url": "http://coinbase-alertverify.duckdns.org",

  "result": "https://urlscan.io/result/cd6db732-b98a-4d27-9960-666c4e96d111/",
  "url": "http://coinbase-alertwithdrawl.duckdns.org",

  "result": "https://urlscan.io/result/4189b06e-8305-44a7-bc63-ad00dd8faa9e/",
  "url": "http://coinbase-confirm-identity.com",

  "result": "https://urlscan.io/result/ebbd4e32-afef-4fbf-8afa-087b42b6e4a9/",
  "url": "http://coinbase-webhook-updates.silverback.ventures",

  "result": "https://urlscan.io/result/0aa797ec-d46d-4d5c-b690-111410e33db7/",
  "url": "http://coinbase-withdrall.duckdns.org",

  "result": "https://urlscan.io/result/5468b4c4-f3e6-4397-a335-b213cb8d9d8d/",
  "url": "http://cronosclassic.com.eth-1inch.io",

  "result": "https://urlscan.io/result/5aaf5e45-cdf3-4048-bc6d-c97a3fc44e84/",
  "url": "http://exodus.com.download-best-secure-wallet-online.maskinogasfalt.net",

  "result": "https://urlscan.io/result/ffcf7b71-ff3d-4431-a1cc-eb7d8dfa5afa/",
  "url": "http://exodus.com.download-secure-wallet-online.maskinogasfalt.net",

  "result": "https://urlscan.io/result/0e6c6c13-c8e0-4be2-a5d9-546c25c39316/",
  "url": "http://forexcryptosexchanges.xyz",

  "result": "https://urlscan.io/result/99c13427-ec75-4466-91aa-79bec4f28d4a/",
  "url": "http://kefu.uniswap9.org",

  "result": "https://urlscan.io/result/387f3aa3-eca2-4174-b866-5cc2caa23f26/",
  "url": "http://lotteryethereum.com",

  "result": "https://urlscan.io/result/44b94072-393d-4cbe-88cc-ee79052ac92e/",
  "url": "http://lottoethereum.com",

  "result": "https://urlscan.io/result/119ff4e3-c8ad-466f-815e-91165127766b/",
  "url": "http://metamask-casino.com",

  "result": "https://urlscan.io/result/9c63ec50-993a-4c26-a2ea-9b2a3dd5f6b2/",
  "url": "http://metamask-cx6.pages.dev",

  "result": "https://urlscan.io/result/7fc8a150-d6c1-4a0b-a763-9dc9b3850809/",
  "url": "http://metamask-giveaway.io",

  "result": "https://urlscan.io/result/d71e820a-10c2-49e0-a15c-1ee15a2c5a16/",
  "url": "http://metamask-mintnft.biz",

  "result": "https://urlscan.io/result/aeabcb24-a23f-4f54-9f18-62bffd1f9623/",
  "url": "http://metamask.authrize.mercamoron.com",

  "result": "https://urlscan.io/result/dd655a01-ee04-4d6b-a2d2-569d3ad1f213/",
  "url": "http://metamask.by.lt",

  "result": "https://urlscan.io/result/e5eb9821-47c6-4e32-8637-2f73af756df4/",
  "url": "http://metamask.io-services.org",

  "result": "https://urlscan.io/result/4a15f145-b2dc-47a1-b596-1d7375488158/",
  "url": "http://metamask.io.merge.2fast2serious.com",

  "result": "https://urlscan.io/result/fdf25d5c-747c-4aea-8c43-9fa91fab0d1f/",
  "url": "http://metamask.io.merge.aceros-monterrey.com",

  "result": "https://urlscan.io/result/184df23a-0ff7-417f-82fc-1a2ecc840910/",
  "url": "http://metamask.io.merge.adeniyicreations.com",

  "result": "https://urlscan.io/result/6ae85f18-95a2-4670-b887-4a225521108d/",
  "url": "http://metamask.io.merge.akbara.ac.id",

  "result": "https://urlscan.io/result/d7c18c97-d16b-486e-b424-e1f649352d76/",
  "url": "http://metamask.io.merge.aldhiyaltd.com",

  "result": "https://urlscan.io/result/5e359332-6e14-4a1e-a173-a21e696cbf56/",
  "url": "http://metamask.io.merge.btcscloudmining.com",

  "result": "https://urlscan.io/result/f8cdc521-bba1-4f2d-9912-41d1bcd8fe2b/",
  "url": "http://metamask.io.merge.checkmyscoresnow.com",

  "result": "https://urlscan.io/result/850f76ec-ce11-4750-8745-42e48bb3b72f/",
  "url": "http://metamask.io.merge.deeventures.net",

  "result": "https://urlscan.io/result/2ddbb22f-287b-43a2-ab3f-c80ff53405d7/",
  "url": "http://metamask.io.merge.demmecare.xyz",

  "result": "https://urlscan.io/result/0fed32e8-79bc-4538-b853-9778b466fb9f/",
  "url": "http://metamask.io.merge.dgcrecharge.com",

  "result": "https://urlscan.io/result/84791dd3-1249-45bb-875c-fb030967b305/",
  "url": "http://metamask.io.merge.dimensionaproyectistas.com",

  "result": "https://urlscan.io/result/4de263f6-d9ca-46a9-ba53-fd0c084f0a85/",
  "url": "http://metamask.io.merge.educationalwriters.com",

  "result": "https://urlscan.io/result/0d5f18f1-0f3f-49fe-8782-2ca891a852e8/",
  "url": "http://metamask.io.merge.eiarash.ir",

  "result": "https://urlscan.io/result/35250d2c-889e-46ea-9944-868f9699f7bf/",
  "url": "http://metamask.io.merge.emplojo.com",

  "result": "https://urlscan.io/result/d3698094-670f-4b7d-ba6d-7c47a9119315/",
  "url": "http://metamask.io.merge.evoitservices.com",

  "result": "https://urlscan.io/result/3142614f-298e-41f9-9fe8-3a75a3fbbca5/",
  "url": "http://metamask.io.merge.grandstyleent.com",

  "result": "https://urlscan.io/result/16183644-27ac-4dfc-b941-1036d60e982b/",
  "url": "http://metamask.io.merge.groupegerminal.com",

  "result": "https://urlscan.io/result/995dac50-d9ce-4872-9401-a0cad3833539/",
  "url": "http://metamask.io.merge.i-securepro.com",

  "result": "https://urlscan.io/result/c0494724-86a8-4c9b-8990-2bd832750709/",
  "url": "http://metamask.io.merge.jantosamstore.xyz",

  "result": "https://urlscan.io/result/c08897a7-f1ea-419c-8836-3d6d3284da3d/",
  "url": "http://metamask.io.merge.laboratorium.bnn.go.id",

  "result": "https://urlscan.io/result/70060fb8-5e6b-454a-ab22-0324bd834504/",
  "url": "http://metamask.io.merge.nandawahyubi.my.id",

  "result": "https://urlscan.io/result/550ddb10-deae-494c-a8e9-dd8dafaf0ebe/",
  "url": "http://metamask.io.merge.okwcq.org",

  "result": "https://urlscan.io/result/904a216e-129d-4a6a-a6d7-31f482a7ee1c/",
  "url": "http://metamask.io.merge.regexbyte.com",

  "result": "https://urlscan.io/result/0f0060ab-4bd8-45f3-b257-eee893a27d07/",
  "url": "http://metamask.io.merge.ruachclass.com",

  "result": "https://urlscan.io/result/f5e7df63-32ce-4705-ab28-2b134a619206/",
  "url": "http://metamask.io.merge.sevensinnovations.com",

  "result": "https://urlscan.io/result/ae2ce1bc-78d2-43e4-8126-390f3fa51c72/",
  "url": "http://metamask.io.merge.simplyamazingidea.com",

  "result": "https://urlscan.io/result/db754ece-8515-4d4b-96a7-bdeae5ea7491/",
  "url": "http://metamask.io.merge.thelifepeople.com",

  "result": "https://urlscan.io/result/9fd596b0-2ecf-4d8e-af93-c2232e0ffc02/",
  "url": "http://metamask.io.merge.tigertiao.com",

  "result": "https://urlscan.io/result/be712a52-5945-4ee0-ba63-3704ecb55540/",
  "url": "http://metamask.io.merge.universalshop.pro",

  "result": "https://urlscan.io/result/7cc62ed9-accf-4e50-923e-75c4ee1661b6/",
  "url": "http://metamask.xn--polatelektrikliit-osb.com",

  "result": "https://urlscan.io/result/2ddbe3f9-5c96-4308-a2a2-c6208094b47d/",
  "url": "http://metamaskdid.com",

  "result": "https://urlscan.io/result/2c90e461-0569-4ca4-8dab-b24c3edab766/",
  "url": "http://metamaskframes.com",

  "result": "https://urlscan.io/result/f4a38a93-ffba-4319-aff6-40dbcca978d1/",
  "url": "http://metamaskhub.me",

  "result": "https://urlscan.io/result/7670278a-082a-470b-8a2c-206f322c5e91/",
  "url": "http://metamaskofficial.ru",

  "result": "https://urlscan.io/result/cee4155d-c6e3-4215-a534-3103b1c5ef99/",
  "url": "http://metamaskslogin.com",

  "result": "https://urlscan.io/result/4dcc5db6-806e-4e96-8a80-399ffd96270c/",
  "url": "http://metamasksupport.pages.dev",

  "result": "https://urlscan.io/result/105d4fba-4a5a-4514-8477-b4c34a565082/",
  "url": "http://muskswap.exchange",

  "result": "https://urlscan.io/result/04fee521-def7-481c-84cf-e032659f192f/",
  "url": "http://myetherwallet.com.allstarbuildinginc.com",

  "result": "https://urlscan.io/result/8139761c-b155-4702-9532-5807f448edcf/",
  "url": "http://myetherwalletp.com",

  "result": "https://urlscan.io/result/4631a120-2675-4c52-8187-60dc6ba7cce4/",
  "url": "http://nft-uniswap.org",

  "result": "https://urlscan.io/result/a10142a0-d9d3-493f-aed7-4758fb01d687/",
  "url": "http://otponline-account-verification-coinbase.com",

  "result": "https://urlscan.io/result/ed4f86d1-878d-495a-8b66-6f884a59b297/",
  "url": "http://pancakeswap-fre.com",

  "result": "https://urlscan.io/result/681938b9-73c7-4011-8ed4-06352d76db4f/",
  "url": "http://pancakeswithfriends.com",

  "result": "https://urlscan.io/result/0e890a33-59ac-45a2-a1d8-e67b80d538c0/",
  "url": "http://support-ethereum.com",

  "result": "https://urlscan.io/result/cd0b4eb3-b5a2-42f8-892c-755375c4ed21/",
  "url": "http://thecrypto-coinbase.com",

  "result": "https://urlscan.io/result/ca971a04-9197-40bb-a988-062fcab894ac/",
  "url": "http://token-metamask.com",

  "result": "https://urlscan.io/result/a2bc8721-dcbb-48fa-adfd-d1df1f8617b5/",
  "url": "http://truswallet-connect.cf",

  "result": "https://urlscan.io/result/82ce1e35-c658-4518-957c-8cdbb654a5db/",
  "url": "http://uniswap.am",

  "result": "https://urlscan.io/result/80f5c80a-95aa-4405-af75-0415a919ed16/",
  "url": "http://uniswap.credit",

  "result": "https://urlscan.io/result/3ebaeae6-cb06-413a-87ff-cff49af31436/",
  "url": "http://uniswap.cryptolisting.com",

  "result": "https://urlscan.io/result/8d360cd4-2bf9-41fd-987b-248aa97eb1c5/",
  "url": "http://uniswap.imbc.app",

  "result": "https://urlscan.io/result/a039876b-1050-4fa5-bc4e-c706a3353705/",
  "url": "http://uniswap.zeon.network",

  "result": "https://urlscan.io/result/d7d69a88-47ec-4c57-853b-6cec4f6c1d5d/",
  "url": "http://uniswapex.xyz",

  "result": "https://urlscan.io/result/b493f104-94db-4a85-96b0-5b6eaeccd433/",
  "url": "http://uniswapme.org",

  "result": "https://urlscan.io/result/a94c8623-0612-4a39-a683-adaa450e7b64/",
  "url": "http://uniswap9.org",

  "result": "https://urlscan.io/result/7c7f7c01-4bcc-4e35-9497-70cdb0ee80b9/",
  "url": "http://upgrade-ethereum.com",

  "result": "https://urlscan.io/result/6e49e251-b3dc-4b6d-a5fc-c771922d130c/",
  "url": "http://usaethereum.com",

  "result": "https://urlscan.io/result/8dbed4b0-c0f0-48dc-8ea3-751216b859ca/",
  "url": "http://usdethereum.com",

  "result": "https://urlscan.io/result/70a698e8-c01a-45ce-ba27-7ca4b20cb0e6/",
  "url": "http://v2ethereum.com",

  "result": "https://urlscan.io/result/a3716dad-6fd1-45ef-8793-92cd71c7acaf/",
  "url": "http://www-coinbase-signin.com",

  "result": "https://urlscan.io/result/d3a5d3e8-9b89-4ec0-b939-6ead6c652742/",
  "url": "http://yandex-metamask.ru",

  "result": "https://urlscan.io/result/674f060b-f5b1-4e3a-a3ea-0b806d54adbf/",
  "url": "http://zethereum.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Removing Duplicates
```
1inch.io.sci-hub.st
account-recovery-coinbase.com
metamask-giveaway.io
metamask-mintnft.biz
metamask-verify-verification.com
myetherwalletp.com
pancakeswap-fre.com
token-metamask.com
```

**Comment by dubstard** [comment]
[Order 66 executed](https://twitter.com/dubstard/status/1572113403560493060)

**Review by dubstard — COMMENTED** [review]
trim empty lines (left from dupes removed)
add two more scams
```
		"pxlme.me",
		"metamask.io.merge.freethingsblog.com",
```
image
h/t DKOB for those two

**Review by dubstard — COMMENTED** [review]
Add two more scams, same pattern

```
"metamask.io.merge.hpe-rpe.com",
"metamask.io.merge.rigeo.org",
```
https://twitter.com/dubstard/status/1572145663030312961

**Comment by dubstard** [comment]
This is a big campaign related to Opensea leaked emails
Spam was sent to all users.
image

**Review by dubstard — COMMENTED** [review]
```
		"metamask.io.merge.amarmultihospital.com",
		"metamask.io.merge.aviraorganics.com",
		"metamask.io.merge.erasky.in",
		"metamask.io.merge.npbconsultants.in",
		"metamask.io.merge.singhgroup-india.com",
```
Add more scams, same pattern.
image
https://twitter.com/dubstard/status/1572182814413717506

**Review by dubstard — COMMENTED** [review]
More scams, same pattern

```
		"metamask.io.merge.aqit.ma",
		"metamask.io.merge.cosdelmar.com",
		"metamask.io.merge.roox.tech",
```
https://twitter.com/dubstard/status/1572199428072820737

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks, this campaign is huge, great that it got blocked on the same day

**Pull request merged**
