### PR TITLE
Add phishing url to blacklist

### PR DESCRIPTION
**Pull request by rxpwnz**
| URL  | Description |
| ------------- | ------------- |
| hopprotocol.app  | a deceptive website mimicking the Hop protocol |

### CODE REVIEW

**Comment by AndrewMohawk** [comment]
I connect to `hopprotocol.app` but it didnt seem to want to do any malicious transactions, is this not just a fork of the frontend code from https://github.com/hop-protocol/hop ?

**Comment by rxpwnz** [comment]
> I connect to `hopprotocol.app` but it didnt seem to want to do any malicious transactions, is this not just a fork of the frontend code from https://github.com/hop-protocol/hop ?

@AndrewMohawk This site doesn't utilize any Hop contracts. Upon source inspection, you will observe that users interact with a phishing contract, `0xA9B843a0A83bf73390a3d1E16f28AA985c022c42`, designed to forward funds to the scammer's address. An example transaction can be found here: https://optimistic.etherscan.io/tx/0xb8bc669cae6c975bca5dd1994d824e0ecdd0be48343381a5980d80f2348a3e19.
image

Additionally, I am curious to hear your thoughts on the reasoning behind creating a fork using the project's name.

**Comment by AlexHerman1** [comment]
im going to merge this, even though it doesn't prompt malicious txns, who knows what they are up to.

**Comment by rxpwnz** [comment]
> im going to merge this, even though it doesn't prompt malicious txns, who knows what they are up to.

Thanks, please see my explanation in the comment above.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
