### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
image
image
image

add scams
```
    "1inch-v1.com",
    "1inch.de.com",
    "1inch.interdesigns.info",
    "1vvwvuniswap.top",
    "1vwwuniswap.top",
    "1wuniswap.top",
    "1wvwvvuniswap.top",
    "1wwuniswap.top",
    "2vvuniswap.top",
    "2vvvvuniswap.top",
    "2wuniswap.top",
    "2wvwvvuniswap.top",
    "6529er.xyz",
    "8liens.live",
    "acrocalypse.live",
    "airdrop.pancakeswap-price-today.com",
    "ak-ultra.live",
    "akumudragonz.live",
    "alphakongsofficial.xyz",
    "amazonclub.live",
    "angrycat.live",
    "angrypitbullnft.xyz",
    "anomura.live",
    "aometaverse.live",
    "apehaternft.live",
    "apereunion.live",
    "apocalyptic-apes.xyz",
    "app-sushiswap.net",
    "app-uniswap.org.kz",
    "app.uniswap.org.recriarcaminhos.pt",
    "aspectkraken.cf",
    "aspectkraken.ga",
    "aspectkraken.ml",
    "aspectkraken.tk",
    "atari-x.live",
    "atlanticapes.live",
    "auth-coinbase.net",
    "azito.live",
    "azuki.web-freemint.com",
    "ballygang.live",
    "bapetaverseofficial.xyz",
    "based-ghouls.xyz",
    "balancer-fi.ga",
    "balancer-fi.gq",
    "balancer-fi.ml",
    "balancer-fi.tk",
    "balancer-fi.cf",
    "beyondearthnft.live",
    "biolockwalletchain.top",
    "biswap-exchange.org.mintfoods.com.au",
    "bitso.click",
    "bitsoft-360.info",
    "bitsoft-360.tech",
    "bitsoft3-60-ai.co",
    "bitsoft3-60-ai.com",
    "bitsoft3-60-ai.net",
    "bitsoft3-60-ai.org",
    "bitsoft3-60-ai.xyz",
    "bitsoft3-60.co",
    "bitsoft3-60.online",
    "bitsoft3-60.shop",
    "bitsoft3-60.store",
    "bitsoft30.com",
    "bitsoft360.international",
    "bitsoft360.ltd",
    "bitsoft360.marketing",
    "blocktones.live",
    "bobuthebeanfarmer.xyz",
    "bokiofficial.xyz",
    "boonji-project.live",
    "boredapeyc.web-freemint.com",
    "cakedapes.live",
    "cameopass.live",
    "capital-exchanges.net.finances-exchange.com",
    "chimpers.web-freemint.com",
    "chinachic.live",
    "chubbiverse.live",
    "coolcats.web-freemint.com",
    "coolmanuniverse.live",
    "cooltimes.live",
    "cosamonstranft.live",
    "critterzmc.xyz",
    "crypto888.live",
    "cryptobatznft.live",
    "cryptomonkz.live",
    "cryptomories.live",
    "cryptopunks.web-freemint.com",
    "cryptosimejiofficia.xyz",
    "cube-x-official.xyz",
    "cultivate.live",
    "cybersnails.live",
    "cyberturtles.live",
    "dape-freemint.xyz",
    "darkfarms.live",
    "deathbatsclub.live",
    "deltaflare.live",
    "dentedfeels.live",
    "doc-metamask.rf.gd",
    "doodlesnft.web-freemint.com",
    "drp-vhils.xyz",
    "elysiumclub.xyz",
    "emanueleferrari.xyz",
    "ezuofficial.xyz",
    "famelady.live",
    "fatcatsnft.live",
    "feline-fiendz.xyz",
    "finiliar.live",
    "flickplay.live",
    "flooz.live",
    "flufworld.web-freemint.com",
    "founderskey.live",
    "froggyfriends.live",
    "fxkraken.co",
    "galaxyeggs.live",
    "gamingapeclub.live",
    "gene-sis.live",
    "genzee.live",
    "gevols.live",
    "goonsnft.live",
    "halfbaycd.live",
    "haunted-space.live",
    "hausphases.live",
    "heartproject.live",
    "hustlers.live",
    "hyhunetwork.live",
    "illogicsnft.live",
    "invisiblefriends.web-freemint.com",
    "jurassicpunks.live",
    "karafuru-official.art",
    "kiwaminft.live",
    "krapopolisnft.live",
    "kryptoria.live",
    "kumaleon.live",
    "larvalads.live",
    "lazyapeyc.live",
    "leagueofkingdoms.live",
    "login.coinbase.accounts.k4at.day",
    "loserclub.live",
    "losmuertos.live",
    "lostpoets.live",
    "love-addicted-girls.xyz",
    "lvcidia.live",
    "mefaverse.live",
    "megami.live",
    "metaapemilitia.live",
    "metalcorenft.live",
    "metalegendsnft.live",
    "metamask-update.iaibserang.ac.id",
    "metamask.evolutcoin.org",
    "metamask.io.update-main-network.com",
    "metamask.io.your-main-network.com",
    "metamask.properties",
    "metamask3.com",
    "metamasks-validate.com",
    "metashima.xyz",
    "metawizardsnft.live",
    "mgxsnft.live",
    "moonbirds.web-freemint.com",
    "moonwalkersnft.live",
    "mplofficial.live",
    "murinft.live",
    "myethereumwallet.uk",
    "mythicals.live",
    "nemus.live",
    "nft-gurus.xyz",
    "noblecards.live",
    "nuclearnerds.live",
    "onewordbrick.live",
    "otakuculturestudio.live",
    "otherside.web-freemint.com",
    "outsadofficial.xyz",
    "pancakerectify.com",
    "pancakeswap.defiapp.network",
    "pancakeswap.finance.apptrade.in",
    "pancakeswap.finance.pantrade.in",
    "parapreppers.live",
    "pekingmonsters.live",
    "peopleofcrypto.live",
    "pepeapeyachtclub.xyz",
    "piratesmeta.live",
    "pixlverse.live",
    "planet-xolo.xyz",
    "pluto-alliance.xyz",
    "popartcats.live",
    "possessed.live",
    "quirkies.web-freemint.com",
    "realgoblins.live",
    "regularsnft.live",
    "rewards-walletstronlink.tk",
    "rtfkt.web-freemint.com",
    "san-official.xyz",
    "satoshiverse.live",
    "seekersnft.xyz",
    "shikigai.live",
    "shrapnel.live",
    "sidus-official.xyz",
    "siphernft.live",
    "slimhoods.live",
    "smallbros.live",
    "spookyboyscc.xyz",
    "squishiversenft.xyz",
    "starlofficial.xyz",
    "steezyapegang.live",
    "superapesclub.xyz",
    "svsnft.live",
    "swampverse.live",
    "syltare.live",
    "tennischamps.live",
    "thealienboy.live",
    "thedoggies.live",
    "theflowergirls.live",
    "thelittles.live",
    "themetroverse.xyz",
    "thundervalley.live",
    "tribeodyssey.live",
    "tribepass.live",
    "trustwallet.com-dapp.online",
    "trustwalletearnmoney.finance.blog",
    "trustwalletgiveaway.rf.gd",
    "trustwalletstakeandearnmoney.finance.blog",
    "tsrocketfactory.xyz",
    "typicaltigers.live",
    "uniswap-apps.casa",
    "uniswap-apps.club",
    "uniswap-apps.space",
    "uniswap-ecosystem.club",
    "uniswap-ecosystem.space",
    "uniswap-ecosystem.top",
    "uniswap-protocol.casa",
    "uniswap.ltd",
    "uniswap.ventures",
    "uniswaplabs.ventures",
    "uniswaplendwap.top",
    "uniswaps.cc",
    "uniswapwallet.com",
    "unxdnft.live",
    "v2exchange-pancakeswap.financia",
    "veefriends.web-freemint.com",
    "verification.coinbase-supportredit-carmail.thuongnhanv.admin.orderonlail.thuongnhanv.admin.orderonline.id",
    "verification.coinbase-supportredit-carmail.thuongnhanv.admin.orderonline.id",
    "violettazironi.live",
    "wagmiofficial.xyz",
    "wagmiunited.live",
    "warpsoundnft.xyz",
    "womenandweapons.live",
    "worldofwomen.web-freemint.com",
    "xn--pancakeswp-j7a.finance",
    "y00tsyachtclub.live",
```

```
 ./BurnTrash.sh | egrep "(result|url)"

  "result": "https://urlscan.io/result/b868e707-ab7f-4eeb-80d0-3cf517b45709/",
  "url": "http://1inch-v1.com",

  "result": "https://urlscan.io/result/1f6b9a66-bbc1-4741-ba71-858e411f86f0/",
  "url": "http://1inch.de.com",

  "result": "https://urlscan.io/result/f492addb-63a7-4046-9b58-d003180f50b4/",
  "url": "http://1inch.interdesigns.info",

  "result": "https://urlscan.io/result/622ab0a2-0f53-4a13-85f5-43f0165f2dc6/",
  "url": "http://1vvwvuniswap.top",

  "result": "https://urlscan.io/result/afd113c4-ff77-4b2b-abc9-59e555b834a7/",
  "url": "http://1vwwuniswap.top",

  "result": "https://urlscan.io/result/6af7e702-342a-4e98-94f8-a5927ebe00c2/",
  "url": "http://1wuniswap.top",

  "result": "https://urlscan.io/result/4be59e22-68e8-49dc-b28d-c0f6ead3bf3f/",
  "url": "http://1wvwvvuniswap.top",

  "result": "https://urlscan.io/result/9801eb84-1953-492b-99b6-a7f58aecd88e/",
  "url": "http://1wwuniswap.top",

  "result": "https://urlscan.io/result/8f4e2e3e-7a53-4e4b-80e4-9e18c2a40ab0/",
  "url": "http://2vvuniswap.top",

  "result": "https://urlscan.io/result/51f072bf-d30b-4bfa-9016-1f6eba3cad33/",
  "url": "http://2vvvvuniswap.top",

  "result": "https://urlscan.io/result/0f5a7dd3-d808-4ef5-9a2e-d44445c8a4c6/",
  "url": "http://2wuniswap.top",

  "result": "https://urlscan.io/result/9a52a82a-a883-42c1-a5ec-04d5503cc1af/",
  "url": "http://2wvwvvuniswap.top",

  "result": "https://urlscan.io/result/3b172781-2d04-4c6d-b992-2f879a76b5cc/",
  "url": "http://6529er.xyz",

  "result": "https://urlscan.io/result/2e448c60-58f8-49e5-bcc7-c5b393dc8f13/",
  "url": "http://airdrop.pancakeswap-price-today.com",

  "result": "https://urlscan.io/result/5cd9174b-0b16-49b7-b58e-1a71d406cbfb/",
  "url": "http://akumudragonz.live",

  "result": "https://urlscan.io/result/cdae9992-080c-406f-97ba-f61605cef8ff/",
  "url": "http://amazonclub.live",

  "result": "https://urlscan.io/result/0dd31b7c-8976-41f2-9d03-b24439bb6952/",
  "url": "http://app-sushiswap.net",

  "result": "https://urlscan.io/result/0dfbfb2d-d304-4e02-93f9-8bf2d48e33e7/",
  "url": "http://app-uniswap.org.kz",

  "result": "https://urlscan.io/result/f35570b3-96fd-4cdd-af0a-5ae70bae21f3/",
  "url": "http://app.uniswap.org.recriarcaminhos.pt",

  "result": "https://urlscan.io/result/d517ace0-529f-4e9b-8857-617693bd5910/",
  "url": "http://aspectkraken.cf",

  "result": "https://urlscan.io/result/5d09b554-0860-4b0a-b365-9358f77f49dc/",
  "url": "http://aspectkraken.ga",

  "result": "https://urlscan.io/result/ba3405aa-8280-410a-afe7-35cee9b6f329/",
  "url": "http://aspectkraken.ml",

  "result": "https://urlscan.io/result/5f230611-ebdd-4338-b7e4-5dbe3ed8aedc/",
  "url": "http://aspectkraken.tk",

  "result": "https://urlscan.io/result/3da6be5f-0a63-4046-8e64-ad5b4f32f3d3/",
  "url": "http://auth-coinbase.net",

  "result": "https://urlscan.io/result/afecc2d3-b0c7-4366-9101-f9b3173b836a/",
  "url": "http://azito.live",

  "result": "https://urlscan.io/result/b0e140e2-bffb-4a8d-a45e-846b2e169255/",
  "url": "http://balancer-fi.cf",

  "result": "https://urlscan.io/result/c8c08398-8f5e-4120-91ad-eb8170294684/",
  "url": "http://biolockwalletchain.top",

  "result": "https://urlscan.io/result/e6da1ee3-1871-4d4d-bc43-9dd4b5261ec6/",
  "url": "http://biswap-exchange.org.mintfoods.com.au",

  "result": "https://urlscan.io/result/b2300648-75c1-4513-aff7-12bc1f4120b5/",
  "url": "http://bitso.click",

  "result": "https://urlscan.io/result/c4ed83ed-70b1-47e0-a56c-bdbe5a0e0f1e/",
  "url": "http://capital-exchanges.net.finances-exchange.com",

  "result": "https://urlscan.io/result/c927b31a-dbf5-40cf-9f04-94c8e2032311/",
  "url": "http://critterzmc.xyz",

  "result": "https://urlscan.io/result/c0d443b5-409d-4b7c-ae54-c382a265d442/",
  "url": "http://cryptosimejiofficia.xyz",

  "result": "https://urlscan.io/result/4ed17bf8-2e46-476d-aa35-a269444ce02c/",
  "url": "http://doc-metamask.rf.gd",

  "result": "https://urlscan.io/result/e251b9d0-b537-410e-8ecb-4e6f0bf6cab8/",
  "url": "http://fxkraken.co",

  "result": "https://urlscan.io/result/61649ade-34a2-4e95-a0ee-ce869be1b0c7/",
  "url": "http://gamingapeclub.live",

  "result": "https://urlscan.io/result/02b357ef-395e-4567-be93-a86d5c1a127c/",
  "url": "http://genzee.live",

  "result": "https://urlscan.io/result/455a8d62-6eb2-42b6-a450-8165d808827a/",
  "url": "http://halfbaycd.live",

  "result": "https://urlscan.io/result/f07970ea-65cf-402b-8a4e-1aa7117590a5/",
  "url": "http://lvcidia.live",

  "result": "https://urlscan.io/result/cd7f3f21-3cb9-477c-a2f0-ce6d5cf79f67/",
  "url": "http://metalcorenft.live",

  "result": "https://urlscan.io/result/69d009ac-992f-4e7d-a77f-74c30df13898/",
  "url": "http://metamask-update.iaibserang.ac.id",

  "result": "https://urlscan.io/result/517b0b1a-5258-4444-b95a-73f173965892/",
  "url": "http://metamask.evolutcoin.org",

  "result": "https://urlscan.io/result/6984ffe5-bb43-4e2c-96de-ed61481e39ed/",
  "url": "http://metamask.io.update-main-network.com",

  "result": "https://urlscan.io/result/7413689f-ed52-4f49-86ea-122bb7af1704/",
  "url": "http://metamask.io.your-main-network.com",

  "result": "https://urlscan.io/result/f0a1c817-0c2e-4fe7-aa01-7c64df5a36ea/",
  "url": "http://metamask.properties",

  "result": "https://urlscan.io/result/bb22b8ac-76c6-4ba7-b3e4-4607184559c0/",
  "url": "http://metamask3.com",

  "result": "https://urlscan.io/result/e2c66972-ee88-42c7-8463-1e13f3509ea0/",
  "url": "http://metamasks-validate.com",

  "result": "https://urlscan.io/result/3dca68b8-724d-409e-b71b-86f489a556d7/",
  "url": "http://murinft.live",

  "result": "https://urlscan.io/result/6c837ca9-9a08-4c48-9e32-dc75c580958e/",
  "url": "http://myethereumwallet.uk",

  "result": "https://urlscan.io/result/9d8637d1-5ef3-480a-a09d-44f51bcac0a8/",
  "url": "http://mythicals.live",

  "result": "https://urlscan.io/result/fdd03e35-558d-438a-862b-ef11e8232e8c/",
  "url": "http://nft-gurus.xyz",

  "result": "https://urlscan.io/result/16a77ce7-f27b-4909-8568-cfb8b31b3574/",
  "url": "http://pancakerectify.com",

  "result": "https://urlscan.io/result/e5208d16-b7d2-40f0-a586-e7a5cae3d9f4/",
  "url": "http://pancakeswap.defiapp.network",

  "result": "https://urlscan.io/result/b3b0759d-d04c-47c1-85b5-6b87cc2ee6a3/",
  "url": "http://pancakeswap.finance.apptrade.in",

  "result": "https://urlscan.io/result/a2b65e36-159b-4c52-b4b7-7969a237d2fc/",
  "url": "http://pancakeswap.finance.pantrade.in",

  "result": "https://urlscan.io/result/90ec44b4-8a96-4b83-9ebd-6c5f626631a5/",
  "url": "http://pepeapeyachtclub.xyz",

  "result": "https://urlscan.io/result/fa0cd2dc-a8e2-41a5-9cf6-c54d9a0bbf38/",
  "url": "http://piratesmeta.live",

  "result": "https://urlscan.io/result/b917fce4-b7e2-4f29-9546-9894f46174e8/",
  "url": "http://possessed.live",

  "result": "https://urlscan.io/result/6ecdc945-9d3c-4866-9d95-8b882b8b2f23/",
  "url": "http://superapesclub.xyz",

  "result": "https://urlscan.io/result/137f4ef1-0946-4fe5-bfa5-c1aede92a7d4/",
  "url": "http://trustwallet.com-dapp.online",

  "result": "https://urlscan.io/result/168d8162-a858-407d-9bb0-40a5c96ee5f3/",
  "url": "http://trustwalletearnmoney.finance.blog",

  "result": "https://urlscan.io/result/db7e5e5d-4ac8-487a-b7ac-f571a22c4045/",
  "url": "http://trustwalletgiveaway.rf.gd",

  "result": "https://urlscan.io/result/19838355-6a6c-4a64-970d-978ae72dadee/",
  "url": "http://trustwalletstakeandearnmoney.finance.blog",

  "result": "https://urlscan.io/result/83e14bcc-9003-4c79-934f-3b1ac7f21801/",
  "url": "http://tsrocketfactory.xyz",

  "result": "https://urlscan.io/result/d597dc8c-8458-4e83-b269-be6f7b5253da/",
  "url": "http://uniswap-apps.casa",

  "result": "https://urlscan.io/result/cacea2ea-f315-4c2b-aabe-258d649a323d/",
  "url": "http://uniswap-apps.club",

  "result": "https://urlscan.io/result/bad2f9f8-21c8-475a-8c01-8fa188bd1cfd/",
  "url": "http://uniswap-apps.space",

  "result": "https://urlscan.io/result/1701204f-9d5a-4826-9580-1f6c9a66ab33/",
  "url": "http://uniswap-ecosystem.club",

  "result": "https://urlscan.io/result/a6970212-ac6a-4d36-bf49-dcf705caab3b/",
  "url": "http://uniswap-ecosystem.space",

  "result": "https://urlscan.io/result/08a054f4-8797-4150-ac50-caa5c501b3df/",
  "url": "http://uniswap-ecosystem.top",

  "result": "https://urlscan.io/result/0da54ba6-9c5f-484d-a18f-2f1b697b84cf/",
  "url": "http://uniswap-protocol.casa",

  "result": "https://urlscan.io/result/cdadd573-3617-4e4b-a5d2-3de04c08ba38/",
  "url": "http://uniswap.ltd",

  "result": "https://urlscan.io/result/182fd8d0-1953-469a-a51c-af997a6ae72d/",
  "url": "http://uniswap.ventures",

  "result": "https://urlscan.io/result/25214368-4733-45c3-8f80-d8b19c66e642/",
  "url": "http://uniswaplabs.ventures",

  "result": "https://urlscan.io/result/568aec13-2a24-4ab2-95bc-afe58f0b7485/",
  "url": "http://uniswaplendwap.top",

  "result": "https://urlscan.io/result/b6a8a0b4-7217-4536-977b-65238eb99b09/",
  "url": "http://uniswaps.cc",

  "result": "https://urlscan.io/result/d2a255d8-b402-4e16-95cf-c5ff0be26be0/",
  "url": "http://uniswapwallet.com",

  "result": "https://urlscan.io/result/0f55be0f-a26d-43a5-8eab-0fea9d6e14c3/",
  "url": "http://unxdnft.live",

  "result": "https://urlscan.io/result/d897be5a-652f-4624-af61-2cea3e688e95/",
  "url": "http://verification.coinbase-supportredit-carmail.thuongnhanv.admin.orderonlail.thuongnhanv.admin.orderonline.id",

  "result": "https://urlscan.io/result/c35fea2d-df0c-47cd-bc83-c3941109246a/",
  "url": "http://verification.coinbase-supportredit-carmail.thuongnhanv.admin.orderonline.id",

  "result": "https://urlscan.io/result/b3e08f57-4f3a-4dd4-94f9-c87fa01edbfb/",
  "url": "http://xn--pancakeswp-j7a.finance",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove duplicates
```
"app.uniswap.org.recriarcaminhos.pt"
"auth-coinbase.net"
"metamask-update.iaibserang.ac.id" 
"metamask.evolutcoin.org" 
"metamask.properties" 
"metamasks-validate.com"
"myethereumwallet.uk" 
```

Add fake balancer scam URLs
```
    "balancer-fi.ga",
    "balancer-fi.gq",
    "balancer-fi.ml",
    "balancer-fi.tk",
    "balancer-fi.cf",
```

**Review by dubstard — COMMENTED** [review]
Remove leftover duplicate
```
"app.uniswap.org.recriarcaminhos.pt",
```

**Review by dubstard — COMMENTED** [review]
Remove FP 
```
1inch.jumperbillijumper.de
```
(Just a referral link, not phishing)

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
thanks

**Pull request merged**
