### PR TITLE
Add sudoswap.xyz to fuzzylist

### PR DESCRIPTION
**Pull request by yoyyyyo**
Sudoswap is a frequently impersonated P2P marketplace / soon to be AMM protocol

### CODE REVIEW

**Comment by 409H** [comment]
Please can you add their domains to the `whitelist` section too

**Review by 409H — DISMISSED** [review]
Please put `sudoswap.xyz` in the `whitelist` array above. It is currently in the `blacklist` array.

**Review by yoyyyyo — COMMENTED** [review]
whoops, should be fixed now

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dacf** [comment]
why is sudoswap in the fuzzy list? It is causing issues with other domains with "swap" in the name.

**Pull request merged**
