### PR TITLE
whiteliste bettamask.com

### PR DESCRIPTION
**Pull request by ARbettamask**
please whitelist www.bettamask.com

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@ARbettamask  this appears to be a blacklist change. If you'd like to request a whitelist please open an issue with a description of your site.

**Comment by ARbettamask** [comment]
I open a request for whitelisted and none has respond or act on it

**Comment by AlexHerman1** [comment]
@ARbettamask please link it here

**Comment by ARbettamask** [comment]
Please look at this link I open the issue 4 times
https://github.com/MetaMask/eth-phishing-detect/issues/8042

**Pull request closed without merging**
