### PR TITLE
Block 115 wallet drainers

### PR DESCRIPTION
**Pull request by dubstard**
Let me "claim" rewards with the same wallet that i have been holding 500 ETH for 6 years. 
-----------------------
https://etherscan.io/tx/0x4b9154dbbac00f3b9c6f5c750954e3aa0db978a6761d13a22247253c77083546

Bro, do you even ...
image
image

```
Over the last several days, 100+ fake $PEPE sites have been spun up that are wallet drainers.

Totaling 713 ETH stolen. The largest single transaction had 494 ETH stolen from a wallet that has been holding for 6 years.
```
  "result": "https://urlscan.io/result/32ca4048-7a43-4a35-b3fa-e5133bd03989/",
  "url": "http://23411-5623.s1.webspace.re/",

  "result": "https://urlscan.io/result/01d16723-7edb-4782-bb6b-1942f70585cc/",
  "url": "http://account-bitpanda-at.web.app/",

  "result": "https://urlscan.io/result/972eba47-a21e-47e6-8aeb-278403fb5987/",
  "url": "http://airdrop.pepecoinhub.com/",

  "result": "https://urlscan.io/result/e347e406-aeaf-4b93-b9be-8bea09161298/",
  "url": "http://airdrop.pepelaunch.com/",

  "result": "https://urlscan.io/result/91a31948-557c-4a22-916e-c2ad3acb1fcc/",
  "url": "http://arb-cryptodrop.com/",

  "result": "https://urlscan.io/result/52fd3c81-3d52-47b9-bbd3-76fb44b08316/",
  "url": "http://arbitrum.web3-airdrop.xyz/",

  "result": "https://urlscan.io/result/184b6a24-84cb-437e-8232-239aa2e06673/",
  "url": "http://arbitrurn-drop.com/",

  "result": "https://urlscan.io/result/44a44e39-9db5-40cd-8177-306853014348/",
  "url": "http://arbpepe.net/",

  "result": "https://urlscan.io/result/aeb1adbb-1400-4ab9-8a47-52cbeae83705/",
  "url": "http://ariaeipourlawoffice.com/",

  "result": "https://urlscan.io/result/9b6fec37-3ece-4c3a-af89-d48befdf7f81/",
  "url": "http://arrb-swap.store/",

  "result": "https://urlscan.io/result/28c4d3b9-90ec-49c6-9d49-6f4d62fcb753/",
  "url": "http://ay-coinbase.xyz/",

  "result": "https://urlscan.io/result/714b778f-1e55-40b2-be18-e9faed53508d/",
  "url": "http://bgmarkazi.com/",

  "result": "https://urlscan.io/result/343e7912-1a36-4e09-ab5b-ff2d43d41b6b/",
  "url": "http://binanca-dapp.com/",

  "result": "https://urlscan.io/result/2ff2286d-5346-411c-8ccd-7646b79858b5/",
  "url": "http://binance-rewards.com/",

  "result": "https://urlscan.io/result/8eacfc09-3ce8-4782-9fb7-4ae2db8c4148/",
  "url": "http://blur-io.org.kz/",

  "result": "https://urlscan.io/result/d7756696-4633-4bf5-8b40-1c6bf1c3af32/",
  "url": "http://chain-gtp.com/",

  "result": "https://urlscan.io/result/a6b28921-c295-4012-bee0-30199140105a/",
  "url": "http://chains-gpt.com/",

  "result": "https://urlscan.io/result/e0b272ff-d8e8-48d6-bdc2-391608bfa0de/",
  "url": "http://chandkalaco.com/",

  "result": "https://urlscan.io/result/43f7065f-8f58-4692-bf92-40b4fcd44c3b/",
  "url": "http://claim-fund.online/",

  "result": "https://urlscan.io/result/9e3d466b-e64f-4364-9073-af372caf1476/",
  "url": "http://claim-pepecoin.net/",

  "result": "https://urlscan.io/result/f3315f0d-4c89-4219-b86e-dd5f89852e7f/",
  "url": "http://claimairdrops.top/",

  "result": "https://urlscan.io/result/78fe2be1-478e-4a0b-b664-7f42f97b3da0/",
  "url": "http://claimgiveaway.cyou/",

  "result": "https://urlscan.io/result/e33205fa-a0ed-44dd-8ee6-7b5c2e75b30a/",
  "url": "http://claims-pepecoin.org/",

  "result": "https://urlscan.io/result/13362442-bd92-4856-832d-36f6791491ac/",
  "url": "http://claimsfund.xyz/",

  "result": "https://urlscan.io/result/3d54802b-9dbd-40d1-98fa-3bb9a74960b7/",
  "url": "http://coinbase-com.onweshon.com/",

  "result": "https://urlscan.io/result/df2ec475-34fb-4d3a-a510-a9cd12075fe5/",
  "url": "http://coinbase-usrrecovrg.com/",

  "result": "https://urlscan.io/result/7c3fdf69-a9d3-42d2-a16e-f5805ec3422a/",
  "url": "http://coinbase-walllet.com/",

  "result": "https://urlscan.io/result/4d2796ac-e58b-48ed-9c0f-57421387b18a/",
  "url": "http://coinbasealert.app/",

  "result": "https://urlscan.io/result/1134fc58-78c0-40c9-8dfd-4572c8193814/",
  "url": "http://coinbaseclaims.com/",

  "result": "https://urlscan.io/result/e9f8e2f4-0e4b-4206-8651-087f34166401/",
  "url": "http://coinshub.top/",

  "result": "https://urlscan.io/result/760f1782-6e8a-4891-93b1-6c50e3016ad8/",
  "url": "http://cointry.gq/",

  "result": "https://urlscan.io/result/d8450648-a736-4b40-bdf0-b3fb7f3a2494/",
  "url": "http://collab.pm/",

  "result": "https://urlscan.io/result/6385676c-d53b-4cd2-aa5c-17981a497f1b/",
  "url": "http://com-loginq1.info/",

  "result": "https://urlscan.io/result/3c1e13c3-a1b5-4aa6-8da1-b5f256e20f5d/",
  "url": "http://connect-openai.com/",

  "result": "https://urlscan.io/result/bbfd5c5c-479e-43d5-bf20-78186e3c55d3/",
  "url": "http://crosschbridges.site/",

  "result": "https://urlscan.io/result/b2960a80-4212-4f16-806d-3dc84a065ef5/",
  "url": "http://dapps-website.firebaseapp.com/",

  "result": "https://urlscan.io/result/c506faa9-da34-4a09-9842-706452424804/",
  "url": "http://decentralizetools.site/",

  "result": "https://urlscan.io/result/b97f5be5-3e9e-46b1-ab85-8e66ad80002e/",
  "url": "http://deelance-official.com/",

  "result": "https://urlscan.io/result/d8854932-20b5-4598-b2f8-4b49b5f7f9b0/",
  "url": "http://deelance-presale.com/",

  "result": "https://urlscan.io/result/81d5d602-ff47-40a2-8d3b-6bf492dcf46e/",
  "url": "http://defijump.live/",

  "result": "https://urlscan.io/result/8b896036-3150-4f24-9f54-4566a67d28ed/",
  "url": "http://digital-hub.top/",

  "result": "https://urlscan.io/result/cd70f443-290e-422e-9694-5be59f11dfe4/",
  "url": "http://droidapp.cloud/",

  "result": "https://urlscan.io/result/962eeeb3-0bc6-4f48-b1d7-89f41fb76f14/",
  "url": "http://ecoterra-official.com/",

  "result": "https://urlscan.io/result/da668d64-94a8-4ca3-ab57-29d4d4a723b7/",
  "url": "http://ecoterra-presale.com/",

  "result": "https://urlscan.io/result/1d522959-8ab6-435b-817c-e70a6fe802e4/",
  "url": "http://elonmusk-giveaway.xyz/",

  "result": "https://urlscan.io/result/c98f7895-1e26-43e1-9a1a-dded987f05c2/",
  "url": "http://healthywayservice.com/",

  "result": "https://urlscan.io/result/64123d88-8239-4ea1-b99a-e49ddbbf4f1a/",
  "url": "http://hex-nft.com/",

  "result": "https://urlscan.io/result/ca2fa36a-fc98-4395-8c30-8ff1806038dd/",
  "url": "http://hnmdraintest1.xyz/",

  "result": "https://urlscan.io/result/43cdeac3-ed19-42b5-907d-6e8ac9ad0751/",
  "url": "http://ledger-sync-live.web.app/",

  "result": "https://urlscan.io/result/8e624e50-afa3-4aa0-a177-88c662337d4c/",
  "url": "http://ledgerlive-synchronize.web.app/",

  "result": "https://urlscan.io/result/dff7e6b4-3374-4655-a562-e8a5eb80f401/",
  "url": "http://lens-protocel.com/",

  "result": "https://urlscan.io/result/dfe9fe2c-8087-4e2f-935a-a5a397bacd68/",
  "url": "http://lens-protocul.com/",

  "result": "https://urlscan.io/result/30229b3d-297a-4f9d-9d79-c592b5bbbdcc/",
  "url": "http://metamask-io.click/",

  "result": "https://urlscan.io/result/e830798b-f532-4d25-91a3-bce36af5e723/",
  "url": "http://metamask-unlock-wallet-943943837.fartit.com/",

  "result": "https://urlscan.io/result/03a8b6f5-14b5-4e2b-814a-4660ff7b05d3/",
  "url": "http://metamask.xlylh6.top/",

  "result": "https://urlscan.io/result/88a18c7a-3ee4-49d4-a8c5-464f3e309b67/",
  "url": "http://metamaskmsa.com/",

  "result": "https://urlscan.io/result/0ef3e1ee-7b0c-4d41-8deb-b58a2a143d99/",
  "url": "http://metamaskstoken.com/",

  "result": "https://urlscan.io/result/1554dc51-a6f6-4175-a69e-6d4c51f593a9/",
  "url": "http://moonwell.netlify.app/",

  "result": "https://urlscan.io/result/c04a1736-97ac-4e67-9429-528529300a41/",
  "url": "http://nakamigos.top/",

  "result": "https://urlscan.io/result/f21388e9-b327-4853-b8e4-dc10912a6eaa/",
  "url": "http://optimism2.online/",

  "result": "https://urlscan.io/result/a5d52a29-956c-4a11-b4c4-250c17ebfe42/",
  "url": "http://optimismcrypto.com/",

  "result": "https://urlscan.io/result/c53f2ec7-67ce-4c2d-a0ad-e739f67cbde8/",
  "url": "http://orthopedicsurgerysandiego.com/",

  "result": "https://urlscan.io/result/4febbc56-71f5-46e6-aed8-67a52d8b0bb5/",
  "url": "http://pancakeswap.agency/",

  "result": "https://urlscan.io/result/20c07b5c-f638-4cee-9ec8-7b2fe20971e1/",
  "url": "http://pancakeswap.wtf/",

  "result": "https://urlscan.io/result/d2e08f8e-33e2-428a-9200-1f0384db57e7/",
  "url": "http://pancakeswapt.com/",

  "result": "https://urlscan.io/result/06f52892-790e-4683-8b4c-9c5de6c46747/",
  "url": "http://pepecoin-airdrop.org/",

  "result": "https://urlscan.io/result/08473492-e1a8-43f2-bc78-d7f530bf736f/",
  "url": "http://pepecoin.cx/",

  "result": "https://urlscan.io/result/c2c0493b-fd32-4719-9b7d-de403df218bd/",
  "url": "http://pepelp.net/",

  "result": "https://urlscan.io/result/e2c61053-9be6-47fa-ae5d-1e4f2a3663f1/",
  "url": "http://pepenft.fun/",

  "result": "https://urlscan.io/result/a4c6197a-22dc-4451-a1dc-ae57be062abe/",
  "url": "http://pepenft.ink/",

  "result": "https://urlscan.io/result/35c3235c-06d8-49e6-a5f7-5f71a24318af/",
  "url": "http://pepesnft.vip/",

  "result": "https://urlscan.io/result/020ecd45-6799-4565-b385-a152b2bb1875/",
  "url": "http://printthemong.com/",

  "result": "https://urlscan.io/result/44f747d7-c5e5-4dfd-9cac-7404c6e72643/",
  "url": "http://reclaimyourcrypto.com/",

  "result": "https://urlscan.io/result/82e505da-9488-4f9e-bf10-fc3a5a07ce8f/",
  "url": "http://semillasplantae.com/",

  "result": "https://urlscan.io/result/204bca86-757f-4a21-b6b7-11c2fadb280b/",
  "url": "http://sldegypt.com/",

  "result": "https://urlscan.io/result/e4cde5fb-e336-4fda-8570-eb0e74558c0e/",
  "url": "http://spaceid-crypto.com/",

  "result": "https://urlscan.io/result/f667258d-7225-4a4c-923c-61cbd602ee9a/",
  "url": "http://swordcofblood.com/",

  "result": "https://urlscan.io/result/265a1020-65bd-4a76-96d7-5f3688f45e3d/",
  "url": "http://synthetikx.io/",

  "result": "https://urlscan.io/result/d90af74e-491b-4837-82cb-8d8a51fbc9b4/",
  "url": "http://synthetix-claim.xyz/",

  "result": "https://urlscan.io/result/b02d1769-7301-40df-9f02-7086fb60cecd/",
  "url": "http://teslamusk-promo.info/",

  "result": "https://urlscan.io/result/3b92796f-b8ce-418f-9c75-6a66a5091db0/",
  "url": "http://teslapromo-2023.net/",

  "result": "https://urlscan.io/result/7ea90fec-058f-455b-9cf1-e4279756a3b6/",
  "url": "http://uniswap-exchange.gb.net/",

  "result": "https://urlscan.io/result/5b9983c9-e792-4274-8c43-3822338d7bf6/",
  "url": "http://uniswap-v3-positions.metabench.io/",

  "result": "https://urlscan.io/result/712d7846-7acb-4926-b14f-e101a114cb9b/",
  "url": "http://uniswap-v3-positions.mintingsmart.io/",

  "result": "https://urlscan.io/result/16412208-2b9f-4c48-b460-7d3fd693b54f/",
  "url": "http://uniswap.agency/",

  "result": "https://urlscan.io/result/af37ec2b-ab01-4e52-b1e5-e934f29bc4b1/",
  "url": "http://uniswap.app.org.kz/",

  "result": "https://urlscan.io/result/05030ead-bb47-408f-8f26-8731ffc36724/",
  "url": "http://uniswap.digital/",

  "result": "https://urlscan.io/result/2e373889-d884-4131-a5f6-55ff80e00713/",
  "url": "http://uniswap.vote/",

  "result": "https://urlscan.io/result/7f706ac2-b876-4178-b49e-0f97f6e529b9/",
  "url": "http://uploadid-support-coinbase.com/",

  "result": "https://urlscan.io/result/9a79b632-43df-449a-9f12-13a4f0bf3aba/",
  "url": "http://walletconnect-protocol.info/",

  "result": "https://urlscan.io/result/3ac58e0e-b56b-4b17-84cd-801b4ba4a5ab/",
  "url": "http://walletconnectcz.gq/",

  "result": "https://urlscan.io/result/016aeca8-2cce-42ee-a678-d224e930a591/",
  "url": "http://web3-wallet6.com/",

  "result": "https://urlscan.io/result/482ccfff-8a98-4f3e-99d4-3d024bef4727/",
  "url": "http://web3dapps.org/",

  "result": "https://urlscan.io/result/ec9f28e6-8a14-4234-bed0-2cd279363ad2/",
  "url": "http://web3pz.ml/",

  "result": "https://urlscan.io/result/e0565b81-11e1-4770-8523-fb8d68fb5206/",
  "url": "http://x-pad.top/",

  "result": "https://urlscan.io/result/1c24efe9-d330-404a-ac71-4a0f3e1838a3/",
  "url": "http://xrpevent-bonus.com/",
```
    "23411-5623.s1.webspace.re",
    "account-bitpanda-at.web.app",
    "airdrop-rewardclaimed.com",
    "airdrop.pepecoinhub.com",
    "airdrop.pepelaunch.com",
    "arb-cryptodrop.com",
    "arbgettrum.online",
    "arbitgetline.site",
    "arbitrum.web3-airdrop.xyz",
    "arbitrurn-drop.com",
    "arbpepe.net",
    "ariaeipourlawoffice.com",
    "arrb-swap.store",
    "ay-coinbase.xyz",
    "bgmarkazi.com",
    "binanca-dapp.com",
    "binance-nft-prize.com",
    "binance-rewards.com",
    "blur-io.org.kz",
    "chain-gtp.com",
    "chains-gpt.com",
    "chandkalaco.com",
    "claim-fund.online",
    "claim-pepecoin.net",
    "claimairdrops.top",
    "claimgiveaway.cyou",
    "claims-pepecoin.org",
    "claimsfund.xyz",
    "coinbase-apps.top",
    "coinbase-com.onweshon.com",
    "coinbase-usrrecovrg.com",
    "coinbase-walllet.com",
    "coinbasealert.app",
    "coinbaseclaims.com",
    "coinshub.top",
    "cointry.gq",
    "collab.pm",
    "com-claims.us",
    "com-loginq1.info",
    "connect-openai.com",
    "crosschbridges.site",
    "dapps-website.firebaseapp.com",
    "dapptestverification.com",
    "dapptrustline.xyz",
    "decentralizetools.site",
    "deelance-official.com",
    "deelance-presale.com",
    "defijump.live",
    "dexresolve.io",
    "digital-hub.top",
    "droidapp.cloud",
    "ecoterra-official.com",
    "ecoterra-presale.com",
    "elonmusk-giveaway.xyz",
    "fixerrorsapp.live",
    "healthywayservice.com",
    "hex-nft.com",
    "hnmdraintest1.xyz",
    "ledger-sync-live.web.app",
    "ledger.live.secure-0541-cloud.com",
    "ledgerlive-synchronize.web.app",
    "lens-protocel.com",
    "lens-protocul.com",
    "mainfix.live",
    "metamask-io.click",
    "metamask-unlock-wallet-943943837.fartit.com",
    "metamask.xlylh6.top",
    "metamaskmsa.com",
    "metamaskstoken.com",
    "moonwell.netlify.app",
    "nakamigos.top",
    "onblurline.store",
    "onlinelocalhost.space",
    "onlineshibu.site",
    "onshibu.store",
    "optimism2.online",
    "optimismcrypto.com",
    "orthopedicsurgerysandiego.com",
    "pancakeswap.agency",
    "pancakeswap.wtf",
    "pancakeswapt.com",
    "pepecoin-airdrop.org",
    "pepecoin.cx",
    "pepelp.net",
    "pepenft.fun",
    "pepenft.ink",
    "pepesnft.vip",
    "printthemong.com",
    "rarityweb-3launchpads.com",
    "reclaimyourcrypto.com",
    "resolveapps.live",
    "resolvewebappnet.online",
    "resolvewebappnet.site",
    "scurencrypt.com",
    "semillasplantae.com",
    "servermetamask.ddns.net",
    "sldegypt.com",
    "spaceid-crypto.com",
    "swordcofblood.com",
    "synthetikx.io",
    "synthetix-claim.xyz",
    "teslamusk-promo.info",
    "teslapromo-2023.net",
    "uniswap-exchange.gb.net",
    "uniswap-v3-positions.metabench.io",
    "uniswap-v3-positions.mintingsmart.io",
    "uniswap.agency",
    "uniswap.app.org.kz",
    "uniswap.digital",
    "uniswap.vote",
    "uploadid-support-coinbase.com",
    "walletconnect-protocol.info",
    "walletconnectcz.gq",
    "web3-wallet6.com",
    "web3dapps.org",
    "web3pz.ml",
    "wuuuoofi.cloud",
    "x-pad.top",
    "xrpevent-bonus.com",
    "yogetline.site",
    "yumyumon.space",
```

### CODE REVIEW

**Comment by dubstard** [comment]
We already have `pepelaunch.com` blocked, so `airdrop.pepelaunch.com` is not needed, gonna get rid of it.
Bro do you even lift?

**Comment by dubstard** [comment]
'arbitrum.web3-airdrop.xyz' already covered by 'web3-airdrop.xyz' in 'blacklist'.
So we don't need `arbitrum.web3-airdrop.xyz`
Gonna get rid of it.

**Comment by dubstard** [comment]
`uniswap-exchange.gb.net` is not needed as we already have `gb.net` backlisted
Gonna get rid of it.

**Comment by dubstard** [comment]
`uniswap-v3-positions.metabench.io` already covered by 'metabench.io' in 'blacklist'.

how extremely sad *.metabench.io = blocked, RIP.

gonna get rid of this one with the subdomain.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
