### PR TITLE
DxSale Phishing pages update

### PR DESCRIPTION
**Pull request by DaRabus**
Hey Guys, as always, new phishing pages are live.

Real page:

dxsale.app

### CODE REVIEW

**Review by AlexHerman1 — DISMISSED** [review]
LGTM.

**Comment by davidwgrossman** [comment]
Hey @DaRabus, the indentation on some of the lines looks off. Could you please fix the indentation?

**Comment by DaRabus** [comment]
I added some more and checked the Ident, seems fine for me, and I use Notepad++

**Comment by DaRabus** [comment]
Guys?

Can you merge this once?

Like 2 weeks now, people loosing money daily on these pages...

**Review by gravelcycles — APPROVED** [review]

**Review by gravelcycles — APPROVED** [review]

**Comment by davidwgrossman** [comment]
@DaRabus no worries! I think the issue is that indentation in this file is using tabs and the lines that seemed off were using spaces.

**Pull request merged**
