### PR TITLE
[Legitimate Site Blocked] arctis.tech

### PR DESCRIPTION
**Pull request by weisser-dev**

### CODE REVIEW

**Comment by 409H** [comment]
https://urlscan.io/result/1005ca6d-dfb3-43f0-bc02-a576dab4fec4/

**Review by 409H — CHANGES_REQUESTED** [review]
`scrumbuddy.org` is not detected and blocked by MetaMask - please remove from this list.

**Review by 409H — DISMISSED** [review]

**Review by AlexHerman1 — DISMISSED** [review]
LGTM.

**Comment by AlexHerman1** [comment]
@weisser-dev  please update branch thanks

**Comment by weisser-dev** [comment]
@AlexHerman1 done!

**Comment by AlexHerman1** [comment]
@weisser-dev  sorry its still out of date

**Comment by weisser-dev** [comment]
@409H @AlexHerman1 could you guys pls merge this...

**Review by 409H — APPROVED** [review]

**Comment by AlexHerman1** [comment]
@weisser-dev can you close and re-open this under a new PR

**Pull request closed without merging**
