### PR TITLE
Add sites to blocklist

### PR DESCRIPTION
**Pull request by ShenWe0x**
Add sites to blocklist

Phishing Airdrop Claim website

https://twitter.com/Anaedoonline_/status/1747916567709397181
https://twitter.com/ENDYDAZ/status/1749035025809457554
https://twitter.com/sonusahu145/status/1748419929680843064
https://twitter.com/rockefellareth/status/1749066439036956676
https://twitter.com/7_bmab/status/1749124868124426428
https://twitter.com/investbaotou/status/1749118899759812832
https://twitter.com/dhal_s0l/status/1748612643902853127

### CODE REVIEW

**Comment by PrivateMiner** [comment]
@ShenWe0x Any updates on the tornado investigation? I guess the people I tagged in the thread didn't see it. We still haven't received a response.

https://github.com/MetaMask/eth-phishing-detect/pull/14941#issuecomment-1891039341

Could you look at the issue from here? As a result of suspicions, investigations were made, but no admin saw it.

**Comment by ShenWe0x** [comment]
@PrivateMiner 
I examined the suspicious js files, made the necessary explanations and asked what should be done about the domain, but I did not receive an answer, so I guess they did not see it, I think they will see it in this PR, we will act accordingly or you can create a new issue about it.

**Comment by PrivateMiner** [comment]
While this PR is being examined, I think they will examine the other issue. It is a serious problem and everyone thinks they are official, so the review is important.

Please, while this PR is being reviewed, we need to examine the above issue and discuss what should be done about the domain.

**Comment by ShenWe0x** [comment]
I've come to realize that you were right about the suspicions. I had sent the code to the ESET team for review via email, and they flagged the website as containing content that 'may be of unwanted type.' They identified a problem in the JavaScript file on the website that you had found.

**Comment by ShenWe0x** [comment]
I haven't received any feedback, but if it weren't for suspicious code, they wouldn't have added this warning for sure.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
