### PR TITLE
A Catch Up on Impersonation Domains

### PR DESCRIPTION
**Pull request by rpolysec**
Doing a quick check for polygon related malicious domains that weren't in metamask list yet and do resolve based on all the malicious domains I've collected this year. The check for duplicates was automated with manual spot checks and should be good. Apologies in advance if I somehow messed this up.

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@rpolysec  thanks, please fix dupes.

**Comment by rpolysec** [comment]
Sorry, thought I had this right. I'll fix this.

**Comment by AlexHerman1** [comment]
@rpolysec  still have dupes in this

**Review by rpolysec — COMMENTED** [review]
If I accept this review does it automatically remove or do I have to generate a new commit?

**Comment by AlexHerman1** [comment]
i think you have to generate a new commit

**Comment by rpolysec** [comment]
I closed this pull request and deleted my path branch. I'll create a brand new request.

Turns out my script that was doing deduping on my end was grabbing an older version of config.json which led to it thinking there weren't any duplicates when there were. Should be fixed, will get a new commit request soon.

**Pull request closed without merging**
