### PR TITLE
chore: add `app.beefy.finance` to blacklist

### PR DESCRIPTION
**Pull request by tp26610**

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by DefiDebauchery** [comment]
Why was this site blocked and this merge approved? @AlexHerman1 @tp26610 

`app.beefy.finance` is a legitimate URL for Beefy.

**Comment by DefiDebauchery** [comment]
Fixed in https://github.com/MetaMask/eth-phishing-detect/pull/14223. Thanks for the quick reversion!

**Comment by tp26610** [comment]
> Fixed in #14223. Thanks for the quick reversion!

@DefiDebauchery I'm so sorry for adding the wrong site to blocklist

**Pull request merged**
