### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
**Add 120 scam URLs** 
Not the 1inch you need
```
		"1inch.exchange.analiticaregional.com",
		"1inch.win",
		"1inch.zone",
		"app-1inch.net",
		"withered-ancient-breeze.lb.1inch.zone",	
		"1inchairdrop.info",
		"email.1inchairdrop.info",
		"inch-uniswap.com",	
```

Not the Coinmarketcap you need
```
		"1coinmarketcap.site",
		"3coinmarketcap.site",
		"6coinmarketcap.site",
		"7coinmarketcap.site",
		"8coinmarketcap.site",
		"5coinmarketcap.site",
		"9coinmarketcap.site",
		"coinmarket500.com",
		"coinmarketcap1.com",
		"coinmarketcap3x.com",
		"coinmarketcap5.com",
		"coinmarketcap500.com",
		"coinmarketcap8.com",
		"coinmarketcapann.com",
```

Not the Coinbase you need
```
		"bitcoin-code-coinbase.com",
		"bitcoin-prime-coinbase.com",
		"bitcoin-profit-coinbase.com",
		"coinbase-supporto.com",
		"coinbase-update-account.com",
		"coinbasebank.co",
		"coinbasebank.xyz",
		"coinbasedefiwallet.net",
		"secure-id-verification-coinbase.com",		
		"support01-coinbase.com",
		"supportd-coinbase.com",
		"verification-secure-coinbase.com",

```

Not the Pancakeswap you need
```
		"1pancakeswap-finance.site",
		"2pancakeswap-finance.site",
		"3pancakeswap-finance.site",
		"4pancakeswap-finance.site",
		"5pancakeswap-finance.site",
		"6pancakeswap-finance.site",
		"7pancakeswap-finance.site",
		"8pancakeswap-finance.site",
		"9pancakeswap-finance.site",
		"usdt.pancakeswep.wang",
		"p-pancakeswap.finance",
		"pancake100x.finance",
		"pancakesvqp.com",
		"pancakeswap-exchange.in",
		"pancakeswap-finance-liquidity-pool.site",
		"pancakeswap-finance.com",
		"pancakeswap.badcryptom.xyz",
		"pancakeswap.cloud",
		"pancakeswap.cn.com",
		"pancakeswap.syncedwallet.com",
		"pancakeswap.uk",
		"pancakeswapefinance.app",
		"pancakeswapfinancin.app",
		"pancakeswapgear.com",
		"pancakeswapps.net",
		"pancakeswapsinc.com",
		"pancakeswep.wang",
		"pancakeswin.click",
		"payment.pancakesvqp.com",
		"photos.pancakesvqp.com",
		"pubregistry.com.pancakeswap.fund.nifraud.com",
		"app.pancakesvqp.com",
		"app1.pancakeswap.cn.com",
		"board.pancakesvqp.com",
		"cake.pancakeswap.cn.com",
		"calendar.pancakesvqp.com",
		"file.pancakesvqp.com",
		"itemap.pancakesvqp.com",
		"kf.pancokeswap.com",
		"live.pancakesvqp.com",
		"llve.pancakesvqp.com",
		"main.pancakesvqp.com",
		"master.pancakesvqp.com",		
		"metapancakeswap.com",
		"file.pancakesvqp.com",
		"itemap.pancakesvqp.com",
		"kf.pancokeswap.com",
		"live.pancakesvqp.com",
		"llve.pancakesvqp.com",
		"main.pancakesvqp.com",
		"master.pancakesvqp.com",		
		"metapancakeswap.com",
		"sp.pancakesvqp.com",
		"traefik.pancakeswap.cn.com",
		"uk.pancakesvqp.com",
		"correo.pancakesvqp.com",
```
Not the Uniswap you need

```
		"4vvuniswap.top",
		"uniswap-allocation.top",
		"uniswap-alt.space",
		"uniswap-entirety.casa",
		"uniswap-entirety.top",
		"uniswap-fill.casa",
		"uniswap-fill.top",
		"uniswap-pro.cc",
		"uniswap-proved.casa",
		"uniswap-proved.top",
		"uniswap-trc.com",
		"uniswap.cat",
		"uniswap.com.mx",
		"uniswap.descipher.io",
		"uniswap.fish",
		"uniswapens.com",
		"uniswapex.io",
		"uniswapexchange.biz",
		"inch-uniswap.com",
		"myuniswap.space",		
```

Not the Metamask you need
```
		"metamask-extension.com.ecovillequimica.com.br",
		"metamask-wallet-verification.com",
		"metamask.biz",
		"metamask.fund",
		"metamask.io.in",
		"metamask.io.log692348.in",
		"metamask.pub",
		"metamask.store",
		"metamask.zone",
		"metamaskc.cc",
		"metamasks.io",
		"metamaskwebwallet.com",
		"metapancakeswap.com",
		"glfts-metamask-io.is-best.net",
		"world-metamask.com",
```

Not the MEW you need
```
		"bettercallbaylee.com.metherwallet.com",
```

Not the ARK Invest you need
```
		"arkinvest-crypto.com",
		"arkinvest-elonmusk.com",
		"arkinvest-musk.com",
		"ark-innovation.net",
		"cryptoarkinvestments.com",
		"cryptoarkinvestments.com.sensaart.com",
		"elonmusk-arkinvest.com",
```

Not the Airdrop you need
```
		"3xairdrop.com",
		"airdrop-spherefinance.app",
		"claim-airdrop.duckdns.org",
		"1inchairdrop.info",
		"giveaway3x.com",
		"ethereum-trust.org",
```

Not the Wallet Connect you need
```
		"all-in-one-sync.com",
		"neutralquickauths.pro",
		"nftethereum.xyz",
		"syncdefiwallet.co",
```

Not the Trustwallet you need
```
		"trustwallet-airdrops.nftwealths.com",
		"trustwallet.com.web3-update.cc",
```

Not the Polygon Matic you need
```
		"web-polygonwallet.icu",		

```

Full list (without the duplicates):
```
		"1coinmarketcap.site",
		"1inch.exchange.analiticaregional.com",
		"1inch.win",
		"1inch.zone",
		"1pancakeswap-finance.site",
		"2pancakeswap-finance.site",
		"3coinmarketcap.site",
		"3pancakeswap-finance.site",
		"3xairdrop.com",
		"4pancakeswap-finance.site",
		"4vvuniswap.top",
		"5coinmarketcap.site",
		"5pancakeswap-finance.site",
		"6coinmarketcap.site",
		"6pancakeswap-finance.site",
		"7coinmarketcap.site",
		"7pancakeswap-finance.site",
		"8coinmarketcap.site",
		"8pancakeswap-finance.site",
		"9coinmarketcap.site",
		"9pancakeswap-finance.site",
		"airdrop-spherefinance.app",
		"airdrop.apexcrypto.xyz",
		"airdrop.cryptoarena.org",
		"airdropfund.finance.blog",
		"all-in-one-sync.com",
		"allcryptowallets.com",
		"an-nft-dapp.webapps.authentic.network",
		"api.ethereumfear.com",
		"app-1inch.net",
		"app1.pancakeswap.cn.com",
		"ark-innovation.net",
		"arkinvest-crypto.com",
		"arkinvest-elonmusk.com",
		"arkinvest-musk.com",
		"bettercallbaylee.com.metherwallet.com",
		"bitcoin-code-coinbase.com",
		"bitcoin-prime-coinbase.com",
		"bitcoin-profit-coinbase.com",
		"cake.pancakeswap.cn.com",
		"claim-airdrop.duckdns.org",
		"coinbase-supporto.com",
		"coinbase-update-account.com",
		"coinbasebank.co",
		"coinbasebank.xyz",
		"coinbasedefiwallet.net",
		"coinmarket500.com",
		"coinmarketcap1.com",
		"coinmarketcap3x.com",
		"coinmarketcap5.com",
		"coinmarketcap500.com",
		"coinmarketcap8.com",
		"coinmarketcapann.com",
		"cryptoarkinvestments.com",
		"cryptoarkinvestments.com.sensaart.com",
		"elonmusk-arkinvest.com",
		"email.1inchairdrop.info",
		"ethereum-trust.org",
		"giveaway3x.com",
		"glfts-metamask-io.is-best.net",
		"inch-uniswap.com",
		"kf.pancokeswap.com",
		"metamask-extension.com.ecovillequimica.com.br",
		"metamask-io.pages.dev",
		"metamask-wallet-verification.com",
		"metamask.biz",
		"metamask.com.mx",
		"metamask.composable.hycom.digital",
		"metamask.fund",
		"metamask.id",
		"metamask.io.id74853758.in",
		"metamask.io.in",
		"metamask.io.log692348.in",
		"metamask.pub",
		"metamask.store",
		"metamask.zone",
		"metamaskc.cc",
		"metamaskio.win",
		"metamasks.io",
		"metamaskwebwallet.com",
		"metapancakeswap.com",
		"myuniswap.space",
		"neutralquickauths.pro",
		"nftethereum.xyz",
		"nftuniswap.com",
		"p-pancakeswap.finance",
		"pancake100x.finance",
		"pancakeswap-exchange.in",
		"pancakeswap-finance-liquidity-pool.site",
		"pancakeswap-finance.com",
		"pancakeswap.badcryptom.xyz",
		"pancakeswap.cloud",
		"pancakeswap.cn.com",
		"pancakeswap.syncedwallet.com",
		"pancakeswap.uk",
		"pancakeswapefinance.app",
		"pancakeswapfinancin.app",
		"pancakeswapsinc.com",
		"pancakeswep.wang",
		"pancakeswin.click",
		"pubregistry.com.pancakeswap.fund.nifraud.com",
		"support01-coinbase.com",
		"supportd-coinbase.com",
		"syncdefiwallet.co",
		"traefik.pancakeswap.cn.com",
		"trustwallet.com.web3-update.cc",
		"uniswap-pro.cc",
		"uniswap-trc.com",
		"uniswap.cat",
		"uniswap.com",
		"uniswap.descipher.io",
		"uniswap.fish",
		"uniswapens.com",
		"uniswapex.io",
		"uniswapexchange.biz",
		"usdt.pancakeswep.wang",
		"web-polygonwallet.icu",
		"withered-ancient-breeze.lb.1inch.zone",
		"world-metamask.com",
```

```
$ ./BurnTrash.sh | egrep '(result|url)'

  "result": "https://urlscan.io/result/400c46e1-af96-4ff4-baf5-716906cef25c/",
  "url": "http://1coinmarketcap.site",

  "result": "https://urlscan.io/result/a075a21f-9e38-4bdd-a0cf-b777414bcf03/",
  "url": "http://1inch.exchange.analiticaregional.com",

  "result": "https://urlscan.io/result/42ede3e0-cb91-4caf-91be-b313edce8a9a/",
  "url": "http://1inch.win",

  "result": "https://urlscan.io/result/b5a165b3-85e0-432b-a7a1-1a391a547063/",
  "url": "http://3coinmarketcap.site",

  "result": "https://urlscan.io/result/e1d5644e-6f5d-43fc-9ec7-6dab338ee688/",
  "url": "http://3xairdrop.com",

  "result": "https://urlscan.io/result/e54092b1-e383-4f2c-bad5-040eec3144cd/",
  "url": "http://4vvuniswap.top",

  "result": "https://urlscan.io/result/726f94ee-424e-4f35-b542-ebe49c5d4e04/",
  "url": "http://5coinmarketcap.site",

  "result": "https://urlscan.io/result/a138fffd-eab1-47e3-b37d-08b3db11a60b/",
  "url": "http://5pancakeswap-finance.site",

  "result": "https://urlscan.io/result/ef87e2a7-12c3-48db-b445-df75bfa31b65/",
  "url": "http://6coinmarketcap.site",

  "result": "https://urlscan.io/result/a60860bf-3ac8-4dd4-9e0a-86ee4425b50a/",
  "url": "http://7coinmarketcap.site",

  "result": "https://urlscan.io/result/fab75c88-72b0-4600-9a8f-1c6df8c727b1/",
  "url": "http://8coinmarketcap.site",

  "result": "https://urlscan.io/result/04d4a3cf-c744-4535-ac4b-f37a7034f979/",
  "url": "http://9coinmarketcap.site",

  "result": "https://urlscan.io/result/482e4dea-f1e4-4b47-a247-316b41628948/",
  "url": "http://airdrop-spherefinance.app",

  "result": "https://urlscan.io/result/c727cccc-04ed-4fe3-91d1-d06919ca5b99/",
  "url": "http://airdrop.apexcrypto.xyz",

  "result": "https://urlscan.io/result/13eb7b62-72ca-4490-9b79-7d955b7815de/",
  "url": "http://airdrop.cryptoarena.org",

  "result": "https://urlscan.io/result/28650ed6-0200-473d-a1ef-13d64f5500a7/",
  "url": "http://airdropfund.finance.blog",

  "result": "https://urlscan.io/result/cb85b33e-72d9-44ba-8d8b-cd2a3444d484/",
  "url": "http://allcryptowallets.com",

  "result": "https://urlscan.io/result/9b8d492e-8807-4fc6-9ed6-7dc0f8ed63fb/",
  "url": "http://an-nft-dapp.webapps.authentic.network",

  "result": "https://urlscan.io/result/a318bb8d-36f4-4d2e-9063-fc5585974aff/",
  "url": "http://result.ethereumfear.com",

  "result": "https://urlscan.io/result/3ac8843d-990a-4165-93df-270aa228b2a3/",
  "url": "http://app-1inch.net",

  "result": "https://urlscan.io/result/df45921e-9090-4f05-b6fa-9eb7bd32b75c/",
  "url": "http://app.pancakesvqp.com",

  "result": "https://urlscan.io/result/e5198b00-9385-4329-b9d9-1ed26128cd48/",
  "url": "http://app1.pancakeswap.cn.com",

  "result": "https://urlscan.io/result/d65eb904-2472-4d74-92f1-77f9fe95d172/",
  "url": "http://ark-innovation.net",

  "result": "https://urlscan.io/result/1b388c43-1e02-4c80-8912-0c71749de875/",
  "url": "http://bettercallbaylee.com.metherwallet.com",

  "result": "https://urlscan.io/result/99891ea1-beb6-4aeb-ad2c-28c76bb8f4a1/",
  "url": "http://bitcoin-code-coinbase.com",

  "result": "https://urlscan.io/result/ba459de9-d6e6-41b4-bcf5-4ccea100f840/",
  "url": "http://bitcoin-prime-coinbase.com",

  "result": "https://urlscan.io/result/32d4b017-9448-4048-8353-d79b3901ef39/",
  "url": "http://bitcoin-profit-coinbase.com",

  "result": "https://urlscan.io/result/a3891cee-8803-4c6a-beff-3de118f0eec6/",
  "url": "http://board.pancakesvqp.com",

  "result": "https://urlscan.io/result/69d0fe60-f431-463a-9404-a7ce64782cb5/",
  "url": "http://cake.pancakeswap.cn.com",

  "result": "https://urlscan.io/result/96564e24-878f-4e18-bf6b-6a96ae8d621c/",
  "url": "http://calendar.pancakesvqp.com",

  "result": "https://urlscan.io/result/bbbf9c7d-81ab-484a-8604-be671338fcd3/",
  "url": "http://claim-airdrop.duckdns.org",

  "result": "https://urlscan.io/result/6345583d-dd14-483e-b5be-a393defc6477/",
  "url": "http://coinbase-update-account.com",

  "result": "https://urlscan.io/result/6a505fd7-e200-4423-bf8a-16882c75f009/",
  "url": "http://coinbasebank.co",

  "result": "https://urlscan.io/result/e686488f-ca02-4d23-b725-1323a7740918/",
  "url": "http://coinbasebank.xyz",

  "result": "https://urlscan.io/result/afd90312-87f7-4590-b860-b81ee8849cd1/",
  "url": "http://coinbasedefiwallet.net",

  "result": "https://urlscan.io/result/064d5e1a-000a-4404-86ed-22e3f3ac0960/",
  "url": "http://coinmarket500.com",

  "result": "https://urlscan.io/result/7325cff0-f382-4c2f-8caf-fed3f1f9d25f/",
  "url": "http://coinmarketcap3x.com",

  "result": "https://urlscan.io/result/bf84f73f-2930-43dc-95d2-6bb2b5333068/",
  "url": "http://coinmarketcap5.com",

  "result": "https://urlscan.io/result/6e6b1160-a723-4c10-85fb-cfd74ac9e332/",
  "url": "http://coinmarketcap500.com",

  "result": "https://urlscan.io/result/d80ba936-284d-45b6-bd1c-4b018a1c19a4/",
  "url": "http://coinmarketcap8.com",

  "result": "https://urlscan.io/result/bf084997-4f41-4506-9550-5aef3794255c/",
  "url": "http://correo.pancakesvqp.com",

  "result": "https://urlscan.io/result/15c48027-1cee-4834-b175-f11d29b31119/",
  "url": "http://cryptoarkinvestments.com",

  "result": "https://urlscan.io/result/b0ffc997-e4fb-4229-bdd8-738e0ac45cf7/",
  "url": "http://cryptoarkinvestments.com.sensaart.com",

  "result": "https://urlscan.io/result/4a8308f8-4eb6-419a-9248-d985f1284a99/",
  "url": "http://email.1inchairdrop.info",

  "result": "https://urlscan.io/result/ad9838c5-55bf-4698-bdff-9f008966de3f/",
  "url": "http://ethereum-trust.org",

  "result": "https://urlscan.io/result/5ade5925-604e-4483-8674-7b0f8355137d/",
  "url": "http://file.pancakesvqp.com",

  "result": "https://urlscan.io/result/f9221411-be05-4168-be70-ca5934b588ef/",
  "url": "http://giveaway3x.com",

  "result": "https://urlscan.io/result/52c677ff-cd97-4907-b3e7-3416fcf2b9aa/",
  "url": "http://glfts-metamask-io.is-best.net",

  "result": "https://urlscan.io/result/b639ebb9-d7d8-4b1a-b804-00a0730f8337/",
  "url": "http://inch-uniswap.com",

  "result": "https://urlscan.io/result/1385966f-3d67-4164-a365-0452a9b03d5b/",
  "url": "http://itemap.pancakesvqp.com",

  "result": "https://urlscan.io/result/b2b7ce94-df8b-4c64-a9bd-f23d1c69b432/",
  "url": "http://kf.pancokeswap.com",

  "result": "https://urlscan.io/result/484b3db3-ba52-419c-b88e-91ea31b4a216/",
  "url": "http://live.pancakesvqp.com",

  "result": "https://urlscan.io/result/bf452d53-b0da-45ce-a2df-70e85b27424e/",
  "url": "http://llve.pancakesvqp.com",

  "result": "https://urlscan.io/result/9555ff43-c86f-4e88-b2db-ff8b4e667ab7/",
  "url": "http://main.pancakesvqp.com",

  "result": "https://urlscan.io/result/2672c65e-6fef-4124-ba54-1279e56b1183/",
  "url": "http://master.pancakesvqp.com",

  "result": "https://urlscan.io/result/7cbb4639-9349-4bb5-ba21-021e85c1003f/",
  "url": "http://metamask-extension.com.ecovillequimica.com.br",

  "result": "https://urlscan.io/result/0246e194-f7b0-4b92-a955-d45fcd45ef36/",
  "url": "http://metamask-io.pages.dev",

  "result": "https://urlscan.io/result/876985a2-3b3f-46c2-bd38-514a1a80cb22/",
  "url": "http://metamask-wallet-verification.com",

  "result": "https://urlscan.io/result/42e02437-9b0c-49d6-b82c-ddda5f8f81c8/",
  "url": "http://metamask.biz",

  "result": "https://urlscan.io/result/ded5907d-5766-4af6-a611-378d49201eff/",
  "url": "http://metamask.com.mx",

  "result": "https://urlscan.io/result/5d640015-d9f6-4791-b2c8-7276841e5b2c/",
  "url": "http://metamask.composable.hycom.digital",

  "result": "https://urlscan.io/result/0e0511e3-4323-4b0d-8d8f-87478ddc6e8d/",
  "url": "http://metamask.fund",

  "result": "https://urlscan.io/result/874003c2-eca7-4fdc-a433-bd2592af884e/",
  "url": "http://metamask.id",

  "result": "https://urlscan.io/result/c554c4ef-59e5-4b2f-8e0f-0490d3b4d0b7/",
  "url": "http://metamask.io.in",

  "result": "https://urlscan.io/result/20f36bd2-f93c-4e84-925c-3d857b4d8c96/",
  "url": "http://metamask.io.log692348.in",

  "result": "https://urlscan.io/result/59a8d39e-11ea-497b-8d2b-909e647cbedc/",
  "url": "http://metamask.pub",

  "result": "https://urlscan.io/result/cfe02270-7a11-4ffb-9982-7ad4f3d18597/",
  "url": "http://metamask.store",

  "result": "https://urlscan.io/result/4649816d-15c2-45c0-93ca-ebf07b8f68b5/",
  "url": "http://metamask.zone",

  "result": "https://urlscan.io/result/a9a9f858-0ed3-470f-a898-8c3c96ccda6a/",
  "url": "http://metamaskc.cc",

  "result": "https://urlscan.io/result/3f579b4f-99ba-4b32-9349-232a3a3d7b0e/",
  "url": "http://metamaskio.win",

  "result": "https://urlscan.io/result/4389139d-a0da-4fee-b6cb-b6431c4e963a/",
  "url": "http://metamasks.io",

  "result": "https://urlscan.io/result/bd81f8c8-9525-4e8b-80f2-2dbe47c1eacb/",
  "url": "http://metamaskwebwallet.com",

  "result": "https://urlscan.io/result/fd525672-def1-47ad-9f98-559e76035237/",
  "url": "http://metapancakeswap.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove duplicates
```
pancakesvqp.com
pancakeswapgear.com
pancakeswapps.net
secure-id-verification-coinbase.com
trustwallet-airdrops.nftwealths.com
uniswap-allocation.top
uniswap-alt.space
uniswap-entirety.casa
uniswap-entirety.top
uniswap-fill.casa
uniswap-fill.top
uniswap-proved.casa
uniswap-proved.top
uniswap.com.mx
verification-secure-coinbase.com
```

**Review by dubstard — COMMENTED** [review]
missed to add one - 
```
"4coinmarketcap.site",
```

**Comment by dubstard** [comment]
✅Ready for review

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Ugh, just found out that `1inch.zone` is not bad. 
image
Looks like the 1inch foundation is squatting on domains.

Will raise another PR to remove it.

**Comment by dubstard** [comment]
https://github.com/MetaMask/eth-phishing-detect/pull/8397 raised to remove the FP, sorry about the nuisance.

**Comment by chunza2542** [comment]
Hey, @dubstard! https://uniswap.fish is a safe domain, could you please recheck for it?
It's a calculator for estimating the fee which I just rebranded to make it easier for people to remember (the project is also approved by The Uniswap grants team)

Related links:
https://github.com/chunza2542/uniswap.fish
https://twitter.com/uniswapdotfish

**Comment by dubstard** [comment]
Hi, thanks for flagging.

**Pull request merged**
