### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
@AlexHerman1 @409H @danfinlay 

I sniff cert-stream all night long and each morning I try to do 1 PR. |
This causes large volumes of data, which sometimes could lead to a false positive, if both me and the cross checking reviewer are not vigilant.
I sincerely apologize for the trouble caused.
Shall be more diligent to prevent FPs, like this:

------
Add scams, all manually verified one by one.

All teams have been notified prior to the PR as an extra precaution step

This is not the 1inch you need
```
    "1inch-account.com",
    "1inch.exchange.silenzze.com",
```
image

This is not the Apeswap you need
```
    "apeswap-airdrop.finance",
```

This is not the Binance you need
```
    "walletebinance.com",
```

Those are not the Pancakeswap you need
image

```
    "pancakesvwape.finance",
    "pancakeswap.finance.change-go.in",
    "pancakeswap.finance.exchange24swap.site",
    "pancakeswap.finance.ez24exchange.host",
    "pancakeswap.finance.go24exchange-swap.online",
    "pancakeswap.finance.gochange-swap.in",
    "pancakeswap.finance.readyforexchange-start.online",
    "pancakeswap.finance.swap-gochange.in",
    "pancakeswap.finance.token-swap.in",
    "pancakeswap.financec.in",
    "pancakeswap.men",
    "pancakeswapp.org",
    "pancakeswithpurpose.com",
```

Those are not the Kraken you need
```
   "auth.kraken.gdn",
    "celuekraken.xyz",
    "kraken.gdn",
    "in-wwwkraken.com",
    "kken-bit.com",
    "kraken-access-pg-kr.com",
    "kraken-alert.com",
    "kraken-deal.com",
    "kraken-energy.com",
    "kraken-hw.com",
    "kraken-iv.xyz",
    "kraken-ja.xyz",
    "kraken-login.club",
    "kraken-login.store",
    "kraken-login.website",
    "kraken-official.club",
    "kraken-official.online",
    "kraken-official.site",
    "kraken-official.store",
    "kraken-official.website",
    "kraken-official.xyz",
    "kraken-vi.com",
    "kraken-wwk.com",
    "kraken-wws.com",
    "kraken-zm.xyz",
    "kraken.company",
    "kraken1573777826.zendesk.com",
    "krakenexeh.com",
    "krakenexei.com",
    "krakenexej.com",
    "krakenexek.com",
    "krakenexel.com",
    "krakenexem.com",
    "krakenexen.com",
    "krakenexeo.com",
    "krakenexep.com",
    "krakenexeq.com",
    "krakenexer.com",
    "krakenexes.com",
    "krakenexet.com",
    "krakenexeu.com",
    "krakenexev.com",
    "krakenexew.com",
    "krakenexex.com",
    "krakenexey.com",
    "krakenexez.com",
    "krakenexfa.com",
    "krakenexfb.com",
    "krakenexfc.com",
    "krakenexfd.com",
    "krakenexfe.com",
    "krakenexff.com",
    "krakenexfg.com",
    "krakenexfh.com",
    "krakenexfi.com",
    "krakenexfj.com",
    "krakenexfk.com",
    "krakenexfl.com",
    "krakenexfm.com",
    "krakenexfn.com",
    "krakenexfo.com",
    "krakenexfp.com",
    "krakenexfq.com",
    "krakenexfr.com",
    "krakenexfs.com",
    "krakenexft.com",
    "krakenexfu.com",
    "krakenexfv.com",
    "krakenexfw.com",
    "krakenexfx.com",
    "krakenexfy.com",
    "krakenexfz.com",
    "krakenexga.com",
    "krakenexgb.com",
    "krakenexgc.com",
    "krakenexgd.com",
    "krakenexge.com",
    "krakenexgf.com",
    "krakenexgg.com",
    "krakenexgh.com",
    "krakenexgi.com",
    "krakenexgj.com",
    "krakenexgk.com",
    "krakenexgl.com",
    "krakenexgm.com",
    "krakenexgn.com",
    "krakenexgo.com",
    "krakenexgp.com",
    "krakenexgq.com",
    "krakenexgr.com",
    "krakenexgs.com",
    "krakenexgt.com",
    "krakenexgu.com",
    "krakenexgv.com",
    "krakenexgw.com",
    "krakenexgx.com",
    "krakenexgy.com",
    "krakenexgz.com",
    "krakenexha.com",
    "krakenexhb.com",
    "krakenexht.com",
    "krakeninteligencelogin.com",
    "krakien-dnj.com",
    "krkeen-logexchan.xyz",  
    "sing-wwwkraken.com",
    "kraken-us-en.com",
    "wvw-lkraken.com",
```

image
image

Those are not the MetaMask you need
```
  "metamask-web.info",
    "metamask.blog",
    "metamask.co",
    "metamask.io.merge.districttravels.com",
    "metamask.recovery.supply",
    "metamasks-extension.empirecare.co.uk",
    "bscmetamask.org",
```
image

Those are not the Uniswap you need
```
    "uniswap-support.org",
    "uniswapcoins.top",
```
image

Those are not the Polygon you need
```
    "polygonfinance.xyz",
```

All

```
    "1inch-account.com",
    "1inch.exchange.silenzze.com",
    "2fa-metamask.io",
    "2facryptowallet.com",
    "apeswap-airdrop.finance",
    "app-etherminwallett.xyz",
    "app-uniswap-org.cf",
    "app-uniswap-org.ga",
    "app-uniswap-org.gq",
    "app-uniswap-org.tk",
    "bscmetamask.org",
    "coinbase-account-supports.com",
    "auth.kraken.gdn",
    "celuekraken.xyz",
    "kraken.gdn",
    "in-wwwkraken.com",
    "kken-bit.com",
    "kraken-access-pg-kr.com",
    "kraken-alert.com",
    "kraken-deal.com",
    "kraken-energy.com",
    "kraken-hw.com",
    "kraken-iv.xyz",
    "kraken-ja.xyz",
    "kraken-login.club",
    "kraken-login.store",
    "kraken-login.website",
    "kraken-official.club",
    "kraken-official.online",
    "kraken-official.site",
    "kraken-official.store",
    "kraken-official.website",
    "kraken-official.xyz",
    "kraken-vi.com",
    "kraken-wwk.com",
    "kraken-wws.com",
    "kraken-zm.xyz",
    "kraken.company",
    "kraken1573777826.zendesk.com",
    "krakenexeh.com",
    "krakenexei.com",
    "krakenexej.com",
    "krakenexek.com",
    "krakenexel.com",
    "krakenexem.com",
    "krakenexen.com",
    "krakenexeo.com",
    "krakenexep.com",
    "krakenexeq.com",
    "krakenexer.com",
    "krakenexes.com",
    "krakenexet.com",
    "krakenexeu.com",
    "krakenexev.com",
    "krakenexew.com",
    "krakenexex.com",
    "krakenexey.com",
    "krakenexez.com",
    "krakenexfa.com",
    "krakenexfb.com",
    "krakenexfc.com",
    "krakenexfd.com",
    "krakenexfe.com",
    "krakenexff.com",
    "krakenexfg.com",
    "krakenexfh.com",
    "krakenexfi.com",
    "krakenexfj.com",
    "krakenexfk.com",
    "krakenexfl.com",
    "krakenexfm.com",
    "krakenexfn.com",
    "krakenexfo.com",
    "krakenexfp.com",
    "krakenexfq.com",
    "krakenexfr.com",
    "krakenexfs.com",
    "krakenexft.com",
    "krakenexfu.com",
    "krakenexfv.com",
    "krakenexfw.com",
    "krakenexfx.com",
    "krakenexfy.com",
    "krakenexfz.com",
    "krakenexga.com",
    "krakenexgb.com",
    "krakenexgc.com",
    "krakenexgd.com",
    "krakenexge.com",
    "krakenexgf.com",
    "krakenexgg.com",
    "krakenexgh.com",
    "krakenexgi.com",
    "krakenexgj.com",
    "krakenexgk.com",
    "krakenexgl.com",
    "krakenexgm.com",
    "krakenexgn.com",
    "krakenexgo.com",
    "krakenexgp.com",
    "krakenexgq.com",
    "krakenexgr.com",
    "krakenexgs.com",
    "krakenexgt.com",
    "krakenexgu.com",
    "krakenexgv.com",
    "krakenexgw.com",
    "krakenexgx.com",
    "krakenexgy.com",
    "krakenexgz.com",
    "krakenexha.com",
    "krakenexhb.com",
    "krakenexht.com",
    "krakeninteligencelogin.com",
    "krakien-dnj.com",
    "krkeen-logexchan.xyz",  
    "sing-wwwkraken.com",
    "kraken-us-en.com",
    "wvw-lkraken.com",
    "metamask-web.info",
    "metamask.blog",
    "metamask.co",
    "metamask.io.merge.districttravels.com",
    "metamask.recovery.supply",
    "metamasks-extension.empirecare.co.uk",
    "pancakesvwape.finance",
    "pancakeswap.finance.change-go.in",
    "pancakeswap.finance.exchange24swap.site",
    "pancakeswap.finance.ez24exchange.host",
    "pancakeswap.finance.go24exchange-swap.online",
    "pancakeswap.finance.gochange-swap.in",
    "pancakeswap.finance.readyforexchange-start.online",
    "pancakeswap.finance.swap-gochange.in",
    "pancakeswap.finance.token-swap.in",
    "pancakeswap.financec.in",
    "pancakeswap.men",
    "pancakeswapp.org",
    "pancakeswithpurpose.com",
    "polygonfinance.xyz",
    "uniswap-support.org",
    "uniswapcoins.top",
    "walletebinance.com",
```

```
$ ./BurnTrash.sh | egrep "(result|url)"

  "result": "https://urlscan.io/result/0d2ed75f-7c1b-4d7b-b3a9-3df9e44e7f35/",
  "url": "http://1inch-account.com",

  "result": "https://urlscan.io/result/cba858ab-1840-4786-abc5-e793bf0d06e1/",
  "url": "http://1inch.exchange.silenzze.com",

  "result": "https://urlscan.io/result/2d740e96-60c1-45c6-bd9a-258994acb0c0/",
  "url": "http://2fa-metamask.io",

  "result": "https://urlscan.io/result/e0c20c9b-bd4c-4561-83c5-be7e75003fdc/",
  "url": "http://2facryptowallet.com",

  "result": "https://urlscan.io/result/4ac8c2e6-58f6-4705-b7c5-d0d992d69a44/",
  "url": "http://apeswap-airdrop.finance",

  "result": "https://urlscan.io/result/23096a56-b2fa-4dcf-a41d-791f5f9fd53e/",
  "url": "http://app-etherminwallett.xyz",

  "result": "https://urlscan.io/result/53fdcda9-7482-4ffb-8600-4e66b9402f01/",
  "url": "http://coinbase-account-supports.com",

  "result": "https://urlscan.io/result/2c6ce340-0741-41e3-80fb-e010562e652c/",
  "url": "http://auth.kraken.gdn",

  "result": "https://urlscan.io/result/88f53c51-a00f-459c-bb14-6c6d9dde2ffb/",
  "url": "http://kraken.gdn",

  "result": "https://urlscan.io/result/dee7b5d0-79e8-4b6c-beea-d22874262469/",
  "url": "http://kraken-access-pg-kr.com",

  "result": "https://urlscan.io/result/5e56ed4d-9c10-4b69-892b-63d21fc34447/",
  "url": "http://kraken-alert.com",

  "result": "https://urlscan.io/result/359388c3-fe25-4e37-b116-cb71a91c1b1b/",
  "url": "http://kraken-deal.com",

  "result": "https://urlscan.io/result/4de6a0ae-bc44-4d70-b72b-2f5ffa9a2d6b/",
  "url": "http://kraken-energy.com",

  "result": "https://urlscan.io/result/9899c191-b975-45b9-a04a-c81ca4dd29e0/",
  "url": "http://kraken-hw.com",

  "result": "https://urlscan.io/result/b6024e62-f2b1-4227-a8f3-f7fd5000beb7/",
  "url": "http://kraken-login.club",

  "result": "https://urlscan.io/result/03da431e-1004-46f0-b15d-3ac35772bc0c/",
  "url": "http://kraken-vi.com",

  "result": "https://urlscan.io/result/f6c929aa-afc4-41fa-a1fd-bd928d4cd170/",
  "url": "http://kraken-wwk.com",

  "result": "https://urlscan.io/result/f90c7a3a-aa9c-43d0-971d-a02415f6b0f6/",
  "url": "http://kraken-wws.com",

  "result": "https://urlscan.io/result/b57a93da-8cd7-4ffb-8821-f123198e6979/",
  "url": "http://kraken.company",

  "result": "https://urlscan.io/result/1e573783-da22-48a9-aee1-ab2cf21fa98f/",
  "url": "http://kraken1573777826.zendesk.com",

  "result": "https://urlscan.io/result/0850a4c3-6484-41e4-8c6b-e607cbeb6444/",
  "url": "http://krakenexeh.com",

  "result": "https://urlscan.io/result/ad59754d-bb57-44d7-a3f7-db10afeaff48/",
  "url": "http://krakenexei.com",

  "result": "https://urlscan.io/result/554a162d-1adc-4ead-9fa5-ce60f01e09b3/",
  "url": "http://krakenexej.com",

  "result": "https://urlscan.io/result/376bd6f7-f733-4dc5-9b94-7673e03c13d0/",
  "url": "http://krakenexek.com",

  "result": "https://urlscan.io/result/63f74d21-f81b-4292-a02d-f77d05874987/",
  "url": "http://krakenexel.com",

  "result": "https://urlscan.io/result/80d6e128-cf9b-4209-b2c8-d9a882e84913/",
  "url": "http://krakenexem.com",

  "result": "https://urlscan.io/result/e906083f-ce4f-4d76-bf9b-f456660f20f6/",
  "url": "http://krakenexen.com",

  "result": "https://urlscan.io/result/8d4f0a23-29f6-4601-af3f-34e208b53a55/",
  "url": "http://krakenexeo.com",

  "result": "https://urlscan.io/result/6baa48d2-5ce4-4eed-abf6-b6bfcfe65307/",
  "url": "http://krakenexep.com",

  "result": "https://urlscan.io/result/30d7e4dc-5323-4b93-baef-54bf5e716cb0/",
  "url": "http://krakenexeq.com",

  "result": "https://urlscan.io/result/07afef59-8342-48d2-a554-27f928426fee/",
  "url": "http://krakenexer.com",

  "result": "https://urlscan.io/result/7cb42c14-71d5-41ba-864b-c6f1dfd485b2/",
  "url": "http://krakenexes.com",

  "result": "https://urlscan.io/result/c93f1047-86a3-4977-a103-ec5849563751/",
  "url": "http://krakenexet.com",

  "result": "https://urlscan.io/result/b2d16dd4-cdb3-4056-bf6b-328fb2b42e25/",
  "url": "http://krakenexeu.com",

  "result": "https://urlscan.io/result/e8a1f028-bded-4751-9602-b80e4947427e/",
  "url": "http://krakenexev.com",

  "result": "https://urlscan.io/result/ad0c2d79-347e-4723-8daa-66913bb87ed3/",
  "url": "http://krakenexew.com",

  "result": "https://urlscan.io/result/cd3687b9-2fa1-42e5-8c20-2cb34e7d68d2/",
  "url": "http://krakenexex.com",

  "result": "https://urlscan.io/result/9ce09780-6ff2-4c2d-a83a-742f9b813a93/",
  "url": "http://krakenexey.com",

  "result": "https://urlscan.io/result/c6e43279-5d2a-4b87-bd9c-256741829d3b/",
  "url": "http://krakenexez.com",

  "result": "https://urlscan.io/result/e5e152e4-1802-4ff4-90cf-713fe7ca8ad3/",
  "url": "http://krakenexfa.com",

  "result": "https://urlscan.io/result/0aa15575-9d8d-44a8-89fb-374268e7ea1e/",
  "url": "http://krakenexfb.com",

  "result": "https://urlscan.io/result/2d1a0342-28cb-4148-8d34-0d7e1ddbac71/",
  "url": "http://krakenexfc.com",

  "result": "https://urlscan.io/result/8f992c3e-e3e1-48a2-8a11-2f70b7f619a7/",
  "url": "http://krakenexfd.com",

  "result": "https://urlscan.io/result/d4fb7b9a-d15c-4947-a124-c2c0161dbcf5/",
  "url": "http://krakenexfe.com",

  "result": "https://urlscan.io/result/3f47f9dc-55ba-4da4-8347-007ed2fa741f/",
  "url": "http://krakenexff.com",

  "result": "https://urlscan.io/result/1930730b-6068-4e2e-b8f5-f8299232fa5d/",
  "url": "http://krakenexfg.com",

  "result": "https://urlscan.io/result/d4ed41fc-557e-4507-9b3e-4ded01f8414e/",
  "url": "http://krakenexfh.com",

  "result": "https://urlscan.io/result/5ae88b1d-e79a-459f-a733-fae41e75ac47/",
  "url": "http://krakenexfi.com",

  "result": "https://urlscan.io/result/5356c661-847d-49ee-8a0a-5ba2880504fd/",
  "url": "http://krakenexfj.com",

  "result": "https://urlscan.io/result/a57b4674-6c27-4aab-bb26-c1976c02e79c/",
  "url": "http://krakenexfk.com",

  "result": "https://urlscan.io/result/03c95120-d79a-49f5-bafd-37ece1b1ec22/",
  "url": "http://krakenexfl.com",

  "result": "https://urlscan.io/result/ff25c871-d36a-4f0b-bb7e-c5ece70419d4/",
  "url": "http://krakenexfm.com",

  "result": "https://urlscan.io/result/689429a2-9021-4c1e-a4f5-4854c4de5779/",
  "url": "http://krakenexfn.com",

  "result": "https://urlscan.io/result/312257c0-528f-4a0f-a790-f810ffb479cd/",
  "url": "http://krakenexfo.com",

  "result": "https://urlscan.io/result/2c775a11-95b2-4008-811a-45d88bf163ea/",
  "url": "http://krakenexfp.com",

  "result": "https://urlscan.io/result/0bccd6ec-0353-42bb-a0d6-628529f74db1/",
  "url": "http://krakenexfq.com",

  "result": "https://urlscan.io/result/b5213115-4452-45a4-814b-e7b1b260b23a/",
  "url": "http://krakenexfr.com",

  "result": "https://urlscan.io/result/334e0408-4df5-44db-bfb8-6e59e4d78d04/",
  "url": "http://krakenexfs.com",

  "result": "https://urlscan.io/result/db2ecf78-f88b-4577-a00d-a736e9365651/",
  "url": "http://krakenexft.com",

  "result": "https://urlscan.io/result/2a1813c9-e77c-4af7-8c4f-39a060f6deb5/",
  "url": "http://krakenexfu.com",

  "result": "https://urlscan.io/result/fa96802c-d9a0-4836-a342-08b680b55469/",
  "url": "http://krakenexfv.com",

  "result": "https://urlscan.io/result/a334b9f4-ca75-4b16-b0f7-5d10a5c0f39b/",
  "url": "http://krakenexfw.com",

  "result": "https://urlscan.io/result/9256dc6c-570e-48a9-968b-fa0041e8de54/",
  "url": "http://krakenexfx.com",

  "result": "https://urlscan.io/result/6bb084a1-41a4-4616-9278-f4294477cdb2/",
  "url": "http://krakenexfy.com",

  "result": "https://urlscan.io/result/d337edbb-6ca4-4f92-bb7b-87ce226e0020/",
  "url": "http://krakenexfz.com",

  "result": "https://urlscan.io/result/f48829bb-bf6c-441e-8a69-d3de5232c324/",
  "url": "http://krakenexga.com",

  "result": "https://urlscan.io/result/8543f181-57e8-4e6a-a123-792ba8f99885/",
  "url": "http://krakenexgb.com",

  "result": "https://urlscan.io/result/be92de58-b5fe-4192-80f0-fb2855df3f40/",
  "url": "http://krakenexgc.com",

  "result": "https://urlscan.io/result/151428a8-c2e6-43a5-9b76-0ef11c4024e6/",
  "url": "http://krakenexgd.com",

  "result": "https://urlscan.io/result/7f586061-dcfa-4b18-aa75-088610693dc9/",
  "url": "http://krakenexge.com",

  "result": "https://urlscan.io/result/79ae01ba-6141-4b49-ad62-dfaa6c0d2f9e/",
  "url": "http://krakenexgf.com",

  "result": "https://urlscan.io/result/f4ffc366-7daf-44e3-b51f-7e7cddd23adf/",
  "url": "http://krakenexgg.com",

  "result": "https://urlscan.io/result/882ffbc1-1b2c-4d1f-8a78-f27dffe8ad53/",
  "url": "http://krakenexgh.com",

  "result": "https://urlscan.io/result/0da10237-a90b-41bf-b05d-753ff8f1e471/",
  "url": "http://krakenexgi.com",

  "result": "https://urlscan.io/result/e6c6b6cb-a5b8-4415-8594-7030ea6e66aa/",
  "url": "http://krakenexgj.com",

  "result": "https://urlscan.io/result/785f87ad-df1d-486a-abf9-6a965cbd06e4/",
  "url": "http://krakenexgk.com",

  "result": "https://urlscan.io/result/e5cb3c2a-fd17-43f5-8f2c-45e71a664f83/",
  "url": "http://krakenexgl.com",

  "result": "https://urlscan.io/result/28d6cd00-cb71-43f8-9b38-6fff3df78f93/",
  "url": "http://krakenexgm.com",

  "result": "https://urlscan.io/result/5410cf81-e363-4c94-aabd-35da6ebc2fcd/",
  "url": "http://krakenexgn.com",

  "result": "https://urlscan.io/result/8c26a325-a4ea-4daa-9a5b-31afead2760a/",
  "url": "http://krakenexgo.com",

  "result": "https://urlscan.io/result/9f2507f2-60b4-4451-ae0a-42524c5512c3/",
  "url": "http://krakenexgp.com",

  "result": "https://urlscan.io/result/f3ff2a2d-a586-4124-a8b3-211880241239/",
  "url": "http://krakenexgq.com",

  "result": "https://urlscan.io/result/3bbd486e-065a-4256-afde-1fd799dec931/",
  "url": "http://krakenexgr.com",

  "result": "https://urlscan.io/result/bb0726fa-469a-4a25-be49-442dff363544/",
  "url": "http://krakenexgs.com",

  "result": "https://urlscan.io/result/43dd69d0-2028-4ca0-a3dd-3faa459ae2a7/",
  "url": "http://krakenexgt.com",

  "result": "https://urlscan.io/result/b65feaae-69de-4c5c-b56a-8dc66023cc0a/",
  "url": "http://krakenexgu.com",

  "result": "https://urlscan.io/result/54662ff4-70b6-4534-9f72-11f76ec97aca/",
  "url": "http://krakenexgv.com",

  "result": "https://urlscan.io/result/f61cd785-0e7a-4750-bd92-3b125c9f2b67/",
  "url": "http://krakenexgw.com",

  "result": "https://urlscan.io/result/7852eb98-8965-4c72-9012-516977df9d3e/",
  "url": "http://krakenexgx.com",

  "result": "https://urlscan.io/result/70dd81e8-d575-4512-9079-36edf8b56906/",
  "url": "http://krakenexgy.com",

  "result": "https://urlscan.io/result/824155ec-497c-4f97-ac41-aa3086472fc2/",
  "url": "http://krakenexgz.com",

  "result": "https://urlscan.io/result/34648dd5-e317-457d-9dd7-09a191b26423/",
  "url": "http://krakenexha.com",

  "result": "https://urlscan.io/result/162c1ca2-531f-425c-a55c-f56682ee7bac/",
  "url": "http://krakenexhb.com",

  "result": "https://urlscan.io/result/32ebed5e-ddf0-4ccd-b07e-e1a55ca0482a/",
  "url": "http://krakenexht.com",

  "result": "https://urlscan.io/result/3e5c07ca-859c-48d7-8039-f7a7d6a4dce6/",
  "url": "http://metamask-web.info",

  "result": "https://urlscan.io/result/2bb3b303-9210-4fb4-86c5-db26cba54583/",
  "url": "http://metamask.blog",

  "result": "https://urlscan.io/result/579d727e-ebec-4475-a432-d6e8d3d7555b/",
  "url": "http://metamask.co",

  "result": "https://urlscan.io/result/cfc9e0e0-4a1e-4eb6-bbc0-210c34d2e580/",
  "url": "http://metamask.io.merge.districttravels.com",

  "result": "https://urlscan.io/result/b943162d-1c8f-4d35-afff-c9126c17b04a/",
  "url": "http://metamask.recovery.supply",

  "result": "https://urlscan.io/result/21eab416-175d-4c97-bbbf-160ff0d93a01/",
  "url": "http://metamasks-extension.empirecare.co.uk",

  "result": "https://urlscan.io/result/2252d33e-e056-4f05-aa15-94240a6120a2/",
  "url": "http://pancakesvwape.finance",

  "result": "https://urlscan.io/result/d60697bf-fcd8-44dd-b4a5-0c1f02607dee/",
  "url": "http://pancakeswap.finance.change-go.in",

  "result": "https://urlscan.io/result/9ef8aaf8-ae43-4b9b-bcbc-460e171fcb56/",
  "url": "http://pancakeswap.finance.exchange24swap.site",

  "result": "https://urlscan.io/result/d3da38a0-244a-4a5c-b4b3-4627d9f36e6c/",
  "url": "http://pancakeswap.finance.ez24exchange.host",

  "result": "https://urlscan.io/result/2ea92173-9ffb-4928-9450-17dd348a7d93/",
  "url": "http://pancakeswap.finance.go24exchange-swap.online",

  "result": "https://urlscan.io/result/e67ecd84-2f3e-439f-b59a-fcf0ee95fe98/",
  "url": "http://pancakeswap.finance.gochange-swap.in",

  "result": "https://urlscan.io/result/af9d3198-bfda-45f6-883b-b32f945e2705/",
  "url": "http://pancakeswap.finance.readyforexchange-start.online",

  "result": "https://urlscan.io/result/1d0b2ed2-c75e-4dc9-9e7b-6638c7ea30b8/",
  "url": "http://pancakeswap.finance.swap-gochange.in",

  "result": "https://urlscan.io/result/6fc5c2d5-6af6-4ff7-a4ae-a471cad6b38d/",
  "url": "http://pancakeswap.finance.token-swap.in",

  "result": "https://urlscan.io/result/bc53eacc-7c3b-4501-9a22-fac54477362b/",
  "url": "http://pancakeswap.financec.in",

  "result": "https://urlscan.io/result/c03d6238-764d-4b03-9253-e7fade4bd974/",
  "url": "http://pancakeswap.men",

  "result": "https://urlscan.io/result/694185b8-1043-41d0-bee1-87e57466c349/",
  "url": "http://pancakeswapp.org",

  "result": "https://urlscan.io/result/dd3ffae8-cef4-45e4-acc4-482230735d69/",
  "url": "http://pancakeswithpurpose.com",
  
  "result": "https://urlscan.io/result/76a6d4a7-ff88-4042-9ee6-a4545fd976b7/",
  "url": "http://xn--meamask-orb.com",

  "result": "https://urlscan.io/result/9a95046d-f97f-446f-92c5-a6116074ed5a/",
  "url": "http://polygonfinance.xyz",

  "result": "https://urlscan.io/result/b63f5c39-f501-41e4-812b-83fad0ccf168/",
  "url": "http://uniswapcoins.top",

  "result": "https://urlscan.io/result/0a22e466-83ea-45da-aafe-2a88e843e34a/",
  "url": "http://walletebinance.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add `xn--meamask-orb.com` (IDN / Punycode)
Related to fake twitter account - https://twitter.com/MetaMaskUpdates/status/1575032542516117504
image
image

**Review by dubstard — COMMENTED** [review]
add
```
"otherside-september.xyz",
"metamask.io.privacy-policy.online",
```
h/t DanielLópez for the [lead](https://twitter.com/0xDanielLopez/status/1575395752964235265)

**Review by dubstard — COMMENTED** [review]
Add more IDN / punycode scams, same threat actor as `xn--meamask-orb.com`


Text | IDN Punycode
-- | --
xn--meamask-orb.com	| meťamask.com
xn--metamak-ipb.net	| metamaśk.net
xn--metamsk-9wa.com	| metamäsk.com
xn--metamsk-d4a.com	| metamăsk.com
xn--metamsk-ixa.com	| metamåsk.com
xn--metamsk-lwa.com	| metamásk.com
xn--metamsk-t4a.com	| metamąsk.com
xn--metmask-7wa.com	| metämask.com
xn--metmask-gxa.com	| metåmask.com
xn--metmask-gxa.org	| metåmask.org
xn--metmask-jwa.com	| metámask.com
xn--metmask-r4a.com	| metąmask.com
xn--metmask-rwa.com	| metâmask.com
xn--metmask-zwa.com	| metãmask.com
xn--mtamask-2xa.com	| mètamask.com
xn--mtamask-98a.com	| mętamask.com
xn--mtamask-t8a.com	| mėtamask.com
xn--mtamask-w7a.com	| mētamask.com
xn--rezor-6db.net	| ţrezor.net
xn--rezor-jeb.net	| ťrezor.net
xn--tezo-04ad.com	| tŗezoŗ.com
xn--tezor-5bb.org	| tŗezor.org
xn--treor-7hb.eu	| treźor.eu
xn--treor-7hb.org	| treźor.org
xn--treor-7hb.shop	| treźor.shop
xn--trezo-9bb.org	| trezoŗ.org
xn--trezr-3ta.eu	| trezór.eu
xn--trezr-3ta.shop	| trezór.shop
xn--trezr-gua.net	| trezõr.net
xn--trezr-gua.shop	| trezõr.shop
xn--trezr-j9a.eu	| trezōr.eu
xn--trezr-j9a.net	| trezōr.net
xn--trezr-j9a.org	| trezōr.org
xn--trezr-xta.eu	| trezòr.eu
xn--trzor-051b.net	| trẻzor.net
xn--trzor-5ra.shop	| trèzor.shop
xn--trzor-7za.eu	| trėzor.eu
xn--trzor-csa.co	| trézor.co
xn--trzor-csa.eu	| trézor.eu
xn--trzor-csa.shop	| trézor.shop
xn--trzor-jza.eu	| trēzor.eu
xn--trzor-k0a.eu	| tręzor.eu
xn--trzor-k0a.org	| tręzor.org

</body>
</html>

```
    "xn--metamak-ipb.net",
    "xn--metamsk-9wa.com",
    "xn--metamsk-d4a.com",
    "xn--metamsk-ixa.com",
    "xn--metamsk-lwa.com",
    "xn--metmask-7wa.com",
    "xn--metmask-gxa.com",
    "xn--metmask-gxa.org",
    "xn--metmask-jwa.com",
    "xn--metmask-r4a.com",
    "xn--metmask-rwa.com",
    "xn--metmask-zwa.com",
    "xn--mtamask-2xa.com",
    "xn--mtamask-98a.com",
    "xn--mtamask-t8a.com",
    "xn--mtamask-w7a.com",
    "xn--rezor-6db.net",
    "xn--rezor-jeb.net",
    "xn--tezo-04ad.com",
    "xn--tezor-5bb.org",
    "xn--treor-7hb.eu",
    "xn--treor-7hb.org",
    "xn--treor-7hb.shop",
    "xn--trezr-3ta.eu",
    "xn--trezr-3ta.shop",
    "xn--trezr-gua.net",
    "xn--trezr-gua.shop",
    "xn--trezr-j9a.eu",
    "xn--trezr-j9a.net",
    "xn--trezr-xta.eu",
    "xn--trzor-051b.net",
    "xn--trzor-5ra.shop",
    "xn--trzor-7za.eu",
    "xn--trzor-csa.eu",
    "xn--trzor-csa.shop",
    "xn--trzor-jza.eu",
    "xn--trzor-k0a.eu",
    "xn--trzor-k0a.org",
```

All conveniently hosted on the same IP
https://www.virustotal.com/gui/ip-address/194.147.142.106/community

**Comment by AlexHerman1** [comment]
@dubstard  have you reviewed this PR closely for any false positives? I will review myself today as well.

**Comment by dubstard** [comment]
Yes, i have also alerted the teams affected (kraken, pancake, uniswap)
Only one seems safe, others are good to block.
`kraken.gdn`
let me remove it

**Review by dubstard — COMMENTED** [review]
remove
```
kraken.gdn
auth.kraken.gdn
```

there is a fraud warning: 
image

but the site does not appear to be phishing for Kraken CEX

**Comment by dubstard** [comment]
@AlexHerman we are good to go now - each one was reviewed manually and is confirmed less-than honest

**Comment by dubstard** [comment]
Perhaps `2facryptowallet.com` is also not necessarily bad, although hardware wallets should always be purchased from the legit sites, i.e. if you want a ledger- buy it from ledger's website
if you want  a trezor - get it from trezor themselves

I have seen hardware wallets sold with pre files seed phrases or tainted firmware.

Not sure how to properly verify if 2facryptowallet.com are bad or good.
they have a whooping ONE twitter follower..
image


and zero on IG

**Review by dubstard — COMMENTED** [review]
remove `2facryptowallet.com` (not 100% sure it is bad)

**Comment by alexHerman** [comment]
> @alexHerman we are good to go now - each one was reviewed manually and is confirmed less-than honest

I think you're looking for alexHerman1, I have no idea what you're talking about.

**Review by dubstard — COMMENTED** [review]
fix json

**Comment by dubstard** [comment]
> > @alexHerman we are good to go now - each one was reviewed manually and is confirmed less-than honest
> 
> I think you're looking for alexHerman1, I have no idea what you're talking about.

Apologies for the mixup!

**Comment by dubstard** [comment]
> @dubstard have you reviewed this PR closely for any false positives? I will review myself today as well.

Yes, confirmed.

I accidentally mentioned another person, whoops.

**Review by 409H — DISMISSED** [review]

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks

**Pull request merged**
