### PR TITLE
Block 337 scams

### PR DESCRIPTION
**Pull request by dubstard**
### Add 195 scams (337 - 143 duplicates + 1) to blacklist
Not the Metamask you need
```
    "merge-manually-metamaskinstitutional.com",
    "metamask-eip-1559.rf.gd",
    "metamask-extension.pages.dev",
    "metamask-kyc.tsiconnections.com",
    "metamask-mob.pw",
    "metamask-mobile.com",
    "metamask-security.io",
    "metamask-verifyprocess.net",
    "metamask.2local.io",
    "metamask.consulting",
    "metamask.fr",
    "metamask.gov.au-crypto.tax",
    "metamask.io-defi-web3-dapps-and-nfts.dommespace.com.br",
    "metamask.io-eip1559.icosales.live",
    "metamask.io.community-scrutiny.in",
    "metamask.io.merge.eumidas.com.br",
    "metamask.io.security-verification.in",
    "metamask.iomoz-extension.gorsesmk.com",
    "metamask.iomoz-extension.mertamesk.com",
    "metamask.iomoz-extension.metmev.com",
    "metamask.metimes.id",
    "metamask.name",
    "metamask.nftfree-drop.online",
    "metamask.rf.gd",
    "metamask.rulaninfo.com",
    "metamask1.kred",
    "metamask2.net",
    "metamaskb.com",
    "metamaskbak.cc",
    "metamaskbnkverificaionupdate.run.place",
    "metamaske-extension.hmongtimes.com",
    "metamaskgrants.org",
    "metamaskhelp.online",
    "metamaskk.biz",
    "metamaskk.pw",
    "metamasks.live",
    "metamasksnft.com",
    "metamaskusdt.org",
    "metamlask.com",
    "metannask.com",
    "metannask.io",
    "kyc-metamask-i0applicationoffceveriflcation11.neconme.com",
    "login.2factor-metamask.io",
    "makeitintowallet2022metamask.work.gd",
    "support-metamask.co",
```

Not the 1inch you need
```
    "1inch-app.com",
    "1inch-app.io",
    "1inch.deffo.xyz",
    "1inch.exchange.aqanu.org",
    "1inch.familyestateplanningny.com",
    "1inch.io-swap.promotion.cidatur.com.br",
    "1inch.uk",
    "1inclh.com",
    "1insh.com",
    "app.1inch.familyestateplanningny.com",
```

Not the Elon Musk, Tesla or airdrop you need
```
    "2x-tesla.top",
    "2xmusketh.com",
    "emetamasks.com",
    "emusk2x.cc",
    "emusk2xw.com",
    "emuskc.com",
    "emusketh.com",
    "emuskq.com",
    "claimisaairdrop.com",
    "claimsand.com",
    "claimx2y2.io",
    "blyr.io",
    "eth-gift.space",
    "eth2xelon.com",
    "eth2xmusk.com",
    "ethelon2x.com",
    "ethereum-events.com",
    "ethereum-usdc.com",
    "ethereumarb-bot.biz",
    "ethereumarb-bot.cc",
    "ethereumarb-bot.co",
    "ethereumarb-bot.live",
    "ethereumarb-bot.pw",
    "ethers-airdrops.io",
    "ethmusk2x.com",
    "events-ethereum.com",
    "pos-ethereum.club",
    "pos-ethereum.com",
    "pos-ethereum.info",
    "pos-ethereum.life",
    "pos-ethereum.net",
    "usdt-tethereum.com",
    "usdttethereum.com",
    "microstrategy-alert.online",
    "musk2xeth.cc",
    "fxwinning-pro-wallet.cf",
    "fxwinning-pro-wallet.ga",
    "fxwinning-pro-wallet.gq",
    "fxwinning-pro-wallet.tk",
    "tesla-alert.online",
    "tesla-event.online",
    "tesla-yt.com",
``` 

Not the Uniswap you need
```
    "4vvwvuniswap.top",
    "8vvvvuniswap.top",
    "8wvwvvuniswap.top",
    "8wwuniswap.top",
    "app.uniswap.homesforsaleoakwood.com",
    "app.uniswap.relationshipinterventionist.com",
    "ethereum-uniswap.com",
    "unicoinclaim.org",
    "uniswap-exchenge.com",
    "uniswap-finance.exchange",
    "uniswap-flow.casa",
    "uniswap.accountant",
    "uniswap.auction",
    "uniswap.bet",
    "uniswap.bike",
    "uniswap.blue",
    "uniswap.center",
    "uniswap.cn.com",
    "uniswap.coach",
    "uniswap.coffee",
    "uniswap.com.kz",
    "uniswap.com.se",
    "uniswap.de.com",
    "uniswap.education",
    "uniswap.enterprises",
    "uniswap.eu.com",
    "uniswap.fashion",
    "uniswap.gmbh",
    "uniswap.gr.com",
    "uniswap.info.pl",
    "uniswap.institute",
    "uniswap.land",
    "uniswap.lt",
    "uniswap.market",
    "uniswap.markets",
    "uniswap.net.pl",
    "uniswap.one",
    "uniswap.onl",
    "uniswap.org.bz",
    "uniswap.org.in",
    "uniswap.org.pl",
    "uniswap.pet",
    "uniswap.pw",
    "uniswap.relationshipinterventionist.com",
    "uniswap.school",
    "uniswap.studio",
    "uniswap.supplies",
    "uniswap.tf",
    "uniswap.tokyo",
    "uniswap.tours",
    "uniswap.uk.com",
    "uniswap.us",
    "uniswap.us.com",
    "uniswap.us.org",
    "uniswap.works",
    "uniswapcoin.store",
    "uniswapdex.com",
    "uniswapex.vip",
    "uniswapi.tech",
    "uniswappix.com",
    "uniswappro.net",
    "uniswapreward.org",
    "uniswapsairdrop.com",
    "unitokenclaim.org",
    "unlswap.app",
    "v2-uniswap.com",
    "xn--unisap-z57b.com",
    "topuniswap.com",
```	
	
Not the Ronin you need
```
    "6vvvroninwallet.top",
    "6vvwvroninwallet.top",
    "6wvvroninwallet.top",
```

Not the AAVE you need
```
    "aave-ethereum.info",
    "aave-ethereum.life",
```
Not the Cardano you need

```
    "ada-news.live",
```

Not the Pancakeswap you need
```
    "admin.pancakeswap.host",
```
    
Not the Ark Invest you need
```
    "arkstrategy.org", 
    "btc-strategy.org",
```

[Not the Balancer you need](https://twitter.com/dubstard/status/1585527785157808129)
```
    "balancers.xyz",
```
	
Not the Apecoin you need
```
    "claimape.com",
    "claimapecoins.com",
    "claimapecolns.com",
    "claimapetoken.com",
    "claimapetokens.com",
```

Not the Aptos you need
```
    "claimaptos.com",
    "xn--aptolabs-pvb.com",
    "xn--aptslabs-080d.com",
```	
	
Not the Coinbase you need
```
    "coinbase-authorized-recent.com",
    "coinbase-review-updateds.com",
    "coinbase-signin.com",
    "coinbase-supportpro.com",
    "coinbase-verify-account.permataqurani.com",
    "coinbase-verify.dkumc.org",
    "coinbase-verify.unibel.net",
    "coinbase-verify.unioni.org",
    "coinbase-verify.vqsoft.net",
    "coinbase-wallet.com.cn",
    "coinbase-wallet.dkumc.org",
    "coinbase-wallet.luthgit.com",
    "coinbase-wallet.nemaplc.com",
    "coinbase-wallet.org.cn",
    "coinbase-wallet.rootbeta.org",
    "coinbase-wallet.sdancc.org",
    "coinbase-wallet.store",
    "coinbase-wallet.unibel.net",
    "coinbase-wallet.unioni.org",
    "coinbase-wallet.vqsoft.net",
    "coinbase.acc-authy.com",
    "coinbase.e-wallet-commerce.com",
    "coinbase.verify.ndfdi.org",
    "coinbase.wallet.ndfdi.org",
    "coinbase.wallet.umph.io",
    "coinbase.wallet.verify.tooits.com",
    "coinbase.yuyuhopamazon.com",
    "coinbaseaccounts.com",
    "coinbasedefi.cloud",
    "coinbasesupport.eu",
    "coinbaseveficationsupport.cf",
    "coinbasewallet.com.cn",
    "coinbasewalletaccount.com",
    "login.coinbase-signin.com",
    "login.coinbase.accounts.gh1v.us",
    "login.coinbase.accounts.i1ye.us",
    "login.coinbase.accounts.p5la.us",
    "login.coinbase.accounts.u4fa.us",
    "login.coinbase.accounts.y9da.autos",
    "login.coinbase.accounts.z0ph.us",
    "login.coinbase.com-authid43857338978934.com",
    "login.coinbasesecureauth.com",
    "login.coinbasesupportcentres.com",
    "login.coinbasesupportsid.com",
    "login.coinbasewalletsupport.com",
    "login.coinbasewalletsupports.com",
    "mobile.login.coinbase.accounts.gh1v.us",
    "mobile.login.coinbase.accounts.u4fa.us",
    "mobile.login.coinbase.accounts.y9da.autos",
    "mobile.login.coinbase.accounts.z0ph.us",
    "signin-coinbase.secure82-cloeorde.com",
    "prosupport-coinbase.com",
    "us-coinbasewallet.com",
    "verify-coinbase.luthgit.com",
    "report-coinbaseaccounts.com",
```

Not the WalletConnect you need
```
    "dappssupportprotocol.com",
```

Not the Element Market you need
```
    "elememt.market",
    "elenemt.market",
    "elernent.market",
```
Not the ENS you need
```
    "ens-airdrop.domains",
    "ens-claim.domains",
    "ensclaim.domains",
```

Not the LooksRare you need
```
    "ioocsrare.org",
    "iooksrara.org",
    "loocsrare.org",
    "xn--looksrar-i1a.org",
    "xn--looksrar-ueb.org",
    "xn--looksrre-eza.org",
```

Not the Pancakeswap you need
```
    "pancakesvap.com",
    "pancakesvvaap.finance",
    "pancakeswap-finance.omnicare.com.fj",
    "pancakeswap-finances.digital",
    "pancakeswap.finance.go24exchange-swap.host",
    "pancakeswap.finance.payntrade.in",
    "pancakeswap.finances.forcemultiplierinteractive.com",
    "pancakeswap.finances.homeownerinsuranceclaimappraiser.com",
    "pancakeswap.finances.introvertadventurers.com",
    "pancakeswap.finances.stl-hydroponics.com",
    "pancakeswap.fmt.co.id",
    "pancakeswap.fund",
    "pancakeswap.host",
    "pancakeswap.kz",
    "pancakeswap.name",
    "pancakeswap.org.kz",
    "pancakeswap.pi-core-team.com",
    "pancakeswap.supplies",
    "pancakeswapa.net",
    "pancakeswapfinance.design",
    "pancakeswapgiftnew-finance.tk",
    "pancakeswapmeta.win",
    "pancakeswaps.finance",
    "pancakeswaps.top",
    "pancakeswvaq.com",
    "notpancakeswap.com",
```
Not the OpenSea you need
```
    "opensea-io.com.kz",
    "opensea.co.cm",
    "opensea.com.cm",
    "opensea.com.de",
    "opensea.com.kz",
    "opensea.org.bz",
    "opensea.org.nz",
    "opensea.tk",
    "xn--opesea-kt7b.com",
    "xn--pensea-ol8b.com",
```

Not the Sushiswap you need
```
    "xn--suhi-m5a.com",
    "xn--sush-3pa.com",
    "xn--ushi-k5a.com",
    "wvw-sushiswap.net",
    "sushiswap-io.com",
    "sushiswap.online",
```

Not the Trustwallet you need
```
    "trustwallet-recover.xyz",
    "trustwallet-recover12.info",
    "trustwallet-recover12.xyz",
    "trustwallet-recovery.info",
    "trustwallet-verify.xyz",
```

Not the Sandbox you need
```
    "xn--sandbx-fxa.com",
    "xn--sandbx-tl8b.com",
    "sandbox.cn.com",
    "sandbox.co.com",
```

Not the MEW you need
```
    "myetherwallet.com.verification.cohencues.com",
```

Not the MEW you need
```
    "walletconnect.com.au-crypto.tax",
    "au-crypto.tax",
    "walletsecureconnection.net",
```

Not the Moonbirds you need
```
    "xn--moonbrds-g2a.com",
```

Not the Goblintown you need
```
    "xn--goblntown-j5a.wtf",
```

Not the Azuki you need
```
    "xn--azki-rra.com",
    "xn--zuki-zna.com",
```

Not the Otherside you need
```
    "otheisde-wallet.xyz",
```

Other various scams
```
    "finances.introvertadventurers.com",
    "fiuff.world",
    "googleystore.com",
    "iayerzero.network",
    "lunarwalletnectcapital.finance.blog",
    "marg.habibitsolutions.com",
    "nyoilngs.io",
    "referral-192771.xyz",
    "refundgas.lol",
    "ripple-xrp.org",
    "sign-lkraken.club",
    "secure82-cloeorde.com",
    "solvaweb.com",
    "wwvw-kraken-it.space",
    "wwvw-kraken-it.xyz",
    "xn--dappradr-fza.com",
    "xn--es-pxs.domains",
    "xn--meeland-wz3c.com",
    "xn--ns-9ia.domains",
    "xn--su-oja.com",
    "zk-reward.com",
```

---------------------------------
 
All 

```
    "1inch-app.com",
    "1inch-app.io",
    "1inch.deffo.xyz",
    "1inch.exchange.aqanu.org",
    "1inch.familyestateplanningny.com",
    "1inch.io-swap.promotion.cidatur.com.br",
    "1inch.uk",
    "1inclh.com",
    "1insh.com",
    "2x-tesla.top",
    "2xmusketh.com",
    "4vvwvuniswap.top",
    "6vvvroninwallet.top",
    "6vvwvroninwallet.top",
    "6wvvroninwallet.top",
    "8vvvvuniswap.top",
    "8wvwvvuniswap.top",
    "8wwuniswap.top",
    "aave-ethereum.info",
    "aave-ethereum.life",
    "ada-news.live",
    "admin.pancakeswap.host",
    "admin.uniswapv3.top",
    "ads-unisvap.org",
    "app-uniswap.org.kz",
    "app-uniswap.org.uk",
    "app.1inch.familyestateplanningny.com",
    "app.uniswap.homesforsaleoakwood.com",
    "app.uniswap.relationshipinterventionist.com",
    "arkstrategy.org",
    "balancers.xyz",
    "blyr.io",
    "btc-strategy.org",
    "claimape.com",
    "claimapecoins.com",
    "claimapecolns.com",
    "claimapetoken.com",
    "claimapetokens.com",
    "claimaptos.com",
    "claimisaairdrop.com",
    "claimsand.com",
    "claimx2y2.io",
    "coinbase-authorized-recent.com",
    "coinbase-review-updateds.com",
    "coinbase-signin.com",
    "coinbase-supportpro.com",
    "coinbase-verify-account.permataqurani.com",
    "coinbase-verify.dkumc.org",
    "coinbase-verify.unibel.net",
    "coinbase-verify.unioni.org",
    "coinbase-verify.vqsoft.net",
    "coinbase-wallet.com.cn",
    "coinbase-wallet.dkumc.org",
    "coinbase-wallet.luthgit.com",
    "coinbase-wallet.nemaplc.com",
    "coinbase-wallet.org.cn",
    "coinbase-wallet.rootbeta.org",
    "coinbase-wallet.sdancc.org",
    "coinbase-wallet.store",
    "coinbase-wallet.unibel.net",
    "coinbase-wallet.unioni.org",
    "coinbase-wallet.vqsoft.net",
    "coinbase.acc-authy.com",
    "coinbase.e-wallet-commerce.com",
    "coinbase.verify.ndfdi.org",
    "coinbase.wallet.ndfdi.org",
    "coinbase.wallet.umph.io",
    "coinbase.wallet.verify.tooits.com",
    "coinbase.yuyuhopamazon.com",
    "coinbaseaccounts.com",
    "coinbasedefi.cloud",
    "coinbasesupport.eu",
    "coinbaseveficationsupport.cf",
    "coinbasewallet.com.cn",
    "coinbasewalletaccount.com",
    "dappssupportprotocol.com",
    "elememt.market",
    "elenemt.market",
    "elernent.market",
    "emetamasks.com",
    "emusk2x.cc",
    "emusk2xw.com",
    "emuskc.com",
    "emusketh.com",
    "emuskq.com",
    "ens-airdrop.domains",
    "ens-claim.domains",
    "ensclaim.domains",
    "eth-gift.space",
    "eth2xelon.com",
    "eth2xmusk.com",
    "ethelon2x.com",
    "ethereum-events.com",
    "ethereum-uniswap.com",
    "ethereum-usdc.com",
    "ethereumarb-bot.biz",
    "ethereumarb-bot.cc",
    "ethereumarb-bot.co",
    "ethereumarb-bot.live",
    "ethereumarb-bot.pw",
    "ethers-airdrops.io",
    "ethmusk2x.com",
    "events-ethereum.com",
    "finances.introvertadventurers.com",
    "fiuff.world",
    "fxwinning-pro-wallet.cf",
    "fxwinning-pro-wallet.ga",
    "fxwinning-pro-wallet.gq",
    "fxwinning-pro-wallet.tk",
    "googleystore.com",
    "iayerzero.network",
    "ioocsrare.org",
    "iooksrara.org",
    "kyc-metamask-i0applicationoffceveriflcation11.neconme.com",
    "login.2factor-metamask.io",
    "login.coinbase-signin.com",
    "login.coinbase.accounts.gh1v.us",
    "login.coinbase.accounts.i1ye.us",
    "login.coinbase.accounts.p5la.us",
    "login.coinbase.accounts.u4fa.us",
    "login.coinbase.accounts.y9da.autos",
    "login.coinbase.accounts.z0ph.us",
    "login.coinbase.com-authid43857338978934.com",
    "login.coinbasesecureauth.com",
    "login.coinbasesupportcentres.com",
    "login.coinbasesupportsid.com",
    "login.coinbasewalletsupport.com",
    "login.coinbasewalletsupports.com",
    "loocsrare.org",
    "lunarwalletnectcapital.finance.blog",
    "makeitintowallet2022metamask.work.gd",
    "marg.habibitsolutions.com",
    "merge-manually-metamaskinstitutional.com",
    "metamask-eip-1559.rf.gd",
    "metamask-extension.pages.dev",
    "metamask-kyc.tsiconnections.com",
    "metamask-mob.pw",
    "metamask-mobile.com",
    "metamask-security.io",
    "metamask-verifyprocess.net",
    "metamask.2local.io",
    "metamask.consulting",
    "metamask.fr",
    "metamask.gov.au-crypto.tax",
    "metamask.io-defi-web3-dapps-and-nfts.dommespace.com.br",
    "metamask.io-eip1559.icosales.live",
    "metamask.io.community-scrutiny.in",
    "metamask.io.merge.eumidas.com.br",
    "metamask.io.security-verification.in",
    "metamask.iomoz-extension.gorsesmk.com",
    "metamask.iomoz-extension.mertamesk.com",
    "metamask.iomoz-extension.metmev.com",
    "metamask.metimes.id",
    "metamask.name",
    "metamask.nftfree-drop.online",
    "metamask.rf.gd",
    "metamask.rulaninfo.com",
    "metamask1.kred",
    "metamask2.net",
    "metamaskb.com",
    "metamaskbak.cc",
    "metamaskbnkverificaionupdate.run.place",
    "metamaske-extension.hmongtimes.com",
    "metamaskgrants.org",
    "metamaskhelp.online",
    "metamaskk.biz",
    "metamaskk.pw",
    "metamasks.live",
    "metamasksnft.com",
    "metamaskusdt.org",
    "metamlask.com",
    "metannask.com",
    "metannask.io",
    "microstrategy-alert.online",
    "mobile.login.coinbase.accounts.gh1v.us",
    "mobile.login.coinbase.accounts.u4fa.us",
    "mobile.login.coinbase.accounts.y9da.autos",
    "mobile.login.coinbase.accounts.z0ph.us",
    "musk2xeth.cc",
    "myetherwallet.com.verification.cohencues.com",
    "notpancakeswap.com",
    "nyoilngs.io",
    "opensea-io.com.kz",
    "opensea.co.cm",
    "opensea.com.cm",
    "opensea.com.de",
    "opensea.com.kz",
    "opensea.org.bz",
    "opensea.org.nz",
    "opensea.tk",
    "otheisde-wallet.xyz",
    "pancakesvap.com",
    "pancakesvvaap.finance",
    "pancakeswap-finance.omnicare.com.fj",
    "pancakeswap-finances.digital",
    "pancakeswap.finance.go24exchange-swap.host",
    "pancakeswap.finance.payntrade.in",
    "pancakeswap.finances.forcemultiplierinteractive.com",
    "pancakeswap.finances.homeownerinsuranceclaimappraiser.com",
    "pancakeswap.finances.introvertadventurers.com",
    "pancakeswap.finances.stl-hydroponics.com",
    "pancakeswap.fmt.co.id",
    "pancakeswap.fund",
    "pancakeswap.host",
    "pancakeswap.kz",
    "pancakeswap.name",
    "pancakeswap.org.kz",
    "pancakeswap.pi-core-team.com",
    "pancakeswap.supplies",
    "pancakeswapa.net",
    "pancakeswapfinance.design",
    "pancakeswapgiftnew-finance.tk",
    "pancakeswapmeta.win",
    "pancakeswaps.finance",
    "pancakeswaps.top",
    "pancakeswvaq.com",
    "pos-ethereum.club",
    "pos-ethereum.com",
    "pos-ethereum.info",
    "pos-ethereum.life",
    "pos-ethereum.net",
    "prosupport-coinbase.com",
    "referral-192771.xyz",
    "refundgas.lol",
    "report-coinbaseaccounts.com",
    "ripple-xrp.org",
    "sandbox.cn.com",
    "sandbox.co.com",
    "sign-lkraken.club",
    "signin-coinbase.secure82-cloeorde.com",
    "secure82-cloeorde.com",
    "solvaweb.com",
    "support-metamask.co",
    "sushiswap-io.com",
    "sushiswap.online",
    "tesla-alert.online",
    "tesla-event.online",
    "tesla-yt.com",
    "topuniswap.com",
    "trustwallet-recover.xyz",
    "trustwallet-recover12.info",
    "trustwallet-recover12.xyz",
    "trustwallet-recovery.info",
    "trustwallet-verify.xyz",
    "unicoinclaim.org",
    "uniswap-exchenge.com",
    "uniswap-finance.exchange",
    "uniswap-flow.casa",
    "uniswap.accountant",
    "uniswap.auction",
    "uniswap.bet",
    "uniswap.bike",
    "uniswap.blue",
    "uniswap.center",
    "uniswap.cn.com",
    "uniswap.coach",
    "uniswap.coffee",
    "uniswap.com.kz",
    "uniswap.com.se",
    "uniswap.de.com",
    "uniswap.education",
    "uniswap.enterprises",
    "uniswap.eu.com",
    "uniswap.fashion",
    "uniswap.gmbh",
    "uniswap.gr.com",
    "uniswap.info.pl",
    "uniswap.institute",
    "uniswap.land",
    "uniswap.lt",
    "uniswap.market",
    "uniswap.markets",
    "uniswap.net.pl",
    "uniswap.one",
    "uniswap.onl",
    "uniswap.org.bz",
    "uniswap.org.in",
    "uniswap.org.pl",
    "uniswap.pet",
    "uniswap.pw",
    "uniswap.relationshipinterventionist.com",
    "uniswap.school",
    "uniswap.studio",
    "uniswap.supplies",
    "uniswap.tf",
    "uniswap.tokyo",
    "uniswap.tours",
    "uniswap.uk.com",
    "uniswap.us",
    "uniswap.us.com",
    "uniswap.us.org",
    "uniswap.works",
    "uniswapcoin.store",
    "uniswapdex.com",
    "uniswapex.vip",
    "uniswapi.tech",
    "uniswappix.com",
    "uniswappro.net",
    "uniswapreward.org",
    "uniswapsairdrop.com",
    "unitokenclaim.org",
    "unlswap.app",
    "us-coinbasewallet.com",
    "usdt-tethereum.com",
    "usdttethereum.com",
    "v2-uniswap.com",
    "verify-coinbase.luthgit.com",
    "walletconnect.com.au-crypto.tax",
	"au-crypto.tax",
    "walletsecureconnection.net",
    "wvw-sushiswap.net",
    "wwvw-kraken-it.space",
    "wwvw-kraken-it.xyz",
    "xn--aptolabs-pvb.com",
    "xn--aptslabs-080d.com",
    "xn--azki-rra.com",
    "xn--dappradr-fza.com",
    "xn--es-pxs.domains",
    "xn--goblntown-j5a.wtf",
    "xn--looksrar-i1a.org",
    "xn--looksrar-ueb.org",
    "xn--looksrre-eza.org",
    "xn--meeland-wz3c.com",
    "xn--moonbrds-g2a.com",
    "xn--ns-9ia.domains",
    "xn--opesea-kt7b.com",
    "xn--pensea-ol8b.com",
    "xn--sandbx-fxa.com",
    "xn--sandbx-tl8b.com",
    "xn--su-oja.com",
    "xn--suhi-m5a.com",
    "xn--sush-3pa.com",
    "xn--unisap-z57b.com",
    "xn--ushi-k5a.com",
    "xn--zuki-zna.com",
    "zk-reward.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove duplicates
```

1inch.io-swap.promotion.cidatur.com.br
1inch.uk
2x-tesla.top
2xmusketh.com
4vvwvuniswap.top
6vvvroninwallet.top
6vvwvroninwallet.top
6wvvroninwallet.top
ada-news.live
ads-unisvap.org
app-uniswap.org.kz
app-uniswap.org.uk
app.uniswap.relationshipinterventionist.com
arkstrategy.org
coinbase-authorized-recent.com
coinbase-review-updateds.com
coinbase-signin.com
coinbase-verify-account.permataqurani.com
coinbase-wallet.com.cn
coinbase-wallet.luthgit.com
coinbase-wallet.nemaplc.com
coinbase-wallet.org.cn
coinbase-wallet.store
coinbase.yuyuhopamazon.com
coinbasedefi.cloud
coinbasewallet.com.cn
coinbasewalletaccount.com
emusk2x.cc
emusketh.com
eth-gift.space
eth2xmusk.com
ethereum-uniswap.com
ethereum-usdc.com
ethers-airdrops.io
ethmusk2x.com
fxwinning-pro-wallet.cf
fxwinning-pro-wallet.ga
fxwinning-pro-wallet.gq
fxwinning-pro-wallet.tk
login.coinbase-signin.com
login.coinbasewalletsupport.com
metamask-extension.pages.dev
metamask-kyc.tsiconnections.com
metamask-mobile.com
metamask-security.io
metamask-verifyprocess.net
metamask.io-defi-web3-dapps-and-nfts.dommespace.com.br
metamask.io.community-scrutiny.in
metamask.iomoz-extension.gorsesmk.com
metamask.iomoz-extension.metmev.com
metamask.metimes.id
metamask.name
metamask.rulaninfo.com
metamask1.kred
metamask2.net
metamaskb.com
metamaskbak.cc
metamaskgrants.org
metamasks.live
metamasksnft.com
metamaskusdt.org
myetherwallet.com.verification.cohencues.com
opensea.co.cm
opensea.com.cm
opensea.org.bz
opensea.org.nz
pancakeswap-finances.digital
pancakeswap.finances.homeownerinsuranceclaimappraiser.com
pancakeswap.finances.introvertadventurers.com
pancakeswap.finances.stl-hydroponics.com
pancakeswap.fund
pancakeswap.host
pancakeswap.kz
pancakeswap.name
pancakeswap.org.kz
pancakeswap.supplies
pancakeswapfinance.design
pancakeswapmeta.win
pancakeswaps.finance
pancakeswaps.top
pancakeswvaq.com
prosupport-coinbase.com
report-coinbaseaccounts.com
signin-coinbase.secure82-cloeorde.com
sushiswap.online
trustwallet-recover.xyz
trustwallet-recover12.info
trustwallet-recover12.xyz
trustwallet-recovery.info
trustwallet-verify.xyz
uniswap-exchenge.com
uniswap-flow.casa
uniswap.accountant
uniswap.auction
uniswap.bet
uniswap.blue
uniswap.center
uniswap.cn.com
uniswap.coach
uniswap.coffee
uniswap.de.com
uniswap.education
uniswap.enterprises
uniswap.fashion
uniswap.gmbh
uniswap.gr.com
uniswap.info.pl
uniswap.institute
uniswap.land
uniswap.lt
uniswap.market
uniswap.markets
uniswap.net.pl
uniswap.one
uniswap.onl
uniswap.org.bz
uniswap.org.in
uniswap.org.pl
uniswap.pet
uniswap.pw
uniswap.relationshipinterventionist.com
uniswap.studio
uniswap.supplies
uniswap.tf
uniswap.tokyo
uniswap.tours
uniswap.uk.com
uniswap.us
uniswap.us.com
uniswap.us.org
uniswap.works
uniswapcoin.store
uniswapi.tech
uniswappix.com
us-coinbasewallet.com
usdt-tethereum.com
verify-coinbase.luthgit.com
wwvw-kraken-it.space
wwvw-kraken-it.xyz
xn--unisap-z57b.com
xn--unisap-z57b.com
zk-reward.com
```

**Review by dubstard — COMMENTED** [review]
add OpenSea scam
image
image

Spread via a fake twitter profile 
```
"xn--opensa-token-ivb.com",
```
https://urlscan.io/result/ca77c629-aeac-463b-a005-221926f79108/

**Comment by AlexHerman1** [comment]
@dubstard  have you checked this closely? this is quite a large list.

**Comment by dubstard** [comment]
> @dubstard have you checked this closely? this is quite a large list.
@AlexHerman1

Yes, confirmed.

I try to do one PR per day. However sometimes the merging happens slower. 

In those cases I merge the data for the past days and it accumulates to insane volumes.

Thus a huge nimber of duplicates.,
---------------

I have taken the time to explain which service each one imitates.

(check the PR - 
```
this is not the Uniswap you need
abc
this is not the MetaMask you need, 
xyz
this is not the Pankaceswap you need
def
```
I have also shared the URLs with the relevant anti fraud teams within each entity - I am in touch with Uniswap and Pancakeswap.

The rest are hosted on bad infrastructure - ANYTHING hosted there will always be a scam:
See for yourself:
image

**Review by dubstard — COMMENTED** [review]
remove     
```
"maler-obitsoe.dk",
```
- issue was resolved (account takeover)

A company for house renovation or something like that had their CMS hijacked (ATO), but they have remediated the issue now and the harmful content is gone, the ATO attack vector was patched.

**Review by legobeat — APPROVED** [review]
lgtm

**Comment by dubstard** [comment]
Thanks, new one incoming.

**Pull request merged**
