### PR TITLE
fake uniswap sites

### PR DESCRIPTION
**Pull request by dpazdan**
xn--unswap-q9a.com
Fake Uniswap phishing for secrets with POST /googleanalytics.php
https://urlscan.io/result/0a123bd5-6eb0-4e87-b5ff-381427ed9ea5/

### CODE REVIEW

**Comment by CondoR100** [comment]
It is NOT a fake site, it is another project called ANYSWAP, built on the Fusion Protocol blockchain.

**Comment by dpazdan** [comment]
This site is requesting for a user's private key or seed phrase.

**Comment by marcelcure** [comment]
The Fusion blockchain uses ETH addresses and private keys, but it is a separate blockchain. The Anyswap project uses MetaMask to unlock the Fusion wallet, although with a different chainID. Anyswap is a fork of Uniswap, but with additional code to make it blockchain agnostic, using Fusions DCRM code. It will support XRP-ETH-BTC-LTC-FSN swaps in the coming weeks.

It is NOT a fake Uniswap

**Comment by CondoR100** [comment]
Sure it does, it is a decentralised exchange, you can connect with Metamask using your Private key, seed phrase. However, to connect on Fusion Blockchain you have to go on Metamask networks and add Fusion custom settings. For now, there is only one par ANY/FSN but soon many coins will be added. If you want to learn more here you can find all info https://www.fusion.org/

**Comment by 409H** [comment]
What domain are you referring to @marcelcure?

**Comment by marcelcure** [comment]
You can see the Anyswap code on github here https://github.com/anyswap
and you can see the exchange running at https://anyswap.exchange

**Comment by guggsverus** [comment]
> What domain are you referring to @marcelcure?

https://anyswap.exchange/

**Comment by marcelcure** [comment]
Yes, Anyswap. https://anyswap.exchange

**Pull request merged**
