### PR TITLE
Block 137 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "aave-usdt.life",
    "aaveliquidity.com",
    "account-coinbaseupdate.com",
    "aduni.site",
    "advancemining-vip.com",
    "advanceminingvip.com",
    "aguni.site",
    "airdrop-aave-claim.com",
    "airrdrops.com",
    "apexcoinex.com",
    "atuni.site",
    "balancer-marketing.pages.dev",
    "balancer-tests.pages.dev",
    "balancerabd.xyz",
    "balancercode.com",
    "balancergty.top",
    "balancermjd.xyz",
    "binance-1inch.listviewss.com",
    "binance-airdrop.win",
    "bitcoinmexc.com",
    "bitxbase.org",
    "bitxbest.com",
    "bitxger.com",
    "bitxler.com",
    "bitxneo.com",
    "ca-uni.org",
    "balancer-appl.click",
    "claim-uni.org",
    "claimuniswap.org",
    "coinsrale.com",
    "community-uni.org",
    "connectwallet1.netlify.app",
    "crypto-tranfer.vip",
    "cryptorabit.com",
    "defi-loan.cloud",
    "defi-mining.store",
    "defi-mining.win",
    "defimanuallsyncc.netlify.app",
    "dex-cloud.net",
    "dfx-eth.com",
    "coinbase.com.ref-2uz39.link",
    "coinbase.com.referral-27up83vbbd.link",
    "event-ethereum.org",
    "evytrade.com",
    "curve-fi.finance",
    "curves-finance.com",
    "farmxcash.com",
    "forexchasersinvestments.com",
    "ftxrewards.com",
    "hetcrypt.com",
    "imtoken-investorm.xyz",
    "imtoken.org.cn",
    "kuberrswap.com",
    "kyberswap.gq",
    "lmt0ken.cc",
    "lmt0ken.cn",
    "magiiceden-jo.com",
    "metamask-upgrade.com",
    "metamask.aspendigital.com.br",
    "metamask.frankandpank.io",
    "metamask.io.barrettenterprize.com",
    "metamask.io.berrybeautyspa.com",
    "metamask.io.classifieds.center",
    "metamask.io.cowryfunds.com",
    "metamask.io.dailybhalukapratidin.com",
    "metamask.io.dfmusanews.com",
    "metamask.io.globalbimcad.com",
    "metamask.io.globalpropay.com",
    "metamask.io.gomywayride.com",
    "metamask.io.mastarstudios.com",
    "metamask.io.merge.etiquettetout.com",
    "metamask.io.pro-maxoil.energy",
    "metamask.io.prodipdas.com",
    "metamask.io.prodombd.com",
    "metamask.io.profitcoins.ltd",
    "metamask.io.signal-trades.com",
    "metamask.io.unitytrade.ltd",
    "metamask.io.vetoplusinvest.com",
    "metamask.io.vids4u.tube",
    "metamask.io.wtfashionjeans.com",
    "metamask.io.yallacustomboxes.com.au",
    "metamaskair.com",
    "metamasker.net",
    "mexsbit.com",
    "mgasvip-wallet.com",
    "miningcoin.club",
    "mqgiiceden-io.com",
    "mywalletconnect.weebly.com",
    "nftopsea.io",
    "nftuniswap.org",
    "okex.net.cn",
    "okx-app.cn",
    "opensea-drop.xyz",
    "oppenseq.com",
    "pancakeswap-claim.com",
    "pancakeswap-en.com",
    "pancakeswap-lottery.com",
    "pancakeswap.benhadi.ma",
    "pancakeswap.imco.site",
    "pancakeswaps.assaas.online",
    "polkastqrtter.com",
    "pollkastarter.co",
    "qurxbit.com",
    "rar-jble.com",
    "rtfktegg.art",
    "secure-coinbase.biz",
    "shlbaswaps-apl.slogln.com",
    "signup-collab.land",
    "stablefund-refund.app",
    "t0kenp0cket.com",
    "t0kenp0cket.org.cn",
    "the-bit-balancer.com",
    "token-im.cc",
    "tokenpocket.net.cn",
    "trading-wave.com",
    "tron-code.com",
    "trust-wallet.com.cn",
    "tterramoney.com",
    "uniminedefi.com",
    "unisnft.net",
    "uniswap-app.tech",
    "uniswap.leads.biz.id",
    "uniswapexchangev3.com",
    "uniswapnft.com",
    "uniswapnft.org",
    "updates-metamask.io",
    "usdt-wallet.cn",
    "vwwv-cosmosapp.com",
    "wallet-polygontechnolodgy.life",
    "walletairdrop.xyz",
    "walletconnect-binance.com",
    "walletresponse.com",
    "web3-metamask.io",
    "www-polkastartar.com",
    "xn--metamak-ipb.io",
    "yugaslab.com",
    "zhifeijimx.com",
```

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@dubstard  this is a large list, has this been vetted closely?

**Comment by dubstard** [comment]
All websites in this list have been checked and are confirmed fraud.

**Comment by dubstard** [comment]
I am also preparing a new pull request from last nights data now.

When a few days pass by with no merge, i collect data from a few days, and thus the list size grows.

I try not to stack too many URLs in one PR, to make it easier for verification

We have also agreed with Harry that he shall stay on tp of my PRs false positive wise.

However I am extra cautious, as in not to block something legit by mistake.

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
Perfect, thanks.
New one incoming.

**Pull request merged**
