### PR TITLE
Add uniswap phishing url from hacked account

### PR DESCRIPTION
**Pull request by ktian94**

### CODE REVIEW

**Review by danfinlay — APPROVED** [review]

**Comment by danfinlay** [comment]
Ugh, I'm so sorry to ask this, but would you mind resolving the merge conflict? This is why I never submit entries at the top of the array, btw.

**Comment by ktian94** [comment]
Yep np, and noted on top of array issue

**Review by danfinlay — APPROVED** [review]

**Comment by ktian94** [comment]
Closing this out as @samczsun beat me

**Comment by ktian94** [comment]
@danfinlay lmk if this helps - https://github.com/MetaMask/eth-phishing-detect/pull/13093

**Pull request closed without merging**
