### PR TITLE
myethereumwallet.su

### LINKED ISSUE #178: myethereumwallet.su new phishing site
Request to add the following to the blacklist:

http://myethereumwallet.su/wallet.php

### PR DESCRIPTION
**Pull request by Samyoul**
Resolves #178

### CODE REVIEW

**Comment by 409H** [comment]
https://urlscan.io/result/aad8c5a8-35ba-4488-adc8-668f956b6b12#summary

**Comment by Samyoul** [comment]
@409H In future would you prefer if I add proof of the phishing site stealing keys?

**Comment by 409H** [comment]
@Samyoul Please, would be very useful - without compromising your own security of course.

For testing MEW clones, I generally use `0x123456789efefefefefefefefefefefefefefefe` with the network panel open to see if it's sent some place.

I do this in a VM (when I'm a home) as to not compromise my main machine of any dodgy things going on - some phishing sites have been auto-blocked by my anti-virus due to malware - could be a false-positive, but wouldn't risk it.

For every site, we use urlscan.io to get a copy of the DOM (main page) and take a screenshot of it - we are working on a bespoke solution to automate this though.

**Comment by Samyoul** [comment]
No problem, I find loads of MEW phishers, so I'll (safely) provide this information.

**Pull request merged**
