### PR TITLE
20180626 user phising report #1654b

### PR DESCRIPTION
**Pull request by alacrity26**

### CODE REVIEW

**Comment by 409H** [comment]
@alacrity26 can we clean this PR up to get merged?

**Comment by alacrity26** [comment]
@409H merged

**Comment by 409H** [comment]
Please don't force merge if the CI fails. Can you roll this back

**Comment by 409H** [comment]
I've rolled back https://github.com/MetaMask/eth-phishing-detect/pull/1985 - please keep an eye on the CI results and don't force-merge if the CI fails.

**Comment by alacrity26** [comment]
@409H thanks! will do!

**Pull request merged**
