### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by kellyfends**
"liquid-eth.net",
    "enroll-magiceden.io",
    "launch-jup.app",
    "pufier.com",
    "home-rendertoken.com",
    "main-fetchtoken.com",
    "gift-paxos.com",
    "home-woo.com",
    "gift-galagames.com",
    "gift-agix.com",
    "dao-chain.link",
    "claim-decentraland.net",
    "app-maker.net",
    "home-injective.com",
    "main-quant.com",
    "home-ens.com",
    "claim-frax.net",
    "gift-dydx.net",
    "usd-claim.org",
    "gift-beam.org",
    "hub-shibatoken.org",
    "gift-hex.com",
    "home-ocean.net",
    "home-synthetix.com",
    "gift-graphtoken.com",
    "gift-realio.com",
    "main-apyeth.com",
    "main-liquideth.com",
    "home-aave.net",
    "bitrock-app.com",
    "zkfair.events",

### CODE REVIEW

**Comment by kellyfends** [comment]
@AlexHerman1 did you send me an email ?

**Comment by AlexHerman1** [comment]
@kellyfends  trying to figure it out will get back to you

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by kellyfends** [comment]
@AlexHerman1 you ask me "can you set up a slack instance of some kind or provide your email and ill seeif i can add you?"

please send me email kellyfends@gmail.com

**Comment by AlexHerman1** [comment]
@kellyfends  i sent you a slack invite, please let me know if it went through

**Pull request merged**
