### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by dubstard**
add scams 
```
"3ethereum.com",
"3vvv-roninwallet.top",
"coinbase-cryptoloan.biz",
"coinbase-resseting-password-clients23rdq.duckdns.org",
"coinbase.com-wallet11-authy-signin.online",
"coinbase.com.secure-auth.sessionid092189.app",
"coinbase.revalwallets.com",
"degenswap.exchange",
"download-metamask.app",
"e-coinbase-auth.com-2fa-verifyotp.com",
"eth-1inch.io",
"ethereum-celebration.net",
"ethereum-concept.com",
"ethereum-faucet.com",
"ethereum-giving.io",
"ethereum-giving.live",
"ethereums.gift",
"exobus-wallet.com",
"giveawayethereum.org",
"globalnewstrade-wallet.cc",
"glveaways-metamasks-lo.html-5.me",
"lcoin-mainnet.coinbasewallet.com",
"metamask-restores.com",
"metamask.firmwareupdate.me",
"metamask.i-chain.site",
"metamask.io.merge.actimaggroup.com",
"metamask.io.merge.alexcoteltee.net",
"metamask.io.merge.alnashamatech.com",
"metamask.io.merge.artandcraftz.xyz",
"metamask.io.merge.arthaoceanlight.com",
"metamask.io.merge.atsonline.shop",
"metamask.io.merge.aviraorganics.com",
"metamask.io.merge.aviraorganics.com",
"metamask.io.merge.bestsoftit.com",
"metamask.io.merge.boldtranslation.com",
"metamask.io.merge.camostory.com",
"metamask.io.merge.clone.divinemedica.de",
"metamask.io.merge.cmuch.mx",
"metamask.io.merge.coursemane.org",
"metamask.io.merge.cripersrisespace.com",
"metamask.io.merge.dartwavedelivery.com",
"metamask.io.merge.e-link.me",
"metamask.io.merge.edesk.io",
"metamask.io.merge.edeskoutsourcing.com",
"metamask.io.merge.educadorxavier.com.br",
"metamask.io.merge.etringallery.com",
"metamask.io.merge.fkg.moestopo.ac.id",
"metamask.io.merge.giletarm.xyz",
"metamask.io.merge.go-getter.in",
"metamask.io.merge.grafieindonesia.com",
"metamask.io.merge.gregtutors.com",
"metamask.io.merge.hotspotmassage.com",
"metamask.io.merge.icedcoffeerecipes.xyz",
"metamask.io.merge.iedi.edu.co",
"metamask.io.merge.inetku.net.id",
"metamask.io.merge.irbestsocial.ir",
"metamask.io.merge.kahfstudio.com",
"metamask.io.merge.labelmystuff.com",
"metamask.io.merge.learnwithmizan.com",
"metamask.io.merge.megsteven.com",
"metamask.io.merge.miraclemiles.us",
"metamask.io.merge.mirshus.moestopo.ac.id",
"metamask.io.merge.mquranacademy.com",
"metamask.io.merge.mskbusiness.com",
"metamask.io.merge.msktranslation.com",
"metamask.io.merge.nevibytes.com",
"metamask.io.merge.nigercareinternational.com",
"metamask.io.merge.nodechain.dev",
"metamask.io.merge.noderon.com",
"metamask.io.merge.origraffes.com.br",
"metamask.io.merge.p2pex.net",
"metamask.io.merge.paporeto.net.br",
"metamask.io.merge.parsix.com.br",
"metamask.io.merge.pristinefoodsgh.com",
"metamask.io.merge.rasattl.ir",
"metamask.io.merge.rione.co.id",
"metamask.io.merge.rioneindonesia.com",
"metamask.io.merge.ritujannat.com",
"metamask.io.merge.romata-group.com",
"metamask.io.merge.rslafrica.org",
"metamask.io.merge.safi.ps",
"metamask.io.merge.samadenterprise.com",
"metamask.io.merge.senglobalmarket.com",
"metamask.io.merge.shreesevenhillshospital.com",
"metamask.io.merge.simbiosisdigital.com",
"metamask.io.merge.sunshinehealthcareltd.com",
"metamask.io.merge.swift2track.org",
"metamask.io.merge.tradingescalonado.com",
"metamask.io.merge.uni-smart.uk",
"metamask.io.merge.westfordtb.com",
"metamask.io.merge.wilsontoursafrica.com",
"metamask.io.merge.yekshahr.ir",
"metamaskshealth.com",
"oasisswap.exchange",
"pancakeswap-org.com",
"pancakeswappriv.com",
"pancakeswapsearch.com",
"safethereum.com",
"sunsaberlp.com.eth-1inch.io",
"truswallet-connect.ga",
"truswallet-connect.gq",
"truswallet-connect.ml",
"truswallet-connect.tk",
"uniswap-uniswap.exchange",
"uniswapgoti.tech",
"uniswaphos.com",
"uniswapi.info",
"uniswapp.cc",
"uniswappes.org",
"uniswaprest.tech",
"uniswapyet.tech",
"wallet.prod.nodleprotocol.io",
"wvwv-metamask.net",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
Remove duplicates (overlap with yesterday)
```
"coinbase-alertverify.duckdns.org",
"cronosclassic.com.eth-1inch.io",
"genuine-metamask.cc",
"installmetamask.shop",
"metamask-casino.com",
"metamask-download.com",
"metamask-giveaway.io",
"metamask.by.lt",
"metamask.io.merge.albio.tech",
"metamask.io.merge.amarmultihospital.com",
"metamask.io.merge.aqit.ma",
"metamask.io.merge.aviraorganics.com",
"metamask.io.merge.cosdelmar.com",
"metamask.io.merge.erasky.in",
"metamask.io.merge.groupegerminal.com",
"metamask.io.merge.singhgroup-india.com",
"metamask.quarantine.wiki",
"metamaskbtc.monster",
"metamaskey.com",
"metamaskio.monster",
"otponline-account-verification-coinbase.com",
"pancakeswap.fund",
"pancakeswapis.click",
"pancakeswapr.net",
"suspend-metamask.com",
"top-ethereum.com",
"uniswap-pos.co",
"uniswap-pos.top",
"uniswap-pos.xyz",
"uniswap-v3.org",
"uniswap-web.com",
"uniswap.credit",
```

**Review by dubstard — COMMENTED** [review]
remove dupes
```
usmetamask.club
v2ethereum.com
withmetamask.shop
```
add scam
```
"metamask.io.merge.invadeacademy.com.ng",
```

**Review by dubstard — COMMENTED** [review]
add 
```
"metamask.io.merge.estudiogr.com.py",
```

```
$ curl -k https://pxlme.me/dtDmBGJe | grep window
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
  window.location = 'https:\/\/metamask.io.merge.estudiogr.com.py'
```

**Review by dubstard — COMMENTED** [review]
add
```
metamask.io.merge.vermogentech.com
```

```
$ curl -k https://pxlme.me/dtDmBGJe | grep window
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
window.location = 'https:\/\/metamask.io.merge.vermogentech.com'
```

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Comment by dubstard** [comment]
Thanks
Side note - The short links now also have a warning, i managed to complain to the company that hosts them.

```
$ curl -A "Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) CriOS/28.0.1500.12 Mobile/10B329 Safari/8536.25" -k https://pxlme.me/dtDmBGJe
<a href="https://pixelme.me/phishing?url=https://metamask.io.merge.vermogentech.com">Found</a>.

 
$ curl -A "Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) CriOS/28.0.1500.12 Mobile/10B329 Safari/8536.25" -k http:///pxlme.me/irzaG2cu
<a href="https://pixelme.me/phishing?url=https://metamask.io.merge.qantikaint.site">Found</a>.

```
image

**Pull request merged**
