### PR TITLE
adding metapass.fyi to the whitelist

### PR DESCRIPTION
**Pull request by benpoliquin**
Adding metapass.fyi to the whitelist.

### CODE REVIEW

**Comment by benpoliquin** [comment]
Issue: https://github.com/MetaMask/eth-phishing-detect/issues/6105

**Comment by benpoliquin** [comment]
@davidwgrossman Any chance this could get approved? Trying to get my project out but this is causing issues saying my site is phishing when it is not

**Comment by davidwgrossman** [comment]
I'll get to it today. It will take another 24 hours for the change to
propagate though.

-David

**Review by gravelcycles — APPROVED** [review]

**Comment by benpoliquin** [comment]
Thank you!

**Pull request merged**
