### PR TITLE
Block scam imitations of Balancer.fi

### PR DESCRIPTION
**Pull request by dubstard**
```
    "balancer-app.finance",
    "balancer-connect.fi",
```
image
image

### CODE REVIEW

**Comment by dubstard** [comment]
You know who it is. The person who finds the phish before it is even operational, hahaha
kekeke get rekt, baaaai
image

**Review by dubstard — COMMENTED** [review]
https://twitter.com/bunnymaid/status/1624673028138487809

blocking in advance

"I hate to brag, but damn I am good."
~SHAQ

```
"balancer-user.fi",
```

**Comment by dubstard** [comment]
After merging [11523](https://github.com/MetaMask/eth-phishing-detect/pull/11523)

My two other pending PRs somehow got conflicts that need to be resolved.
[11521](https://github.com/MetaMask/eth-phishing-detect/pull/11521)
[11513](https://github.com/MetaMask/eth-phishing-detect/pull/11513)

I think it has to do with the order of the URLs, there shouldn't be duplicates, but I can not fix it on my own.
Thanks and cheers

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks for rebase & merge

**Pull request merged**
