### PR TITLE
Add various phishing sites

### PR DESCRIPTION
**Pull request by ghost**
#### deadfeilaz[.]io
- https://urlscan.io/result/3d22cc9a-ac1d-45e1-b895-45347fcac26f/
#### premint[.]host
- https://urlscan.io/result/d9e26c9e-738d-4817-ab0a-7a16a1f87ea8/
#### rtfkt-space[.]com
- https://urlscan.io/result/d5534f8a-138c-4643-a534-38635be42f93/

### CODE REVIEW

**Comment by JMAKE5611** [comment]
Add various phishing sites
https://arketh.io/

**Comment by JMAKE5611** [comment]
@0xLimerence  
Add various phishing sites
https://arketh.io/

**Review by JMJMJM2008 — CHANGES_REQUESTED** [review]
Add  phishing sites
https://arketh.io/

**Comment by AlexHerman1** [comment]
@JMAKE5611  thanks for contributing. Please open New individual PR's to add sites to our Blocklist, with context/research about the sites.

**Review by AlexHerman1 — APPROVED** [review]
lgtm.

**Pull request merged**
