### PR TITLE
Block circle scams (continued....)

### PR DESCRIPTION
**Pull request by dubstard**
`Live your life by the hour, not by the day. What will you achieve in the next hour?`
~ Frank Zane

This PR contains the data from https://github.com/MetaMask/eth-phishing-detect/pull/11951 in it.
11951 closed without merge due to conflicts.
As usual all scams are [mirrored on UrlScan](https://urlscan.io/search/#task.tags:%22spamreports%22) with my tag.

```
    "1inch-cryptoairdrop.com",
    "aauniswap.top",
    "app-lido.org",
    "bakery-uniswape.com",
    "bakery-uniswape.org",
    "bbuniswap.top",
    "blur-cryptoairdrop.com",
    "bsc-airdrops.xyz",
    "cndfbdnbfd.com",
    "ccuniswap.top",
    "cfd500connect.xyz",
    "claim-airdroping.com",
    "claimcircle-usdc.com",
    "claims-my-usdc.com",
    "claims-usdcnow.com",
    "coinbase-api.serveirc.com",
    "coinbase-secuerz.myvnc.com",
    "coinbase.usdt.monero.monster",
    "dduniswap.top",
    "dexairdrops.top",
    "ethereum-event.dev",
    "eulerrefund.com",
    "event-claim-ff-old207.duckdns.org",
    "ff-claim-event41.duckdns.org",
    "lido-fi.in",
    "market-blur.io",
    "marketplace-blur.io",
    "metamask-access.io",
    "metamask.io-7p4s.13-72.site",
    "metamask.io.mastarstudios.com ",
    "metamaskairdrops.net",
    "myeterwalletinfomyetherwallet.com",
    "primerewards.io",
    "pancakeswap.workers.dev",
    "pancakeswaps.us",
    "panicrek.site",
    "polygonexchange.xyz",
    "polygonventures.xyz",
    "redeemable-circle.com",
    "svb-usdc.com",
    "take-blur.com",
    "teamservice-coinbase.com",
    "truemining.space",
    "usd-circle.com",
    "uniinterface-qppjgj9n-invinciblemax.4everland.app",
    "usdcbanketh.com",
    "verifyxxvemtb.authorizeddns.org",
    "www-bittrex-exchange.com",
    "www-exodus-com-wallet-hardware.gscsupportservices.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
fix json

**Review by dubstard — COMMENTED** [review]
remove dupe

**Review by dubstard — COMMENTED** [review]
block uniinterface-qppjgj9n-invinciblemax.4everland.app

**Review by dubstard — COMMENTED** [review]
block scams related to EchelonFND Discord attack
image

```
"primerewards.io",
"cndfbdnbfd.com",
```

**Review by dubstard — COMMENTED** [review]
1inch.altinity.cloud  seems to be some k8s instance, likely FPO
not phishy

**Review by deshvin — APPROVED** [review]

**Pull request merged**
