### PR TITLE
Block USDC Circle redeem scams (continued...)

### PR DESCRIPTION
**Pull request by dubstard**
image
image
image
image
image
image

```
    "claims-circle.icu",
    "claims-circle.top",
    "1inch-network.com",
    "balancer-dashboard.com",
    "binance-exchange.vip",
    "bitcoins2day.com",
    "bits-capital.co.metamark-crypto.co",
    "cakeconnect.cfd",
    "capital-gains.co.metamark-crypto.co",
    "circle-airdrops.com",
    "claim-airdrop.site",
    "claim-gro.site",
    "claimpayment.top",
    "claims-circle.info",
    "claims-circle.org",
    "claims-stable.com",
    "claims-usdc.com",
    "claims-usdc.info",
    "claims-usdc.org",
    "coinbase-reset-password.com.ccda1683d8c9.xyz",
    "coinbase-resets.serveirc.com",
    "coinbase-revert.com",
    "coinbase.taeon.ga",
    "coinsdex.top",
    "connectnode.sbs",
    "cryptocurrency-trading-exchange.com",
    "cryptocurrency-trading-exchange.top",
    "cryptogpt-claim.org",
    "dexmoney.io",
    "metamask.club",
    "metamask.inses.top",
    "metamask987.com",
    "metamaskming.com",
    "myehetrewallet.finance-accessme.com",
    "nanox.vip",
    "nodeconnect.sbs",
    "portfolio-metamask.duia.eu",
    "processkyc-metamask.ddns.net",
    "protocoldapps.web.app",
    "reviewactivity.sbs",
    "sign-claim.xyz",
    "smartfinancecontrol.net",
    "sushiswap.se",
    "sushiswap.world",
    "takeblur.com",
    "uniswap.blog",
    "uniswap.dance",
    "uniswap.desi",
    "uniswap.gratis",
    "uniswap.pics",
    "uniswaprotocol.org",
    "vc-coinbase.com",
    "walletconnect-dapp.app",
    "ww-coinbase.com",
    "xn--laim-optimism-9sb.net",
    "xn--uniswp-tta.exchange",
```

```
 diff all_original.txt ALL_with_new_added_without_dupes.txt
0a1,3
>       "1inch-app.co",
>       "claims-circle.icu",
>       "claims-circle.top",
132a136
>     "1inch-network.com",
159a164
>     "1inch.club",
3035a3041
>     "balancer-dashboard.com ",
3744a3751
>     "binance-exchange.vip",
4285a4293
>     "bitcoins2day.com",
4445a4454
>     "bits-capital.co.metamark-crypto.co",
6042a6052
>     "cakeconnect.cfd",
6088a6099
>     "capital-gains.co.metamark-crypto.co",
6502a6514
>     "circle-airdrops.com",
6512a6525
>     "circlebay.info",
6521a6535
>     "citizenbankonline111.moneyhome.biz",
6537a6552
>     "claim-airdrop.site",
6591a6607
>     "claim-gro.site",
6722a6739
>     "claimpayment.top",
6732a6750,6751
>     "claims-circle.info",
>     "claims-circle.org",
6736a6756,6759
>     "claims-stable.com",
>     "claims-usdc.com",
>     "claims-usdc.info",
>     "claims-usdc.org",
7122a7146
>     "coinbase-reset-password.com.ccda1683d8c9.xyz",
7123a7148
>     "coinbase-resets.serveirc.com",
7124a7150
>     "coinbase-revert.com",
7328a7355
>     "coinbase.taeon.ga",
7859a7887
>     "coinsdex.top",
8174a8203
>     "connectnode.sbs",
8618a8648,8649
>     "cryptocurrency-trading-exchange.com",
>     "cryptocurrency-trading-exchange.top",
8663a8695
>     "cryptogpt-claim.org",
9737a9770
>     "dexmoney.io",
20067a20101
>     "metamask.club",
20184a20219
>     "metamask.inses.top",
20971a21007
>     "metamask987.com",
21202a21239
>     "metamaskming.com",
23033a23071
>     "myehetrewallet.finance-accessme.com",
24515a24554
>     "nanox.vip",
25064a25104
>     "nodeconnect.sbs",
27846a27887
>     "portfolio-metamask.duia.eu",
28027a28069
>     "processkyc-metamask.ddns.net",
28856a28899
>     "reviewactivity.sbs",
30076a30120
>     "sign-claim.xyz",
30257a30302
>     "smartfinancecontrol.net",
31212a31258
>     "sushiswap.se",
31222a31269
>     "sushiswap.world",
31533a31581
>     "takeblur.com",
33706a33755
>     "uniswap.blog",
33761a33811
>     "uniswap.dance",
33766a33817
>     "uniswap.desi",
33807a33859
>     "uniswap.gratis",
33891a33944
>     "uniswap.pics",
34256a34310
>     "uniswaprotocol.org",
34915a34970
>     "vc-coinbase.com",
35663a35719
>     "walletconnect-dapp.app",
36506a36563
>     "ww-coinbase.com",
37330a37388
>     "xn--laim-optimism-9sb.net",
38205a38264
>     "xn--uniswp-tta.exchange",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove dupe "1inch-app.co",

**Review by dubstard — COMMENTED** [review]
block scam protocoldapps.web.app 
h/t https://twitter.com/malwrhunterteam

**Review by dubstard — COMMENTED** [review]
image
block wallet drainer `ocaenprotocol.com`

ProMoTeD
image

**Review by dubstard — COMMENTED** [review]
block fake metamask airdrops

Bait shows the supposed imaginary asset amount, that is due to be "given away"
 _see how much ETH we are going to "give away"_

```
"metamaskairdrops.com",
"metamasksrewards.com",
"metamasksirdrops.wixsite.com",
```
h/t [@bumbl3r](https://twitter.com/bumbl3r)
image

**Review by AlexHerman1 — COMMENTED** [review]
LGTM.

**Comment by dubstard** [comment]
thanks

**Review by deshvin — APPROVED** [review]

**Pull request merged**
