### PR TITLE
 Block 60 scam URLs (#12266)

### PR DESCRIPTION
**Pull request by legobeat**
(ported from #12266. original credit goes to @dubstard )

Not the 1inch you need
```
    "1-inch-claim.xyz",
    "1inch-connect.xyz",
    "1inch-cryptos.top",
    "1inch-event.site",
    "1inch-event.xyz",
    "1inch-wallet.com",
    "inch-claim.xyz",
    "drop-1inch.site",
```
	
Not the Arbitrum you need
```
    "arbitrumclaim.click",
```
	
Not the Cryptopunks you need
```
    "cryptopunks.claims",
```
    
Not the Airdrop you need
```
    "claim-500usd.top",
    "claim-airdrop.top",
    "claim-airdrops.top",
    "claimairdrop.app",
    "coresky-claim.xyz",
    "deficlaimingairdropandrewards.org",
    "drops-web3.foundation",
    "harmonize-web.net",
    "rangers-ajaw.xyz",
```
    
Not the Metamask you need
```
    "auto-eth.org",
    "iweb3access.net",
    "iweb3connect.net",
    "kyc-metamask-io.ddnss.eu",
    "meta-mask-official.com",
    "metamask-activation.ddns.net",
    "metamask-securityverification.com",
    "metamask-services.ddns.net",
    "metamask.io.web3secureapp.com",
    "metamask.web3check.online",
    "metamask4.top",
    "metamaskhgjsweder.work.gd",
    "metamass.io",
    "wen-metamask.com",
    "canitransferfrommetamasktocrypto.com",
```
	
Not the Otherside you need
```
    "otherclaim.xyz",
```
	
Not the Pancakeswap you need
```
    "pancakesvap.flnacne.online",
    "pancakesvap.flnacne.site",
    "pancakesvap.flnacne.tech",
    "pancakeswap-amm.com",
    "pancakeswap-discover.com",
    "pancakeswap-exchanger.com",
    "pancakeswap-platform.com",
    "pancakeswap-trade.com",
```

Not the Nansen you need
```
    "portfolio-nansens-ai.com",
```
 
Not the Opensea you need
```
    "register-openseapro.com",
```
	
Not the Seedify you need
```
    "seedifiy.org",
    "claims-seedify.net",
```
	
Not the Loopnetwork you need
```
    "theloopnetwork-coin.org",
```
	
Not the Vulcan bot you need
```
    "vulcanauthentication.xyz",
```
	
Not the Uniswap you need
```
    "unisvap.org",
    "uniswap-build.com",
    "uniswap-dex.com",
    "uniswap-discover.com",
    "uniswap-earn.com",
    "uniswap-exch.org",
    "uniswap-marketplace.com",
    "uniswap-platform.com",
    "uniswapfnd.com",
```
	
Not the Coinbase you need
```
    "cccoinbasee.com",
```
	
Not the Zksync you need
```
    "zksevent.com",
```

All
-----------------
Block 60 scam URLs
```
    "1-inch-claim.xyz",
    "1inch-connect.xyz",
    "1inch-cryptos.top",
    "1inch-event.site",
    "1inch-event.xyz",
    "1inch-wallet.com",
    "arbitrumclaim.click",
    "auto-eth.org",
    "canitransferfrommetamasktocrypto.com",
    "cccoinbasee.com",
    "claim-500usd.top",
    "claim-airdrop.top",
    "claim-airdrops.top",
    "claimairdrop.app",
    "claims-seedify.net",
    "coresky-claim.xyz",
    "cryptopunks.claims",
    "deficlaimingairdropandrewards.org",
    "drop-1inch.site",
    "drops-web3.foundation",
    "harmonize-web.net",
    "inch-claim.xyz",
    "iweb3access.net",
    "iweb3connect.net",
    "kyc-metamask-io.ddnss.eu",
    "meta-mask-official.com",
    "metamask-activation.ddns.net",
    "metamask-securityverification.com",
    "metamask-services.ddns.net",
    "metamask.io.web3secureapp.com",
    "metamask.web3check.online",
    "metamask4.top",
    "metamaskhgjsweder.work.gd",
    "metamass.io",
    "otherclaim.xyz",
    "pancakesvap.flnacne.online",
    "pancakesvap.flnacne.site",
    "pancakesvap.flnacne.tech",
    "pancakeswap-amm.com",
    "pancakeswap-discover.com",
    "pancakeswap-exchanger.com",
    "pancakeswap-platform.com",
    "pancakeswap-trade.com",
    "portfolio-nansens-ai.com",
    "rangers-ajaw.xyz",
    "register-openseapro.com",
    "seedifiy.org",
    "theloopnetwork-coin.org",
    "unisvap.org",
    "uniswap-build.com",
    "uniswap-dex.com",
    "uniswap-discover.com",
    "uniswap-earn.com",
    "uniswap-exch.org",
    "uniswap-marketplace.com",
    "uniswap-platform.com",
    "uniswapfnd.com",
    "vulcanauthentication.xyz",
    "wen-metamask.com",
    "zksevent.com",
```

### CODE REVIEW

**Comment by dubstard** [comment]
thanks!

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Yes. New one incoming

**Review by Bedis5454 — COMMENTED** [review]
Yw

**Pull request merged**
