### PR TITLE
Add sites to blocklist [ 8 ]

### PR DESCRIPTION
**Pull request by ShenWe0x**
Add sites to blocklist

Phishing Airdrop Claim website

https://twitter.com/gott_brad18959/status/1753801722483396667
https://twitter.com/alarganprojects/status/1753789624982352127
https://twitter.com/0xThorne/status/1753791851390255260
https://twitter.com/theBdizzle_eth/status/1753796872798446048
https://twitter.com/Jameseth100x/status/1753752785299059155
https://twitter.com/fischerhz99/status/1753789569697227230
https://twitter.com/smith21_wyatt/status/1753399115466125585

### CODE REVIEW

**Comment by ShenWe0x** [comment]
"syncsswap.app" was added a few hours ago, so it has been removed.

**Comment by ShenWe0x** [comment]
@AlexHerman1 https://ipfs.io/ipns/"domain" How can we block such URLs?
ipfs.io is an open system for managing data without a central server. I don't know how to add banned sites hosted on this domain to the list without banning ipfs.io. In which format can we ban the banned site without banning the main domain?

**Comment by AlexHerman1** [comment]
will look into this

**Comment by AlexHerman1** [comment]
@ShenWe0x  please stop trying to add tornado.ws it is just causing merge delays and more work. I will look into figuring out how to add it myself

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
