### PR TITLE
Block scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
block 
```
    "meta-maks.com",
    "mmemtatamasmssks.azurewebsites.net",
    "officialnetworktech.cc",
    "rectification-dapp.com.officialnetworktech.cc",
    "metatasmasmskjy.azurewebsites.net",
```
image
image
image
image
image

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block
```
metatasmasmskjy.azurewebsites.net
```

**Review by dubstard — COMMENTED** [review]
block bitdrops.online
image
image

**Review by dubstard — COMMENTED** [review]
block `fixie.live`
image

**Review by dubstard — COMMENTED** [review]
block `adidasusonlineshop.com`

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Pull request merged**
