### PR TITLE
Allowlist opende.fi (#6927)

### LINKED ISSUE #6927: [Legitimate Site Blocked] opende.fi
Hi, I purchased a new domain: https://opende.fi/, but the domain was blocked as a phishing site.
How could this happen?
I searched the domain at https://cryptoscamdb.org/search/?, but the site is not listed here.
What is the current situation???

### LINKED ISSUE #6972: [Legitimate Site Blocked] mint.adrunner.io
https://mint.adrunner.io/ is not a scam. I have successfully minted 8 NFTs from this amazing project

### PR DESCRIPTION
**Pull request by visvirial**
This will fix #6927 .

### CODE REVIEW

**Comment by visvirial** [comment]
Note: the site is hosted at GitHub pages, where the source code is available at https://github.com/opende-fi/opende.fi

**Comment by visvirial** [comment]
> According to https://metamask.github.io/eth-phishing-detect/,
> 
> ```
> This domain was blocked for its similarity to opensea.io, a historical phishing target.
> ```
> 
> which is not the case for this domain.

https://github.com/MetaMask/eth-phishing-detect/issues/6927#issuecomment-1079818258

The similarity is too small IMO.

**Comment by ethphishingmaintainer1000** [comment]
@visvirial could you please rebase?

**Review by ethphishingmaintainer1000 — APPROVED** [review]
approving since `opende.fi` is not visually similar to `opensea.io`

**Comment by visvirial** [comment]
Thank you for merging!

**Pull request merged**
