### PR TITLE
block 59 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "1inch.xp-cdn.com",
    "asia-pancakeswap.dysnix.org",
    "eu-pancakeswap.dysnix.org",
    "app-ethome-explore.com",
    "app.metamask.xp-cdn.com",
    "blockchain-walletlogin.com",
    "cryptowalletbank.cf",
    "cryptowalletbank.ga",
    "cryptowalletbank.gq",
    "cryptowalletbank.ml",
    "cryptowalletbank.tk",
    "dappsiconnect.com",
    "dappswalletconnectplug.com",
    "dydx-claim.exchange",
    "eethereum.xyz",
    "ethereum-defi.top",
    "ethereum-to-usd.com",
    "giftwaveswallet.com",
    "good2metamask.run.place",
    "legdder.xp-cdn.com",
    "legderlive.xp-cdn.com",
    "martianaptoswallet.xp-cdn.com",
    "metamask.xp-cdn.com",
    "outiok-live-ethereumfreebies.josephburck.com",
    "outiok-live.ethereumfreebies.com",
    "outiook-live-giftwaveswallet.josephburck.com",
    "pancakeswap-finance-v2.com",
    "pancakeswap-finance-v3.com",
    "pancakeswapreward.com",
    "ronin-network.xp-cdn.com",
    "ronin-wallet.xp-cdn.com",
    "ronin.xp-cdn.com",
    "ronins.xp-cdn.com",
    "shapeshift.xp-cdn.com",
    "sheapeshift.xp-cdn.com",
    "spx.sale",
    "suite-trezor.xp-cdn.com",
    "temple-app.xp-cdn.com",
    "trezor-suite.xp-cdn.com",
    "tronlink.xp-cdn.com",
    "uniswapapp.xyz",
    "uniswaplabs.app",
    "unfitoken.com",
    "walletconnect-tool.xyz",
    "web3-connectzx.cf",
    "web3-connectzx.ga",
    "web3-connectzx.gq",
    "web3-connectzx.ml",
    "web3-connectzx.tk",
    "xp-cdn.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
remove redundant duplicate `legdder.xp-cdn.com`

**Review by dubstard — COMMENTED** [review]
add scam "aavepool.com",

**Review by dubstard — COMMENTED** [review]
add 
```
pkrd7.finance
```

**Review by dubstard — COMMENTED** [review]
```
    "my-newweb3.com",
    "spxblockchain.com",
    "methodsmoney.com",
    "stealthcryptosecrets.com",
    "fluffworld.xyz",
    "mint.worldcupinu.app",
    "worldcupinu.app",
    "accessglobalfinancial.com",
```

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
thanks!

**Pull request merged**
