### PR TITLE
[URGENT] Allowlist spotonchain.ai spotonchain.com (#13565)

### LINKED ISSUE #13565: [Legitimate Site Unblocked][Urgent] https://platform.spotonchain.ai/
**Domain:** spotonchain.ai, spotonchain.com, platform.spotonchain.ai, friendex.spotonchain.ai, platform.spotonchain.com, friendex.spotonchain.com

**Details:** *We develop an AI insight platform to provide users information about the on-chain activities, we request signatures from users to verify their address ownership for authenticating (nothing else). Some users report they see Deceptive site ahead. We have just released the beta launch and people are blocked due to this error. Please help to unlock us*

image

- I have checked to make sure that there is not a duplicate issue(https://github.com/MetaMask/eth-phishing-detect/issues)

### PR DESCRIPTION
**Pull request by nhudinhtuan**
We have just launched the beta version and some users got blocked from Metamask.

In this PR, we want to add our platform domain to the whitelist.

About spotonchain:
Spot On Chain is a pioneering platform designed to simplify on-chain data analysis and provide accessible insights for all in the cryptocurrency space. Our AI-powered platform offers easily digestible insights, intuitive visualizations, AI assistance, one-click alerts, and mobile accessibility. Our aim is to make on-chain data usable and comprehensible to a wide range of users, regardless of their technical background, ensuring confident decision-making in the cryptocurrency market.

Twitter: https://twitter.com/spotonchain
Website: https://spotonchain.ai/

Fixes: https://github.com/MetaMask/eth-phishing-detect/issues/13565

### CODE REVIEW

**Comment by 409H** [comment]
Hi @nhudinhtuan - this is included in the blocklist of one of our partners - phishfort - please send a pull request there: https://github.com/phishfort/phishfort-lists/blob/b5e86586d6264474ac03064d6309a9e3811a80d2/blacklists/hotlist.json#L6594

**Comment by 409H** [comment]
@nhudinhtuan please alter the PR and remove the subdomains - the apex domain being in an allowed list will include subdomains

**Review by 409H — CHANGES_REQUESTED** [review]
please alter the PR and remove the subdomains - the apex domain being in an allowed list will include subdomains

**Comment by nhudinhtuan** [comment]
> please alter the PR and remove the subdomains - the apex domain being in an allowed list will include subdomains

I have removed the sub domains

**Comment by nhudinhtuan** [comment]
@409H We believe the phishfort added our platform as we get hot on Twitter with our beta launch program. We submitted our appeal https://github.com/phishfort/phishfort-lists/issues/968, but they seem not so active recently, could you help us to whitelist our domain as soon as possible as many of our users are affected. Thanks

**Comment by AlexHerman1** [comment]
this isn't blocked for me, i think phishfort removed it?

**Comment by nhudinhtuan** [comment]
> this isn't blocked for me, i think phishfort removed it?

yes, we contacted them to remove us. However, to be safe for the future, could you whitelist our domain? We will have the even bigger event on Twitter for the Mainnet launch and it may trigger other 3rd parties (one of the reason for phishfort to block us as many people share about our upcoming airdrop program)

**Comment by AlexHerman1** [comment]
we dont use the allowlist in that way, sorry.

**Pull request closed without merging**
