### PR TITLE
block three scams

### PR DESCRIPTION
**Pull request by dubstard**
block three scams 
`balancerfi.org` (imitation of Balancer.fi)
image

`app-uniswap.site` (imitation of Uniswap.org)
image

`metamask.eip-1559.network` (imitation of Metamask.io)
image
image

### CODE REVIEW

**Comment by dubstard** [comment]
hat tip to cryptorachel for the uniswap fake

**Review by dubstard — COMMENTED** [review]
add "eip-1559.network",

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
