### PR TITLE
Block 41 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
h/t ecarlesi, bunny, malwrhunterteam

☢ 

Top dyslexia quality such as **axieifinitys**, **blockhaine**, **exodlus**, **pancakasvap** and **unyswap** and dont forget about **looksrers**

```
    "assace.me",
    "aut-compound.com",
    "banktrade.capital",
    "binance-globals-campaign-support.net",
    "bisawap.com",
    "bizswep.com",
    "blochicnain.com",
    "blockhain.en.virtualstaffingco.com",
    "cancel11058954-binance-com.web.app",
    "coinlise.com",
    "coinmaigrattee.xyz",
    "coinmixer.online",
    "collapse.fun",
    "corimigratesolutiions.online",
    "deconrtalond.com",
    "defiprotocol-xyz.web.app",
    "unyswap.com",
    "exodlus-web.org",
    "financialkashbnc.org",
    "invsiblefriendsmint.com",
    "loggon-user.cfd",
    "looksrers.org",
    "marketplace-axieifinitys.xyz",
    "metamask.io.index-2022.icu",
    "mintsecure.io",
    "mirror-official.com",
    "mxeth.com",
    "pancakasvap.one",
    "raven-network.net",
    "remove-notifications.com",
    "shop-chainlist.com",
    "smart-wallet1.web.app",
    "staking-ethereum.net",
    "sushiaswap.org",
    "tronlinlkapp.org",
    "trustweta.com",
    "wallet.blockchain.en.virtualstaffingco.com",
    "wellet.blockhaine.en.virtualstaffingco.com",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
add 
"unisnft.org",

h/t exec

image

**Review by dubstard — COMMENTED** [review]
block fake uniswap airdrops
"claimuniswaplp.com",
"claimunilp.com",

https://etherscan.io/address/0xc1c8c49b0405f6cffba5351179befb2d8a2c776c
https://urlscan.io/result/f420e7e1-df68-462b-bf63-62bd331f2b03/
image
image

**Review by dubstard — COMMENTED** [review]
block uniswap scam "uniswap-app.web.app",
image

**Review by 409H — APPROVED** [review]

**Comment by dubstard** [comment]
Thanks!

**Pull request merged**
