### PR TITLE
remove bnbminer.finance from blacklist

### PR DESCRIPTION
**Pull request by AlexHerman1**

### CODE REVIEW

**Comment by TheRealDeveloper-BNBMiner** [comment]
Thank you @AlexHerman1! That warning has caused an extra tough week for our entire community, during an already sensitive phase of our project. It has spread a false sense of danger throughout. Our project is nearly 2 years old with thousands of daily users. Our community has never and will never deal in malicious practices. Our website also doesn't ask for any sensitive information or permissions from its users. Is there a way to avoid this in the future? Thanks again!

**Comment by AlexHerman1** [comment]
@TheRealDeveloper-BNBMiner  can you provide some context on the purpose of your dapp, the economics behind it, and why it is called "BNBminer" when BNB chain is a proof of stake network?

**Comment by TheRealDeveloper-BNBMiner** [comment]
BNBMiner.finance has never claimed to actually mine BNB, it's simply designed and named as a fun theme. Of course there is always someone who refuse to read but out of thousands of daily users the overwhelming majority of our users know that we don't actually mine BNB. The actual mechanics are explained right there on the home page of our website.

Users hire miners with BNB and are given a personal TVL at the time of doing so (equal to the BNB used to hire miners). Personal TVL is based on the current value of an individual's total miners. The contract allows each user to withdraw up to 3% of their personal TVL daily. The contract also gives users the option to compound that 3% for more miners in anticipation of future upward pressure on the value of miners.

The value of miners increases and decreases based on the combined actions of the community. When the community as a whole extracts more value than they inject, the value of miners naturally decrease. When the community injects more value than they extract, the value of miners increases.

The BNB Miner contract is open source, immutable and there has never been any malicious activity within our contract, website or social media accounts. Our concept has been cloned and used in many very successful projects. Unfortunately, it has also been cloned and manipulated by many bad actors as well due to it's open-sourced nature and success. Some bad actors have gone as far as using our exact name and design, but they do that with everything successful; celebrities, projects, companies and so on. We also regularly warn our community of such bad actors, just as everyone that has online popularity is forced to do these days.

The BNB Miner community has experienced two complete cycles since it's launch on March 22, 2021 and we expect to see many more within the years to come. We are also in the middle of developments aimed at providing further utility and excitement to our current project. Thank you for taking the time to hear us out and hopefully address our current issue.

**Comment by TheRealDeveloper-BNBMiner** [comment]
@AlexHerman1 I'm really confused about our status. Can you please provide an update on our request to be removed from the MetaMask blacklist? It's been nearly 3 weeks, our community simply wants to know if we will be removed from the blacklist or not. It seems that the Metamask main code has been updated multiple times since our first contact but our website remains on the blacklist. Anything that I can share with our community would be greatly appreciated. Thank you!

**Review by legobeat — APPROVED** [review]

**Comment by TheRealDeveloper-BNBMiner** [comment]
Would someone please take the time to remove us from the MataMask blacklist. It's been nearly 3 weeks that we've been dealing with the unjustified phishing label being shown to our MetaMask users. @409H @devenblake @ethphishingmaintainer1000 @AlexHerman1

**Pull request merged**
