### PR TITLE
chore: Add scam site pinksale.finance

### PR DESCRIPTION
**Pull request by nshCore**
I am founder of @Kitsumon (please see github org)

Site listed is listing our token as well as other tokens they do not have to sell, they have specifically listed our $KMC token as a BSC token, when it launches on Matic.

Although the site is aimed at BSC users since, people use Metamask for BSC as well we should extend protection from scam sites like this to all Metamask users.

### CODE REVIEW

**Comment by JayArrowz** [comment]
Scammers list coins on the site mods cant be bothered to read scam reports as said by the admin:
image

No response in stopping scammers from scamming 100 BNB from members on their site:
image

Huge scam occurred just now from BNB queen 
image

They have also listed Kitsumon on there and are not taking it down even though we own the project.

**Review by JayArrowz — APPROVED** [review]

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by davidwgrossman** [comment]
@nshCore this PR is ready to go! I think you will need to rebase and merge yourself though

**Comment by nshCore** [comment]
> @nshCore this PR is ready to go! I think you will need to rebase and merge yourself though. Feel free to tag me if you need any help

Have updated can be merged now.

**Comment by DeFiforlife** [comment]
> I am founder of @Kitsumon (please see github org)
> 
> Site listed is listing our token as well as other tokens they do not have to sell, they have specifically listed our $KMC token as a BSC token, when it launches on Matic.
> 
> Although the site is aimed at BSC users since, people use Metamask for BSC as well we should extend protection from scam sites like this to all Metamask users.

You call yourself the owner of a DeFi project and you don't understand how a decentralised platform works?

**Comment by DeFiforlife** [comment]
> I am founder of @Kitsumon (please see github org)
> 
> Site listed is listing our token as well as other tokens they do not have to sell, they have specifically listed our $KMC token as a BSC token, when it launches on Matic.
> 
> Although the site is aimed at BSC users since, people use Metamask for BSC as well we should extend protection from scam sites like this to all Metamask users.

You call yourself the owner of a DeFi project and you don't understand how a decentralised platform works?????

**Comment by DeFiforlife** [comment]
> I am founder of @Kitsumon (please see github org)
> 
> Site listed is listing our token as well as other tokens they do not have to sell, they have specifically listed our $KMC token as a BSC token, when it launches on Matic.
> 
> Although the site is aimed at BSC users since, people use Metamask for BSC as well we should extend protection from scam sites like this to all Metamask users.

You call yourself the owner of a DeFi project and don't even understand how a decentralized platform works????        

Pinksale is a decentralized platform, just like Pancakeswap. Anyone can list a presale, just like anyone can make a new token with the same name as your project and make a pairing to launch on Pancakeswap.                                                            

Instead of resorting to cowardly reporting our platform maybe augment your clearly lacking SKA levels so as to send your investors to the right links.

**Review by russiancryptomillionaire — COMMENTED** [review]
This is wrong, you made a mistake.

**Comment by contractchecker-harry** [comment]
Hello all,

First, welcome to decentralized platform.
I would like to kindly ask you to remove Pinksale from blacklist.
I saw some Screenshots in this topic but in the group there are more than 50K members and it's almost impossible to audit 1 by 1 all the Launchpads. BUT you have to know that Pinksale Owners recently started a SCAMLESS, RUGLESS project where a firm is reporting SCAM and RUGS with real reason and Proof. If the reason is valable then the launchpad is cancelled.

image

image

image

image

image

Again it's impossible to see all of them because huge number of Launchpads are created, but at least they are working hard to make a platform clean.

Thanks to remove them from blacklist asap, 50K members are waiting for this.

**Comment by JayArrowz** [comment]
> 

Do you not choose what data you display on your website. After all your hosting is centralised, yet you still display these scams which are on there for days.

**Comment by DeFiforlife** [comment]
> > 
> 
> Do you not choose what data you display on your website. After all your hosting is centralised, yet you still display these scams which are on there for days.
> 
> Even though your data may be decentralised your web host is centralised and you **can** choose to blacklist and vet the content you put on the site, instead of allowing a scam pot to go on.
> 
> Infact im in the right mind of making a PR for your other domains, until this issue is addressed. You can't just keep saying your platform is decentralised as a excuse to allow scams to go on


You are clearly misinformed. When we are made aware of a fake project or scam our devs act upon it _as soon as humanly possible._

**Comment by HizzleDev** [comment]
Yeah, this has caused a large problem for a number of people who are legitimately running PreSales on this platform (like us). Unfortunately In a DeFi universe, there will be people that scam hence why PinkSale added KYC and Audit functionality so people can sift through.

Honestly, I'm shocked that you pushed this commit through so quickly @AlexHerman1 

_Note_ I am not affiliated with PinkSale in any way.

**Comment by contractchecker-harry** [comment]
it's not a excuse like you say, i am showing you that they work hard to eliminate scam and rugs. I can't tell the same things for other platform. Today 3 pools were cancelled because of SCAM possibility, or rug possibility or just a copy from another project.

**Comment by JayArrowz** [comment]
I understand this.
But there are so many launchpad platforms which vet every project that comes through to make sure each project has real people behind it and not just scammers. I dont see why pinksale can't do this. Are pinksale not profiting from each scam offering that gets completed on their platform?

**Comment by HizzleDev** [comment]
> I understand this. But there are so many launchpad platforms which vet every project that comes through to make sure each project has real people behind it and not just scammers. I dont see why pinksale can't do this. Are pinksale not profiting from each scam offering that gets completed on their platform?
> 
> Edit:
> 
> I can advise some KYC/KYB platforms which can help with this if needed ...

They have a KYC option, which is performed via Veriff, on their website for the users to be able to filter by already? Are you suggesting everyone that runs a project should perform KYC? Does that mean Satoshi should have done too?

We are in a Decentralised world and I understand your sentiment as we need to keep people safe but suggesting nothing is in place is ludicrous. This PR has done more harm than good for those people wanting to invest in genuine projects and for those people that want to launch a genuine project.

**Comment by DeFiforlife** [comment]
Our KYC process is probably the strictest of all crypto world. Just ask any project that has done it. 

You have to wrong people guys. We are 100% for decentralisation but also 100% against scams.

**Comment by DaRabus** [comment]
LOL, Decentralized with Proxy Contracts and WITHDRAW functions eveywhere :D

You even cancel presalesby your own wishes and unlock LPs

**Comment by DeFiforlife** [comment]
> LOL, Decentralized with Proxy Contracts and WITHDRAW functions everywhere :D
> 
> You even cancel presales by your own wishes and unlock LPs
> 
> Withdrawing Tokens from a Presale... https://bscscan.com/tx/0xc808e8dde645b91c3d75cbefd069924f7b909dff0dce79e99fe84be45225a5b0
> 
> https://bscscan.com/address/0xe29f0b490f0d89ca7acac1c7bed2e07ecad65201

Hi DXsale, you're not invited to this conversation. And your claims are , as usual, baseless.

**Comment by yelnats126** [comment]
FINALLY! Enough is enough with these scams and rug pulls. Pinksale is notorious for rug pulls. In a crypto market where there are fewer scams, this means there will be more investors, and this benefits the entire community. GOOD JOB BANNING PINKSALE FROM METAMASK! 
There are other sites with at least some credibility running like DXLaunch with a telegram group that even have live AMAs where the creators are asked questions by the community.

**Comment by namangangwar** [comment]
image
image

> Hi DXsale, you're not invited to this conversation. And your claims are , as usual, baseless.
> You have the wrong people guys. We are 100% for decentralisation but also 100% against scams.

Not so sure about **100% decentralisation!**
These claims don't look useless to me, it's the same **contract** in both screenshots.

**Comment by tadowhowyoulikemenow** [comment]
Ehh..I'd rather use DXSale over Pinksale. Go with them. Pinksale is notorious with rugpulls to the point where anyone who wants to list a rugpull they do it there.

**Comment by tadowhowyoulikemenow** [comment]
> Hello all,
> 
> First, welcome to decentralized platform. I would like to kindly ask you to remove Pinksale from blacklist. I saw some Screenshots in this topic but in the group there are more than 50K members and it's almost impossible to audit 1 by 1 all the Launchpads. BUT you have to know that Pinksale Owners recently started a SCAMLESS, RUGLESS project where a firm is reporting SCAM and RUGS with real reason and Proof. If the reason is valable then the launchpad is cancelled.
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> Again it's impossible to see all of them because huge number of Launchpads are created, but at least they are working hard to make a platform clean.
> 
> Thanks to remove them from blacklist asap, 50K members are waiting for this.

I think the issue is that even though scams are reported they do little to block them, basically saying "too bad". They should take accountability for at least not responding to scam reports!

**Comment by SquidGameArmy** [comment]
WTF METAMASK WHAT DID YOU DOOOO ARE YOU SERIOUS PUT PINKSALE ON THE WHITELIST SO AMATEUR!!!!

**Review by ghost — COMMENTED** [review]
I don't think this line is correct and merge should be reverted.

**Comment by tedy5** [comment]
Did you guys seriously merge this just because some moron crying about his token listed as scam on decentralized launchpad? Are you serious? Deleting metamask now.

**Comment by nshCore** [comment]
> > > 
> > 
> > 
> > Do you not choose what data you display on your website. After all your hosting is centralised, yet you still display these scams which are on there for days.
> > Even though your data may be decentralised your web host is centralised and you **can** choose to blacklist and vet the content you put on the site, instead of allowing a scam pot to go on.
> > Infact im in the right mind of making a PR for your other domains, until this issue is addressed. You can't just keep saying your platform is decentralised as a excuse to allow scams to go on
> 
> You are clearly misinformed. When we are made aware of a fake project or scam our devs act upon it _as soon as humanly possible._

no you actually banned and blocked us from your channels :D

**Pull request merged**
