### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by AlexHerman1**
adding phishing sites

### CODE REVIEW

**Comment by Gudahtt** [comment]
These websites don't seem to load at the moment :thinking: 
Where were these reported? Do we have any screenshots or user reports? They certainly _seem_ like imposter MetaMask sites though, by the domain.

**Comment by AlexHerman1** [comment]
@Gudahtt they were reported via twitter actually

**Comment by AlexHerman1** [comment]
possibly already taken down by google or namecheap, I'm assuming they were SE results

**Review by Gudahtt — APPROVED** [review]
OK, well we can ban them for now I suppose, since they look like imposters. Next time I'd be great to link the source of the report if possible though. Just in case there's a mistake or a typo or something.

**Pull request merged**
