### PR TITLE
Add eigenlayer.xyz to allowlist

### PR DESCRIPTION
**Pull request by Hamin-eigen**

### CODE REVIEW

**Comment by pcaversaccio** [comment]
fixed via https://github.com/MetaMask/eth-phishing-detect/commit/dc4aa89e03b6810e64a2cfb4b94277a974333583

**Comment by Hamin-eigen** [comment]
Thank you. I have confirmed that our domain has been removed from the blacklist. Could it also be added to the whitelist?

**Comment by pcaversaccio** [comment]
> Thank you. I have confirmed that our domain has been removed from the blacklist. Could it also be added to the whitelist?

I have added it to our own whitelist within SEAL-ISAC. @0xOhm @AlexHerman1 can you please add it separately to your own whitelist please.

**Comment by 0xOhm** [comment]
Can do!

**Comment by Hamin-eigen** [comment]
Thanks!

**Comment by AlexHerman1** [comment]
took care of this.

**Pull request closed without merging**
