### PR TITLE
Add phishing url mimicking hop.exchange

### PR DESCRIPTION
**Pull request by rxpwnz**

### CODE REVIEW

**Comment by rxpwnz** [comment]
Also added suvenirforu.com which is advertised as Google ad, but it redirects to the phishing site (see screenshot):
redirect
.

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Review by 409H — APPROVED** [review]

**Comment by 409H** [comment]
@rxpwnz pls update your branch so i can merge

**Comment by rxpwnz** [comment]
> @rxpwnz pls update your branch so i can merge

is it ok now?

**Pull request merged**
