### PR TITLE
Add new phishing domains

### PR DESCRIPTION
**Pull request by vile**
Add many, many new phishing domains (from [this urlscan indicator](https://urlscan.io/search/#hash%3A67ad2454feca6eb213f4a70cc588137e6bd21ad95c0eda2709faa2317ff90359)): 
```
azuki-hilumia.com
akidcalledbeastclaim.net
binanceusdt.org
aave.swapairdrop.com
labgrownbeasts3-free.xyz
usdcircle.org
matamasks.org
opensaee.top
wave-porsche.com
cyberkongz-klaw.xyz
veefriends-gift.com
memellands.com
boredbox.tech
pit.mhound.xyz
devilsnft.xyz
apesbanana.com
projectfox.xyz
createraland.xyz
app-rocketpool.click
cyberbrokers-mech.xyz
mlagents.info
mvhq2023.xyz
twiprysm.xyz
uaenft.org
projectpengu.org
sappyseals.fun
pudgytank.xyz
thecaptainz.link
quest3.fun
azukicommission.xyz
0n1force.info
memelandmap.xyz
artblocks.website
vetmeblocks.com
ethereumporsche.com
arbitrurn.com
terraforms.world
messiofficialnft.com
busdt.app
wl-mdvmm.xyz
rocketpool-reth.link
artgobbler.online
goexfe.cc
vectorspacesbio.science
degenwarriorss.xyz
musdt.xyz
racket-pool.tech
rocketpool-reth.tech
cyberkongzklaw.xyz
rocketpool-reth.com
rocketpool-reth.org
roocket-pool.link
gotouchi-drop.online
revokecash.co
evo-defi.online
musdc.site
roketsppol.shop
roketsppol.store
roketsppol.online
alphakongseclub.pro
fidenzacurated.art
coindeal-eth.com
thedarkflex.xyz
hasbullanft.xyz
metakrew.site
metabountyhunters.fun
artblock.tech
blockpax.xyz
meekicks.io
memeland.click
timexyuga.world
akidcalledbeast.fun
troublemakers.world
animus.fun
uland.space
fluf-burrows.xyz
holoframes.org
dookeydash.fun
boredbanana.org
huslnft.org
sougen.online
keungz.tech
lidos-fi.website
acumen.network
keungz-pass.com
officialtrumpnfts.com
kadamian.xyz
val-halla.wl-pre.com
murakami-flower.wl-pre.com
interapps.xyz
10ktf-shops.wl-pre.com
banana-pass.xyz
lazylions-nft.com
helploginamaz00.authorizeddns.net
claim.gforce689.com
tritonpass.org
ebonus.site
evosdefis.website
evosdefis.tech
evosdefis.com
evaddefi.website
evaddefi.com
ape-nft.io
claims-sea.com
claims-ethw.com
rocket-pools.net
project-qql.com
akidcalledbeastclaim.online
airdrop.arbitrum-labs.net
ethw-aidrop.com
site.secureappvalidations.network
blurclaim.vc
rocketpool.tech
rocket-pools.link
rocket-pool.org
pepabstractss.xyz
royalsociety.fun
dragonskate.xyz
hexcoin.finance
alertnfts.org
cybersamurai.live
yukimoo.xyz
artblocks.space
polyproof.xyz
meta-pass.online
akidcalledbeastclaim.com
sns.claims
akidcalledbeast.shop
mint.cryptohastbullanft.com
mint.cryptohasbullanft.com
mdvmn.com
flarenetwork.space
hasbullacryptonft.com
officialcristianonfts.com
pepelaand.xyz
crewbirbs.xyz
claim-pass.xyz
rtfkt-tokyo.com
app.myaquare.io
main-onchain.online
colla-b.land
1inameelionwatch.org
prysmsquads.fun
boredbananas.com
wenmint.tech
storyverse.site
cosmicisles.fun
mint.claim-mdvmm.xyz
stardome.jedstar.com
mddvmn.xyz
outside-yc.xyz
mint.sneakerheads.xyz
battle-nft.world
nftiff.pro
alphakongclub.pro
rtfkt.su
tlprotocol.xyz
alldiscount.shop
apecoin-rewards.link
akidcalledbeast.cc
akidcalledbeastwl.xyz
magicegg.site
akidcalledbeast.site
ultradao.pro
nftminer.fun
proofart.info
fluf-burrows.world
richfoxclub.xyz
thecaptainz.xyz
kubz.tech
lionleader.fun
nooxbadge.com
musd.tech
gentcroquet.club
weway-airdrop.tech
porscheth.app
thecaptainz.info
rfktf.com
grandpa-apecc.freemiting.cyou
outside-yc.freemiting.cyou
arbitrum-iabs.net
unipool.space
supernormal.fun
faralandnft.xyz
hashverse.tech
puzziland.fun
edo2022.in
zombieverse.space
mutant-hideout.xyz
animesolus.fun
dubaibornapes.xyz
cubeanz.xyz
azukipbt.xyz
esportsone.fun
smashverse.fun
aipalbum.xyz
galafilm.space
itrump.info
anomalyproject.world
creepz.tech
niftytailors.io
jrnyc.xyz
ladyapeclub.org
ogmotorcycle.fun
galafilms.xyz
savagenation.shop
webaverse.fun
antilia.live
redfox.fun
meekicks.world
nativepunk.world
artblocks.shop
captainz.info
primehape.site
chaossun.xyz
lionsnotsheep.fun
cosmicisle.fun
nutsavatar.xyz
doodlebucket.xyz
joinvalcoin.fun
arkpia.xyz
creawearables.org
bobucard.xyz
0n1pass.xyz
sougen.world
mdnvm.xyz
hashflow.world
shibstart.world
allinventors.xyz
starfighter.fun
forgekeys.xyz
holoframes.fun
ethereumtowers.world
chainzoku.world
3dpudgypenguin.xyz
heroart.fun
cosmicisles.xyz
resourgence.xyz
mydayaway.world
bullvbear.fun
kodao.fun
nutsbox.site
nutsplay.xyz
aave-aave.net
evosdefis.click
node.authenticatedsystemlog.com
bedtimee.xyz
wl-azuki.com
thebananaa.xyz
bnbdisk.xyz
arbitrum-iabs.com
alphakongeclub.pro
mint.lucii.io
createraa.xyz
gitoadz.com
riftersio.freemiting.cyou
cameo-pass.freemiting.cyou
dsea.io
bgverse.io
presale-robotera.info
frutizbeach.space
mitsoftware.com
fair-mutanthound.com
fidenza-artbiocks.io
restlessapeyachtclub.com
shapeshift.news
hexdrop.org
world-imaginaryones.io
zrx.xyz
sappysealsnft.org
coldbunker.com
evodefiapps.online
rtfkt.app
mnlth.rtfkt.app
imlpti-app.store
imdptio.online
coolpetnfts.com
claim-bnb.com
irokunft.xyz
coinbaseth.net
riftersio.xyz
cameo-pass.xyz
aotuworld.xyz
spingame.me
basedaf-nft.xyz
ace-eth.io
claim-blur.xyz
elephantsmoney.online
elephantmoney.online
elephanltmoney.online
elephamtmoney.online
ellephantmoney.online
ace-eth.net
rig-coin.com
author.addyourtour.com
taprotocol.xyz
coinbasedapp.site
arbitrum-lab.com
estlatex.com
imlppt.store
swapnanilghosh.github.io
dexxo.tech
fidelity-mining.club
new-chain.link
mail.frutizbeach.space
rugradio.info
genmarket.app
otherside-otherdeed.xyz
official-cr7.com
ambrustudio.xyz
ambrusstudioo.xyz
rektguy.org
rifteers.xyz
sandboxclaim.web.app
mint-rifters.xyz
riftiers.xyz
abracadabras-money.org
buy.metaplanetary.io
fidelity-eth.net
shibusocialclub.site
skatreshomies.site
loopworms.io
airdrop.optimismiabs.com
xhamstrasnft.site
sarclbox.site
cleloark.site
amezo.site
ehtrescor.site
igevers.site
cprasoe.site
bnbescor.site
polgynescor.site
dracopix.xyz
minimekanft.xyz
dogheroes.xyz
omnisee.xyz
evudefis.website
evudefis.tech
evudefis.online
evudefis.link
evudefis.com
evudefis.click
zksync-network.com
mtmsk-safebot.com
memeland-mint.cc
unstake-chain.link
superboys.fun
abracadabras-money.info
traitsniper.us
houseofabsurdities.com
mainnet-blur.io
claim-qql.com
traitsniper.ink
digidaigaku-genesis.com
premint-adidas.com
memeland-captainz.co
murakami-flower.xyz
artiesltd2-free.xyz
thewackydogclub.com
memeland-thecaptainz.com
digi-daigaku.net
nft-adidas.us
xhamstranft.site
us-adidas.io
skatrehomies.site
shibosocialclub.site
sanclloox.site
polgnescor.site
osyatchclub.xyz
meemeland.xyz
ehtroscar.site
```

### CODE REVIEW

**Comment by AlexHerman1** [comment]
@vile  thanks for the submission. Its perfectly fine to add punycode domains to the blocklist. how did you come to find this urlscan indicator?

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by Acumen-Protocol** [comment]
Hello, What is https://urlscan.io/search/#hash%3A67ad2454feca6eb213f4a70cc588137e6bd21ad95c0eda2709faa2317ff90359 ?

And why was Acumen.Network added to the phishing list?

**Comment by Acumen-Protocol** [comment]
> 

I see, thanks for the reply. We will upload without JavaScript obfuscated now

**Comment by Acumen-Protocol** [comment]
> @Acumen-Protocol Hello, URLScan is a web analysis tool, specifically their search feature allows you to search for websites that are similar to each other. In this case, I scanned a website and looked for similiar sites with a specific "indicator" (the "hash" search you sent above). "acumen[.]network" could of been included in that indicator for many reasons, and according to URLScan themselves, "[indicators do] not imply that any of these [sites are malicious]", however, I do not individually check every domain I submit as I just scrape by popular indicators between known phishing sites.
> 
> This false positive was most likely caused by having every single JS file on your site obfuscated, which is a common tactic used by phishing pages. There is no legitimate reason to obfuscate your scripts as it can be easily bypassed, slows down perfomance, and looks extremely sketchy. I took a look at your site and socials and I did not find any malicious or phishing content, I will open a PR to remove your domain from the list.

Please Kindly open a PR to remove this domain from the list.

**Comment by AlexHerman1** [comment]
@vile i think lucii.io may be a legitimate project can you check please and submit a PR as needed

**Comment by maxi0422** [comment]
@vile mitsoftware.com is not a phishing site, on what basis do you include it in the list? It is a company incorporated in Spain where all its information is published on its website. contact number and more.

**Comment by maxi0422** [comment]
> Voy a revisar esta lista nuevamente, este indicador tiene demasiados falsos positivos

I would appreciate it, we are an authentic site, located in Barcelona Spain, please when you want you can contact us to clarify doubts

Best regards.

**Pull request merged**
