### PR TITLE
Add phishing link #14679

### PR DESCRIPTION
**Pull request by PeterBxs**
Cloned phishing websites similar to OFAC-blocked tornado.cash pose a potential risk to MetaMask users.    

    "tornado.ws",
    "tornadocash.vn",
    "tornado.foundation",

### CODE REVIEW

**Review by 409H — CHANGES_REQUESTED** [review]
I believe `tornado.ws` a legitimate domain owned by Tornado

**Comment by JackWtx** [comment]
It looks official, you are right, they added the link everywhere, I don't know how they solved this, but all my funds were stolen and I saw the comments of many people like me.

Please check and add so that no more people become victims.

**Comment by PeterBxs** [comment]
https://bitcointalk.org/index.php?topic=5472406.0

Can you take a look at this discussion?

**Comment by Jackofusu80** [comment]
@PeterBxs (former @JackWtx) You did not check for any previously opened issues related to these domains before opening them. 

**Do you have any evidence, such as a video, showing how you were scammed by the websites you mentioned or anything of that nature?**

Furthermore, it appears that there are strong indicators suggesting that you are a multi-account of the banned GitHub accounts "cryptofbi007" and "Ceytllle". These accounts attempted to circumvent their bans, resulting in the ban of "Ceytllle" as well. There are traces leading back to your new account "@PeterBxs", and in a concerning development, I noticed that you changed your GitHub name from "@JackWtx" to "@PeterBxs" after the post below was published on BitcoinTalk. 
This seems to be a malicious impersonation attempt against me, which can also be observed in your new account. For more information, please refer to this link: https://bitcointalk.org/index.php?topic=5475430.msg63411893#msg63411893

**Pull request closed without merging**
