### PR TITLE
Block 80 scam URLs

### PR DESCRIPTION
**Pull request by dubstard**
```
    "accountupdate-coinbase.com",
    "airdrop-bonus-connect.com",
    "ammaetamsks.azurewebsites.net",
    "app-uniswap-wallet.cf",
    "app-uniswap-wallet.ga",
    "app-uniswap-wallet.gq",
    "app-uniswap-wallet.ml",
    "app-uniswap-wallet.tk",
    "app-uniswaps.life",
    "bnb-smartchain.com",
    "coiinbasepru.logiins.us",
    "coimbase-pro.logiins.us",
    "coinbase-pro.logiins.us",
    "coinbase.accountinformation859067349853.com",
    "coinbase.auth-server-login.com",
    "dnjkfnjdiwnfjiwbei.online",
    "emmmetamamsswalle.azurewebsites.net",
    "eth968.com",
    "ethereum19miningarea.com",
    "etherpow-airdrop.com",
    "fast-dapp.site",
    "free-crypto-airdrop.com",
    "gemini-en-login.bloggerstow.com",
    "gemini-en-login.xyz",
    "goparaswap.com",
    "kyberswap-exchange.com",
    "kyberswap-exchange.org",
    "log-secure-en.blogspacecap.com",
    "log-secure-en.com",
    "login-reverifycoinbase.com",
    "mail.trust-online-wallet.com",
    "mememmemmtaasmms.azurewebsites.net",
    "metamask-en-login.xyz",
    "metamask-login-en.xyz",
    "metamask.logiins.us",
    "metamasklogin.us.com",
    "mmeatamammssks.azurewebsites.net",
    "mmeatamsmsakkslog.azurewebsites.net",
    "mmetaamsmammskskss.azurewebsites.net",
    "mmetamaasskskss.azurewebsites.net",
    "mmetamamakasss.azurewebsites.net",
    "mmetamammaksks.azurewebsites.net",
    "mmetamamsksks.azurewebsites.net",
    "mmetamasksk.azurewebsites.net",
    "mmetanmk.azurewebsites.net",
    "mmetatamammaks.azurewebsites.net",
    "mmetmamamskss.azurewebsites.net",
    "mmmeatamamsk.azurewebsites.net",
    "mmmetamamsks.azurewebsites.net",
    "mmmetamamsmmska.azurewebsites.net",
    "mmmetasnks.azurewebsites.net",
    "mmmetatamamamsk.azurewebsites.net",
    "mmmetsammk.azurewebsites.net",
    "mmmettanaams.azurewebsites.net",
    "newdapp.hujinsuo06.vip",
    "pancakeswapechange.azurewebsites.net",
    "pancakeswpteam.com",
    "paraswap-fi.com",
    "recoveryaccount-coinbase.com",
    "robinheod-logi.us",
    "robinhood-en-login.bloggerstow.com",
    "robinhood-en-login.xyz",
    "robinhood-logiin.us",
    "robinhoodaccount.logiin.us",
    "robinhoodmyaccount.logiin.us",
    "secure-en-wallet.blogspacecap.com",
    "secure-en-wallet.com",
    "secure4-coinbase.com",
    "sign-in-your-coinbase-account-page20211.authorizeddns.net",
    "tlrustwaliet.com",
    "trsstlwt.site",
    "trust-online-wallet.com",
    "trust-walet.live",
    "trust-wallet.kipuperu.com",
    "trust-walletsx.online",
    "uniswapcsma.top",
    "uphold-en-login.bloggerstow.com",
    "uphold-en-login.xyz",
    "walleetcoennetclog.azurewebsites.net",
```
Coinbase
```
    "accountupdate-coinbase.com",
    "coiinbasepru.logiins.us",
    "coimbase-pro.logiins.us",
    "coinbase-pro.logiins.us",
    "coinbase.accountinformation859067349853.com",
    "coinbase.auth-server-login.com",
    "log-secure-en.blogspacecap.com",
    "log-secure-en.com",
    "login-reverifycoinbase.com",
    "recoveryaccount-coinbase.com",
    "secure4-coinbase.com",
    "sign-in-your-coinbase-account-page20211.authorizeddns.net",
```
	
Fake airdrop
image
image

```
    "airdrop-bonus-connect.com",
    "etherpow-airdrop.com",
    "free-crypto-airdrop.com",
```

Uniswap
image

```
    "app-uniswap-wallet.cf",
    "app-uniswap-wallet.ga",
    "app-uniswap-wallet.gq",
    "app-uniswap-wallet.ml",
    "app-uniswap-wallet.tk",
    "app-uniswaps.life",
    "uniswapcsma.top",
```

BNB
```	
    "bnb-smartchain.com",
```

Gemini
```	
    "gemini-en-login.bloggerstow.com",
    "gemini-en-login.xyz",
```

Trustwallet
image

```
    "dnjkfnjdiwnfjiwbei.online",
    "fast-dapp.site",
    "tlrustwaliet.com",
    "trsstlwt.site",
    "trust-online-wallet.com",
    "trust-walet.live",
    "trust-wallet.kipuperu.com",
    "trust-walletsx.online",	
    "mail.trust-online-wallet.com",
```

Metamask
image
image

```
    "metamask-en-login.xyz",
    "metamask-login-en.xyz",
    "metamask.logiins.us",
    "metamasklogin.us.com",
    "secure-en-wallet.blogspacecap.com",
    "secure-en-wallet.com",
    "mmeatamammssks.azurewebsites.net",
    "ammaetamsks.azurewebsites.net",
    "emmmetamamsswalle.azurewebsites.net",
    "mememmemmtaasmms.azurewebsites.net",
    "mmeatamsmsakkslog.azurewebsites.net",
    "mmetaamsmammskskss.azurewebsites.net",
    "mmetamaasskskss.azurewebsites.net",
    "mmetamamakasss.azurewebsites.net",
    "mmetamammaksks.azurewebsites.net",
    "mmetamamsksks.azurewebsites.net",
    "mmetamasksk.azurewebsites.net",
    "mmetanmk.azurewebsites.net",
    "mmetatamammaks.azurewebsites.net",
    "mmetmamamskss.azurewebsites.net",
    "mmmeatamamsk.azurewebsites.net",
    "mmmetamamsks.azurewebsites.net",
    "mmmetamamsmmska.azurewebsites.net",
    "mmmetasnks.azurewebsites.net",
    "mmmetatamamamsk.azurewebsites.net",
    "mmmetsammk.azurewebsites.net",
    "mmmettanaams.azurewebsites.net",
```

Kyberswap
image
```
    "kyberswap-exchange.com",
    "kyberswap-exchange.org",
```

Robinhood
```
    "robinheod-logi.us",
    "robinhood-en-login.bloggerstow.com",
    "robinhood-en-login.xyz",
    "robinhood-logiin.us",
    "robinhoodaccount.logiin.us",
    "robinhoodmyaccount.logiin.us",
```

Fake Eth Mining
image

```
    "eth968.com",
    "ethereum19miningarea.com",    
    "newdapp.hujinsuo06.vip",
```

Paraswap
```
    "goparaswap.com",
    "paraswap-fi.com",
```
    
    
Pancakeswap  
image
 
```
    "pancakeswpteam.com",
    "pancakeswapechange.azurewebsites.net",
```    

Uphold    
```
    "uphold-en-login.bloggerstow.com",
    "uphold-en-login.xyz",
```

WalletConnect
```
    "walleetcoennetclog.azurewebsites.net",
```

### CODE REVIEW

**Review by dubstard — COMMENTED** [review]
block `dnjkfnjdiwnfjiwbei.online`

https://urlscan.io/result/8cb6d4ae-c3a7-46af-b324-737d0ff317e3/

**Review by dubstard — COMMENTED** [review]
Block trustwallet scams, "twins" of `dnjkfnjdiwnfjiwbei.online`

```
trsstlwt.site
trust-wallet.kipuperu.com
mail.trust-online-wallet.com
trust-online-wallet.com
trust-walet.live
trust-walletsx.online
fast-dapp.site
```

Based on IoC `9574464982d6510b24574af8dd38b7283f78bc0067771a2f200d2e0a3252f02d`
https://urlscan.io/search/#hash%3A9574464982d6510b24574af8dd38b7283f78bc0067771a2f200d2e0a3252f02d

**Review by dubstard — COMMENTED** [review]
block 
```
"mmeatamammssks.azurewebsites.net",
```
https://urlscan.io/result/a848010d-f948-464d-bf21-6380e1ee247e/

A short story in pictures:
image

**Review by dubstard — COMMENTED** [review]
Block 23 scams, all on the same IP 20.118.48.12
```
    "ammaetamsks.azurewebsites.net",
    "emmmetamamsswalle.azurewebsites.net",
    "mememmemmtaasmms.azurewebsites.net",
    "mmeatamsmsakkslog.azurewebsites.net",
    "mmetaamsmammskskss.azurewebsites.net",
    "mmetamaasskskss.azurewebsites.net",
    "mmetamamakasss.azurewebsites.net",
    "mmetamammaksks.azurewebsites.net",
    "mmetamamsksks.azurewebsites.net",
    "mmetamasksk.azurewebsites.net",
    "mmetanmk.azurewebsites.net",
    "mmetatamammaks.azurewebsites.net",
    "mmetmamamskss.azurewebsites.net",
    "mmmeatamamsk.azurewebsites.net",
    "mmmetamamsks.azurewebsites.net",
    "mmmetamamsmmska.azurewebsites.net",
    "mmmetasnks.azurewebsites.net",
    "mmmetatamamamsk.azurewebsites.net",
    "mmmetsammk.azurewebsites.net",
    "mmmettanaams.azurewebsites.net",
    "pancakeswapechange.azurewebsites.net",
    "walleetcoennetclog.azurewebsites.net",
```

**Review by dubstard — COMMENTED** [review]
block fake gitcoin giveaway 
```
"offering.top",
```
IoC
`hash:44d8f71c454ad48e2630171f4840767f886a36ec6dfa43aec2ae8089b4722f3f`
https://urlscan.io/search/#hash%3A44d8f71c454ad48e2630171f4840767f886a36ec6dfa43aec2ae8089b4722f3f
image

suspended image

**Review by AlexHerman1 — APPROVED** [review]
ty.

**Pull request merged**
