### PR TITLE
Add nfinite.app to whitelist

### PR DESCRIPTION
**Pull request by ludoviclefevrehubstairs**
Related to issues #5421 : Add nfinite.app to allowlist

### CODE REVIEW

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by Gudahtt — CHANGES_REQUESTED** [review]
Oh, it looks like you blocked your own site! You added it to the blacklist. It should be added to the whitelist instead.

**Comment by ludoviclefevrehubstairs** [comment]
> Oh, it looks like you blocked your own site! You added it to the blacklist. It should be added to the whitelist instead.

My mistake, it's fixed. Thx

**Review by AlexHerman1 — APPROVED** [review]
Looks good!

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
