### PR TITLE
Remove FP [1]

### PR DESCRIPTION
**Pull request by deshvin**
"zksync.netlify.app",

### CODE REVIEW

**Comment by deshvin** [comment]
addresses #13393

**Review by tarballqc — APPROVED** [review]
LGTM

**Comment by yusufky63** [comment]
Hello, when will my site be deployed it still seems to be banned

**Comment by yusufky63** [comment]
How long will this take, we're losing users

**Comment by yusufky63** [comment]
@AlexHerman1 
please take care, be faster

**Comment by yusufky63** [comment]
@dubstard please deal with the situation

**Comment by yusufky63** [comment]
@409H please take care

**Pull request merged**
