### PR TITLE
Block Alchemix-targeted phishing sites

### PR DESCRIPTION
**Pull request by pxrl**
Reported via users in the Alchemix Discord.

### CODE REVIEW

**Review by tarballqc — DISMISSED** [review]

**Comment by legobeat** [comment]
Thank you for the contribution! The root of neither seems to be serving anything under http(s) `/` - do you have a link/archive link/screenshot we could look at?

**Comment by pxrl** [comment]
> Thank you for the contribution! The root of neither seems to be serving anything under http(s) `/` - do you have a link/archive link/screenshot we could look at?

alcemix.fi seems to be listening on HTTP/80 and redirects to alchemix.online:443.

2022-11-01-141132_1333x761_scrot

**Review by AlexHerman1 — DISMISSED** [review]
lgtm.

**Comment by pxrl** [comment]
@legobeat The two domains are still active in my testing. Anything more I can do to help on this one?

**Review by 409H — APPROVED** [review]

**Pull request merged**
