### PR TITLE
Remove domains from allowlist

### PR DESCRIPTION
**Pull request by kellyfends**
delete "etherkan.com", and "ethersat.io", in whitelist this is fake site 
original site https://lnk.bio

### CODE REVIEW

**Comment by deshvin** [comment]
ethersat added to allowlist in #1514
etherkan added to allowlist in #2292

**Comment by deshvin** [comment]
The sites are mirror images of lnk.bio, and the links on the page redirect to lnk.bio.

@kellyfends 
do you know what the scam vector is here, and if the scam is crypto-related?

**Comment by kellyfends** [comment]
> The sites are mirror images of lnk.bio, and the links on the page redirect to lnk.bio.
> 
> @kellyfends do you know what the scam vector is here, and if the scam is crypto-related?

they simply copied the site design and are posting fake token giveaways
They have nothing to do with satyu lnk bio
remove them from the whitelist

https://etherkan.com/arb/
https://ethersat.io/lzero/

**Comment by deshvin** [comment]
That's exactly what I was looking for; thanks for calling this out!

Screenshot 2023-12-12 at 11 46 20
Screenshot 2023-12-12 at 11 46 22

**Comment by kellyfends** [comment]
> That's exactly what I was looking for; thanks for calling this out!
> 
> Screenshot 2023-12-12 at 11 46 20 Screenshot 2023-12-12 at 11 46 22

block this site please

**Review by deshvin — APPROVED** [review]

**Pull request merged**
