### PR TITLE
Add 2 sites on the blacklist

### PR DESCRIPTION
**Pull request by tarballqc**
tutorial.cell.computer
galaxyeggs.link

### CODE REVIEW

**Review by AlexHerman1 — APPROVED** [review]
LGTM.

**Comment by kumavis** [comment]
@tarballqc cell.computer is being removed from the denylist per request of the author -- can you provide some reasoning for the blacklist?

**Comment by skogard** [comment]
@tarballqc I am the owner of the tutorial.cell.computer website, it's just a documentation website with one index.html file with zero script and zero iframes. Just a simple html that renders README.md file so I'm pretty sure it's impossible for this site to phish anyone. Please let me know if there was a vulnerability you found, I would happy to fix it. Thank you!

**Comment by AlexHerman1** [comment]
@skogard  did you create a PR for removal?

**Comment by skogard** [comment]
@AlexHerman1 yes I did. https://github.com/MetaMask/eth-phishing-detect/pull/8038/files 

But it's still happening. Would appreciate if you could look into this. Thank you.

Also I still would like to know why this was added to the blacklist in the first place.

Just want to get some insights so I know what to avoid.

**Pull request merged**
